.github/workflows/test.yml
The Artifact storage quota is maxed out on the NHSUK org, which means we can't successfully run this step.
=> Disable Playwright artifact uploading

app/javascript/serviceworker/cache.js, app/javascript/serviceworker/main.js, app/javascript/serviceworker/network.spec.ts, app/javascript/serviceworker/network.ts
These don't use Workbox and can be customised to use IndexedDB behind the scenes. This is coming in a follow-up PR.
=> Implement manual NetworkFirst, CacheFirst strategies

app/javascript/serviceworker/main.js, app/javascript/serviceworker/record-route.js, app/javascript/serviceworker/record-route.spec.js, app/javascript/serviceworker/store.spec.ts, app/javascript/serviceworker/store.ts
Rename them and implement a new `getByUrl` method.
Also rename the POST requests table to `delayedRequests`, and add a table that will be used for `cachedResponses`. The schema can currently be shared between the two.
This is more prep-work beore we can use IndexedDB instead of the cache API in the `NetworkFirst` strategy, followed by encrypting content as it goes in/out of the cache.
Review commit by commit.
=> Refactor store methods

app/javascript/serviceworker/cache.spec.ts, app/javascript/serviceworker/cache.ts, app/javascript/serviceworker/network.spec.ts, app/javascript/serviceworker/network.ts
Defer to our module instead of calling `caches.open` directly. This will allow us to change the caching mechanism behind the scenes while not having to update all the call sites.
Refactor some other things on the way there, see commits.
This is part of shifting from using the Cache API to IDB as the backing store, and will be done in roughly 3 parts:
0: This PR, prepwork
1: Adding `store` calls to the `put` and `addAll` methods in the cache module, to start storing things in `idb` but not yet reading them
2: Adding `store` calls to the `match` function, completely shifting the implementation from using the Cache API to IDB
3: Removing Cache API related code
Following this, we can move on to actually encrypting/decrypting requests.
=> Use cache match and put in network strategies

app/javascript/serviceworker/cache.spec.ts, app/javascript/serviceworker/cache.ts, app/javascript/serviceworker/network.spec.ts, app/javascript/serviceworker/network.ts, app/javascript/serviceworker/store.spec.ts, app/javascript/serviceworker/store.ts
The NetworkFirst strategy will continue to use the CacheAPI mainly, but this adds initial support to additionally save the requests to IDB.
Few other refactors done on the way, see commits.
=> Add requests to idb through NetworkFirst strategy

app/javascript/serviceworker/cache.spec.ts, app/javascript/serviceworker/cache.ts, app/javascript/serviceworker/network.spec.ts, app/javascript/serviceworker/network.ts, app/views/layouts/application.html.erb
This migrates the `cache` methods to use `idb` as the backing store instead of the Cache API.
There are a few bugs left over, but functionality is good enough to the point that tests pass. We can tackle these in follow-up PRs:
See commits.
=> Fetch cached requests from idb

app/views/layouts/application.html.erb
Caching redirects for offline use isn't possible using our IndexedDB approach. When our ServiceWorker's event listener for `fetch` events receives the request for `/`, which is a redirect, the response object is of type `opaqueredirect` and contains no information about where the redirect is meant to go. This is by design: https://github.com/whatwg/fetch/issues/763
Alternatives to handling redirects in the application when offline include:
- Falling back to the Cache API to handle these types of requests
- Writing some very brittle code that depends on a redirect request + its follow-up request to happen sequentially, which sounds hacky
- Simply not using redirects where possible when designing the core GET-based navigation and features of our app
The latter option is easiest.
=> Replace link to / with /dashboard in header

app/controllers/vaccinations_controller.rb, spec/requests/pages_spec.rb
This prevents the browser from saving a request for this file to the Cache_Data folder.
This is just the bare minimum for now, but we'll probably expand this to other files or perhaps create a separate controller to inherit from for sensitive endpoints and data.
There might be downsides to setting aggressive no-cache headers; it potentially breaks the back button in situations of flaky connectivity.
=> Disable browser caching for children.json

app/javascript/serviceworker/simple-crypto.test.ts, app/javascript/serviceworker/simple-crypto.ts
Turns out that using apply can result in a `Maximum call stack size exceeded` error with sufficiently large inputs...
=> Use for instead of apply when converting to base64

app/javascript/serviceworker/network.ts
We need to pull out the `put` call from the try.
=> Don't swallow `put` errors in NetworkFirst strategy

app/controllers/application_controller.rb, app/controllers/vaccinations_controller.rb
Without this, the browser can choose to temporarily store pages in the user's navigation in a client-side plaintext cache. Because our pages can contain things like NHS numbers or user data, this is a potential security risk.
There's no tests in this commit because `spec/requests/pages_spec.rb` covered testing the `/children.json` endpoint, and it should still pass.
=> Set all pages to Cache-Control no-store

app/controllers/vaccinations_controller.rb, app/views/vaccinations/index.html.erb
Flashes oddly can only be a string if you're using `redirect_to`, but they can be hashes if you `render`.
=> Fix empty flash message when updating a record

app/javascript/serviceworker-companion.js
ServiceWorkers are designed to go to sleep after 30 seconds of inactivity, to preserve memory and battery.
For our application, we need the ServiceWorker to stay alive once the user has initialised the encryption secret, so that the secret stays in memory. Otherwise, when offline working, if they don't touch the browser tab for 30 seconds, we'd have to ask them for the password again.
To work around this, we can force the service worker to stay alive by pinging it every 20 seconds.
In my testing, this seems to work consistently in Firefox (devtools opened or not), and inconsistently in Chrome-based browsers.
As this is imperfect, it's optional to merge and I extracted it from the main offline password PR. It makes offline working a little more reliable, but we'll have to replace this with …
=> Keep service worker alive

app/javascript/controllers/offline_campaign_controller.js, app/javascript/serviceworker/messages.js, app/javascript/serviceworker/messages.spec.js, app/javascript/serviceworker/network.spec.ts, app/javascript/serviceworker/network.ts, spec/factories/campaigns.rb, spec/factories/children.rb, spec/factories/schools.rb
Prerequisite for: https://github.com/nhsuk/record-childrens-vaccinations/pull/198
Depends on https://github.com/nhsuk/record-childrens-vaccinations/pull/200 (roughly... it might be mergeable without, but because this piles on additional requests in the `addAll`, the test just becomes even flakier without it).
The key bit in this PR is removing the `await put(request, networkResponse.clone());` call in the `NetworkFirst` strategy.
By doing this, pages are no longer cached implicitly, but instead have to be cached *explicitly*, via the "Save offline" button. The button is also updated to cache the JS and CSS alongside some other pages.
There's also a random "annotate" commit thrown in, I didn't want to split it off as its own PR, but it's harmless.
Disabling implicit offline caching is a …
=> Disable implicit offline caching

config/database.yml
This isn't necessary and breaks when running `bin/setup` locally unless DATABASE_URL is defined.
=> Remove URL from staging database config

Gemfile, Gemfile.lock, app/avo/resources/campaign_resource.rb, app/avo/resources/child_resource.rb, app/avo/resources/location_resource.rb, app/avo/resources/session_resource.rb, app/controllers/avo/campaigns_controller.rb, app/controllers/avo/children_controller.rb, app/controllers/avo/locations_controller.rb, app/controllers/avo/sessions_controller.rb, app/models/campaign.rb, app/models/child.rb, app/models/location.rb, app/models/session.rb, config/initializers/avo.rb, config/routes.rb
[Avo](https://github.com/avo-hq/avo) is a Rails engine that provides a batteries-included Rails admin interface, to edit individual models or run rake tasks using a web interface.
Because we don't yet have Devise set up, or authorization, this PR includes a Demo Admin user stub.
Whenever a model is updated, we'll have to ensure the Avo resources are kept in sync with any new fields being added/removed.
TODO:
=> Add backend admin using Avo

app/components/app_status_tag_component.html.erb, app/components/app_status_tag_component.rb, app/helpers/triage_helper.rb, app/helpers/vaccinations_helper.rb, app/models/application_record.rb, app/models/triage.rb, app/views/triage/_patient_row.html.erb, app/views/vaccinations/_patient_row.html.erb, config/locales/en.yml, db/sample_data/example-campaign.json, spec/components/app_status_tag_component_spec.rb
Refactoring of the status tag component to be less use-case specific. This was done to make it easier to add pages like the triage index.
=> Update status tag component

app/assets/stylesheets/application.sass.scss, app/javascript/controllers/child_vaccination_controller.js, app/views/layouts/application.html.erb, app/views/sessions/index.html.erb, app/views/sessions/show.html.erb, app/views/triage/index.html.erb, app/views/triage/show.html.erb, app/views/vaccinations/_patient.html.erb, app/views/vaccinations/index.html.erb, app/views/vaccinations/show.html.erb, tests/offline.spec.ts, tests/vaccinations.spec.ts
Some fields are missing because they aren't part of the data model or are pulled in from consent. We can add them later.
See commits.
=> Update child details card on vaccinations show

app/views/vaccinations/_patient.html.erb
The link doesn't work when the fhir server integration is disabled.
=> Put vaccination history link behind a guard

app/controllers/triage_controller.rb, app/helpers/triage_helper.rb, app/models/triage.rb, app/views/layouts/application.html.erb, app/views/layouts/two_thirds.html.erb, app/views/sessions/show.html.erb, app/views/triage/_patient_row.html.erb, app/views/triage/_patient_triage.html.erb, app/views/triage/_patient_triage_card.html.erb, app/views/triage/show.html.erb, config/routes.rb, spec/requests/triage_spec.rb, tests/triage.spec.ts
Adds triage notes to patient triage page.
Note the change to the routes table (commit: [Nest triage route under sessions/patients](https://github.com/nhsuk/record-childrens-vaccinations/commit/ec6322c5d56efaaeaadd45eaf4369637fdc41571)). This change may be controversial and worth a discussion. If accepted it'll mean changes to the vaccinations routes (probably).
=> Add triage form

app/views/layouts/application.html.erb
=> Fix the page alignment for the breadcrumbs, back-links and connection panel

app/assets/stylesheets/_empty-list.scss, app/assets/stylesheets/application.sass.scss, app/views/layouts/_empty_list.html.erb, app/views/vaccinations/index.html.erb
1. Made the "record vaccinations" index page two-thirds width, to bring closer to the designs
2. Introduced an empty state when there are no vaccinations to record. This will come in handy when tabs are introduced.
1. There's some inline CSS – should I extract it into the CSS files? If so, what could I name the class?
2. Does the proposed microcopy for the empty state make sense?
=> Show empty state when a session has no vaccinations to record

config/settings/test.yml, spec/requests/vaccinations_spec.rb, tests/vaccinations.spec.ts
This should have been done as part of the vaccinations show page update, but it was skipped, because in order to do it, we need to disable the `fhir_server_integration` flag in the tests. This breaks an existing request spec. It's been commented out for now, as the `fhir` integration is less important than the model office work.
=> Update vaccinations end to end spec

app/assets/stylesheets/_action-tag.scss, app/assets/stylesheets/application.sass.scss, app/components/app_action_tag_component.html.erb, app/components/app_action_tag_component.rb, app/controllers/vaccinations_controller.rb, app/helpers/vaccinations_helper.rb, app/models/campaign.rb, app/views/vaccinations/_patient_row.html.erb, app/views/vaccinations/index.html.erb, config/locales/en.yml, tests/vaccinations.spec.ts
Update the designs of the record vaccinations index page to show actions and outcomes.
=> Record vaccinations: display actions and outcomes

app/views/triage/_patient_triage.html.erb, app/views/triage/_patient_triage_consent_response.html.erb, app/views/vaccinations/_patient.html.erb
One issue with this approach is that we're using a `triage/` partial in a vaccinations view. Ideally, we'd want to componentise this. In the interest of speed, let's kick that to later.
Humanise consentee in consent card so that `grandmother` becomes `Grandmother`.
Display consent above patient card info as per the prototype (both triage and vaccination show pages).
=> Display triage info in vaccinations#show page

app/components/app_health_questions_component.html.erb, db/sample_data/example-campaign.json, db/sample_data/example-test-campaign.json, spec/components/app_health_questions_component_spec.rb, spec/factories/consent_responses.rb, tests/triage.spec.ts
When health question response is "Yes", display it with the additional notes: "Yes – Notes go here"
=> Add notes to health questions when response is yes

app/components/app_patient_card_component.html.erb, app/views/sessions/_session_row.html.erb, app/views/sessions/show.html.erb, app/views/triage/_patient_row.html.erb, app/views/triage/_patient_triage_consent_response.html.erb, app/views/vaccinations/_patient_row.html.erb, app/views/vaccinations/confirm.html.erb, config/initializers/date_formats.rb, config/initializers/time_formats.rb, spec/components/app_patient_card_component_spec.rb
The NHS Digital Service Manual [says the following about dates](https://service-manual.nhs.uk/content/numbers-measurements-dates-time#dates):
> We use this format: 6 August 2018.
=> Standardise formatting of dates and times, make more Rails-idiomatic

Gemfile
Since we use it for rake tasks, Heroku expects it to be available in the production env.
This fixes deployments. The review app on this branch should deploy successfully.
=> Move faker out of test group

app/helpers/triage_helper.rb, app/models/consent_response.rb, app/views/triage/_patient_triage_consent_response.html.erb, app/views/vaccinations/_patient.html.erb, tests/triage.spec.ts
* it fixes a couple of UI glitches
* "their other gave consent"
* small g on grandmother
* move a helper method onto the model, closer to the data
=> Minor UI fixes/tweaks about consent responder

app/views/vaccinations/_patient.html.erb
=> Record Vaccs: orange check refusal banner

app/views/vaccinations/_patient.html.erb
This implementation deviates from the prototype designs because the app currently doesn't record the reason for vaccination not occurring.
=> Record vaccs: orange 'could not vaccinate' banner on child page

app/components/app_patient_medical_history_card_component.html.erb, app/components/app_patient_medical_history_card_component.rb, app/controllers/vaccinations_controller.rb, app/models/consent_response.rb, app/views/vaccinations/_patient.html.erb, db/sample_data/example-campaign.json, db/sample_data/example-test-campaign.json, spec/components/app_patient_medical_history_card_component_spec.rb, spec/factories/consent_responses.rb
This component, primarily for the vaccination history page, encapsulates the logic for displaying triage information. The logic is intricate enough to warrant it's own component and a couple helper methods in models; the tests attempt to be thorough at the cost of increasing spec runtime.
This component has to address specific cases, here are a few examples of the changes:
=> Add medical history component

app/controllers/triage_controller.rb, app/views/triage/_patient_triage.html.erb, app/views/vaccinations/_banners.html.erb, app/views/vaccinations/_patient.html.erb
* Add a banner for patients where triage determined "do not vaccinate"
* pull all banner code into a partial
* display the same banners consistently between record and triage child pages
=> More improvements to child page banners

app/components/app_flash_success_component.html.erb, app/components/app_flash_success_component.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, app/views/dashboard/index.html.erb, app/views/sessions/index.html.erb, app/views/triage/index.html.erb, app/views/triage/show.html.erb, app/views/vaccinations/index.html.erb, spec/components/app_flash_success_component_spec.rb
Fixes flash messages on triage and vaccination pages.
Also adds a component to keep the implementation in line across pages.
Various pages have been updated to use the new component, including pages that may not actually be using flash messages anymore. Those pages haven't been tested (e.g TriageController#show ... after a cursory look wasn't sure how to trigger that), but the flash message has been left in. I'd be interested in other's opinions on whether to keep those.
no flash message
=> Triage success flash

app/views/vaccinations/confirm.html.erb
Instead, show a reason. Adding a reason is coming in a follow-up PR.
=> Don't show site when vaccination was not administered

app/controllers/triage_controller.rb, app/models/patient.rb, app/views/triage/_patient_row.html.erb, app/views/triage/index.html.erb, tests/triage.spec.ts
Replaces the date of birth, as per designs. A little bit janky in the current state because we don't filter on the triage page, and we have a "Needs follow-up" record that doesn't have any good reason to need follow-up, but these should be tidied up as part of other work.
=> Triage reason on index page

app/controllers/vaccinations_controller.rb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb, app/views/vaccinations/index.html.erb
This doesn't work without client-side JavaScript. On a mobile, all three text boxes will be visible.
The code leaves room for improvement 😬 (shouldn't be generating JS dynamically).
https://github.com/nhsuk/record-childrens-vaccinations/assets/23801/b7302a9e-e52f-4969-bf6b-ffc2491f5fc6
=> Record vaccinations: Rudimentary client-side patient name search

app/controllers/triage_controller.rb
The index needs full-width, but it's safe to assume that most of the actions should display with a two_thirds layout, mimicking vaccinations_controller.rb
=> Use a two_thirds layout for the ConsentController

app/components/app_patient_medical_history_card_component.html.erb
The notes appeared to get ignored in research if they are before the answers in the reading order.
=> Reposition medical history below medical answers

app/helpers/vaccinations_helper.rb, app/models/vaccination_record.rb, app/views/vaccinations/reason.html.erb
These were pointed out as more descriptive than simply "absent" in the model office session.
The old `absent` state should automatically match the new `absent_from_school` state by virtue of having the same position in the enum.
=> Add absent_from_school and absent_from_session reasons

app/components/app_patient_medical_history_card_component.html.erb, spec/components/app_patient_medical_history_card_component_spec.rb
The triage notes have been moved underneath the health questions, so this heading isn't necessary anymore.
=> Remove medical history notes heading

app/assets/stylesheets/application.sass.scss, app/javascript/controllers/govuk_radios_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/nhsuk_radios_controller.spec.ts, app/javascript/controllers/nhsuk_radios_controller.ts, app/views/vaccinations/_patient.html.erb, config/initializers/govuk_formbuilder.rb, jest.setup.js, package.json, yarn.lock
This should make the forms look more consistent with the prototype.
Bugs:
=> Replace govuk_formbuilder classes with nhsuk ones

app/views/vaccinations/index.html.erb
This title is only visible on mobiles.
=> Fix vaccinations table title in mobile view

app/helpers/patient_session_helper.rb
Found while investigating something else.
The helper method `banner_explanation_for_state` isn't referenced anywhere, and the `banner_explanation` key in `STATUS_COLOURS_AND_TEXT` isn't referenced anywhere other than the deleted helper method, as far as I can tell.
=> Remove unused helper code

config/locales/patient_session_statuses.en.yml, spec/components/app_status_banner_component_spec.rb, spec/factories/patient_sessions.rb, spec/factories/vaccination_records.rb
There is consent and no contraindications, so the patient is ready to vaccinate:
According to the banner, a nurse has deemed the patient can be vaccinated. This isn't true as this record hasn't gone through triage:
The description has been removed.
* Best reviewed commit-by-commit
* I've added extra spec coverage to `app_status_banner_component_spec`
=> Banner bugfix when patient ready to vaccinate without triage

db/sample_data/model-office.json, lib/tasks/generate_model_office_data.rake, spec/factories/patients.rb
* add parents' details into the model office data
* randomise the parent details on the patient factory so they're not just all dads
* give the parent details on the patient record a last name, which matches the kid's last name
* ensure that mum and dad details match between the patient and consent records
=> Update model office data: part 2

app/components/app_gillick_card_component.html.erb, app/controllers/consent_responses_controller.rb, app/models/concerns/patient_session_state_machine_concern.rb, app/models/patient_session.rb, app/views/vaccinations/show.html.erb, config/locales/en.yml, config/locales/patient_session_statuses.en.yml, spec/models/concerns/patient_session_state_machine_concern_spec.rb, tests/gillick.spec.ts
Builds on https://github.com/nhsuk/record-childrens-vaccinations/pull/379.
This adds a new transition from the `added_to_session` state to the `unable_to_vaccinate_not_gillick_competent` state. It updates the controller when the consent_response is being updated so that it shortcuts to this state.
Best reviewed commit by commit.
=> Handle journey where patient is not Gillick competent

app/components/app_banner_component.html.erb, app/components/app_status_banner_component.html.erb, config/locales/patient_session_statuses.en.yml, spec/components/app_status_banner_component_spec.rb
Also make the periods consistent in explanations.
=> Make banner and periods spacing consistent

app/controllers/vaccinations_controller.rb, app/helpers/patient_session_helper.rb, app/models/concerns/patient_session_state_machine_concern.rb, app/models/patient_session.rb, app/views/vaccinations/index.html.erb, app/views/vaccinations/show.html.erb, config/locales/patient_session_statuses.en.yml, spec/models/concerns/patient_session_state_machine_concern_spec.rb
Add the controller action that triggers the state transition, and hide the vaccination CTAs unless the user is able to be vaccinated.
=> Handle "No, I am not vaccinating" journey

app/controllers/vaccinations_controller.rb, app/helpers/vaccinations_helper.rb, app/models/vaccination_record.rb, app/views/vaccinations/show.html.erb
Fixes a couple bugs on vaccinations page:
If a vaccination site is selected (Left arm, etc), this choice isn't persisted if you come back to the vaccination page without completing the vaccination recording journey. This rarely happens, but when it does is noticeable because the Administered / Not administered option is retained.
This fix also simplifies some code around processing the site params.
When a user clicks "Continue" without selecting "Yes, they got the vaccine" or "No, they did not get it" this was resulting in a server error. This now returns with the correct validation error.
No validation was happening for the reason why a vaccine wasn't being administered. This is now fixed.
=> Fix vaccination validation

app/controllers/vaccinations_controller.rb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb, app/views/vaccinations/index.html.erb, tests/default_batch.spec.ts, tests/vaccinations.spec.ts
This PR moves the tab partitioning logic out of the view and into the controller.
=> Tab counts in record area

app/controllers/triage_controller.rb, app/views/triage/_patients_with_dob.html.erb, app/views/triage/_patients_with_triage_reasons.html.erb, app/views/triage/index.html.erb, tests/consent.spec.ts, tests/example_data.ts, tests/triaging_patients.spec.ts, tests/viewing_patients_in_triage.spec.ts
This PR moves the tab partitioning logic out of the view and into the controller.
It's really frustrating having to specify the tab counts in the Playwright specs.
It's doubly frustrating that the tab IDs have the counts in them, as they're derived from the tab label.
=> Tab counts in triage area

app/controllers/consent_responses_controller.rb, app/views/consent_responses/edit_confirm.html.erb, app/views/consent_responses/edit_questions.html.erb, tests/consent.spec.ts, tests/gillick.spec.ts
This adds a triage form and fields that can be filled in to immediately add a triage to the patient. Once consent is granted, .do_consent and .do_triage are run sequentially to bring the patient_session to the vaccinate/do not vaccinate state.
=> Allow triaging during consent journey

config/application.rb, config/routes.rb
Adds a new config variable and exposes it using a route.
```
$ curl http://localhost:4000/sha 
b9f1d67
```
=> Display current short git sha at /sha

app/javascript/controllers/govuk_error_summary_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/nhsuk_error_summary_controller.ts
The summary isn't getting focused because the GOVUK Error Summary JS doesn't match the NHSUK Frontend HTML.
=> Fix nhsuk-error-summary

Gemfile, Gemfile.lock, config/initializers/sentry.rb
Generic Sentry integration added. Relies on `SENTRY_DSN` being set in the deployed environment.
This change has been tested, however we don't have a team account on Sentry. At the moment I'm just using a DSN for the organisation "Good Machine" setup on my account; to invite other members to it will require a team, business or open source account, so far as I can see.
=> Add sentry integration

.rubocop.yml, app/controllers/application_controller.rb
This allows us to use `staging` instead of `production` on Heroku.
=> Add password protection to staging environment 

app.json, config/initializers/check_production.rb
We want to ensure that when we release the application, we don't forget to configure certain things, like Active Record Encryption. We can codify these to reduce the chance of this occuring in production mode.
=> Add intitializer for production checks

app/controllers/triage_controller.rb, app/models/triage.rb
This prevents the 500 from occuring due to attempting to progress the state machine with no triage status.
=> Show validation errors when submitting a blank triage

app/views/vaccinations/show.html.erb
This was missing from the table in the show page.
=> Show vaccination method

app/controllers/consents_controller.rb, tests/consent.spec.ts, tests/consent_no_response.spec.ts
This fixes a bug where users are not able to submit a consent multiple times, in scenarios such as:
- Nurse attempts to contact parent
- Parent doesn't reply
- Time passes
- Nurse attempts again, parent replies and agrees
=> Allow resubmitting a consent after "No response" selected

tests/consent_gillick_validations.spec.ts, tests/consent_refused_validations.spec.ts, tests/consent_validations.spec.ts, tests/triage_validations.spec.ts, tests/vaccination_refused_validations.spec.ts, tests/vaccination_validations.spec.ts
These tests that validations errors are displayed on forms. With the complexity of the various form journeys we have, and given the setting that this tool will be used, these are useful to ensure that the service communicates errors in the correct way to nurses.
=> Add validations specs

app/models/concerns/patient_session_state_machine_concern.rb, spec/models/concerns/patient_session_state_machine_concern_spec.rb
Nurses should be able to change a patient between, for example, "Ready to vaccinate" and "Do not vaccinate" at any time.
=> Allow state changes between triage states

app/controllers/application_controller.rb, app/controllers/consents_controller.rb, app/controllers/errors_controller.rb, app/controllers/vaccinations/batches_controller.rb, app/controllers/vaccinations/delivery_site_controller.rb, app/controllers/vaccinations_controller.rb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/unprocessable_entity.html.erb
Users can use the browser back button to return to old forms that are part of the consent journey, resulting in undefined behaviour in the app. This change makes it clearer that what they are doing isn't supported by rendering errors when form pages are requested in an inconsistent state.
This change now renders the error `unprocessable entity` page instead of the form when there no `draft_consent` object on pages that require it. Only the `create` and `new` pages should be able to create these objects. However, a 500 error can still easily be triggered if the user creates another consent object by going back to the `assessing_gillick` page and restarts the journey there.
https://github.com/nhsuk/record-childrens-vaccinations/assets/15608/450e2d74-c19e-4624-9ada-1adbf83d51d6
Unless we …
=> Error when revisiting old forms

app/controllers/consents_controller.rb
This plugs the whole left from a previous PR which the user to revisit gillick assessment when they were already assessed as not being Gillick competent, due to the existing code only checking for the presence of a consent record.
=> Raise UnprocessableEntity when assessing gillick

app/helpers/application_helper.rb, app/views/consent_forms/confirm.html.erb, app/views/consent_forms/start.html.erb, app/views/consents/assessing_gillick.html.erb, app/views/consents/edit_confirm.html.erb, app/views/consents/edit_consent.html.erb, app/views/consents/edit_gillick.html.erb, app/views/consents/edit_questions.html.erb, app/views/consents/edit_reason.html.erb, app/views/consents/edit_who.html.erb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/unprocessable_entity.html.erb, app/views/layouts/application.html.erb, app/views/offline_passwords/new.html.erb, app/views/pages/start.html.erb, app/views/sessions/index.html.erb, app/views/sessions/show.html.erb, app/views/triage/index.html.erb, app/views/triage/show.html.erb, app/views/vaccinations/batches/edit.html.erb, app/views/vaccinations/confirm.html.erb, app/views/vaccinations/delivery_site/edit.html.erb, app/views/vaccinations/edit_reason.html.erb, app/views/vaccinations/history.html.erb, app/views/vaccinations/index.html.erb, app/views/vaccinations/new.html.erb, app/views/vaccinations/show.html.erb, spec/helpers/application_helper_spec.rb
This introduces a h1 helper that automatically sets `content_for(:page_title)`. Currently none of our pages have custom titles, which is an accessibility issue. Every page must also have one (and preferably only one) h1 element, and in most cases the content of the custom title prefix and the h1 will coincide.
TODO:
=> Populate page titles based on h1 content

app/controllers/application_controller.rb, app/controllers/consent_forms/base_controller.rb, app/controllers/consent_forms/name_controller.rb, app/controllers/consent_forms_controller.rb, app/helpers/application_helper.rb, app/views/consent_forms/name/edit.html.erb, app/views/errors/not_found.html.erb, app/views/errors/unprocessable_entity.html.erb, app/views/layouts/application.html.erb, app/views/pages/start.html.erb, config/locales/en.yml
This changes from using the `t('service.name')` translation string to a `@service_name` instance variable that's set by `ApplicationController` and can be overridden by other controllers that inherit from it.
It introduces a new `ConsentForms::BaseController` that can be used for this purpose.
This PR also includes a couple of other small tweaks, see commits.
=> Override service name in consent journeys

app/controllers/consent_forms/edit_controller.rb, app/lib/date_params_validator.rb, config/locales/en.yml, spec/lib/date_params_validator_spec.rb
The approach is taken partially from DfE's FindALostTRN, slightly tweaked here as we don't have form objects and want to reuse model validations.
In this approach we only validate the form inputs, but not the actual parameters required by the date of birth attribute on consent forms. This should make this library usable on other models.
=> Add DateParamsValidator for date_of_birth

Gemfile, Gemfile.lock, app/controllers/consent_forms/edit_controller.rb, app/controllers/consent_forms_controller.rb, app/models/consent_form.rb, spec/factories/consent_forms.rb, spec/models/consent_form_spec.rb, spec/rails_helper.rb
Replace the `on:` context based validation with conditional validation that relies on specifying a `form_step`. This also makes the validations fire off for previous steps, and at the end for the final `record` step.
Unifies the `*_params` methods in the EditController into one `update_params` method.
`required_for_step?` takes an optional `exact` parameter, for transient steps like the `school` one that ask a question but don't actually save a field to the database (and shouldn't be re-validated on other steps).
Overall approach based on:
https://www.joshmcarthur.com/2014/12/23/rails-multistep-forms.html
=> Define steps in ConsentForm

app/models/consent_form.rb, spec/models/consent_form_spec.rb
We should only present the offer to have a nurse contact a user to administer an injection only if the reason is not:
- Vaccine already received
- Vaccine will be given elsewhere
This adds a new method and uses it in the form_steps. It also adds more test coverage to the method.
=> Only offer injection for specific reasons

app/assets/stylesheets/application.sass.scss, app/controllers/consent_forms/edit_controller.rb, app/helpers/consent_forms_helper.rb, app/models/consent_form.rb, app/views/consent_forms/confirm.html.erb, app/views/consent_forms/edit/contact_method.html.erb, app/views/consent_forms/edit/parent.html.erb, app/views/vaccinations/show.html.erb, config/locales/en.yml, spec/components/app_flash_message_component_spec.rb, spec/models/consent_form_spec.rb, tests/parental_consent.spec.ts, tests/parental_consent_refused.spec.ts
Follows the new design in the prototype, allowing users to specify that there is no preferred contact method they need, unlike the old design.
See commits, first is unrelated to this work, but too small to PR on its own.
See https://github.com/nhsuk/consent-for-vaccinations-prototype/pull/97
=> Move contact method to separate page

app/models/consent_form.rb, app/views/consent_forms/edit/injection.html.erb, config/locales/en.yml, spec/models/consent_form_spec.rb, tests/parental_consent_refused.spec.ts
`presence: true` makes the "false" option the same as selecting nothing at all. `inclusion` works better.
=> Allow users to answer "No" when refusing contact for an injection

app/controllers/consent_forms/edit_controller.rb, app/views/consent_forms/confirm.html.erb
Depends on https://github.com/nhsuk/record-childrens-vaccinations/pull/518.
This sets `skip_to_confirm=true` as a parameter on most of the change links from the confirmation page. If this is set, we then redirect the user to the confirmation page after they submit the step.
See commits.
=> Skip to confirmation page if param is set

.rubocop.yml, lib/example_campaign_generator.rb, spec/fixtures/example-flu-campaign-42.json, spec/fixtures/example-hpv-campaign-42.json, spec/lib/example_campaign_generator_spec.rb
This adds random flu case generation (health questions and triage notes). It includes a bit of refactoring to make it a bit more streamlined. It also adds a spec for flu data re-using the "model office" preset.
It's a big commit so here's a breakdown:
- Hardcode counts in presets instead of calculating it from the lengths of generated data ... as the methods used to generate the data have been refactored to take a `count` argument.
- Significant refactoring of the `health_question_responses_*` methods that used CSV to generate data:
- Call them `cases_*`.
- Add flu versions of the methods.
- Add a `count` parameter so that we can optimise how the flu cases are generated. This also means moving more logic into these methods since how we generate X CSV records for HPV is different from how …
=> Flu health questions

app/controllers/dev_controller.rb, lib/load_example_campaign.rb, lib/tasks/load_campaign_example.rake
Add `LoadExampleCampaign` and use it from the `load_example_campaign` Rake task and from `/reset`.
This was motivated by strange behaviour when using `/reset` whereby for each time `/reset` was triggered, the action would trigger the task n+1 times. This wasn't noticeable when we the HPV campaign was being created with `find_or_create`, but with the new tests where we've added another campaign which simply uses `create`, we were getting many copies of the same campaign and related data.
=> Load example campaign

app/avo/resources/team_resource.rb, app/controllers/avo/teams_controller.rb, app/controllers/dev_controller.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, config/environments/test.rb, db/sample_data/example-flu-campaign.json, db/sample_data/example-test-campaign.json, db/sample_data/model-office.json, lib/example_campaign_data.rb, lib/example_campaign_generator.rb, lib/load_example_campaign.rb, lib/tasks/generate_example_campaign.rake, tests/session_authorisation.spec.ts, tests/shared/sign_in.ts, tests/triage_authorisation.spec.ts, tests/vaccination_authorisation.spec.ts
**NB: This PR depends on #533**
Add authorisation to triage and vaccination controllers. Users will only be able to see the patients that are in campaigns that their team are running.
In addition to adding the policies, a lot of the work was uplifting the testing environment:
- Allow error pages to be rendered in the test environment
- Allow usernames to be specified when generating example campaigns (to support consistent usernames in tests)
- Add example flu campaign and load it in `/reset`
- And, of course, adding tests for the triage and vaccinations pages
=> More authorisationz

docs/architecture-future.adoc, docs/architecture.adoc, docs/diagrams/component-view-future.puml, docs/diagrams/component-view.puml, docs/diagrams/container-view-future.puml, docs/diagrams/container-view.puml, docs/diagrams/context-view-future.puml, docs/diagrams/context-view.puml, docs/diagrams/development-process-overview.puml, docs/diagrams/failed-malicious-get-of-csrf.puml, docs/diagrams/failed-malicious-offline-post-without-csrf.puml, docs/diagrams/failed-malicious-post-with-csrf.puml, docs/diagrams/failed-offline-post-with-outdated-csrf.puml, docs/diagrams/malicious-offline-post-without-csrf.puml, docs/diagrams/service-worker.puml, docs/diagrams/staging-deployment-process.puml, docs/diagrams/successful-offline-post-with-csrf.puml, docs/diagrams/successful-offline-post-without-csrf.puml, docs/diagrams/successful-post-with-csrf.puml, docs/diagrams/testing-deployment-process.puml
This updates the architecture docs, major changes being:
- Copy current architecture docs to a "future" version, reflecting that our current scope is smaller.
- Remove National vaccination record and PDS from current architecture version.
- Add GOVUK Notify to current and future state.
=> Update architecture docs

.github/workflows/test.yml
We were running certain CI tasks using an implicit node version, instead of the explicit one specified in our .tool-versions.
=> Set up node version for all test workflows

Gemfile, Gemfile.lock, app/models/user.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/locales/en.yml, spec/factories/users.rb
Bump the minimum character requirement to 8 characters as per the [design system guidance](https://design-system.service.gov.uk/patterns/passwords/).
Integrate the [devise-pwned_password](https://github.com/michaelbanfield/devise-pwned_password) gem to check that user-submitted passwords haven't been found in any previous security breaches.
The gem has an implicit timeout of 5 seconds, and is also designed to work as a progressive enhancement, so it [won't block our users if the HaveIBeenPwned API goes down](https://github.com/michaelbanfield/devise-pwned_password#considerations):
> The gem is designed to silently swallows errors if the PwnedPasswords service is unavailable, allowing users to use compromised passwords during the time when it is unavailable.
=> Improve password security

app/models/consent_form.rb, app/validators/email_validator.rb, app/validators/phone_number_validator.rb, config/locales/en.yml, spec/models/consent_form_spec.rb, spec/validators/email_validator_spec.rb, spec/validators/phone_number_validator_spec.rb
This PR contains an email and phone validator that's implemented to a similar spec as the GOVUK Notify one. This reduces the chance that emails entered by our users will be rejected by Notify.
It follows their implementation and implements their test cases:
- https://github.com/alphagov/notifications-utils/blob/9311851c105237dc5d770c9f1c0a5ad4c2acb380/notifications_utils/recipients.py#L622
- https://github.com/alphagov/notifications-utils/blob/9311851c105237dc5d770c9f1c0a5ad4c2acb380/notifications_utils/__init__.py#L14
- https://github.com/alphagov/notifications-utils/blob/9311851c105237dc5d770c9f1c0a5ad4c2acb380/tests/test_recipient_validation.py#L118
For the email validator, International Domain Names (IDNs) are not currently implemented. The two test cases with non-UTF-8 characters are …
=> Implement email and phone validator

bin/release
Since updating to 7.1, the `STDOUT` of `bin/rails db:version` has changed to include the current database being used:
```
$ bin/rails db:version
database: manage_vaccinations_development
Current version: 0
```
Before, it was just `Current version: 0`.
=> Fix heroku release script

app/assets/stylesheets/application.sass.scss, app/controllers/consent_forms_controller.rb, app/mailers/consent_form_mailer.rb, app/views/consent_forms/record.html.erb, config/environments/test.rb, tests/parental_consent.spec.ts, tests/parental_consent_change_answers.spec.ts
=> Add consent form confirmation page and email

app/controllers/consent_forms/edit_controller.rb, app/helpers/consent_forms_helper.rb, app/views/consent_forms/edit/address.html.erb, app/views/consent_forms/edit/consent.html.erb, app/views/consent_forms/edit/contact_method.html.erb, app/views/consent_forms/edit/date_of_birth.html.erb, app/views/consent_forms/edit/gp.html.erb, app/views/consent_forms/edit/health_question.html.erb, app/views/consent_forms/edit/injection.html.erb, app/views/consent_forms/edit/parent.html.erb, app/views/consent_forms/edit/reason.html.erb, app/views/consent_forms/edit/school.html.erb, spec/helpers/consent_forms_helper_spec.rb
This fixes the back buttons which were broken for pretty much all health question steps (since the recent change to how they work) and for the "change answers from the confirmation page" journey for the rest of the questions.
=> Fix back buttons

app/mailers/consent_form_mailer.rb, config/locales/en.yml, spec/mailers/consent_form_mailer_spec.rb
We want to include a phone for the model office. But in the future, we'll need to add phones that are different per team.
Also update the passed in personalitation to include things like an apostrophed name and a conditional full name that contains an "(known as X)" variation.
=> Update consent form confirmation mail

app/controllers/consent_forms_controller.rb, app/mailers/consent_form_mailer.rb, app/models/consent_form.rb, app/views/consent_forms/_confirmation_agreed.html.erb, app/views/consent_forms/_confirmation_needs_triage.html.erb, app/views/consent_forms/record.html.erb, spec/mailers/consent_form_mailer_spec.rb, spec/models/consent_form_spec.rb, tests/parental_consent_change_answers.spec.ts
When submitting a consent form, there are 4 possible cases:
- Confirmed (done)
- **Confirmed, but needs triage** :point_left: this PR
- Confirmed, using injection
- Refused
Each case has slightly different content on the confirmation page, and a different email gets sent out to the parent.
See commits.
=> Update consent form confirmation page when consent needs triage

app/controllers/concerns/consent_form_mailer_concern.rb, app/controllers/consent_forms_controller.rb, app/mailers/consent_form_mailer.rb, app/views/consent_forms/_confirmation_injection.html.erb, app/views/consent_forms/_confirmation_refused.html.erb, app/views/consent_forms/record.html.erb, config/locales/en.yml, spec/controllers/concerns/consent_form_mailer_concern_spec.rb, spec/mailers/consent_form_mailer_spec.rb, tests/parental_consent_change_answers.spec.ts
This adds two more mail templates and two more view templates for the remaining consent form final states. This covers the last two scenarios where users refuse consent and agree or disagree to be contacted with the offer of an injection instead.
| | Confirmation page | Email |
|-|-|-|
| Accepted - All health questions "No" | <img width="1222" alt="Screenshot 2023-11-14 at 17 50 33" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/1650875/85300f4a-840c-40ea-9d54-5420f14cf83b"> | <img width="1624" alt="Screenshot 2023-11-14 at 17 51 04" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/1650875/3bdae3fc-25ea-4659-a49f-0e9918d13cfd"> |
| Accepted - At least one health question is "Yes" | <img width="1222" alt="Screenshot 2023-11-14 at 17 51 37" …
=> Add confirmation pages for offering injection and for refused consent

config/locales/en.yml, db/sample_data/example-flu-campaign.json, lib/example_campaign_generator.rb, spec/lib/example_campaign_generator_spec.rb, tests/session_authorisation.spec.ts
The `.upcase` method does not work for a vaccine type of `flu`, as it causes it to render as `FLU`.
=> Fix campaign type capitalisation

app/views/consent_forms/_confirmation_agreed.html.erb, app/views/consent_forms/_confirmation_injection.html.erb, app/views/consent_forms/_confirmation_needs_triage.html.erb, app/views/consent_forms/_confirmation_refused.html.erb, app/views/consent_forms/edit/consent.html.erb, app/views/consent_forms/start.html.erb, app/views/consents/edit_consent.html.erb, app/views/users/shared/_error_messages.html.erb, app/views/vaccinations/_form.html.erb, app/views/vaccinations/confirm.html.erb, app/views/vaccinations/edit_reason.html.erb, config/locales/en.yml, tests/parental_consent_authentication.spec.ts, tests/parental_consent_refused.spec.ts
Use the @session.type instead combined with translation strings.
=> Replace hardcoded references to HPV or flu

app/components/app_status_banner_component.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, app/models/concerns/patient_session_state_machine_concern.rb, app/models/patient.rb, app/models/patient_session.rb, app/views/triage/_patient_row.html.erb, spec/components/app_status_banner_component_spec.rb, spec/models/concerns/patient_session_state_machine_concern_spec.rb
This is partial support for the state machine for multiple consents in the state machine. I haven't thoroughly reviewed all the scenarios to see if it behaves correctly. The tests pass for scenarios where there is only one consent, but we don't have test coverage for multiple consents.
We also have to update the triage/vaccination flows. For now, this just stubs out the respective places where @consent is defined to use the `.first` consent, which is similar to the previous code.
=> Update state machine to take into account multiple consents

app/controllers/consents_controller.rb, app/models/concerns/patient_session_state_machine_concern.rb, app/views/consents/index.html.erb
This queries the list of patient_sessions and splits them into the respective categories that match the tabs in the design.
The tabs contain just the number of items in each category for now. The tables are coming in a follow-up PR, as componentised versions of the partials used for tables in the other sections.
This moves some of the `consent_given?` and associated methods out of the state machine concern and into the `patient_session` model.
=> Display basic tabs in consents index page

config/initializers/devise.rb
It's coming from Devise and can be removed by specifying the secret_key_base explicitly: https://github.com/heartcombo/devise/issues/5644
=> Remove deprecation warning

app/components/app_patient_page_component.html.erb, app/components/app_patient_page_component.rb, app/views/triage/show.html.erb, app/views/vaccinations/show.html.erb, spec/components/app_patient_page_component_spec.rb, tests/triage.spec.ts
Beginning of incremental approach to moving to the new child/patient page design.
This PR simply adds a `AppPatientPageComponent` and moves the common components between the triage and the vaccinations show pages into it. No visual changes and the only changes to journey tests are to add checks for the Back button in the triage journey.
=> Make show pages one

app/components/app_empty_list_component.rb, app/components/app_patient_table_component.rb, app/views/consents/index.html.erb, app/views/layouts/_empty_list.html.erb, app/views/triage/_patients_with_dob.html.erb, app/views/triage/_patients_with_triage_reasons.html.erb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb, spec/components/app_empty_list_component_spec.rb, spec/components/app_patient_table_component_spec.rb
This adds a reusable table component that can be expanded and reused across the consents/triage/vaccinations index pages.
=> Add table to consents index

app/components/app_consent_card_component.html.erb, app/components/app_consent_card_component.rb, app/components/app_details_component.rb, app/components/app_patient_page_component.html.erb, app/components/app_patient_page_component.rb, app/views/triage/show.html.erb, app/views/vaccinations/show.html.erb, spec/components/app_consent_card_component_spec.rb, spec/components/app_details_component_spec.rb, spec/components/app_patient_page_component_spec.rb, spec/factories/consents.rb, tests/nurse_consent_during_vaccination.spec.ts, tests/nurse_consent_gillick.spec.ts, tests/nurse_consent_gillick_refused.spec.ts, tests/nurse_consent_gillick_validations.spec.ts, tests/nurse_consent_refused_during_vaccination.spec.ts, tests/vaccination.spec.ts
This moves the rendering of the consent section of the patient's page to the patient's page component. Not all of the new designs have been implemented, seeing as this PR is already pretty large they'll come as follow-up PR(s). Known issues:
- "Assess Gillick competence" button is missing
- "No response given" should be "No response yet" with styling changes -- also, the spacing between the text and the button here is different from the new design. However, the new design has a hidden field between these two which is adding this space. Is this space intentional?
- Open health questions for "Triage needed" patients
- Clear green "Consent given" and red "Consent refused"  messages
- Update consent fields in consent response section
- Making consent response sections closable
- Support …
=> Merge consent on triage and vaccinations pages

app/views/sessions/_session_row.html.erb, app/views/sessions/index.html.erb, tests/session_authorisation.spec.ts, tests/shared/index.ts
This PR adds `session.location.town` and `session.location.postcode` to each session row. Also, it changes the link to show the `session.location.name`, not `session.name`. Is location information guaranteed to be always available, or does it require checking for the presence of these values, first?
It also updates the table to use the responsive variant provided by the NHS Design System. While not perfect (right aligned values, hmmm), it adapts better to smaller screens than the non-responsive table.
| - | - |
| <img width="378" alt="Screenshot 2023-11-30 at 13 32 06" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/fd57670e-8697-47da-84b7-3e49d4aa5a34"> | <img width="378" alt="Screenshot 2023-11-30 at 13 37 49" …
=> Update session table display to include town and postcode, make responsive

app/assets/stylesheets/_utilities.scss, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, app/views/sessions/index.html.erb
[Fixes issue with column alignment in different campaign sessions](https://github.com/nhsuk/manage-childrens-vaccinations/pull/634#issuecomment-1833848701)
Also uses `app-u-*` (to keep with NHSUK Frontend conventions), and groups all utility styles together in one stylesheet.
=> Constrain column widths in session tables

app/components/app_patient_table_component.rb, app/controllers/consents_controller.rb, app/views/consents/index.html.erb, app/views/consents/show.html.erb, config/routes.rb, spec/components/app_patient_table_component_spec.rb, spec/rails_helper.rb, tests/consent.spec.ts
Updates the names in the patient table component to link to the consents show page. This is passed in as a `route` argument which we can customise when we reuse this component across the other sections.
=> Consents show page

app/avo/resources/consent_form_resource.rb, app/avo/resources/consent_resource.rb
Adds better formatting of the JSON health question and answer fields in the `consent` and `consent_form` resources. Without this when editing the a consent record Avo somehow modified the healh questinos JSON, it stripped the topmost wrapping `[]`.
Also fixes complaints about `datetime` not being a field type in these resources.
| Viewing health questions before | Viewing health questions after |
|-|-|
| ![image](https://github.com/nhsuk/manage-childrens-vaccinations/assets/15608/a355a8f8-e6a1-4402-b33c-265176366f75) | ![image](https://github.com/nhsuk/manage-childrens-vaccinations/assets/15608/4478eb7a-64f4-4cbe-aeff-ec4ef5ed7872) |
| Editing health questions before | Editing health questions after |
|-|-|
| ![image](https://github.com/nhsuk/manage-childrens-vaccinations/assets/15608/5514 …
=> Fix consent fields in avo

app/components/app_consent_component.html.erb, app/components/app_consent_component.rb, app/components/app_consent_details_component.rb, app/components/app_consent_response_component.rb, app/components/app_details_component.rb, config/locales/en.yml, spec/components/app_consent_component_spec.rb, spec/components/app_consent_details_component_spec.rb, spec/components/app_consent_response_component_spec.rb, spec/factories/patient_sessions.rb
Updated consent section:
- make details collapsable. These are closed by default when the user has reached an outcome of do not vaccinate or vaccinated
- added "Contact parent or guardian" if consent is refused. This should also show up in the future when conflicting consents state is added. ❗*These don't go to the right place yet, there isn't an appropriate journey for this yet.* ❗ 
- support multiple consent responses. The consent responses are grouped together by the parent giving the response
|--------|------|
| ![image](https://github.com/nhsuk/manage-childrens-vaccinations/assets/15608/1f4f6fcb-9539-49e3-aa24-438409564cac) | ![image](https://github.com/nhsuk/manage-childrens-vaccinations/assets/15608/dc7df30f-8c79-4416-b9ca-de5f32277662) |
=> Support multiple consents and make details collapsable.

app/components/app_consent_response_component.rb, config/locales/en.yml, spec/components/app_consent_details_component_spec.rb, spec/components/app_consent_response_component_spec.rb
> [!Caution]
> This PR is based on #638 which should be merged first.
This adds "online", "phone", etc to the response field in the consent details. Whereas this was hardcoded to "online" before.
=> Display the consent route

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
Also fixes the size of the ‘Sign out’ button, which was appearing to small at the mobile breakpoint; removing `@include nhsuk-font(16);` seemingly does the trick.
=> Add link to ‘School sessions’ to signed in header navigation

app/assets/stylesheets/_table.scss, app/assets/stylesheets/application.scss, app/components/app_patient_table_component.rb, app/views/triage/_patients_with_dob.html.erb, app/views/triage/_patients_with_triage_reasons.html.erb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb
* Remove existing table overrides used for all tables with tabs
* Add patient specific table modifier to present denser rows
* Ensure ‘By name’ filter label aligns with table headers
| - | - |
| <img width="980" alt="Before screenshot." src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/db547827-2557-4a59-bb07-e557d9856c73"> | <img width="980" alt="After screenshot." src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/fcdf69b7-1697-4827-b61f-365d8bbec29b"> |
=> Update design of patient tables

README.md, app/views/triage/_patient_row.html.erb, db/sample_data/example-flu-campaign.json, db/sample_data/example-hpv-campaign.json, db/sample_data/model-office.json, lib/example_campaign_generator.rb, spec/factories/consents.rb, spec/factories/patients.rb, spec/lib/example_campaign_generator_spec.rb, tests/shared/index.ts, tests/triage.spec.ts, tests/vaccination_authorisation.spec.ts
This builds on the previous `match_mum_and_dad_info_to_consent` method. The previous way would massage the patient data based on the randomly generated consent data.
This new approach instead purposefully generates a number of consent objects that plausibly match the patient details. It also makes sure that situations where there are 2 consents are uniformly from a mum and a dad, and that situation with 3 consents are from a mum, dad, and granddad.
There's a few more commits that do related work in this area of making the factories more robust/predictable.
See commits.
=> Match mum/dad to patient records

app/components/app_patient_page_component.html.erb, app/components/app_patient_page_component.rb, app/components/app_vaccinate_form_component.html.erb, app/components/app_vaccinate_form_component.rb, app/views/vaccinations/show.html.erb, spec/components/app_patient_page_component_spec.rb, spec/components/app_vaccinate_form_component_spec.rb
This change doesn't change the journey much, aside from making the vaccination card visible on all the pages. This isn't ideal but I want to get this change in before we go down the rabbit-hole of adding session-awareness and other changes to stuff like the journey (hiding the delivery site on the patient page).
=> Move vaccination card to patient page component.

copilot/.workspace, copilot/environments/staging/manifest.yml, copilot/webapp/manifest.yml, docs/aws-copilot.md
* Changed the name of the application
* Modified the base manifest file to include subdomains under the environment variables
* Modified the environment manifest file to include certificate ARNs
* Updated the docs with newer instructions
=> Add certificates to AWS Copilot setup

README.md, app/components/app_vaccinate_form_component.rb, app/controllers/dev_controller.rb, app/models/patient_session.rb, app/models/session.rb, lib/example_campaign_data.rb, lib/load_example_campaign.rb, lib/tasks/load_campaign_example.rake, spec/components/app_patient_page_component_spec.rb, spec/components/app_vaccinate_form_component_spec.rb, spec/factories/patient_sessions.rb, spec/factories/sessions.rb, spec/models/patient_session_spec.rb, spec/models/session_spec.rb
The patient must be ready to vaccinate and the session must be in progress for the vaccination form to be shown.
This doesn't change the appearance of the vaccination form.
=> Conditionally render vaccination forms

Gemfile.lock, app/components/app_consent_component.html.erb, app/components/app_consent_component.rb, app/components/app_health_questions_component.rb, app/components/app_patient_medical_history_card_component.html.erb, app/components/app_patient_medical_history_card_component.rb, app/views/nurse_consents/edit_confirm.html.erb, spec/components/app_health_questions_component_spec.rb
This updates the various calls to run on the array of consents instead of a singular consent.
Moves the `# HACK` comment deeper to the component stack, which will be addressed in a future commit/PR.
First commit is unrelated and came up from my editor.
=> Make AppConsentComponent work with multiple consents 

app/components/app_consent_component.rb, app/components/app_patient_page_component.html.erb, app/components/app_patient_page_component.rb, app/components/app_triage_form_component.html.erb, app/components/app_triage_form_component.rb, app/models/concerns/patient_session_state_machine_concern.rb, app/views/triage/show.html.erb, spec/components/app_patient_page_component_spec.rb, tests/triage.spec.ts, tests/vaccination_refused_validations.spec.ts
Move the triage form card rendering to the patient page.
This doesn't change the design, but it does add conditional rendering of the triage form. This adds a `next_step` to the state machine to bring this one bit of logic closer to the state machine.
=> Add AppTriageFormComponent

app/views/nurse_consents/assessing_gillick.html.erb, app/views/nurse_consents/edit_confirm.html.erb, app/views/nurse_consents/edit_consent.html.erb, app/views/nurse_consents/edit_gillick.html.erb, app/views/nurse_consents/edit_questions.html.erb, app/views/nurse_consents/edit_reason.html.erb, app/views/nurse_consents/edit_who.html.erb, app/views/vaccinations/_form.html.erb, app/views/vaccinations/batches/edit.html.erb, app/views/vaccinations/confirm.html.erb, app/views/vaccinations/delivery_site/edit.html.erb, app/views/vaccinations/edit_reason.html.erb, app/views/vaccinations/history.html.erb
Show patient name as page/form caption in consent and vaccination flows
=> Design snags (Part 2: Show patient name in page captions)

app/components/app_patient_page_component.rb, app/components/app_triage_form_component.html.erb, app/components/app_triage_form_component.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, spec/components/app_triage_form_component_spec.rb, spec/factories/triage.rb, tests/triage.spec.ts
Creates multiple triage notes by default now, populating the triage form with the status of the latest triage entry if available.
e.g. for a patient that has been kept in triage, the triage form on their page will now look like this by default:
And saving the triage there will create new triage note that will be displayed in the "Triage notes" section.
=> Create multiple triage notes

app/views/triage/index.html.erb, tests/triage.spec.ts, tests/triage_authorisation.spec.ts, tests/triage_validations.spec.ts
Follow the design from the prototype.
This is spun out from https://github.com/nhsuk/manage-childrens-vaccinations/pull/669.
=> Rename Needs triage tab to Triage needed

app/controllers/consents_controller.rb, app/controllers/sessions_controller.rb, app/controllers/triage_controller.rb, app/models/consent.rb, app/models/patient_session.rb, app/views/sessions/show.html.erb
I had a quick go at adding relevant stats to the session page:
- Number of patient in cohort
- Patients with consent given
- Patients with consent refused
- Patients without a response
- Patients needing triage
- Patients ready to vaccinate
To get some of these numbers, it seems as if various states are combined in the consents, triage and vaccination and controllers; it doesn’t seem right to repeat that same or similar logic in the sessions controller too.
All of which is to say is, here’s a page where we’d want to show some information we already show in other places, maybe some broader refactoring is required to make it easier to build out the above?
=> Show stats on session page

app/components/app_vaccinate_form_component.html.erb, app/components/app_vaccinate_form_component.rb
Use `(upper position)` for the left and right arm sites.
=> Update vaccination site values and labels

app/components/app_flash_message_component.html.erb, app/javascript/controllers/index.js, app/javascript/controllers/nhsuk_notification_banner_controller.ts, app/views/vaccinations/index.html.erb, spec/components/app_flash_message_component_spec.rb
Change the classnames and module to `nhsuk-notification-banner` across the board. This uses the `govuk-notification-banner` JS, which is a total hack, but it seems to work.
=> Fix notification banner

app/controllers/nurse_consents_controller.rb, app/views/consents/index.html.erb, app/views/consents/show.html.erb, tests/full_journey.spec.ts, tests/nurse_consent_no_response.spec.ts, tests/nurse_consent_refused.spec.ts, tests/nurse_consent_refused_during_vaccination.spec.ts
When nurses get consent for a patient from the consents page, return them to the consents page when done. Likewise, when getting consent during vaccination, return them to the vaccination pages (only necessary for consent refused as the consent given flow already did this).
=> Return to consent responses page in consent and vaccination flows

app/controllers/nurse_consents_controller.rb, app/models/consent.rb, app/models/session.rb, db/sample_data/example-flu-campaign.json, db/sample_data/example-hpv-campaign.json, lib/example_campaign_generator.rb, spec/factories/consents.rb, spec/lib/example_campaign_generator_spec.rb, tests/full_journey.spec.ts, tests/nurse_consent_during_vaccination.spec.ts, tests/nurse_consent_gillick.spec.ts, tests/nurse_consent_no_response.spec.ts
This only works with campaigns that have one vaccine.
TODO:
=> Use health_questions from db when creating consent

app/assets/stylesheets/_card.scss, app/assets/stylesheets/_empty-list.scss, app/assets/stylesheets/application.scss, app/components/app_card_component.rb, app/components/app_empty_list_component.html.erb, app/components/app_empty_list_component.rb, app/views/consents/index.html.erb, app/views/triage/index.html.erb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb, spec/components/app_card_component_spec.rb, spec/components/app_empty_list_component_spec.rb, spec/components/app_status_banner_component_spec.rb
Refactor `AppEmptyListComponent` to use `AppCardComponent`. Currently, this component contains hard-coded values, so maybe it should be a partial instead? However, I can imaging it needing to become a component in the future, so maybe this is fine?
Also…
* Use `app-` prefix for card colours (this is what I should have done in the prototype)
* Allow the card component to have a different heading size, and additional classes added to the container. This enables the above refactor of the empty list component.
| - | - |
|  <img width="980" alt="Screenshot 2023-12-11 at 12 33 17" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/5654168f-ca12-4afd-9522-b0dc98dc3268"> | <img width="974" alt="Screenshot 2023-12-11 at 12 33 36" …
=> Refactor empty list component to use card component

app/controllers/nurse_consents_controller.rb, tests/nurse_consent_during_vaccination.spec.ts, tests/nurse_consent_no_response.spec.ts, tests/nurse_consent_refused.spec.ts, tests/nurse_consent_refused_during_vaccination.spec.ts, tests/nurse_consent_validations.spec.ts
This is temporary. The prototype has a better design but it's more effort to implement at this stage.
This prefills the fields when a user attempts to submit consent for a patient whose parent didn't respond to requests for cconsnt.
=> Prefill consent

app/controllers/nurse_consents_controller.rb, tests/full_journey.spec.ts, tests/nurse_consent_no_response.spec.ts, tests/nurse_consent_refused.spec.ts, tests/nurse_consent_refused_during_vaccination.spec.ts
"Record saved" is more accurate than "Consent saved."
=> Update banner content for nurse consent journey

app/controllers/vaccinations_controller.rb, app/helpers/patient_session_helper.rb, app/models/concerns/patient_session_state_machine_concern.rb, config/locales/patient_session_statuses.en.yml, spec/models/concerns/patient_session_state_machine_concern_spec.rb
This requires updating the state machine to take this state into account.
This brings us a little bit closer to properly supporting multiple consents.
=> Display conflicting consent banner

app/assets/stylesheets/_header.scss, app/assets/stylesheets/_summary-list.scss
Removing some of the styles we’re applying to the header improves the responsiveness of the logo+service name lock-up. Possibly due to upstream improvements in NHS.UK Frontend?
=> Improve header adaption

app/views/nurse_consents/edit_questions.html.erb
| - | - |
| <img width="685" alt="Screenshot 2023-12-11 at 14 34 51" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/3362015c-150a-492a-8b32-2cff644e9043"> | <img width="665" alt="Screenshot 2023-12-11 at 14 43 46" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/fc7ea9a9-035e-49fa-8070-5d317a6acadb"> |
=> Use same ordering and heading for triage question in consent journey

app/components/app_consent_component.html.erb, app/components/app_consent_component.rb, app/controllers/nurse_consents_controller.rb, app/models/concerns/patient_session_state_machine_concern.rb, tests/nurse_consent_conflicting_consent.spec.ts, tests/shared/index.ts
Allow nurses to contact a parent and edit their consent if they accept on the phone.
Stretch:
=> Allow editing a consent

app/components/app_consent_component.rb, app/components/app_consent_details_component.rb, app/models/consent.rb, app/views/nurse_consents/edit_confirm.html.erb
Use the patient's name and hide the contact details and relationship.
=> Display consent correctly for gillick consent

app/components/app_consent_component.html.erb, app/controllers/nurse_consents_controller.rb, app/models/concerns/patient_session_state_machine_concern.rb, db/sample_data/model-office.json, spec/models/concerns/patient_session_state_machine_concern_spec.rb, tests/nurse_consent_no_response.spec.ts
Previously, we would save these as a draft consent record with no recorded_at. Attempting to submit another consent later would surface the details and you'd be able to continue.
Instead, we want to display the consent records in the consent card. The patient session should stay in the same state ("Added to session") when handling consent in this way.
The design isn't final but the functionality is there to test.
=> Display attempts to contact a parent for consent

app/components/app_consent_response_component.rb
This is a more relevant value of when consent was attempted.
=> Display recorded_at on consents

copilot/webapp/manifest.yml
Adding more memory for the webapp cluster so the IRB console can be accessed without crashing the app.
=> Add more memory to the webapp cluster

app/components/app_consent_component.html.erb, app/controllers/dev_controller.rb, app/controllers/manage_consents_controller.rb, app/views/manage_consents/who.html.erb, config/locales/en.yml, config/routes.rb, db/seeds.rb
This is the start of a Wicked rewrite of the NurseConsentsController. The new controller is hidden behind a feature flag and will be built piecemeal, in parallel to the old one.
This first PR implements a stubbed version of the first step (`/consents/who`) as well as the surrounding feature flagging machinery and route. Following PRs will implement the next steps in order.
There are no tests for this, as the intention is to reuse the existing `nurse_consents_*` tests, once the flow is working end to end, to prove that the new implementation is functionally identical to the old.
Review without significant whitespace for the changes to the `routes.rb`.
=> Add ManageConsentsController

app/components/app_consent_component.html.erb, app/controllers/manage_consents_controller.rb, app/controllers/nurse_consents_controller.rb, app/models/consent.rb, app/views/manage_consents/who.html.erb, config/routes.rb, spec/factories/patients.rb
This populates the first page of the new nurse consents journey and sets up the rest of the validations/machinery required to get the rest of the journey in.
One thing to note is that the journey now creates a Consent before the first step, in order to have an ID to allow editing of the consent on the following steps.
See commits.
=> Update manage_consents#who template

app/controllers/manage_consents_controller.rb, app/models/consent.rb, app/views/manage_consents/confirm.html.erb, config/locales/en.yml
Implements a streamlined version of the edit_confirm page from the old journey.
=> Add :confirm step to ManageConsent journey

config/initializers/flipper.rb
We were getting warnings pop up during tests after a database reset (rails db:reset). This approach appears to remove the warnings when testing.
=> Move feature initialization from seeds

db/sample_data/pentest-campaign-1.json, db/sample_data/pentest-campaign-2.json, lib/tasks/generate_example_campaign.rake, lib/tasks/load_campaign_example.rake
These will be used in the pentest env as dummy data for testing. It includes logins for pentesters and ensures one session is in progress for each day of pen testing.
```
rails db:schema:load
rails db:seed
rails load_campaign_example[db/sample_data/pentest-campaign-1.json]
rails load_campaign_example[db/sample_data/pentest-campaign-2.json]
```
To load these up in the pentest environment do:
=> Add pentest campaigns

app/controllers/manage_consents_controller.rb, app/models/consent.rb
Add a validation to the model and match the params correctly in order to trigger it.
Set @triage on questions step in ManageConsents journey.
=> Validate health questions in ManageConsents journey

app/components/app_health_questions_component.rb, app/controllers/manage_consents_controller.rb, app/models/consent.rb, app/views/manage_consents/confirm.html.erb, app/views/manage_consents/questions.html.erb, app/views/manage_consents/who.html.erb
This completes the end to end ManageConsent journey.
Gillick competence is next to do in a follow-up, and then we can flip the feature flag and run the tests against the new journey to see what else needs aligning.
=> Successfully submit consent in ManageConsents journey

db/sample_data/example-flu-campaign.json, db/sample_data/example-hpv-campaign.json, spec/factories/patients.rb, spec/lib/example_campaign_generator_spec.rb, tests/shared/index.ts, tests/vaccination_authorisation.spec.ts
Use Faker's `cell_phone` to generate a mobile number for patient's parents in factories.
However, in making this change we appear to have fallen down a crevasse where the team names generated for our example campaigns are identical. This doesn't happen for every seed, but it seems to be more common when the seeds are the same.
Having the same team name causes issues when loading the example campaigns because the teams are created with "find_or_*" methods. This could be fixable in the campaign loader, but changing the seed used for the flu campaign seems easier and still quite sensible
The second commit addresses this issue.
The last commit demonstrates how we can use a CSS selector that uses `[id^='tab-name']` to match tabs that begin with, for example, `tab-name`. Since we can't easily …
=> Generate correct fake parent mobile numbers

Procfile.dev, README.md, bin/dev, package.json, yarn.lock
`foreman` doesn't properly forward the echo of input to commands. This means that when using the `debugger` or `binding.pry` statements in Rails, we can't see anything that's being typed into the REPL. This makes debugging difficult.
[`concurrently`](https://github.com/open-cli-tools/concurrently) is a JS CLI tool that can be used as an alternative to foreman. It has a `--handle-input` flag that does what we need.
More context: https://github.com/ddollar/foreman/issues/703
=> Replace foreman with concurrently

db/sample_data/example-flu-campaign.json, db/sample_data/example-hpv-campaign.json, lib/example_campaign_data.rb, lib/example_campaign_generator.rb, lib/load_example_campaign.rb, spec/factories/consent_forms.rb, spec/lib/example_campaign_generator_spec.rb, tests/parental_consent_authentication.spec.ts, tests/shared/index.ts, tests/vaccination_authorisation.spec.ts
Starter for 10 of generating example consent forms. The db structure for these may change, but this data is meant to help us start to build the consent form matching pages out and we can roll-forward changes.
=> Generate unmatched example consent forms

app/components/app_health_questions_component.rb, app/controllers/manage_consents_controller.rb, app/views/manage_consents/confirm.html.erb, config/initializers/flipper.rb, spec/components/app_consent_component_spec.rb, spec/components/app_health_questions_component_spec.rb, tests/full_journey.spec.ts, tests/nurse_consent_during_vaccination.spec.ts, tests/nurse_consent_gillick.spec.ts, tests/nurse_consent_gillick_refused.spec.ts, tests/nurse_consent_gillick_validations.spec.ts, tests/nurse_consent_no_response.spec.ts, tests/nurse_consent_refused.spec.ts, tests/nurse_consent_refused_validations.spec.ts, tests/nurse_consent_validations.spec.ts
Depends on https://github.com/nhsuk/manage-childrens-vaccinations/pull/763.
Switches to the new `ManageConsents` journey and `health_answers` for handling all nurse-facing consent flows. Updates the tests where necessary.
See commits.
=> Enable :new_consents

app/components/app_patient_details_component.html.erb, app/components/app_patient_details_component.rb, app/views/consent_forms/show.html.erb, spec/components/app_patient_details_component_spec.rb
Update `AppPatientDetailsComponent` to support displaying child details from a `ConsentForm`.
=> Add child details section to consent response page

config/initializers/check_production.rb, copilot/webapp/manifest.yml
Encryption is now on by default in all environments.
Remove `SKIP_PRODUCTION_CHECKS` env var in the pentest env as it's no longer necessary.
=> Remove encryption check in production

config/initializers/session_store.rb
This prevents the browser from sending cookies if it's not connecting over HTTPS.
=> Set up secure cookies in production

app/controllers/errors_controller.rb
Errors should not require the user to be signed in to display correctly.
=> Display errors correctly when not signed in

config/environments/production.rb
This should hopefully allow us to enable `force_ssl` which also enables TLS on the application level, while allowing the healthcheck to work.
=> Disable SSL on /ping endpoint

app.json, config/environments/production.rb, copilot/webapp/manifest.yml
Makes the default host setting in prod-like envs more agnostic of the hosting environment.
Also use `RCVAPP__IS_REVIEW` instead of `ENV["IS_REVIEW"]`, and populate `Settings.host` in the AWS envs.
=> Use Settings.host instead of HEROKU_APP_DEFAULT_DOMAIN_NAME 

.dockerignore
These might contain local secrets that shouldn't make it into the container.
=> Ignore settings.local.yml files in Docker build

Dockerfile
Running `npm` scripts can lead to running malware if packages are compromised.
=> Don't run npm scripts when building docker

db/sample_data/pentest-campaign-1.json, db/sample_data/pentest-campaign-2.json
We agreed that we'd prefer to add them via rake task.
=> Remove pen testers from pentest campaigns

app/models/consent.rb, app/models/consent_form.rb, app/models/health_answer.rb, app/models/patient_session.rb, app/models/triage.rb, app/models/vaccination_record.rb, app/views/vaccinations/confirm.html.erb, config/locales/en.yml
These are intended as a backstop to ensure that nobody can enter in large amounts of data which could serve as a DOS. In cases where validations are scoped to specific steps in a form wizard, this protection is implemented outside of that scope so that if someone circumvents the wizard step for whatever reason, we are still protected. 
The size limits here follow the general rule of thumb where fields that are entered on a single line have a maximum of 255 chars and fields that use a text area have a max of 1023. These numbers are guesses as to what's best, I'd almost prefer to just use 1000 everywhere. Also, the wording is my best guess.
Discussion and suggestions welcome, but we should probably get this merged in before Monday and we can look at updating size limits, wording, etc, …
=> Add length validation on (most) text fields

app/models/patient.rb
Also strip spaces when saving it so that the formatter can display it correctly.
=> Ensure NHS Number only contains digits/spaces

app/avo/resources/consent.rb, app/models/consent.rb, db/migrate/20240108120307_remove_unused_consent_columns.rb, db/schema.rb, lib/example_campaign_data.rb, spec/factories/consents.rb, spec/models/consent_spec.rb
These were originally added before we understood the data model the way we currently do.
=> Remove unused fields from Consent model

copilot/environments/addons/db.yml
This parameter is documented here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-storageencrypted
A feature request for AWS Copilot to include it by default is here:
https://github.com/aws/copilot-cli/issues/4949
And further discussion of encrypting Amazon Aurora DBs is here:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Overview.Encryption.html
It's not clear whether this will trigger a rebuild of the DB on the next deploy, or whether we'll manually need to recreate the environment. The official suggestion is to:
- create a snapshot
- copy it with encryption enabled to create an encrypted snapshot
- create a new db with the encrypted snapshot
- point the app to the new dbcluster
We'll probably just want to …
=> Enable DB encryption at rest

copilot/webapp/manifest.yml
Copilot includes a security group that allows our containers to talk to each other by default. That's being picked up in a pen test and we probably don't need that.
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-security-groups-deny-default
Issue also discussed here:
https://github.com/aws/copilot-cli/issues/2848
=> Deny default access in copilot

copilot/environments/staging/manifest.yml, copilot/webapp/manifest.yml, docs/aws-copilot.md
The `flow_logs` and `deny_default` settings need to sit under different sections.
Remove `deny_default: true` as it breaks the app.
=> Update copilot docs and settings

bin/lint
This removes the default progress reports so that we can better focus on any warning or errors emitted from the linters.
=> Make bin/lint quieter

app/assets/stylesheets/_phase-banner.scss, app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/controllers/parent_interface/consent_forms/base_controller.rb, app/views/layouts/application.html.erb
Add phase banner to application layout, and because the text we show varies between what parents see and what SAIS teams see, set @phase_banner_text using `set_phase_banner_text`, like we do for service name, etc.
=> Add phase banners

app/controllers/pilot_controller.rb, app/views/dashboard/index.html.erb, app/views/pilot/cohort.html.erb, app/views/pilot/manage.html.erb, config/routes.rb, tests/pilot_cohort.spec.ts
Form and upload-handling functionality coming in a follow-up.
=> Add initial cohort upload controller and pages

app/controllers/registrations_controller.rb, app/views/registrations/closed.html.erb, app/views/registrations/new.html.erb, config/locales/en.yml, spec/mailers/consent_form_mailer_spec.rb, tests/pilot_registration.spec.ts
This gets shown when registration is not open, as controlled by a feature flag.
Still need to hear back if this is the right email address to use, though. Will wait for that before merging.
=> Add registration closed page

app/assets/stylesheets/_action-table.scss, app/assets/stylesheets/_utilities.scss, app/assets/stylesheets/application.scss, app/components/app_patient_table_component.rb, app/javascript/application.js, app/views/sessions/index.html.erb, app/views/vaccinations/_patient_row.html.erb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb, package.json, yarn.lock
[action-table](https://github.com/colinaut/action-table) is a web component that progressively enhances tables. It can add sorting, as well as filtering and pagination.
This PR adds `<action-table>` web component, and adds column sorting to school session and patient tables. A follow up PR can add the client-side filters, which will enable showing rows in patient tables that match a client-side filter query.
=> Use `action-table` web component to sort table columns

.github/workflows/test.yml
This makes the videos created by Playwright on test failure available for download. These will show up at the bottom of the action run page as the `playwright-report`artifact.
I've added the globbing character `?` to the path specifier because that causes the `upload-artifact` action to preserve that path in the zipfile. Without it, unzipping the zip file splats the contents of the `playwright-report/` directory into the current dir which is messy and time consuming to clean up if you do it in the wrong place. Not sure why `upload-artifact` doesn't have a better way to do this.
10 days is the maximum retention, presumably set by our open-source status.
=> Add playwright-reports to ci artifacts

app/controllers/pilot_controller.rb, app/views/pilot/manage.html.erb, app/views/pilot/manual.html.erb, config/routes.rb
New link on "Manage pilot" page:
And a copy pasta of the manual:
... etc ...
=> Add pilot manual

app/controllers/pilot_controller.rb, app/models/user.rb, app/views/pilot/manage.html.erb, app/views/pilot/manual.html.erb, app/views/pilot/registrations.html.erb, config/routes.rb, tests/pilot_download_cohort.spec.ts, tests/pilot_upload_cohort.spec.ts
Prerequisites:
- https://github.com/nhsuk/manage-childrens-vaccinations/pull/849
- https://github.com/nhsuk/manage-childrens-vaccinations/pull/850
- https://github.com/nhsuk/manage-childrens-vaccinations/pull/856
This displays all the registrations that have been submitted by parents to participate in the pilot.
TODO:
Coming soon
=> Add /pilot/registrations page

app/javascript/application.js, app/views/sessions/show.html.erb, config/routes.rb
We won't be shipping this in the pilot, and having it in the UI can be confusing.
The JS is commented out because we don't have an easy mechanism of leveraging feature flags in the JS.
Review without whitespace changes.
=> Hide offline working functionality behind feature flag

app/assets/stylesheets/_action-table.scss, app/assets/stylesheets/_button.scss, app/assets/stylesheets/application.scss, app/components/app_patient_table_component.html.erb, app/components/app_patient_table_component.rb, app/components/app_patient_table_filter_component.html.erb, app/components/app_patient_table_filter_component.rb, app/views/consents/index.html.erb, app/views/triage/index.html.erb, app/views/vaccinations/_patient_row.html.erb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb, spec/components/app_patient_table_component_spec.rb
This PR uses the `<action-table-filters>` web component to filter rows in patient tables.
I’ve created a ViewComponent for the filters, which takes a `tab_id` (used in `id` and `for` attributes on the filter fields) and `filter_actions`, a boolean to determine if the filters for actions is shown).
A test for this new component is failing currently, not sure how/what I need to change to clear this.
=> Add filtering to patient tables

app/assets/stylesheets/_tabs.scss, app/assets/stylesheets/application.scss, app/components/app_patient_table_component.html.erb, app/components/app_patient_table_component.rb, app/components/app_patient_table_filter_component.html.erb, app/views/consents/index.html.erb, app/views/triage/index.html.erb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb, app/views/vaccinations/index.html.erb, config/locales/en.yml, spec/components/app_patient_table_component_spec.rb, tests/nurse_consent_conflicting_consent.spec.ts
- Adds (or makes visible) captions for patient tables. This is so that tables are properly labelled, and that in mobile views, they have a clear heading.
- Localises tab labels and table captions for patient views
- Adjust the font sizing of tabs so that the font is 16px between `tablet` and `desktop` breakpoints
- Fix spacing on filter fieldset legend so that it aligns with table caption
- Some light refactoring of `consent_tab` to make it a little DRYer
=> Patient table captions

app/avo/resources/patient.rb, app/controllers/registrations_controller.rb, lib/example_campaign_data.rb, tests/pilot_registration_close.spec.ts
Finishes the work of the previous PR to add a "close pilot for school" journey by ensuring that the registration page does not show when the school's registration is closed.
Also adds a test for the close pilot registration journey.
=> Do not show registration page when school registration is closed

app/controllers/pilot_controller.rb, app/helpers/registration_helper.rb, app/models/location.rb, app/views/pilot/registrations.html.erb
This change ensures the option to close registrations is always available, even if a school has not received any registration responses.
@misaka; feel free to fix the code to prevent the unoptimised database call.
=> Always show schools when managing pilot registrations

app/views/registrations/new.html.erb
Updates terms and conditions on registration form to point participants to the full privacy policy.
The email address to use if participants want to withdraw need to be that for the SAIS team, but we don’t have that in the application yet. I’ll create a follow up PR to add that, and then use that data on this page.
=> Update terms and conditions on registration form

app/assets/stylesheets/application.scss, app/components/app_patient_table_filter_component.html.erb, app/views/edit_sessions/timeline.html.erb
- Update CSS fix for `nhsuk-label` and `nhsuk-fieldset` that normalises the spacing
- Fix the alignment of first label on patient table filter
- Consistent conditional label/fieldset size on session timeline page
=> Update fieldset and label spacing

app/assets/stylesheets/application.scss, app/components/app_breadcrumb_component.html.erb, app/components/app_patient_table_filter_component.html.erb, app/views/parent_interface/consent_forms/confirm.html.erb
- Tweaks previous legend/label spacing (#912), scoping it only to those with `--s` modifier. This also fixes longstanding issue of small fieldset legends appearing bold.
- Move headings into cards, and use `AppCardComponent` on consent confirmation page.
- Refactor `AppBreadcrumbComponent` so that whitespace is removed, fixing issue with too much space around chevron:
| - | - |
| <img width="370" alt="Screenshot 2024-02-01 at 16 48 27" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/fa831898-642c-485f-9d73-8196ffc4a6b0"> | <img width="390" alt="Screenshot 2024-02-01 at 16 46 36" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/9d6f27f9-e648-4824-bf89-9c317e89ceb5"> |
=> Design snags

app/controllers/edit_sessions_controller.rb, app/views/edit_sessions/confirm.html.erb
Horrible temporary hack to just automatically add all patients to a new session, if they haven't been added to a session yet.
=> Add all unassigned patients to new session

app/controllers/sessions_controller.rb, app/models/session_stats.rb, spec/models/session_stats_spec.rb
* Avoid counting draft consent forms when counting unmatched forms
Without this fix, you see an inconsistency:
* Don't count patients in triage or without consent as 'ready to vaccinate'
* Extract a `SessionStats` model to make it easier to test the logic
Best reviewed commit by commit.
=> Session stats: bugfixes

app/views/edit_sessions/cohort.html.erb, app/views/edit_sessions/timeline.html.erb
=> Add session: display dates of birth and session date as human-readable dates

app/models/cohort_list.rb
Graphical spreadsheet editors like Excel, Google Sheets, and Numbers tend to mangle data such as phone numbers (which have a leading 0) when importing CSV data. Using quotes around all fields should help to prevent this.
=> Force quotes when generating cohort CSV

app/assets/stylesheets/registration.scss, app/views/registrations/closed.html.erb, app/views/registrations/confirmation.html.erb, app/views/registrations/new.html.erb
Adds print styles to registration form. Ensures that: 
- conditional fields are shown when form is being printed
- reduces sizing so that form appears across 3 pages of A4 instead of 4.
- hides button and privacy link destination
Preview:
- [before.pdf](https://github.com/nhsuk/manage-childrens-vaccinations/files/14185659/before.pdf)
- [after.pdf](https://github.com/nhsuk/manage-childrens-vaccinations/files/14185658/after.pdf)
=> Add print styles to registration form

app/views/dashboard/index.html.erb
This functionality isn't available in the pilot.
=> Remove unimplemented dashboard links

app/models/cohort_list.rb, app/models/cohort_list_row.rb, spec/models/cohort_list_row_spec.rb, spec/models/cohort_list_spec.rb
Otherwise someone could add a child to a school that belongs to another school, which would make that child visible to the team that owns that school.
=> Validate school ids in cohort list belong to team

app/controllers/application_controller.rb, app/views/sessions/_session_row.html.erb, app/views/sessions/edit.html.erb, config/initializers/flipper.rb, tests/pilot_phase_1.spec.ts
When enabled, this flag restricts the interface and hides links to consent/triage/vaccination pages. It does not restrict the actual routes. It's enabled by default in prod-like environments.
=> Add pilot_phase_1 feature flag

lib/example_campaign_data.rb
The `else` block never gets triggered as all of our example files contain a `sessions` key. So the mapping of `sendConsentAt` -> snake_cased versions didn't work before. The reason we didn't catch this is because we relied on `in_progress=true` which takes the importer down a different path that manually specifies the timestamps.
=> Fix campaign loader

.github/workflows/deploy.yml
This adds the possibility to deploy the application using the GitHub actions UI to the training and staging environments.
`test` is the default which is used for automatic deploys from `main`.
=> Add on-demand deployment option

app/components/app_flash_message_component.html.erb, app/views/consents/index.html.erb, app/views/layouts/application.html.erb, app/views/layouts/two_thirds.html.erb, app/views/pages/start.html.erb, app/views/pilot/registrations.html.erb, app/views/sessions/edit.html.erb, app/views/sessions/index.html.erb, app/views/sessions/show.html.erb, app/views/triage/index.html.erb, app/views/vaccinations/index.html.erb
Before this, the two_thirds layout included a banner, and some pages would also include their own banner.
This changes so that the layout always includes a banner and makes it always span two thirds, which was another previous inconsistency.
=> Remove double flash message banner

.dockerignore
The spec/factories are necessary if we want to run FactoryBot create's in the prod-like envs.
=> Add spec/factories folder to production docker build

config/locales/en.yml
See
- https://design-system.service.gov.uk/patterns/telephone-numbers/#using-example-telephone-numbers
- https://www.ofcom.org.uk/phones-telecoms-and-internet/information-for-industry/numbering/numbers-for-drama
=> Use a valid UK mobile number in error messages

app/controllers/edit_sessions_controller.rb, app/models/session.rb, app/views/edit_sessions/timeline.html.erb, config/locales/en.yml, tests/pilot_journey.spec.ts, tests/session_create.spec.ts
This replaces the field that asks for a day before the session to one that simply asks for a specific day/month/year.
One bug with this approach is that the `DateParamsValidator` comes before the validations on the model, so if there are errors there, the errors on the model don't get surfaced and re-appear once the date is entered correctly. I'd like to revisit the `DateParamsValidator` implementation at some point and hopefully get it working more similarly to other validators.
Also changes `DEFAULT_DAYS_FOR_REMINDER` to `2`.
=> Use date fields for send_consent_at

bin/generate-example-campaigns, bin/show-testing-fixtures
First take at automating generating the fixtures used by tests from the example campaign JSON. As discussed this could be improved with a JS (or even Ruby) implementation, but this is the first stab.
=> Add script to extract testing fixtures

app/views/edit_sessions/confirm.html.erb, tests/session_create.spec.ts
If the date to send consent requests is today, we should display a small warning text above the confirm button.
=> Add inset text to session create confirmation page

app/controllers/testing_controller.rb, config/routes.rb, spec/factories/teams.rb, tests/pilot_registration_checkboxes.spec.ts, tests/pilot_registration_no_observation.spec.ts
It's important that the behaviour of the checkboxes the parents use to agree to having their child observed work reliably. This adds extra testing to ensure:
- if the parent does not check the observation checkbox (or any of the other agreement/confirmation checkboxes) they cannot join the pilot
- if the school does not require agreement to observation the checkbox does not appear
This also adds a new approach to generating fixtures by using a `TestingController` to try to simplify the process.
Questions about test coverage:
- We don't have a test to ensure that if a parent fills in the registration form but does _not_ check any of the required agreements / confirmations, their child is not added to the system. Worth adding?
=> Add more testing around the agree to observe checkbox

copilot/webapp/manifest.yml
Puma scales well with multiple processes, and each worker/process gets it's own request queue, so having more than one helps manage request waiting if one of the processes's threads get stuck in CPU and within the GIL. And running multiple processes uses up more RAM.
We also scale down staging resources, but leave two containers running because that potentially allows us to catch cross-host parallalisation issues.
=> Scale up production resources

app/mailers/consent_form_mailer.rb, spec/mailers/consent_form_mailer_spec.rb
- Add the conditional consent boolean for the UR observation content
- Add the "vaccination" personalisation to display "HPV vaccination" or "Flu vaccination" in the title/body
=> Tweak parental consent emails

app/views/parent_interface/consent_forms/confirm.html.erb
"Alternative option" should only display when the parent has been offered an alternative as part of the flu consent process.
=> Bugfix: hide alternative option when confirming HPV refusal

app/mailers/consent_form_mailer.rb, spec/mailers/consent_form_mailer_spec.rb
Notify ignores additional values passed into the personalisation hash. As such, we can always pass in every configuration option and they will get ignored if they are not necessary.
This means we can use a single `personalisation` hash and vastly simplify our mailer code.
In a follow-up PR, we can lift/shift some of these fields (like `short_date`, `team_email` etc) to the ApplicationMailer so they are inherited and reused across all the mailers.
=> Refactor consent form mailer

app/models/team.rb
We need to migrate these in a different way, as simply adding the encrypts call breaks in test.
=> Don't encrypt team attributes

app/mailers/application_mailer.rb, app/mailers/consent_form_mailer.rb, config/locales/en.yml, spec/mailers/application_mailer_spec.rb, spec/mailers/consent_form_mailer_spec.rb
Follow-up to https://github.com/nhsuk/manage-childrens-vaccinations/pull/1011, same idea, but taken a step further.
These can sit in the ApplicationMailer to help with code reuse across different mailers.
=> Lift common mailer attrs out of ConsentFormMailer

app/controllers/consents_controller.rb, app/views/consents/index.html.erb, app/views/sessions/show.html.erb, tests/pilot_journey.spec.ts, tests/schools_match_response.spec.ts
It used to be on the session page, now it's on the 'check consent responses' page
There is no more link here to the unmatched responses page:
The link is now here:
=> Move link to unmatched responses page

app/mailers/consent_request_mailer.rb, copilot/webapp/manifest.yml, spec/mailers/consent_request_mailer_spec.rb
This will be the email sent out by the scheduled job to request that parents submit consent for their children. That code is to come, this email isn't being sent yet.
The template in GOVUK Notify has been updated and set to live.
=> Add consent request mailer

app/controllers/parent_interface/consent_forms/edit_controller.rb, app/models/consent_form.rb, app/views/parent_interface/consent_forms/edit/reason.html.erb, app/views/parent_interface/consent_forms/edit/reason_notes.html.erb, config/locales/en.yml, spec/models/consent_form_spec.rb, tests/parental_consent_refused.spec.ts
The reason is mandatory in the following cases:
* vaccine will be given elsewhere
* vaccine already administered
* medical reasons
* other
For "personal reasons" and "contains gelatine" refusals, the details are optional.
=> Ask the parent for refusal reason details on a separate page

app/jobs/consent_requests_job.rb, app/jobs/consent_requests_session_batch_job.rb, app/models/patient.rb, config/environments/test.rb, db/migrate/20240220165801_add_sent_consent_at_to_patients.rb, db/schema.rb, spec/factories/patients.rb, spec/jobs/consent_requests_job_spec.rb, spec/jobs/consent_requests_session_batch_job_spec.rb, spec/models/patient_spec.rb, spec/rails_helper.rb
This is email sent out by the scheduled job to request that parents submit consent for their children. This PR adds a job `ConsentRequestsJob` that can be scheduled to run daily at an appropriate time. It will trigger another job, `ConsentRequestsSessionBatchJob` which will send an email to the parent of each patient in a session that has not yet been sent a consent request.
The cron scheduler hasn't been setup yet, this will be done after we do some more testing of how Good Job's scheduled jobs work.
=> Add job to send consent requests for sessions

app/mailers/consent_request_mailer.rb, config/initializers/date_formats.rb, config/initializers/date_time_formats.rb, spec/mailers/consent_request_mailer_spec.rb
This will be used to send consent request reminders to patient's parents.
Also includes an update to the initial consent request email to differentiate between the session and close consent dates.
Both templates have been tested.
=> Add consent reminder email

app/controllers/concerns/triage_mailer_concern.rb, app/controllers/triage_controller.rb, app/mailers/triage_mailer.rb
This sends parents emails to let them know whether the vaccination will or will not happen after patients go through nurse triage.
TODO:
=> Add TriageMailer and wire up nurse triage journey

app/controllers/consent_forms_controller.rb, app/controllers/schools_controller.rb, app/views/consent_forms/show.html.erb, app/views/consent_forms/unmatched_responses.html.erb, app/views/consents/index.html.erb, config/routes.rb, tests/schools_match_response.spec.ts
Changes:
* moving the page's path from `/schools/XX` to `/sessions/XX/consents/unmatched-responses` to reflect that it's part of the `Check consent responses` area of the product. "Unmatched consent responses" under schools doesn't feel quite correct, as a school will have multiple sessions (i.e. unmatched responses are session-specific, not school-specific)
* updating breadcrumbs
* updated designs
=> Bring unmatched consent responses page into line with latest designs

config/application.rb
We have this set up on Heroku, but we forgot to add the environment variable to our Copilot environments.
This runs the GoodJob worker in the same process as the main Rails process.
=> Enable good job async processing on AWS Copilot envs

app/controllers/consents_controller.rb, app/controllers/sessions_controller.rb, app/models/session_stats.rb, spec/models/session_stats_spec.rb
Before the fix, the stats were being calculated off the *location*, which may have multiple sessions.
Afeter this fix, the stats calculate only the unmatched responses for the specific *session*.
=> Bugfix to unmatched responses calculations

config/database.yml
In envs where we run GoodJob async, we need to ensure we have enough connections to the db available, as recommended by the GoodJob docs.
=> Increase db connection pool

app/models/consent.rb, app/models/consent_form.rb, app/views/parent_interface/consent_forms/edit/reason.html.erb, config/locales/en.yml, db/sample_data/example-flu-campaign.json, lib/example_campaign_generator.rb, spec/models/consent_form_spec.rb
Make them consistent so creating consents from consent_forms works OOTB.
=> Match consent and consent_form reason_for_refusals

app/views/consents/index.html.erb, app/views/edit_sessions/confirm.html.erb, tests/consent.spec.ts, tests/full_journey.spec.ts, tests/nurse_consent_conflicting_consent.spec.ts, tests/schools_match_response.spec.ts
=> Fix model office snags

config/environments/production.rb
This job will send out consent request emails to parents on the configured day for each session.
=> Enable Good Job cron in production

app/components/app_breadcrumb_component.html.erb, app/components/app_breadcrumb_component.rb, spec/components/app_breadcrumb_component_spec.rb
On narrow viewports, back links were linking to the last element, which was the title of the current page.
It should be linking to the last actual link in the breadcrumb.
=> Fix back links on mobile in Mavis

copilot/webapp/manifest.yml
The support user will be used to protect parts of the service in production and requires credentials be kept secret.
Secrets have been added and will need to be tested through `test` and `staging` before going to `production`.
=> Move support user credentials to secrets

config/initializers/good_job.rb, config/routes.rb
This job will send out consent request emails to parents on the configured day for each session.
=> Protect good-job dashboard with basic auth

app/controllers/application_controller.rb, app/controllers/cohort_lists_controller.rb, app/controllers/consent_forms_controller.rb, app/controllers/csrf_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/dev_controller.rb, app/controllers/errors_controller.rb, app/controllers/manage_consents_controller.rb, app/controllers/pages_controller.rb, app/controllers/parent_interface/consent_forms/base_controller.rb, app/controllers/pilot_controller.rb, app/controllers/registrations_controller.rb, app/controllers/schools_controller.rb, app/controllers/sessions_controller.rb, app/controllers/testing_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/vaccinations/batches_controller.rb, app/controllers/vaccinations/delivery_site_controller.rb, app/controllers/vaccinations_controller.rb, app/policies/consent_policy.rb, app/policies/registration_policy.rb, lib/load_example_campaign.rb, tests/pilot_upload_cohort.spec.ts
This is a security measure to ensure we always scope the DB requests appropriately to the current user.
We also fix the data as many patients were being created without a link to location.
=> Use pundit policies in all necessary controllers

lib/tasks/performance.rake
The count does not add up as it checks total registrations from every team.
=> Exclude test team from performance stats

.github/workflows/deploy.yml
This is an attempt to fix the run name being set to "Deploy to " for the deploy GitHub actions. After some testing `null` appears to restore the default behaviour, so we use that if we've been triggered by anything other than a `workflow_dispatch` event.
The use of a `null` value has been tested, but the real test will be when this gets deployed on PR merge.
=> Only set run name on workflow_dispatch events

app/jobs/consent_form_matching_job.rb, app/models/patient.rb, spec/features/parent_gives_consent_spec.rb, spec/models/consent_form_spec.rb
This makes the deterministic AR encryption only active on environments where we have enabled automatic matching. This allows us to keep using the automatic matching on `test` while we migrate the fields.
=> Add feature flag for automatic matching

app/jobs/consent_reminders_job.rb, app/jobs/consent_reminders_session_batch_job.rb, app/jobs/consent_requests_session_batch_job.rb, config/environments/production.rb, spec/jobs/consent_reminders_job_spec.rb, spec/jobs/consent_reminders_session_batch_job_spec.rb
Same as the consent requests, nearly an identical copy. It may be tempting to move these into the same job, but by keeping them separate it will offer finer grained control in case we need to pause or stop one job and not the other.
=> Add jobs to send consent reminders

app/jobs/consent_reminders_job.rb, app/jobs/consent_requests_job.rb, spec/jobs/consent_reminders_job_spec.rb, spec/jobs/consent_requests_job_spec.rb
We need to hold off temporarily from sending scheduled emails in production.
=> Send scheduled emails only if feature flag enabled

Gemfile, Gemfile.lock, app/models/consent_form.rb, app/models/health_question.rb, lib/tasks/add_health_questions.rake, spec/models/health_question_spec.rb
To enable adding or replacing health questions in deployed environments.
=> Add health questions task

bin/docker-entrypoint, bin/release, lib/tasks/prepare_swallowing_concurrent_migration_exceptions.rake
Because we deploy to multiple machines at the same time, it's possible to run into concurrent migration issues. It's safe to swallow these errors and let the deploy carry on.
=> Add db:prepare:ignore_concurrent_migration_exceptions

app/models/consent_form.rb, app/views/parent_interface/consent_forms/confirm.html.erb, spec/features/parent_gives_consent_spec.rb, spec/models/consent_form_spec.rb, tests/parental_consent_asthma_route.spec.ts
At the moment the service won't be able to honour this if set.
This also removes the form page and validation, since they're easy to re-add, but leaves the db field in case we want to populate it another way at some point.
=> Remove contact method page from parental consent

app/mailers/triage_mailer.rb, spec/mailers/triage_mailer_spec.rb
The consent object gets the parent's name from the consent form or from the nurse when they call the parent. This is more likely to be accurate and up-to-date than what's on the patient record.
There's still the question of what to do when more than one parent has submitted consent, how do we know we have the right parent?
=> Use parent name from consent in triage email

Dockerfile, config/environments/production.rb, supervisord.conf
This attempts to fix the current issue with running `good_job` in async mode. It switches to external mode and runs `bundle exec good_job start` as a separate process in the Docker container.
Because Docker containers are designed to be single process, we need to use `supervisor` to manage running the two processes.
=> Run good_job in external mode using supervisor

app/models/session.rb, spec/features/pilot_journey_spec.rb
Validations started failing in this test because we went past the 27th of Feb and certain dates can't be in the past.
=> Add Timecop freeze to pilot journey test

app/assets/stylesheets/registration.scss, app/controllers/parent_interface/consent_forms_controller.rb, config/initializers/flipper.rb, spec/features/parent_gives_consent_spec.rb, spec/features/pilot_journey_spec.rb
This was added during an incident and can be removed now.
=> Remove temporary parental consent feature flag

spec/factories/teams.rb
When we create many teams within the same transaction we can occasionally get a duplicate that causes the unique index on team name to raise an error. Using a sequence avoids this.
This was tested with the following rspec. Using the random identifier didn't seem to clash very often, but we've seen this issue at least once and probably more in CI, so better to tidy it up.
```
require 'rails_helper'
RSpec.describe Team do
100.times do |n|
it "works #{n}" do
create_list(:team, 20)
end
end
end
```
=> Use sequence for team name instead of random

config/initializers/good_job.rb, config/settings.yml
This makes /good-job consistently ask for a password in all environments, including development, to make it more similar to production.
=> Always ask for password for good_job dashboard

app/models/consent.rb, spec/components/app_patient_medical_history_card_component_spec.rb, spec/models/concerns/patient_session_state_machine_concern_spec.rb, spec/models/consent_spec.rb
Before this change, if the consent form was submitted by "other" carer, it would automatically go to triage.
Since we're changing the design so that "other" carers have to explicitly confirm parental responsibility on the consent form, this special case is no longer necessary.
=> Don't explicitly triage consent forms from "other" carer

app/controllers/parent_interface/consent_forms/edit_controller.rb, app/controllers/parent_interface/consent_forms_controller.rb, app/models/consent_form.rb, app/views/parent_interface/consent_forms/cannot_consent_responsibility.html.erb, app/views/parent_interface/consent_forms/cannot_consent_school.html.erb, app/views/parent_interface/consent_forms/edit/parent.html.erb, config/locales/en.yml, config/routes.rb, tests/parental_consent_change_answers.spec.ts
This ensures that consent forms can't be submitted by a parent who isn't mum/dad/guardian unless they accept a radio button confirming they have parental responsibility.
=> Add parental responsibility radio to parent page

app/components/app_status_banner_component.rb, config/locales/patient_session_statuses.en.yml, spec/components/app_status_banner_component_spec.rb
We currently hardcode the string “Nurse” in a few places in Mavis. This isn’t inclusive of paramedics and we should use people’s names instead.
=> Remove "Nurse" wording from UI

config/environments/production.rb, config/puma.rb, copilot/webapp/manifest.yml
This simplifies our infrastructure and deploy pipeline, and should be resilient now that we found the Puma restart bug that previously led to jobs not being enqueued successfully in production.
First commit sets up Puma to cleanly restart good_job when it restarts following the advice in https://github.com/bensheldon/good_job?tab=readme-ov-file#execute-jobs-async--in-process
Second makes `test` more similar to `staging`, so that we can test this more thoroughly and also shut down staging once we switch to using `test` more (after this change ships successfully most likely).
Third removes the `good_job` execution mode override in `production.rb`, finishing the transition.
Follow-up PR to this will remove the `goodjob/manifest.yml` service and infrastructure.
This also fixes job execution …
=> Set good_job to async in production 

app/components/app_patient_table_component.html.erb, app/views/consent_forms/show.html.erb, app/views/vaccinations/_patients_with_actions.html.erb, app/views/vaccinations/_patients_with_outcomes.html.erb
I may have spend a good number of hours attempting to build this myself, only to find that the absolutely brilliant `action-table` component already had this feature built in, and all I needed to do was add a `store` attribute (and an `id` to identify saved filters in local storage) to the relevant `action-table`s. FML (and always RTFM).
Anyhoo… added this feature to all patient tables, and to the cohort matching table. There might be some lingering UX issues, in that it’s not immediately obvious if filters have been persisted, but we can cross that bridge when we come to it. We might want a clearer CTA to clear selected filters.
=> Persist selected action table filters

app/assets/stylesheets/_header.scss, app/controllers/batches_controller.rb, app/controllers/vaccines_controller.rb, app/policies/vaccine_policy.rb, app/views/batches/new.html.erb, app/views/dashboard/index.html.erb, app/views/layouts/application.html.erb, app/views/pilot/manage.html.erb, app/views/vaccines/index.html.erb, config/locales/en.yml, config/routes.rb, spec/features/manage_batches_spec.rb
This PR includes another experiment in the feature spec; instead of using FactoryBot to set up data, I'm calling operational Rake tasks (as this is how teams / vaccines / users are set up in production-like environments). This should hopefully mean that this feature spec is more likely to spot issues with these Rake tasks, and less prone to suffer from factory bugs. The  Rake task calls are wrapped in a method that temporarily suppresses STDOUT output, to prevent stray noise in the test runner.
=> Allow SAIS team members to add vaccine batches, see existing batches

app/controllers/batches_controller.rb, app/controllers/concerns/todays_batch_concern.rb, app/controllers/vaccinations/batches_controller.rb, app/controllers/vaccinations_controller.rb, app/controllers/vaccines_controller.rb, app/views/vaccines/index.html.erb, config/routes.rb, spec/factories/sessions.rb, spec/factories/teams.rb, spec/features/manage_batches_spec.rb
PR is best reviewed commit-by-commit.
I ran out of time to fix the following (will be sorted in subsequent PRs):
* The included spec doesn't cover removing a default.
* There's overlap between `manage_batches_spec.rb` and `vaccination_default_batch.spec.ts` (probably resolved by consolidating into RSpec land)
* The factories don't make it obviously straightforward to create a patient in a session who is ready to vaccinate. This requires the spec to go through self-consent to get the patient into the right state.
* The "set default" and "remove default" should look like links but they currently don't have the right styling.
=> Manage batch defaults

app/components/app_consent_response_component.rb, spec/components/app_consent_response_component_spec.rb, spec/factories/consents.rb
Depends on https://github.com/nhsuk/manage-childrens-vaccinations/pull/1110.
This uses the recorded_by attribute which captures the user who handled the verbal consent.
Must be deployed only after all environments have `recorded_by` populated on `Consent`.
=> Show nurse who recorded verbal consent 

Gemfile, Gemfile.lock, app/javascript/controllers/index.js, app/javascript/controllers/nhsuk_button_controller.js, app/views/edit_sessions/confirm.html.erb, app/views/manage_consents/confirm.html.erb, app/views/parent_interface/consent_forms/confirm.html.erb, app/views/sessions/show.html.erb
We've confirmed that double-tapping these stand-alone buttons cause errors to show, even if the actual action is performed. Usually the first POST/PUT works, but the subsequent one is the one that error and that the user sees.
This change relies on https://github.com/x-govuk/govuk-components/pull/513 being accepted and merged (which seems imminent), and released. Until then we are using the fork I created get the functionality now.
=> Prevent users from double-tapping on stand-alone buttons

app/components/app_consent_component.rb, app/models/vaccination_record.rb, spec/components/app_consent_component_spec.rb, tests/vaccination.spec.ts
As they're ultimately the responsible clinician, vaccinators will often double check what notes the parents left as part of a light-touch triage just before vaccination, even if triage has already been done.
To support this, we should "unfold" the health questions whenever there are notes, before vaccination. If this isn't the case, vaccinators would have to manually open every patient's health questions to see if there are any notes there or not.
=> Before vaccination, open the health questions if there are notes

Dockerfile, config/environments/production.rb, config/initializers/check_production.rb
We're running in production now and it feels unlikely that we'd ship an environment without Sentry setup given that we use the same IAAS templates for everything.
Second commit allows RAILS_ENV=production without a Notify key being set, making it easier to test it locally. This is slightly more controversial as you can argue that it's better if the app refuses to boot up if Notify isn't set, but same logic as the SENTRY_DSN; I think we're protecting from a fairly low risk...
=> Remove production checks

app/controllers/concerns/triage_mailer_concern.rb, app/mailers/consent_form_mailer.rb, spec/controllers/concerns/triage_mailer_concern_spec.rb, spec/features/verbal_consent_given_needs_triage_do_not_vaccinate_spec.rb, spec/features/verbal_consent_given_needs_triage_kept_in_triage_spec.rb, spec/features/verbal_consent_given_needs_triage_ready_to_vaccinate_spec.rb, spec/features/verbal_consent_given_spec.rb, spec/features/verbal_consent_refused_spec.rb, spec/mailers/consent_form_mailer_spec.rb
We normally request feedback after they fill in the consent form, but for those parents who need to be contacted during the session to get feedback, we need to trigger sending them a request for feedback separately.
This has been manually tested to check the personalisations match what GOVUK is looking for:
=> Request feedback form parents after verbal consent

app/components/app_patient_table_component.rb, app/controllers/component_previews_controller.rb, app/views/vaccinations/_patient_row.html.erb, config/application.rb, spec/components/app_patient_table_component_spec.rb, spec/components/previews/app_patient_table_component_preview.rb, spec/factories/users.rb
To test this change, it was handy to add a preview for `AppPatientTableComponent`. The preview relied on factories and I ran into problems when refreshing the preview because of sequence clashes in the factories.
To deal with this, I introduced a custom preview controller (see 7ad28aeb84bd16969892391efdfe64994f85c9d7) that wraps a transaction around the preview action and silently rolls everything back after it's run, so the development DB isn't polluted and the sequence clashes can be avoided. This seems to be working well so far 🤞 .
=> Show the preferred name in consent, triage, record and matching patient lists

app/assets/stylesheets/_list.scss, app/assets/stylesheets/application.scss, app/components/app_consent_response_component.rb, spec/components/app_consent_details_component_spec.rb, spec/components/app_consent_response_component_spec.rb, spec/components/previews/app_consent_component_preview.rb, spec/factories/patients.rb
* add a preview for `AppConsentComponent`
* refactor `AppConsentResponseComponent` to use ERB templates, to make it a bit to parse at a glance. Also split out the logic for rendering a single consent response, and logic needed to render a list of them
=> Make consents list look right with multiple consents for same parent

app/components/app_consent_details_component.rb, spec/components/app_consent_details_component_spec.rb, spec/components/previews/app_consent_component_preview.rb, spec/factories/patient_sessions.rb, spec/factories/patients.rb
=> Display refusal notes from consent forms in Mavis

config/application.rb, config/initializers/precompile.rb
Significantly reduces asset sizes.
Propshaft requires some additional changes to `assets:precompile` in order to manually gzip assets.
This can be removed in Rails 8 once Thruster is released.
https://github.com/rails/rails/issues/50479
=> Enable gzip compression

app/assets/stylesheets/_inset-text.scss, app/assets/stylesheets/_offline.scss, app/assets/stylesheets/_summary-list.scss, app/assets/stylesheets/application.scss, app/javascript/controllers/govuk_accordion_controller.js, app/javascript/controllers/govuk_header_controller.js, app/javascript/controllers/govuk_skip_link_controller.js, app/javascript/controllers/index.js, app/views/vaccines/index.html.erb
- Remove extending `.govuk-inset-text` (NHS.UK Frontend has it’s own styles)
- Only load the component styles from GOV.UK Frontend that we are using:
- File upload
- Notification banner
- Panel
- Phase banner
- Disable offline style (not currently being used)
- Remove unused GOV.UK JavaScript controllers:
- Accordian 
- Header
- Skip link
Uncompressed CSS file size before: 312 KB
Uncompressed CSS file size after: 182 KB
=> Reduce asset size

package.json
Enable the flags for sass and esbuild.
```bash
$ wc -c app/assets/builds/application.css app/assets/builds/application.js
181694 app/assets/builds/application.css
206443 app/assets/builds/application.js
388137 total
```
```bash
$ wc -c app/assets/builds/application.css app/assets/builds/application.js
126270 app/assets/builds/application.css
115710 app/assets/builds/application.js
241980 total
```
=> Minify CSS and JS

config/application.rb
We already use cache-busting strings, so this should be safe to do.
=> Cache assets forever

app/views/vaccinations/confirm.html.erb
Remove redundant date (it's already above), match what's in the prototype.
=> Show only the time of day when confirming the vaccination record

config/puma.rb, config/settings/development.yml
Set web_concurrency to 0 in development and don't restart/shutdown GoodJob unless web_concurrency > 1.
=> Puma worker updates

app/components/app_status_banner_component.rb, config/locales/patient_session_statuses.en.yml, spec/components/app_status_banner_component_spec.rb, spec/components/previews/app_status_banner_component_preview.rb, spec/features/hpv_vaccination_not_administered_spec.rb
If a child couldn't be vaccinated at the session for any reason other than refusal, the patient page was always showing "refused vaccine" rather than the actual recorded reason.
Below, the vaccinator recorded that the child couldn't be vaccinated due to contraindications:
* add a component preview for this case
* fix the bug in the component spec (one was already written but it wasn't actually testing what was on the page)
* fix the bug in the component itself
* remove full stops from the banner messages (to be consistent with the other banners)
=> Show right reason when unable to vaccinate

config/locales/patient_session_statuses.en.yml, spec/components/app_status_banner_component_spec.rb, spec/components/previews/app_status_banner_component_preview.rb, spec/factories/patient_sessions.rb
**Depends on #1155, rebase after that's merged.**
* Add previews for most patient banner types
* Remove full-stops from banner messages
* 8205df30c2a4986cc72998d3ee46c3aaead7600a: fix typo in a banner message (it might not actually be used though!)
Best reviewed commit by commit.
=> More banner fixes and improvements

config/environments/development.rb, config/environments/test.rb
This should help spot cases where we've overeagerly removed translation strings.
=> Enable error raising on missing translation in dev and test

copilot/webapp/manifest.yml
This is in an attempt to speed up the deploy times. It's not quite certain how these will affect the deploys yet, so we'll try these in test and training and then see about production later.
=> Reduce healthcheck times in test and training

app/controllers/parent_interface/consent_forms_controller.rb, app/mailers/consent_request_mailer.rb, app/mailers/session_mailer.rb, app/mailers/vaccination_mailer.rb, app/views/parent_interface/consent_forms/deadline_passed.html.erb, config/initializers/email_templates.rb, config/routes.rb, spec/features/hpv_vaccination_administered_spec.rb, spec/features/hpv_vaccination_not_administered_spec.rb, spec/features/parental_consent_spec.rb, spec/features/session_management_spec.rb, spec/mailers/vaccination_mailer_spec.rb, tests/parental_consent_asthma_route.spec.ts, tests/parental_consent_authentication.spec.ts, tests/parental_consent_change_answers.spec.ts, tests/parental_consent_refused.spec.ts
Close parental consent by forcing users to go to a separate page once the deadline has passed.
TODO:
=> Implement consent deadline

lib/tasks/send_consent_reminders.rake
Sends consent reminders to patient's parents who have not yet submitted consent.
Tested locally
=> Add rake task to re-send consent reminders

app/views/manage_consents/agree.html.erb
=> Show validation error on verbal consent 'agree' page

app/components/app_outcome_banner_component.rb, spec/components/app_outcome_banner_component_spec.rb
It doesn't make sense to show the location if the patient was triaged out before the school session.
=> Hide the location in the outcome banner if patient triaged out before the session

lib/tasks/performance.rake
Just noticed that this improves spacing in the rendered markdown.
=> Move empty line above school in performance output

app/mailers/consent_form_mailer.rb, app/mailers/triage_mailer.rb, config/initializers/email_templates.rb, spec/features/verbal_consent_given_do_not_vaccinate_spec.rb, spec/features/verbal_consent_given_keep_in_triage_spec.rb, spec/features/verbal_consent_given_ready_to_vaccinate_spec.rb, spec/features/verbal_consent_given_spec.rb, spec/features/verbal_consent_refused_spec.rb
Adds the remaining email UUIDs to the mapping of email templates. This gives each UUID an understandable name.
This came out of other work to add tests, decided it was better PRed on it's own.
=> Add remaining email UUIDs

spec/features/parental_consent_refused_spec.rb
The spec wasn't actually testing whether:
* the refusal could even be submitted
* the right emails were sent
* the patient is left in the right state in Mavis
=> Extend the 'parental consent refused' feature spec

app/controllers/consents_controller.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, spec/factories/patients.rb, spec/features/triage_during_consent_spec.rb, spec/features/triage_during_vaccination_spec.rb
The implementation here is pretty simple, although I'm still a little on the fence about it. Basically when they visit either the "Triage health questions" or the "Record vaccinations" pages, this is recorder in their session info as their `current_section` and can be `triage` or `vaccinations`. Then, the `create` or `update` actions during triage will examine `current_section` and return them to the appropriate page.
The alternative to this, admittedly quite simple, approach is to use the paths, e.g.:
> [!Note]
> This is an illustration of an alternative implementation, not what was implemented in this PR
```
/sessions/1/vaccinations
/sessions/1/vaccinations/patients/2
/sessions/1/vaccinations/patients/2/triage
/sessions/1/triage/patients/2
/sessions/1/triage/patients/2/triage
``` …
=> Return users to vaccination section when doing triage while vaccinating

app/views/cohort_lists/new.html.erb, app/views/consents/index.html.erb, app/views/edit_sessions/confirm.html.erb, app/views/edit_sessions/timeline.html.erb, app/views/parent_interface/consent_forms/edit/school.html.erb, app/views/registrations/new.html.erb
Spotted a few inconsistencies and missing visually hidden text when using the inset text component:
- Always use a paragraph to wrap text (ensuring correct font size)
- Always show visually hidden ‘Information: ’ text (when relevant)
- Use default top and bottom margins
Example:
| When | Screenshot |
| :- | :- |
| Before | <img width="595" alt="Screenshot 2024-03-12 at 11 33 46" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/bea076d7-7bb2-45bc-8052-dc2838204197"> |
| After | <img width="680" alt="Screenshot 2024-03-13 at 11 44 46" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/a8e86350-c63a-4e1b-9172-13dc0e384fb7"> |
=> Review inset text font size, spacing and visually hidden text

app/components/app_patient_table_filter_component.html.erb, app/controllers/vaccinations_controller.rb, config/locales/patient_session_statuses.en.yml, spec/features/parental_consent_refused_spec.rb
=> Record vaccinations: move refusers and conflicting responses to 'Could not vaccinate' tab

app/components/app_consent_card_component.html.erb, app/components/app_consent_response_component.rb, app/components/app_timestamped_entry_component.rb, spec/components/app_consent_response_component_spec.rb, spec/components/app_timestamped_entry_component_spec.rb
Adopt consistent presentation for the "Response" row of the consent tables across:
* the patient page
* the "verbal consent" confirmation page
* the "manual matching" page
* show the timestamp when the response was recorded
* show the name of the staff member who recorded the consent, for verbal or self-consent
* don't display the parent's name for online consent (previously the parent's name was shown)
* the name and timestamp are shown on the same line (previously they were across two lines on some pages)
Scenario|Before             |  After
:-------------:|:-------------:|:----------------:
Online consent|<img width="528" alt="image" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/23801/3a7eb91a-0619-4a26-b505-e61077834727">|<img width="537" alt="image" …
=> Consent response summary: response row redesign

app/controllers/patient_sessions_controller.rb, app/controllers/vaccinations/batches_controller.rb, app/controllers/vaccinations/delivery_site_controller.rb, app/controllers/vaccinations_controller.rb, app/models/patient.rb, app/models/vaccination_record.rb
This helps reduce problems like the one in #1194.
=> VaccinationRecord: set the 'recorded' scope as default

Gemfile, Gemfile.lock, app/controllers/manage_consents_controller.rb, app/helpers/manage_consents_helper.rb, app/models/concerns/patient_session_state_machine_concern.rb, app/models/consent.rb, app/models/patient_session.rb, app/views/manage_consents/agree.html.erb, config/routes.rb, spec/factories/patient_sessions.rb, spec/factories/patients.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb, spec/models/concerns/patient_session_state_machine_concern_spec.rb, spec/models/consent_spec.rb, spec/models/patient_session_spec.rb
This fixes an error triggereg when a nurse tries to record consent given verbally when it was previously refused by the parent.
We fix this by cloning the existing consent instead of editing the existing one. This means when determining the state of consent we need to only look at the most recent response from a parent. It's also exposed other missing state transitions, such as if the parent verbally refuses consent again in the above scenario, or if another consent form is filled in. Fixes to these other transitions will be done in a follow-up PR to keep this one small(er).
Re: the cloning implementation, there are a couple things to point out. Because the link to changing the consent response is a link and not a button, we can't clone consent response when they click that link. We …
=> Allow consent to be changed to given via verbal consent

app/controllers/consents_controller.rb, app/controllers/sessions_controller.rb, app/controllers/triage_controller.rb, app/models/concerns/patient_session_state_concern.rb, app/models/patient_session.rb, spec/components/app_outcome_banner_component_spec.rb, spec/components/app_patient_page_component_spec.rb, spec/factories/patient_sessions.rb, spec/factories/patients.rb, spec/models/concerns/patient_session_state_concern_spec.rb, spec/models/patient_session_spec.rb
Now that we understand how states work better, and put all the states we need into the various objects connected to PatientSessions, it seems clear that the state machine isn't actually adding anything beyond additional hurdles and a false sense of comfort.
The new approach in this concern is something we discussed in the beginning; we "calculate" the PatientSession state by looking at the state of the various connected objects: consent, triage and vaccination_record. This was all being done in the state machine as it stands, anyway, the only additional complexity is the order in which we look at these objects. What's removed, really, are the transitions, and all the code to define, manage and test them.
Tasks remaining:
=> Add state concern to replace state machine

app/controllers/consents_controller.rb, app/controllers/manage_consents_controller.rb, app/controllers/patient_sessions_controller.rb, app/controllers/sessions_controller.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, app/models/concerns/patient_session_state_concern.rb, app/models/consent.rb, app/models/patient_session.rb, spec/models/consent_spec.rb, spec/models/patient_session_spec.rb
This PR optmises our queries related to PatientSession and it's associations, `consents`, `triage` and `vaccination_records`. The primary issue was that N+1 queries were being generated, even for associations that were included in the original query, because we were using the `recorded` scope which discarded the already loaded objects and reloaded them again with a new query. Also some of the associations weren't being preloaded correctly.
The result was that before the new state concern, on my system, the Check consent, Triage or Vaccination pages would all take about 200ms for the request to complete according to Rails. With the original version of the new state refactoring, that ballooned up to around 400ms or more, but with these optimisations this has been brought down to 100ms or …
=> Improve performance of consent, triage and vaccination index pages

config/settings.yml
We're showcasing the pilot on the training environment and need to delay the last possible date when a session can be created.
=> Bump latest session date for pilot

app/models/consent_form.rb, spec/components/app_patient_details_component_spec.rb, spec/models/consent_form_spec.rb
This prevents a case where users change their mind on the common name field but it stays on the actual record.
=> Reset common name if not used

app/assets/stylesheets/_password-input.scss, app/assets/stylesheets/_utilities.scss, app/assets/stylesheets/application.scss
- Incorporate relevant styling from upstream GOV.UK component
- Adjust design of button to work in this inline context (button shadow size, mainly)
- Move `govuk-visually-hidden` into same file as `nhsuk-visually-hidden`
=> Adjust password input styling

app/components/app_tab_component.rb, app/controllers/triage_controller.rb, app/views/triage/index.html.erb, config/initializers/tabs.rb, config/routes.rb, spec/features/triage_delay_vaccination_spec.rb, tests/nurse_consent_no_response.spec.ts, tests/sign_in.spec.ts, tests/triage.spec.ts
Make the triage tabs do full page reloads instead of using JS to hide/show tabs.
Currently the consent, triage and vaccination sections load up all the tabs and use JS to switch between them. The current implementation has a couple downsides:
- back-buttons are harder to implement
- the page is a mess on mobile and non-JS
- and to a lesser extent, there will be performance risks as we have sessions with more users
This PR is the first step to changing them all to page reloads. Current issues with this implementation:
- nhsuk-frontend currently breaks because it depends on discovering the tab label by examining the link for the tab and using the fragment from it (see https://github.com/nhsuk/nhsuk-frontend/blob/main/packages/components/tabs/tabs.js#L306). This means that the `role` and …
=> Make triage tabs do page reloads

bin/lint
Required when passing in multiple files.
=> Quote args in bin/lint

app/models/consent_form.rb, spec/models/consent_form_spec.rb
Ensures that data stored in dynamic fields is not saved when the form is updated and those fields become irrelevant.
=> Reset unused fields on ConsentForm when saving

app/models/consent_form.rb, spec/models/consent_form_spec.rb
This consolidates some of the existing before_save hooks into a single method that handles all the different cases.
=> Reset more fields on ConsentForm when switching paths

app/controllers/manage_consents_controller.rb, app/helpers/manage_consents_helper.rb, app/views/manage_consents/agree.html.erb, app/views/manage_consents/confirm.html.erb, app/views/manage_consents/gillick.html.erb, app/views/manage_consents/questions.html.erb, app/views/manage_consents/reason.html.erb, app/views/manage_consents/who.html.erb, spec/features/verbal_consent_given_when_previously_refused_spec.rb
When nurses amend an existing consent, the link sends them to the middle of a consent wizard. `previous_wizard_path` links to the first step in the journey, which causes the back button to go into a loop, because the first step is the :agree one which the user is currently on.
This adds a special `back_link_path` helper that checks for this case and works around it by instead sending a user to the session path for their route. The code to do this is extracted from the :who step. This way, every step is now a possible "first step" depending on how the logic to handle the list of `form_steps` changes.
TODO:
=> Fix back link on manage consents journey

app/controllers/consents_controller.rb, app/views/consents/index.html.erb, config/initializers/tabs.rb, config/locales/en.yml, config/routes.rb, spec/features/triage_during_consent_spec.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb, tests/nurse_consent_conflicting_consent.spec.ts, tests/schools_match_response.spec.ts
For the same reason why we did the triage tabs, this makes is easier for us to do some things like back buttons.
These commits have been split off of an existing branch to make reviewing easier. This other branch adds a concern to encapsulate methods to group patient_sessions.
=> Convert consents to page-load tabs

spec/models/patient_session_spec.rb
Since latest_consents doesn't explicitly order results, we have to accomodate different ordering in the specs.
=> Fix PatientSessions#latest_consents spec - order

app/controllers/concerns/patient_tabs_concern.rb, app/controllers/consents_controller.rb, app/controllers/triage_controller.rb, spec/controllers/concerns/patient_tabs_concern_spec.rb
This encapsulates logic to split patient_sessions up into groups and to do the counts. We'll continue to move the logic for tab groupings into the concern in follow-up PRs.
=> Add PatientTabsConcern for controllers

app/controllers/vaccinations_controller.rb, app/views/vaccinations/index.html.erb, config/initializers/tab_paths.rb, config/locales/en.yml, config/routes.rb, spec/features/triage_delay_vaccination_spec.rb, spec/routing/vaccinations_routing_spec.rb, tests/vaccination.spec.ts
Last section to do. There is still some more refactoring that can be done to the PatientTabsConcern, e.g. moving the conditions and states that define each section into it. This would make it cleaner to test the tabs and which patients go into each. There are also design changes that can start to be implemented.
=> Update vaccinations pages to use page loads

app/components/app_simple_status_banner_component.rb, app/mailers/vaccination_mailer.rb, app/models/concerns/patient_session_state_concern.rb, config/initializers/email_templates.rb, config/locales/patient_session_statuses.en.yml, spec/components/app_simple_status_banner_component_spec.rb, spec/factories/patient_sessions.rb, spec/features/hpv_vaccination_delayed_spec.rb, spec/features/hpv_vaccination_not_administered_spec.rb, spec/mailers/vaccination_mailer_spec.rb
This fell through and was not being handled. Patients absent were being treated as "Unable to vaccinate" whereas it should be "Delay vaccination."
Related to https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1157.
=> Handle case where patient is absent from school

app/controllers/concerns/patient_tabs_concern.rb, app/controllers/consents_controller.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, spec/controllers/concerns/patient_tabs_concern_spec.rb, spec/factories/patient_sessions.rb
This move makes `PatientTabsConcern` centrally responsible for how we group patients into each of the tabs across consents, triage and vaccinations tabs. It also adds more thorough testing.
As part of this work I also tried to convert the triage section's tabs to use conditions instead of states. Unfortunately this didn't work out as some of the patients ended up in the wrong tab. For example, with the condition `needs_triage: %w[triage_needed? triage_keep_in_triage?]` we get the following states in the "needs_triage" tab:
```ruby
(ruby) result["needs_triage"].map &:state
["consent_given_triage_needed", "delay_vaccination", "triaged_do_not_vaccinate", "triaged_kept_in_triage", "triaged_ready_to_vaccinate", "unable_to_vaccinate", "unable_to_vaccinate_not_gillick_competent", "vaccinated"] …
```
=> Move all tab conditions into PatientTabsConcern

app/controllers/users/passwords_controller.rb, app/controllers/users/unlocks_controller.rb, app/views/users/passwords/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_links.html.erb, app/views/users/unlocks/new.html.erb
Also tweaks the forgot password and account unlock pages to make them consistent.
Disables pundit policy checking on these controllers as it isn't relevant.
Width of input fields isn't set to 20 as that's more involved for the password field and can be done separately.
=> Align sign in page to prototype

app/assets/stylesheets/_overrides.scss, app/views/layouts/application.html.erb
Follows the prototype, in order to give more space to the consent/triage/vaccination views.
=> Make layout wider only when signed in

app/controllers/users/accounts_controller.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/dashboard/index.html.erb, app/views/layouts/application.html.erb, app/views/users/accounts/show.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/users.rb, spec/features/user_account_spec.rb
This adds a `/users/accounts/1` path that users can access in order to edit their name/email/registration number.
Pundit is used to prevent unauthorised users from accessing and modifying other people's accounts.
=> Allow users to edit their account details

app/controllers/users/accounts_controller.rb, config/locales/en.yml, spec/features/user_account_spec.rb
Also update the wording of the error for a registration number that's too long.
=> Update account details flash wording

app/assets/stylesheets/_count.scss, app/assets/stylesheets/_secondary-navigation.scss, app/assets/stylesheets/application.scss, app/components/app_count_component.rb, app/components/app_secondary_navigation_component.html.erb, app/components/app_secondary_navigation_component.rb, spec/components/app_secondary_navigation_component_spec.rb
This is a port of `x-govuk-secondary-navigation` and is required by the new patients table layout.
https://x-govuk.github.io/govuk-prototype-components/secondary-navigation/
Also add `AppCountComponent`.
=> Add AppSecondaryNavigationComponent

app/assets/stylesheets/_status.scss, app/components/app_consent_status_component.rb, spec/components/app_consent_component_spec.rb, spec/components/app_consent_status_component_spec.rb
Scenario|Before             |  After
:-------------:|:-------------:|:----------------:
Consent given|<img width="212" alt="image" src="https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/874cf189-b941-4ca7-aaa4-039ddaf1601c">|<img width="178" alt="image" src="https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/ba6ebf21-af01-4902-b175-60bbf660ed49">
Consent refused|<img width="225" alt="image" src="https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/05034b6c-e33d-4d9c-8f86-fe140ba076c5">|<img width="179" alt="image" src="https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/666e2967-17a9-42fd-9644-2b95be9e650b">
Conflicting consent|<img width="241" alt="image" src="https://github.com/nhsuk/manage-vaccinations-in-schools/asse …
=> Patient table consent status: new designs

app/assets/stylesheets/_card.scss, app/assets/stylesheets/_status.scss, app/assets/stylesheets/application.scss, app/components/app_consent_status_component.rb, config/locales/patient_session_statuses.en.yml, spec/components/app_simple_status_banner_component_spec.rb
Conflicting consent currently uses warm-yellow for the banner heading, with black text (other banner headings use white text). We also use red text to reflect this in the status text further down the page.
To reflect the colour used in the banner in the status text, and have it contrast on white, necessitates using a darker colour.
Let’s fix a few things by:
- Adding a new, app-specific dark orange colour
- Using this for both the conflicting banner heading and its corresponding status text
- Using red for refused consent
Existing `$color_nhsuk-yellow`, `$color_nhsuk-warm-yellow` and `$color_nhsuk-orange` colours, and the new `$color_app-dark-orange` colour (with a [contrast ratio of 4.72:1](https://webaim.org/resources/contrastchecker/?fcolor=BD5413&bcolor=FFFFFF)):
=> Use dark orange colour for conflicting status

app/controllers/manage_consents_controller.rb, app/models/consent.rb, spec/models/consent_spec.rb
Before this fix, when verbal consent was recorded, it incorrectly included questions with nil answers, when in fact it should have been persisting an empty `health_answers` field.
Solve this issue by resetting unused fields before saving, similarly to how it's done in `ConsentForm` (see #1238). This fix means that the controller doesn't need to pre-seed health questions during `Consent` creation.
=> Avoid persisting empty health answers for verbal refusals

spec/controllers/concerns/triage_mailer_concern_spec.rb, spec/factories/patient_sessions.rb, spec/factories/patients.rb, spec/factories/sessions.rb, spec/factories/teams.rb
We were using `after :create` blocks in the factories to create `has_one` and `has_many` associations, but there is a better way to do this, implemented here. We also created extra `consent` objects in `triage_mailer_concern_spec.rb`.
=> Tidy up the specs, mostly to avoid creating extra objects

app/controllers/dev_controller.rb, spec/controllers/concerns/triage_mailer_concern_spec.rb, spec/factories/example_campaigns.rb, spec/factories/patient_sessions.rb, spec/factories/patients.rb, spec/factories/sessions.rb, spec/factories/teams.rb, spec/features/verbal_consent_given_spec.rb
We've removed the Playwright tests that rely on the JSON-based example campaigns. The `/reset` endpoint is now used for manual testing and this PR removes the dependence on the example campaign JSON. The benefits of the changes in this PR:
- Brings us closer to being able to remove the JSON-based example campaign generation completely, which would remove a lot of code.
- Also won't have to regenerate the example campaign JSON once we're done.
- With this new implementation we aren't logged out automatically (probably achievable with the JSON-based reset, but this is where we are now).
- We're more reliant on our factories, which is better than relying on the example campaign support code. This has already exposed a couple of issues worth fixing in our factories that has helped speed up …
=> Refactor /reset to use factories.

app/components/app_consent_component.html.erb, app/components/app_consent_component.rb, app/components/app_health_questions_component.rb, app/controllers/consents_controller.rb, app/models/consent.rb, app/models/patient.rb, app/views/consents/show.html.erb, config/locales/en.yml, config/routes.rb, spec/components/app_consent_component_spec.rb, spec/features/verbal_consent_given_spec.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb, spec/features/verbal_consent_refused_spec.rb, spec/models/consent_spec.rb
This is a follow-on from https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1307.
Best reviewed commit-by-commit.
While the previous implementation used a view component, the new implementation is done with a view, and is predominantly tested by feature specs. This approach trades indirection and complexity for reduced reusability.
Looking ahead, consent details will need to be presented in a very similar way on the confirmation page of the redesigned consent recording flow; that page will include edit links so the presentation may not be directly reusable.
=> Patient page: use a table to present consents, tuck the consent details away onto a dedicated page

app/models/consent_form.rb, app/views/consents/show.html.erb, spec/models/consent_form_spec.rb
* Ensure that if the parent/carer doesn't provide a contact phone number, it's saved as `nil` on `ConsentForm` (currently `""`)
* If a phone number isn't provided, still show the row on the consent details page in Mavis, just populate the row with "Not provided"
=> Consent form phone number fixes

app/views/consents/show.html.erb, app/views/patients/show.html.erb, spec/features/parental_consent_spec.rb
* [Patient page: fix label on back button](https://github.com/nhsuk/manage-vaccinations-in-schools/commit/17bb364a42ecc9eb3d19b3cd9948504f4b69943c)
* [Fix crash on consent details page for digital consent](https://github.com/nhsuk/manage-vaccinations-in-schools/commit/84325e36ef5805f56c23fd5d512cfbfe5da952ae)
* [Handle the parent not knowing the GP reg or child not being registered](https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1328/commits/3d880687fe67bd252e07db7c20c5596c8e663fb3)
=> Consent details: fix crash, improve how GP info is shown

app/components/app_secondary_navigation_component.html.erb, app/helpers/application_helper.rb, app/javascript/application.js, spec/helpers/application_helper_spec.rb
We added Turbo and left it on globally which is the default.
This introduced a bug with the parental consent journey that causes users to not reach the confirmation page, which might lead them to think that the service is broken.
Turbo allows an alternate mode of operation where it's off by default and can be introduced on a per-link basis with the `data-turbo="true"` attribute: https://turbo.hotwired.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms
=> Disable turbo globally

app/controllers/concerns/patient_tabs_concern.rb, app/views/vaccinations/index.html.erb, config/initializers/tab_paths.rb, config/locales/en.yml, spec/controllers/concerns/patient_tabs_concern_spec.rb, spec/features/pilot_journey_spec.rb
Without this, the vaccinator needs to navigate to the specific child's page to record a vaccination.
Before:
After:
=> Bring back a list of children to vaccinate

spec/factories/patient_sessions.rb, spec/factories/patients.rb
Without this, patients were being created with no location. We may want to look at not allowing that to happen ... perhaps all patients should have a location, but this just fixes the factories to ensure that there's a location set for patients by default.
=> Ensure patients get a location in factories

lib/tasks/add_new_location.rake
This makes the all-in-one invocation consistent with the order in which the questions are asked in interactive mode.
=> Reverse order of parameters in add_new_location Rake task

Gemfile, Gemfile.lock, app/views/layouts/application.html.erb
This enables live reloading of CSS, JS, and even HTML in local development, improving the developer experience by shortening the feedback loop between making a change and seeing that change reflected in the frontend.
I've found some caveats when testing this locally:
- CSS is a cascading language, so updates are applied on top of each other, and code that has already been declared can't be "undeclared." As such, if you remove CSS and live-reload a new version of the CSS, those old rules will persist until a hard reload
- The JS for `nhsuk-button` isn't idempotent, and applying it multiple times to the same elements leads to a JS error. I believe it's harmless
- When reloading HTML, the turbo websocket appears to temporarily disconnect. It reconnects on its own in a few seconds but if you …
=> Add hotwire-livereload in development

.dockerignore
Our `.dockerignore` removes the `spec` folder but keeps `spec/factories`. The patient factory requires the `spec/support/faker/national_health_service` patch, which was missing from the Docker build, which causes `assets:precompile` to fail.
=> Fix assets:precompile in Docker

app/assets/stylesheets/_patients.scss, app/components/app_patient_table_component.html.erb, app/components/app_patient_table_component.rb, app/controllers/concerns/patient_sorting_concern.rb, app/controllers/consents_controller.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, app/helpers/application_helper.rb, app/javascript/controllers/autosubmit_controller.js, app/javascript/controllers/index.js, app/views/consents/index.html.erb, app/views/triage/index.html.erb, app/views/vaccinations/index.html.erb, spec/components/app_patient_table_component_spec.rb, spec/controllers/concerns/patient_sorting_concern_spec.rb, spec/features/patient_sorting_filtering_spec.rb, spec/helpers/application_helper_spec.rb, spec/rails_helper.rb
This implements filtering using a server-side request and turbo to progressively enhance it to be in-place.
A form with a method of `GET` is added to the patients table that sends name/dob parameters to the server. These params are handled in the controller to filter the list of patients down. The `sort` and `direction` parameters are maintained through hidden fields, allowing sorting and filtering to occur at the same time.
An `autosubmit` Stimulus controller then progressively enhances the form by hiding the submit button and automatically submitting the fields for the user 250ms after their last input. The content of the input fields are maintained using `data-turbo-permanent`. There is a `Reset filters` button that is set to disabled when the fields are empty and enabled when not.
The …
=> Allow users to filter patients by name/dob 

app/components/app_consent_component.html.erb, app/components/app_consent_component.rb, app/components/app_patient_page_component.html.erb, app/components/app_patient_page_component.rb, spec/components/app_consent_component_spec.rb, spec/components/app_patient_page_component_spec.rb, spec/features/self_consent_gillick_competent_spec.rb, spec/features/self_consent_not_gillick_competent_spec.rb
* Display the results of a Gillick assessment on the patient page
* Move the "Assess Gillick competence" button out of the Consent section and into the new Gillick Assessment section
* Add a (skipped) feature spec for a child who doesn't pass a Gillick assessment – there's a bug here currently, as the app lets the child give consent even if they are not Gillick competent
The following will be done in follow-up PRs:
* Turn the Gillick assessment button into a link
* Split up the Gillick assessment and self-consent into separate flows
* Ability to edit the Gillick assessment
* Roll self-consent in with verbal assessment etc
* Fix bug around consent when the child is not Gillick competent
Scenario|Before             |  After
:-------------:|:-------------:|:----------------:
Planned …
=> Patient page: display Gillick assessment results and other Gillick-related tweaks

app/components/app_consent_component.html.erb, app/components/app_patient_details_component.rb
Compared to the prototype, the areas of the patient page below have excessive whitespace, compared to the prototype:
=> Visual fixes (margin, extra borders) on the patient page

app/components/app_patient_table_component.html.erb, spec/features/patient_sorting_filtering_spec.rb
This test was relying on a race condition and the hidden behaviour of `expect` in rspec system tests.
Because system specs often trigger JavaScript and network requests, they have a built-in "sleep". If the assertion fails immediately, they try again after a short while, and only fail if all the tries fail.
This test was sorting the list as such:
```
- Cassidy
- Casey
- Blair
- Alex
```
And then testing that after filtering for `cas` that we're left with:
```
expect Cassidy
expect Casey
expect no third item
```
However, the implementation had a bug. Namely that `sort` and `direction` parameters were being lost upon using the name filtering. So the actual list from the server would be:
```
- Casey
- Cassidy
```
So why did the test succeed? The first two `expects` should fail. The reason …
=> Fix flakey patient sorting spec

spec/rails_helper.rb
From https://viewcomponent.org/guide/testing.html#rspec-configuration
Before:
```bash
Failure/Error: it { should have_text("Consent Given by John Doe (Mother)") }
expected `#<Capybara::Node::Simple tag="" path="/">.has_text?("Consent Given by John Doe (Mother)")`
to be truthy, got false
```
After:
```bash
Failure/Error: it { should have_text("Consent Given by John Doe (Mother)") }
expected to find text "Consent Given by John Doe (Mother)" in "Foobar\n"
```
=> Improve output of view component tests

app/components/app_activity_log_component.html.erb, app/components/app_activity_log_component.rb, app/views/patients/log.html.erb, spec/components/app_activity_log_component_spec.rb, spec/components/previews/app_activity_log_component_preview.rb
Prerequisite: https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1355
This refactors the log to a component, allowing us to more easily unit test the output against multiple scenarios without relying on heavy feature tests.
It also improves the component by adding the consolidated headers and by creating an `events` array that has a unified structure in the component class. We can add to this with all the different event types in follow-up PRs.
TODO:
http://localhost:4000/rails/view_components/app_activity_log_component/default
=> Refactor activity log to separate component

spec/components/app_patient_details_component_spec.rb, spec/components/app_simple_status_banner_component_spec.rb, spec/factories/consents.rb, spec/factories/patients.rb, spec/features/hpv_vaccination_administered_spec.rb, spec/features/hpv_vaccination_delayed_spec.rb, spec/features/hpv_vaccination_not_administered_spec.rb, spec/features/nivs_hpv_report_spec.rb, spec/features/triage_delay_vaccination_spec.rb, spec/features/triage_during_consent_spec.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb, spec/mailers/triage_mailer_spec.rb
This is a quick tidy-up of the factories with the main aim of fixing an issue with our generated data that caused consents not to have any `parent_relationship` defined.
To this end, `consents` now always inherit the parent information from the `patient` unless otherwise specified via `:from_mum` or `:from_dad`.
A few other changes:
- Some redundant traits were removed from the `patient` factory that created transient `patient_sessions`. The call-sites of these have been replaced with calls to the `patient_session` factory instead
- All patients now have an `address` by default as that's the more common case
- All patients now have a default age between 12-13 as that's the more common case
=> Ensure patient_relationship exists on factory'd consents

app/components/app_outcome_banner_component.rb, app/controllers/vaccines_controller.rb, app/helpers/vaccines_helper.rb, app/views/vaccines/index.html.erb, app/views/vaccines/show.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/vaccines.rb, spec/features/manage_vaccines_spec.rb
Adds show page for vaccines.
The layout is currently two-thirds but looks like it should be three-quarters looking at the prototype. To be addressed later. The prototype also adds the "Dose" field and pre-screening questions, which we don't have yet. Will add these later.
=> Add vaccines show page

app/components/app_activity_log_component.html.erb, app/components/app_activity_log_component.rb, spec/components/app_activity_log_component_spec.rb, spec/components/previews/app_activity_log_component_preview.rb, spec/factories/triage.rb
Prerequisite: https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1360
Events:
Further refinements:
http://localhost:4000/rails/view_components/app_activity_log_component/default
=> Add more events to activity log

app/components/app_patient_page_component.html.erb, app/controllers/gillick_assessments_controller.rb, app/controllers/manage_consents_controller.rb, app/models/consent.rb, app/models/gillick_assessment.rb, app/models/patient_session.rb, app/views/gillick_assessments/confirm.html.erb, app/views/gillick_assessments/gillick.html.erb, app/views/gillick_assessments/new.html.erb, app/views/gillick_assessments/notes.html.erb, config/locales/en.yml, config/routes.rb, spec/components/app_patient_page_component_spec.rb, spec/features/self_consent_gillick_competent_spec.rb, spec/features/self_consent_not_gillick_competent_spec.rb
This PR:
* splits up the Gillick assessment steps into a stand-alone 4-step journey
* makes the "get consent" journey record self-consent if the child is Gillick competent
* splits the Gillick assessment recording across two screens, as per the new design
* re-enables validations for those two screens
=> Gillick assessment recording: redesign

app/views/consents/show.html.erb, spec/features/self_consent_gillick_competent_spec.rb
=> Bugfix: on the consent details page, hide parent section for self-consent

app/assets/stylesheets/_table.scss, app/components/app_breadcrumb_component.html.erb, app/components/app_triage_form_component.html.erb, app/controllers/triage_controller.rb, app/views/patients/show.html.erb, spec/features/triage_during_consent_spec.rb
This functionality was broken when we added the secondary navigation menu to allow users to get to the Activity Log. This updates the test coverage and fixes the bug.
Also a couple of small but unrelated commits to the CSS.
=> Show validation error when user doesn't choose a triage status

.tool-versions, db/migrate/20240531213930_remove_gillick_fields_from_patient_session.rb
These are being interpreted as fields and breaking.
Also bump aws-copilot version.
=> Remove types from RemoveGillickFields migration 

spec/factories/consent_forms.rb
The consent_form factory autogenerates an email for the parent based on a faked name. Sometimes the name is something like "Sen. Star Hickle" which contains a period and gets email-ified to "sen..star.hickle@stamm.test" or similar. The double period doesn't pass our email RegExp validation.
=> Fix flakey test

db/seeds.rb
Without this, `audits` for creating sessions/patient_sessions are attributed to `nil` which isn't realistic.
=> Ensure initial seeds are audited to Nurse Joy

app/views/manage_consents/triage.html.erb
#1388 left a bug, whereby the error summary wasn't being displayed.
=> Manage consents: show error summary on triage step

app/components/app_card_component.rb, app/components/app_patient_page_component.html.erb, app/components/app_simple_status_banner_component.html.erb, app/components/app_simple_status_banner_component.rb, app/components/app_triage_form_component.html.erb, app/components/app_triage_form_component.rb, app/controllers/triage_controller.rb, app/views/triage/new.html.erb, config/locales/patient_session_statuses.en.yml, config/routes.rb, spec/components/app_patient_page_component_spec.rb, spec/components/app_simple_status_banner_component_spec.rb, spec/components/previews/app_simple_status_banner_component_preview.rb, spec/features/triage_spec.rb, spec/features/verbal_consent_refused_spec.rb
This adds a `/triage/new` page.
=> Allow users to update a triage outcome

app/controllers/manage_consents_controller.rb, app/models/parent.rb, app/views/manage_consents/who.html.erb, config/locales/en.yml, spec/factories/consents.rb
This makes the Mavis interaction consistent with the parent consent forms.
=> Mavis consent: must confirm parental responsibility when 'other' parent

app/assets/stylesheets/_card.scss, app/components/app_card_component.rb, app/components/app_compare_consent_form_and_patient_component.html.erb, app/components/app_outcome_banner_component.rb, app/components/app_patient_page_component.html.erb, app/components/app_session_details_component.html.erb, app/components/app_simple_status_banner_component.html.erb, app/views/consent_forms/review_match.html.erb, app/views/consent_forms/show.html.erb, app/views/consent_forms/unmatched_responses.html.erb, app/views/consents/show.html.erb, app/views/dashboard/index.html.erb, app/views/gillick_assessments/confirm.html.erb, app/views/manage_consents/confirm.html.erb, app/views/parent_interface/consent_forms/confirm.html.erb, app/views/sessions/show.html.erb, app/views/vaccines/index.html.erb, app/views/vaccines/show.html.erb, spec/components/app_card_component_spec.rb
Also remove the `feature` option and make it implicit on receiving `colour`.
Like https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1403 but done in ViewComponent instead.
Plus a few other commits.
=> Add heading and description slots to AppCardComponent

app/models/pds/patient.rb, config/initializers/inflections.rb, spec/models/pds/patient_spec.rb, spec/support/pds-get-patient-response.json
This is the simplest possible way of getting a patient from PDS. Wrapped up into a model so we can change the implementation later.
The model itself is also quite simple, whereas the FHIR model may potentially have multiple names (in case the patient has changed their name), etc. We need to better understand how Mavis uses this data before we expand our own model, so consider this a proof-of-concept.
=> PDS Integration

config/routes.rb
This will further break offline support, but I suspect that stopped working a long time ago and would need to be revived separately, in any case.
=> Remove routes flagged by `rails routes --unused`

spec/rails_helper.rb
When pyjama coding 😬  on a train without internet, the build intermittently fails.
To reproduce:
```
% bundle exec rspec ./spec/features/patient_sorting_filtering_spec.rb:41 spec/models/pds/patient_spec.rb --seed 27063
Run options: include {:locations=>{"./spec/features/patient_sorting_filtering_spec.rb"=>[41]}}
Randomized with seed 27063
.F
Failures:
1) PDS::Patient.find returns a patient with the correct attributes
Failure/Error:
Net::HTTP.get(
URI(
"https://sandbox.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/#{nhs_number}"
),
"X-Request-ID": SecureRandom.uuid
)
Socket::ResolutionError:
Failed to open TCP connection to sandbox.api.service.nhs.uk:443 (getaddrinfo: nodename nor servname provided, or not known)
Finished in 1.95 seconds (files took 1.34 seconds to load)
2 …
```
=> Re-enable WebMock after each system test

app/components/app_matching_criteria_component.rb, app/mailers/application_mailer.rb, app/models/consent_form.rb, app/views/consent_forms/review_match.html.erb, app/views/consent_forms/show.html.erb, app/views/consent_forms/unmatched_responses.html.erb, app/views/parent_interface/consent_forms/record.html.erb
This PR cleans up some stuff left broken after #1407.
As the obsolete fields were still being mentioned in the `encrypts` invocation on ConsentForm, the model still had getters for them, which returned nulls.
After cleaning up those invocations, a bunch of templates, which were not properly ported across to the `Parent` model, broke.
Clearly our feature specs could be more thorough in asserting on the strings like the parent's name, otherwise this would have been picked up earlier.
=> Properly remove obselete ConsentFrom.parent_* fields

app/views/application/_header.html.erb, app/views/users/sessions/new.html.erb, spec/features/user_authentication_spec.rb
In the designs these have been renamed to "Log in" and "Log out". I've decided internally to keep the naming "Sign X" as that matches our database column names and the naming convention that Devise uses.
Although I've changed the content on the log in page as well, this design is likely to change anyway as we integrate with CIS2.
=> Rename sign in and sign out

spec/features/triage_spec.rb, spec/support/email_expectations.rb
The triage feature specs were failing intermittently when the order that the emails were sent didn't match the order they were being tested. This change adds a way to ignore the ordering to the support helper used.
Just for the record, the seed `7582` seemed to be able to trigger this error more often than not.
=> Ignore order of emails in triage specs

.rubocop.yml
This is a convention we've adopted for a local directory to store project-related files that we don't want to add to the repo. It's ignored in the other files, but recently I've added some dirty, smelly Ruby code that even Rubocop couldn't fix for me, and its errors were blocking running bin/lint, so let's just ignore it.
=> Ignore scratchpad dir in Rubocop

app/components/app_activity_log_component.rb, app/components/app_triage_form_component.html.erb, app/components/app_triage_notes_component.html.erb, app/components/app_triage_notes_component.rb, config/locales/en.yml, spec/components/app_activity_log_component_spec.rb, spec/components/app_triage_form_component_spec.rb, spec/components/app_triage_notes_component_spec.rb, spec/factories/triage.rb
This updates the patient triage notes component to include the triage decision heading that we show in the activity log, and ensures that the service matches the designs in the prototype.
=> Show "triaged decision" on the patient triage notes

bin/heroku-release
It appears that `db:prepare` already takes into account whether the database has been setup. It runs `db:schema:load` and `db:seed` the first time, and `db:migrate` on subsequent attempts.
=> Simplify bin/heroku-release

spec/features/verbal_consent_given_do_not_vaccinate_spec.rb, spec/features/verbal_consent_given_keep_in_triage_spec.rb, spec/features/verbal_consent_given_ready_to_vaccinate_spec.rb, spec/features/verbal_consent_given_safe_to_vaccinate_spec.rb, spec/features/verbal_consent_given_spec.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb, spec/features/verbal_consent_refused_spec.rb
I was doing more design alignment work around the consents recorded by staff. The current verbal consent specs feel more awkward to work with than they could be, due in part to:
* the top-level specs including lots of granular 'how' steps (e.g. talking about page navigation), instead of focusing on the 'what' (i.e. what the user is trying to achieve)
* some extra bits that can be checked once and don't need to be repeated across multiple specs
I've revised each of the specs, so hopefully they are easier to read, and it's more obvious how they differ from one other.
=> Verbal consent spec improvements

config/locales/en.yml
These messages got lost during the refactoring to the `Parent` model.
=> Bugfix: reinstate parent email validation messages

config/routes.rb
This ensures that our production deployment steers users to the naked/root domain, so that users don't end up with cookies on both domains and a potentially confusing user experience.
Based on https://masilotti.com/rails-redirect-www/
Tested locally by temporarily whitelisting two domains in `config/application.rb`:
```ruby
config.hosts << "app.local:4000"
config.hosts << "www.app.local:4000"
```
I added those to my hosts file:
```bash
127.0.0.1  app.local
127.0.0.1  www.app.local
```
The result is that the www subdomain redirects to the root:
```bash
$ curl -I http://www.app.local:4000
HTTP/1.1 301 Moved Permanently
location: http://app.local:4000/
content-type: text/html; charset=UTF-8
cache-control: no-cache
x-request-id: 7b54f3fa-0fc6-4109-96b3-d97bf7615ece
x-runtime: 0.013215 …
```
=> Redirect www subdomain to root

app/components/app_secondary_navigation_component.rb, app/controllers/reports_controller.rb, app/views/campaigns/show.html.erb, app/views/reports/index.html.erb, config/routes.rb, spec/components/app_secondary_navigation_component_spec.rb, spec/features/nivs_hpv_report_spec.rb
This adds a new tab shown on the campaign page which allows the user to download the NIVS data report, currently only available by going directly to the `/reports` URL. This moves us closer to the designs in the prototype, and it's where we will start to add the journey related to uploading data from NIVS.
=> Add reports page to campaigns

app/assets/stylesheets/_highlight.scss, app/assets/stylesheets/_overrides.scss, app/assets/stylesheets/application.scss, app/components/app_compare_consent_form_and_patient_component.rb, spec/components/app_compare_consent_form_and_patient_component_spec.rb
Copied from prototype: https://github.com/nhsuk/manage-vaccinations-in-schools-prototype/commit/8b1f6ff15f5e3700dcbd1b69e7fa6b78a48b1b9e
=> Replace mark CSS with app-highlight

app/controllers/immunisation_imports_controller.rb, app/views/immunisation_imports/_breadcrumbs.html.erb, app/views/immunisation_imports/errors.html.erb, app/views/immunisation_imports/new.html.erb, app/views/immunisation_imports/success.html.erb, spec/features/immunisation_imports_upload_spec.rb
This ensures that if any validation errors occur as part of importing vaccination events, they are shown to the user who originally uploaded the file.
This is based on a similar journey in the pilot cohort list, and will be further improved with designs later.
=> Show immunisation import errors

app/controllers/concerns/authentication_concern.rb, app/controllers/users/accounts_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/views/users/accounts/role_not_found.html.erb, config/routes.rb, spec/features/user_cis2_authentication_with_wrong_role_spec.rb, spec/features/user_cis2_authentication_with_wrong_team_spec.rb, spec/fixtures/cis2_auth_info.rb
Users must have certain roles to be able to access the system. If they do not have an appropriate role they will get the page below. The list of valid roles is still naively implemented, we will refine that as we develop authorisation flows to match the designs.
=> Check user's role on cis2 login

app/controllers/dev_controller.rb, db/seeds.rb
`replant` was added in Rails 6 and seems like it does what we want in this case:
```sh
bin/rails db:seed:replant
Truncate tables of each database for current environment and load the seeds
```
This also aligns the seeds to populate the `Y51` team.
Notable differences:
- We don't reset the identity counter anymore, so IDs will continue incrementing after resets from where they left off. This is fine; we used to rely on predictable IDs for the Playwright tests, but it isn't necessary anymore.
- We opted out of resetting feature flags before, which made local development easier on new features that relied on us keeping a feature flag around. In that situation, I think we could include the feature flags into `seeds` as well. `seeds` are already configured not to run in prod-like environments, …
=> Use db:seed:replant in reset script

app/models/patient.rb
When importing NIVS immunisation data, we don't get the parent information. Rather than making up a parent record, we should allow patient records without parent records.
=> Make parents optional on patients

app/controllers/concerns/authentication_concern.rb, app/controllers/users/omniauth_callbacks_controller.rb
No functional change. This changes it so we only accommodate a single role to be selected in CIS2, which tracks our understanding of how CIS2 works: you can only select one org / role combo at a time.
This was originally going to be part of a bigger bit of work, but that is now waiting for more design input so I thought I'd 🚢 this.
=> Tidy up cis 2 role info in session

app/controllers/manage_consents_controller.rb, app/models/consent.rb, app/models/parent.rb, app/views/manage_consents/confirm.html.erb, app/views/manage_consents/parent_details.html.erb, app/views/manage_consents/who.html.erb, config/locales/en.yml, spec/features/pilot_journey_spec.rb, spec/features/verbal_consent_given_by_new_parental_contact_spec.rb, spec/features/verbal_consent_given_do_not_vaccinate_spec.rb, spec/features/verbal_consent_given_keep_in_triage_spec.rb, spec/features/verbal_consent_given_safe_to_vaccinate_spec.rb, spec/features/verbal_consent_given_spec.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb, spec/features/verbal_consent_refused_spec.rb
* allow the "who" to be a parent from a previous consent form or consent
* allow the "who" to be the child after they've been assessed as Gillick competent
=> Mavis consents: record consent from existing cohort parent, instead of creating new parent contact every time

app/models/patient.rb
The uniqueness validation and database constraint on the `nhs_number` field is currently failing to work because the field is changing each time it's saved.
This also allows us to `find_by(nhs_number:)` which is very likely to be a need at some point.
=> Deterministically encrypt NHS number

app/components/app_patient_details_component.rb, app/controllers/campaigns_controller.rb, app/controllers/immunisation_imports_controller.rb, app/controllers/reports_controller.rb, app/helpers/patient_helper.rb, app/models/vaccination_record.rb, app/views/campaigns/sessions.html.erb, app/views/campaigns/show.html.erb, app/views/immunisation_imports/_breadcrumbs.html.erb, app/views/immunisation_imports/errors.html.erb, app/views/immunisation_imports/index.html.erb, app/views/immunisation_imports/new.html.erb, app/views/immunisation_imports/show.html.erb, app/views/immunisation_imports/success.html.erb, config/routes.rb, spec/features/immunisation_imports_upload_spec.rb, spec/features/nivs_hpv_report_spec.rb, spec/features/parental_consent_refused_spec.rb, spec/features/parental_consent_spec.rb, spec/features/response_matching_spec.rb, spec/features/self_consent_gillick_competent_spec.rb, spec/features/self_consent_not_gillick_competent_spec.rb, spec/features/user_authorisation_spec.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb, spec/helpers/patient_helper_spec.rb
This makes a number of changes to the pages related to immunisation imports to match the prototype. See individual commits for more details. It's a relatively large PR, and I could extract some of the changes to separate PRs if that's preferred.
As we don't currently process the import and generate vaccination records, there will always be 0 records shown, but once we process the import we can update the tests to ensure the records come through.
=> Update immunisation import designs to match prototype

app/models/immunisation_import.rb, app/models/session.rb, db/migrate/20240717155646_add_imported_from_to_sessions.rb, db/schema.rb, spec/factories/sessions.rb, spec/models/immunisation_import_row_spec.rb, spec/models/immunisation_import_spec.rb, spec/models/session_spec.rb
This allows us to finally replace the stubbed patient_session.
Reviewing the individual commits might be easier.
=> Create Session and PatientSession records during import

app/models/immunisation_import.rb, app/views/immunisation_imports/show.html.erb, config/locales/en.yml, spec/features/immunisation_imports_upload_spec.rb, spec/models/immunisation_import_row_spec.rb
This ensures that postcodes are imported from the CSV immunisation import and then displayed as part of the patient records.
=> Import postcodes

app/controllers/manage_consents_controller.rb, app/models/consent.rb, app/views/manage_consents/who.html.erb, spec/factories/consents.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb
Make it easier to contact parents from previous consents, not just the cohort parent.
=> Mavis consents: Make it easy to pick parents from previous consents

.github/workflows/deploy.yml
This block accomplishes two things:
- The `concurrency.group` setting ensures that only 1 deploy can be attempted at any time
- The `concurrency.cancel-in-progress` setting ensures that the last scheduled deploy cancels any in-progress earlier deploys
This should lead to less failed deploys on Tuesday when we usually merge a few Dependabot PRs back to back and cause a deploy queue to occur.
Using `github.workflow` and `github-ref` to identify the concurrency group ensures that deploys from different branches or to different environments should not clash.
=> Cancel in progress deploys

app/components/app_patient_details_component.rb, app/views/immunisation_imports/show.html.erb, spec/components/app_patient_details_component_spec.rb, spec/features/pilot_journey_spec.rb
This formats the NHS numbers as per the designs with a monospace font.
=> Update NHS number formatting

app/controllers/immunisation_imports_controller.rb, app/views/immunisation_imports/show.html.erb, spec/features/immunisation_imports_upload_spec.rb
Currently we're using the recorded at date, but this will always be when the immunisation import was imported, whereas instead we want to show when the vaccination session happened.
=> Use session date in immunsation import show view

.github/workflows/deploy.yml
Currently, deploys to training are being cancelled by deploys to `test` because the deploy environment isn't part of the concurrency group.
=> Fix deploy concurrency group

app/controllers/dev_controller.rb, spec/components/app_patient_details_component_spec.rb, spec/components/app_patient_page_component_spec.rb, spec/components/previews/app_activity_log_component_preview.rb, spec/components/previews/app_consent_component_preview.rb, spec/components/previews/app_consent_summary_component_preview.rb, spec/components/previews/app_health_questions_component_preview.rb, spec/components/previews/app_outcome_banner_component_preview.rb, spec/components/previews/app_patient_table_component_preview.rb, spec/components/previews/app_simple_status_banner_component_preview.rb, spec/models/session_spec.rb, spec/models/vaccine_spec.rb
FactoryBot is already in the global scope in the context of RSpec tests so we don't need to call it with the FactoryBot prefix.
This change is purely stylistic and should have no changes to the tests themselves.
=> Remove explicit reference to FactoryBot

app/controllers/component_previews_controller.rb, spec/components/previews/app_activity_log_component_preview.rb, spec/components/previews/app_consent_component_preview.rb, spec/components/previews/app_health_questions_component_preview.rb, spec/components/previews/app_outcome_banner_component_preview.rb, spec/components/previews/app_patient_table_component_preview.rb, spec/components/previews/app_simple_status_banner_component_preview.rb
This fixes an issue that was introduced in https://github.com/nhsuk/manage-vaccinations-in-schools/commit/3869396d1d696cea865e2be15e7da5a3bfe9e6a6 where the components could no longer be rendered as they were referring to `FactoryBot` methods implicitly which are not automatically included in previews.
I was hoping there was a way of including this automatically in all previews, but aside from creating our own `ViewComponent::Preview` base class there doesn't seem to be a nice way of doing it.
=> Include FactoryBot methods in previews

app/components/app_vaccination_record_details_component.rb, app/controllers/vaccination_records_controller.rb, app/helpers/vaccines_helper.rb, app/views/immunisation_imports/show.html.erb, app/views/vaccination_records/show.html.erb, app/views/vaccines/show.html.erb, config/routes.rb, spec/components/app_vaccination_record_details_component_spec.rb, spec/factories/batches.rb, spec/factories/vaccination_records.rb, spec/features/immunisation_imports_upload_spec.rb, spec/helpers/vaccines_helper_spec.rb
This adds a page which users can use to view the details of a particular vaccination record that may have been imported from an immunisation import.
=> Add vaccination record page

config/environments/development.rb
Without this, the websocket disconnects after every change to the HTML. It reconnects after a few seconds, but during that time, changes aren't reflected.
This seems to make it more robust.
=> Use Turbo streams for local hotwire livereload

spec/models/consent_form_spec.rb
This was causing intermittent failures in spec runs. With a completely random name this will hopefully be avoided.
=> Avoid random name clash in consent form spec

app/models/dps_export_row.rb, spec/models/dps_export_row_spec.rb
These are static values for the time being so may as well just add them.
I also found it a bore to count the fields to get the right index for the specs, so decided to try out adding the numbers to them like this. Our formatters don't like space in front of the comment "`#`" which is why the spaces have been added after like this. Dunno what people think, happy to skip it if it's too fugly.
=> Add action_flag and primary_source fields to dps export

app/models/vaccine.rb
This was a typo. The term is correct.
=> Fix incorrect procedure code

app/models/immunisation_import.rb, spec/models/immunisation_import_spec.rb
If the vaccine record is at a previously created patient session, it's in the same delivery site and using the same delivery method, it's likely the same vaccination record as before. So we should skip it.
=> Do not duplicate vaccination records during import

app/models/dps_export_row.rb, spec/controllers/concerns/triage_mailer_concern_spec.rb, spec/factories/patient_sessions.rb, spec/factories/vaccination_records.rb, spec/models/dps_export_row_spec.rb
This ensures that the location code is included as part of the DPS export, either coming from the URN of the location itself or if that's not available, the ODS code of the team running the campaign.
I've also done a small refactor in the first commit that can be reviewed separately.
=> Add location code to DPS export

app/models/dps_export_row.rb, spec/models/dps_export_row_spec.rb
This ensures that the location code type URI is included as part of the DPS export, either created from the URN of the location itself or if that's not available, the ODS code of the team running the campaign.
I've also done a small refactor in the first commit that can be reviewed separately.
=> Add location code type URI to DPS export

app/components/app_patient_details_component.rb, app/components/app_vaccination_record_details_component.rb, app/components/app_vaccination_record_table_component.html.erb, app/components/app_vaccination_record_table_component.rb, app/controllers/vaccination_records_controller.rb, app/helpers/patient_helper.rb, app/helpers/patients_helper.rb, app/helpers/vaccines_helper.rb, app/views/campaigns/sessions.html.erb, app/views/campaigns/show.html.erb, app/views/immunisation_imports/_breadcrumbs.html.erb, app/views/immunisation_imports/index.html.erb, app/views/immunisation_imports/new.html.erb, app/views/immunisation_imports/show.html.erb, app/views/vaccination_records/index.html.erb, app/views/vaccination_records/show.html.erb, app/views/vaccines/show.html.erb, config/locales/en.yml, config/routes.rb, spec/components/app_vaccination_record_table_component_spec.rb, spec/features/immunisation_imports_upload_spec.rb, spec/features/nivs_hpv_report_spec.rb, spec/helpers/patients_helper_spec.rb, spec/helpers/vaccines_helper_spec.rb
This improves various pages related to vaccination records, immunisation imports and campaigns to match the latest designs in the prototype. See individual commits for more details.
=> Update vaccination record and immunsation import designs

app/models/dps_export_row.rb, spec/models/dps_export_row_spec.rb
The primary_source value in DPSExportRow is updated to 'TRUE' to reflect that the record is coming from the organisation administering the vaccine.
=> Update primary_source value to 'TRUE' in DPS Export

app/models/dps_export_row.rb, spec/models/dps_export_row_spec.rb
This ensures that the dose sequence is included in the DPS export, although we don't yet import this value which will come in follow up commits.
=> Export dose sequence to DPS

app/models/immunisation_import.rb, spec/models/immunisation_import_row_spec.rb
We expect that some import CSV will use the column `GENDER_CODE` and some will use `GENDER` so we need to update the importer to handle both.
I've also removed this column from the required columns validation as it could be either. This will still raise a row-level validation error on the gender if neither column exists, but we might want to improve the header validation in the future to handle optional values.
=> Handle variations in gender code column name

app/assets/stylesheets/_button-group.scss
Fix nested rules for button group styles to address the following Sass deprecation notice:
> DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
> rules will be changing to match the behavior specified by CSS in an upcoming
> version. To keep the existing behavior, move the declaration above the nested
> rule. To opt into the new behavior, wrap the declaration in `& {}`.
>
> More info: https://sass-lang.com/d/mixed-decls
=> Fix Sass deprecation for nested rules

app/assets/stylesheets/_button.scss
With #1563, we no longer need custom warning button styles.
That said, it doesn’t look like we’re using warning buttons in the app yet, so this can be merged independent of the above PR.
=> Remove warning button styles

app/models/immunisation_import_row.rb, spec/features/immunisation_imports_upload_spec.rb, spec/models/immunisation_import_row_spec.rb, spec/models/immunisation_import_spec.rb
For HPV, it's valid to have a dose sequence and therefore we need to ensure that it's imported correctly. This is an optional field, as Flu files won't contain a dose sequence.
To determine whether we need to import the dose sequence or not we use the maximum dose sequence on the vaccine.
This depends on the vaccine being imported, which hasn't yet been implemented.
=> Import dose sequence from HPV files

app/models/immunisation_import_row.rb, app/models/patient_session.rb, app/models/vaccination_record.rb, spec/components/app_activity_log_component_spec.rb, spec/components/app_vaccination_record_details_component_spec.rb, spec/factories/campaigns.rb, spec/factories/vaccines.rb, spec/features/manage_vaccines_batches_spec.rb, spec/fixtures/immunisation_import/valid_hpv.csv, spec/helpers/vaccines_helper_spec.rb, spec/models/dps_export_row_spec.rb, spec/models/immunisation_import_row_spec.rb, spec/models/immunisation_import_spec.rb, spec/models/nivs_report_row_spec.rb, spec/models/vaccination_record_spec.rb
This updates the immunisation import code to import vaccines from the `VACCINE_GIVEN` column, matching them with the `nivs_name` column we added in #1568.
See individual commits for more details.
=> Import vaccines from NIVS spreadsheets

config/vaccines.yml, db/seeds.rb, lib/tasks/vaccines.rake, spec/factories/campaigns.rb, spec/factories/vaccines.rb
This builds on top of #1550 to use the configuration in a number of ways:
- automatically define factory traits that we can use in our tests
- populate vaccines as part of running `db:seed`
- provide a Rake task (`vaccines:seed`) that can be used to populate only the vaccines in deployed environments
=> Seed vaccines from an initialiser configuration 

app/assets/stylesheets/_file-upload.scss
Fix alignment of file selector text in Firefox and Chrome. Also remove unsoiled focus ring, which is fine as the button already receives focus styles. 
| - | - |
| <img width="300" alt="Before screenshot" src="https://github.com/user-attachments/assets/e6c8b626-9d9f-45d3-97f8-623b0d2b77ec"> | <img width="300" alt="After screenshot" src="https://github.com/user-attachments/assets/66ee7d6b-3a9c-4a37-ae6d-9483fbf5bcd6"> |
=> Fix alignment of text on file upload button

app/controllers/immunisation_imports_controller.rb
The success action of the immunisation imports controller used to be used but now we show a flash banner so it can be safely removed.
=> Remove unused controller action

app/controllers/concerns/authentication_concern.rb, spec/features/user_authentication_failure_spec.rb
This was sending users back to the start page which can be confusing. Worth noting, users will probably not see this journey because they'll be using CIS2, but it's still a qol issue in development.
=> Keep user on login page when they fail auth

app/models/immunisation_import_row.rb, app/models/session.rb, spec/models/immunisation_import_spec.rb
Also validate that it's set on for non-draft sessions.
=> Bigfix: set session time of day during imms import

app/controllers/vaccination_records_controller.rb, app/jobs/dps_export_job.rb, app/models/campaign.rb, app/models/dps_export.rb, app/models/dps_export_row.rb, app/views/immunisation_imports/index.html.erb, config/routes.rb, spec/jobs/dps_export_job_spec.rb, spec/models/dps_export_spec.rb
This refactors the DPSExport class to encapsulate everything related to the DPS export (fetching the correct vaccination records with SQL joins for performance, exporting only new records, and resetting exported records) so it can be used in multiple places with the same logic applied each time.
A few things this improves:
- The send to MESH job was exporting unadminstered records, unlike via the UI
- The send to MESH job had N+1 query performance issues
- The logic around which records have already been exported was found separately in the controller and job
=> Refactor DPSExport

app/controllers/immunisation_imports_controller.rb, app/models/immunisation_import.rb, app/models/immunisation_import_row.rb, spec/models/immunisation_import_spec.rb
When importing data for the immunisation import we want to ignore records where the vaccine wasn't administered, rather than importing them. This is to match the Mavis reporting specification.
For now we should another flash banner with the number of ignored records, but we might want to improve the UI in the future.
=> Don't import un-administered records

app/helpers/patients_helper.rb, spec/components/app_patient_details_component_spec.rb, spec/components/app_vaccination_record_table_component_spec.rb, spec/features/immunisation_imports_upload_spec.rb, spec/features/pilot_journey_spec.rb, spec/helpers/patients_helper_spec.rb
Currently, in certain scenarios (notably iOS Safari, perhaps other user agents), NHS numbers get detected as being phone numbers and are linked to accordingly. Trying to copy an NHS number, or accidentally clicking on a linked NHS number may initiate a phone call.
We can prevent numbers from being detected as phone numbers by adding the following meta tag:
```html
<meta name="format-detection" content="telephone=no">
```
However, that prevents actual telephone numbers from being linked as well, which is useful. We could revert this behaviour by adding a link with the `tel:` protocol to telephone numbers, but linked phone numbers may not make sense on desktop browsers where there is less likelihood of there being a telephony function.
What we need to do is opt-out NHS numbers from being …
=> Prevent detection of NHS numbers as telephone numbers

app/models/location.rb
This adds validation using the standard Rails validation to ensure that location URLs are correctly formatted as valid URLs.
=> Ensure location URL is a URL

app/components/app_vaccination_record_details_component.rb, app/models/immunisation_import_row.rb, app/models/vaccination_record.rb, spec/components/app_vaccination_record_details_component_spec.rb, spec/models/immunisation_import_row_spec.rb
It's very likely that the person who is uploading the vaccinations **isn't** the vaccinator, so we can't make that assumption.
* Allow `VaccinationRecord#user` to be `nil`
* Don't populate `VaccinationRecord#user` when importing
* Don't break when showing a vaccination record without a `user`
=> Immunisation importer: don't set the import user as vaccinator

app/models/immunisation_import_row.rb, config/locales/en.yml, spec/features/immunisation_imports_upload_spec.rb, spec/models/immunisation_import_row_spec.rb, spec/models/immunisation_import_spec.rb
This implements the logic related to importing session locations to correctly handle home educated patients, and vaccination records where we don't have the school URN. See individual commits for more details.
=> Improve logic related to importing session locations

app/models/vaccine.rb, spec/models/health_question_spec.rb, spec/models/vaccine_spec.rb
This adds an enum definition to vaccines to formalise the types of vaccines we support. This will support the creation of new campaigns as we can use the list from the enum to decide the campaign type (either Flu or HPV).
=> Formalise vaccine types

spec/components/app_activity_log_component_spec.rb, spec/components/app_outcome_banner_component_spec.rb, spec/components/app_patient_page_component_spec.rb, spec/factories/campaigns.rb, spec/factories/example_campaigns.rb, spec/factories/vaccines.rb, spec/features/immunisation_imports_upload_spec.rb, spec/models/consent_form_spec.rb, spec/models/consent_spec.rb, spec/models/immunisation_import_row_spec.rb, spec/models/immunisation_import_spec.rb
This makes a number of changes to the campaign factory to simplify the default set up (reducing the number of associations) and updates the tests to only use a specific trait when required. Locally this has improved the performance of the tests by about 15 seconds:
```
Executed in   71.39 secs    fish           external
usr time   47.79 secs    0.09 millis   47.79 secs
sys time    3.35 secs    2.15 millis    3.35 secs
```
```
Executed in   56.78 secs    fish           external
usr time   38.35 secs    0.09 millis   38.35 secs
sys time    2.64 secs    2.07 millis    2.63 secs
```
=> Simplify campaign factory

app/models/campaign.rb, spec/models/campaign_spec.rb
This adds validation on the campaign name to ensure that it's provided. The field is already marked as not null, but this adds user-facing errors to the model.
=> Ensure campaign name is present

lib/tasks/mesh.rake
This rake task isn't tested because it's not on the critical path, so errors may crop up.
=> Fix mesh:validate_mailbox task

app/controllers/campaigns/new_controller.rb, app/controllers/campaigns_controller.rb, app/helpers/campaigns_helper.rb, app/models/campaign.rb, app/models/vaccine.rb, app/views/campaigns/index.html.erb, app/views/campaigns/new/confirm.html.erb, app/views/campaigns/new/dates.html.erb, app/views/campaigns/new/details.html.erb, config/locales/en.yml, config/routes.rb, spec/features/create_campaign_spec.rb, spec/models/campaign_spec.rb
This adds a new step-by-step interface for creating new campaigns based on the designs in the prototype. I've introduced a new controller which handles all the logic related to the steps using the Wicked Gem that we're using in other places.
=> Add interface for creating campaigns

config/locales/en.yml
This adds a missing error message to the campaign creation page when the programme type is not selected.
=> Add missing campaign error message

app/models/immunisation_import_row.rb, spec/models/immunisation_import_row_spec.rb
This improves the test by explicitly checking the time zone to ensure that we're correctly choosing GMT or BST according to the date of the vaccination.
We've also decided to change the time of day to be midday rather than midnight.
=> Refactor administered_at test

app/models/consent.rb, app/models/consent_form.rb, app/models/health_answer.rb, app/models/immunisation_import_row.rb, app/models/parent.rb, app/models/session.rb, app/models/triage.rb, app/models/vaccination_record.rb, config/locales/en.yml, spec/models/consent_form_spec.rb
When a presence validation is paired with an inclusion validation there's often no need to have both. The inclusion implicitly checks whether the value is present by requiring it to match the list of valid values, and we often don't need to present the user with two error messages (one for presence and one for inclusion).
=> Remove unneeded presence validations

app/models/dps_export.rb, spec/models/dps_export_spec.rb
Despite being described as a CSV file, the spec for this DPS export wants a pipe field separator. Is this really still called a CSV file??
=> Use pipe to separate the DPS csv fields

app/models/immunisation_import_row.rb, app/models/vaccination_record.rb, spec/components/app_vaccination_record_details_component_spec.rb, spec/controllers/concerns/vaccination_mailer_concern_spec.rb, spec/factories/patient_sessions.rb, spec/factories/vaccination_records.rb, spec/features/hpv_vaccination_administered_spec.rb, spec/features/hpv_vaccination_default_batch_spec.rb, spec/features/immunisation_imports_upload_spec.rb, spec/features/pilot_journey_spec.rb, spec/models/dps_export_row_spec.rb, spec/models/immunisation_import_row_spec.rb, spec/models/immunisation_import_spec.rb, spec/models/vaccination_record_spec.rb
This validates the `administered_at` column to ensure that it's always within the start and end date of the campaign. We need this to ensure that we're only recording vaccinations that are part of the campaign.
=> Validate vaccination record administered at date

lib/tasks/schools.rake
Use `import!` which causes the import to fail if any locations don't pass validations.
The GIAS CSV contains some school addresses that don't have a protocol. As such, they are not valid URLs according to validate_url.
To work around this, we can force prepend `https://`, which assumes that the school websites have HTTPS setup. This isn't a given, but it feels like the better default, since HTTPS is pretty strongly pushed by browser vendors.
The URL for Legh Vale Primary School is also malformed and starts with `http:www`. It's the only instance of this, but we have to work around it.
=> Fix school importer

Gemfile
This gem is required to run the `schools:import` task.
=> Move ruby-progressbar to default dependencies

app/components/app_vaccination_record_details_component.rb, spec/components/app_vaccination_record_details_component_spec.rb
Sometimes sessions won't have a location associated with them (in particular as part of the import process where we're unable to identify exactly where a vaccination event happened), at the moment the page shows an error by trying to get access to the name of a `nil` location.
=> Support sessions without locations

app/models/immunisation_import_row.rb, config/locales/en.yml, spec/models/immunisation_import_row_spec.rb
This follows up from #1644 with further improvements to the error handling for the immunisation import to make the error messages clearer and more consistent, see individual commits for more details.
=> Further improvements to import error handling

app/controllers/vaccines_controller.rb, app/models/vaccine.rb, app/views/vaccines/index.html.erb
When we're displaying the vaccines index page we also display the batches, currently this performs a separate query for each vaccine rather than pre-fetching the batches for all the vaccines.
=> Remove N+1 query from vaccines index

app/components/app_vaccination_record_details_component.rb, spec/components/app_vaccination_record_details_component_spec.rb
We store the school name in the notes on the vaccination record if we're unable to link it with a stored location, so it makes sense that we'd want to show these notes back to users.
=> Show vaccination record notes

app/models/immunisation_import_row.rb, spec/models/immunisation_import_row_spec.rb
The spec actually has these values written as `Y` or `N`, but currently we're testing with `Yes` and `No`, this commit updates the importer to support both variations.
=> Allow more values for vaccinated

app/components/app_activity_log_component.rb, app/components/app_outcome_banner_component.rb, app/components/app_session_details_component.rb, app/controllers/sessions_controller.rb, app/helpers/sessions_helper.rb, app/models/session.rb, app/models/vaccination_record.rb, app/views/campaigns/sessions.html.erb, app/views/consent_forms/unmatched_responses.html.erb, app/views/consents/index.html.erb, app/views/sessions/_session_row.html.erb, app/views/sessions/edit.html.erb, app/views/sessions/index.html.erb, app/views/sessions/show.html.erb, app/views/triage/index.html.erb, app/views/vaccinations/batch.html.erb, app/views/vaccinations/edit/confirm.html.erb, app/views/vaccinations/index.html.erb, spec/helpers/sessions_helper_spec.rb
This is now a valid state for sessions that have been imported as some of the rows won't match with a known location. I've updated most cases where we show the session location to use a new helper that handles the value being `nil`.
I haven't updated all places as there are many parts of the service that require the location to be present, and for records created in the service this will always be true, it's only those that were imported where it's possible.
=> Handle session location being nil

app/jobs/dps_export_job.rb, config/environments/production.rb, spec/jobs/dps_export_job_spec.rb
This ensures that MESH receives periodic scheduled exports.
Also loop through active campaigns for DPSExportJob instead of just picking the first one.
=> Add DPSExportJob cron schedule 

app/views/application/_header.html.erb
This ensures that header items are highlighted when users are in one of the sections.
=> Add aria-current to header items

app/jobs/dps_export_job.rb, app/lib/mesh.rb, config/environments/production.rb, config/environments/staging.rb, lib/tasks/mesh.rake, spec/factories/dps_exports.rb, spec/jobs/dps_export_job_spec.rb, spec/lib/mesh_spec.rb
Adds error handling and a few other tidbits to the DPS export:
- only create DPS exports for campaigns that have unexported `vaccination_records`
- use `mesh_jobs` feature flag to control whether the job runs
- change `Content-Type` to `application/octet-stream` when sending files to MESH
- disable cron in production and enable in staging
- add logging to $stdout to `mesh:dps_export` rake task for dev purposes
- add `mesh:send_file` rake task for dev purposes
Sorry for packing them all into one, but they're all on a similar topic and a few of these are quite small. Can break these out into separate PRs if they're too much here.
Short example of using the cli to trigger the DPS export job:
```
$ rails mesh:dps_export
D, [2024-08-22T00:36:18.776567 #71193] DEBUG -- :   Flipper …
```
=> Update DPSExportJob with error handling

app/models/dps_export.rb, app/models/dps_export_row.rb, app/models/immunisation_import_row.rb, spec/models/dps_export_row_spec.rb, spec/models/immunisation_import_row_spec.rb
This stores the performing professional names on the vaccination record (if the information is available) and again exports it to DPS (if the information is available).
These values must be provided by Flu, and may be provided for HPV.
=> Import and export performing professional names

app/controllers/immunisation_imports_controller.rb, app/models/immunisation_import.rb, app/models/immunisation_import_row.rb, app/views/immunisation_imports/duplicates.html.erb, spec/features/immunisation_imports_upload_spec.rb, spec/models/immunisation_import_spec.rb
This updates the importer to skip duplicate records and show the number of records skipped to the user. If all the records are duplicates we show a page that explains there's nothing to do, otherwise we include a banner at the top of the page showing how many were duplicates.
=> Skip importing duplicate records

app/controllers/vaccination_records_controller.rb, app/views/immunisation_imports/index.html.erb
When we just unassociate the vaccination records with the dps exports, as we were doing before, this leaves behind the dps exports with no vaccination records associated with them. These just end up being noisy and unnecessary.
=> Remove dps exports on reset

app/components/app_consent_component.html.erb, app/components/app_consent_component.rb, app/components/app_outcome_banner_component.rb, app/components/app_patient_page_component.html.erb, app/components/app_patient_page_component.rb, app/components/app_simple_status_banner_component.rb, app/controllers/campaigns_controller.rb, app/controllers/consents_controller.rb, app/controllers/manage_consents_controller.rb, app/controllers/triage_controller.rb, app/mailers/vaccination_mailer.rb, app/models/consent.rb, app/models/consent_form.rb, app/models/gillick_assessment.rb, app/models/parent.rb, app/models/patient_session.rb, app/models/session.rb, app/models/vaccination_record.rb, app/policies/session_policy.rb, lib/tasks/performance.rake, spec/models/consent_spec.rb
A number of models use default scopes to automatically only show "active" or "recorded" instances. This can be useful, but as the codebase grows it can start to cause unexpected behaviour and the need to override the default scope becomes more common.
I've attempted to find all the places where the default scopes were being used and update them in this commit, but it's possible some of them may have been missed and will need to be updated in the future.
=> Remove default scopes

app/models/immunisation_import.rb, spec/models/immunisation_import_spec.rb
This refactors the validation added in 64a51954efaa4e462c94aa377c41498c7cb7fe05 to replace it with a `before_save` callback which raises an exception if the state is invalid which makes the intention clearer and hopefully easier to read and understand.
=> Refactor immunisation import processed validation

app/controllers/consents_controller.rb, app/controllers/immunisation_imports_controller.rb, app/controllers/sessions_controller.rb, app/controllers/triage_controller.rb, app/controllers/vaccination_records_controller.rb, app/controllers/vaccinations_controller.rb
A statement such as `layout "full", only: :index` reads like this uses the default layout for all actions, except the `index` action where instead we use `full`.
This doesn't work like this, instead the call to `layout` replaces the call to `layout` in the `ApplicationController` and instead we end up with `layout "full"` only been called for `index`, and no layout is specified for the the other actions, which then ends up being the `application` layout.
This improves upon f82d2771f4a85e095a251eb23ae2147a78ee2065 which first introduced the default two thirds layout.
See https://stackoverflow.com/a/1576165 for more details.
=> Avoid layout with only constraint

Gemfile, Gemfile.lock, spec/components/app_triage_notes_component_spec.rb, spec/features/hpv_vaccination_administered_spec.rb, spec/features/hpv_vaccination_default_batch_spec.rb, spec/features/manage_vaccines_batches_spec.rb, spec/features/pilot_journey_spec.rb, spec/features/self_consent_gillick_competent_spec.rb, spec/features/self_consent_not_gillick_competent_spec.rb, spec/features/session_management_spec.rb, spec/lib/mesh_spec.rb, spec/models/concerns/age_concern_spec.rb, spec/models/patient_spec.rb, spec/rails_helper.rb
This replaces all uses of Timecop with the built-in time helpers provided by Rails directly, to reduce the number of third party libraries.
=> Switch to ActiveSupport::Testing::TimeHelpers

app/components/app_vaccination_record_details_component.rb, app/components/app_vaccination_record_table_component.html.erb, app/components/app_vaccination_record_table_component.rb, app/controllers/vaccination_records/edit_controller.rb, app/views/vaccination_records/edit/date_and_time.html.erb, config/locales/en.yml, config/routes.rb, spec/components/app_vaccination_record_details_component_spec.rb, spec/components/app_vaccination_record_table_component_spec.rb, spec/features/edit_vaccination_record_spec.rb, spec/jobs/remove_immunisation_import_csv_job_spec.rb
This adds the ability to edit the date and time an existing vaccination record.
I've decided to add these actions to a new controller as it's likely we'll need to edit different parts of the vaccination records in the future. I've also set up the controller in a similar way to how we handle wizards as I imagine we'll likely need that functionality in the future.
The `govuk_form_builder` Gem doesn't currently support time fields (and there's no mention of how they should work in the design system) so I've had to re-create it myself in the form.
If the user is on this page we should expect the date/time to always be set, whereas we allow the field to be optional on the model. One way to solve this could be to use a form object, however for this page I've decided to add some validation logic …
=> Add ability to edit vaccination record date/time

app/models/immunisation_import_row.rb, spec/models/immunisation_import_row_spec.rb
We won't be importing records which haven't been vaccinated so we don't need the CSV file to include a `NOT_VACCINATED_REASON` column, and instead we can simply ignore it.
=> Don't require a not vaccinated reason

app/controllers/sessions/edit_controller.rb
There are 51k+ locations in the database after running the GIAS import. We can't display all of them at the same time, and instead should use something like an autocomplete that fetches locations from the server.
=> Temporarily limit locations when creating sessions

app/controllers/immunisation_imports/patients_controller.rb, app/controllers/immunisation_imports_controller.rb, app/controllers/sessions_controller.rb, app/views/immunisation_imports/edit.html.erb, app/views/immunisation_imports/patients/show.html.erb, config/routes.rb, spec/features/immunisation_imports_upload_duplicates_spec.rb
This implements the design that allows users to apply the `pending_changes` that are added to patient records when matching records that match on NHS Number are uploaded a second time.
TODO in follow-up PRs:
(Font is wrong because these are taken from tests)
=> Handle duplicate patient records during immunisation import

app/controllers/cohort_lists_controller.rb, app/models/cohort_list.rb, app/models/concerns/csv_importable.rb, app/models/immunisation_import.rb, config/locales/en.yml, spec/features/pilot_upload_cohort_spec.rb, spec/models/cohort_list_spec.rb
This refactors the `ImmunisationImport` and `CohortList` models to use a common `CSVImportable` concern which encapsulates the logic of both classes and ensure the behaviour is consistent across the two.
=> Refactor models related to CSV imports

app/jobs/pds_lookup_job.rb, app/lib/nhs/pds/patient.rb, app/models/pds/patient.rb, lib/tasks/pds.rake, spec/fixtures/patient_record.json, spec/jobs/pds_lookup_job_spec.rb, spec/lib/nhs/pds/patient_spec.rb, spec/lib/nhs/pds_spec.rb, spec/models/pds/patient_spec.rb
This adds the function to `NHS::PDS` and an example job to perform the lookup with rate limiting. This implementation is still only half-done, as we'll probably want a job called something like `UpdateNHSNumberJob`. However, that's a bit more work since it relies on `patients.nhs_number` being an optional field.
=> Add find_by to do patient search in PDS

app/components/app_patient_summary_component.rb, app/models/patient.rb, app/views/immunisation_imports/patients/show.html.erb, spec/components/app_patient_summary_component_spec.rb, spec/models/patient_spec.rb
Refactor the duplicate patient summary to use a component.
Add a `with_pending_changes` method to patients that assigns all the attributes, allowing us to check whether they're changed using [ActiveModel::Dirty](https://api.rubyonrails.org/classes/ActiveModel/Dirty.html) built-ins.
=> Display highlighted changes to patients 

app/controllers/parent_interface/consent_forms_controller.rb, app/models/session.rb, spec/factories/sessions.rb, spec/features/parental_consent_backfilled_session_spec.rb
If a session has been backfilled by the immunisations importer, it won't have timestamps for when consent requests were sent, when reminders were sent and when consent closed. 
For such sessions, trying to give consent should show that the session is closed and not crash.
=> Don't crash on parental consent form for backfilled sessions

sonar-project.properties
This is an automatically generated file so it doesn't make sense to run Sonar code checking on it as we wouldn't be able to fix any of the issues.
I've also added `spec` and `tests`, which is already configured in Sonar Cloud, but now replicated here too.
=> Ignore db/schema.rb code duplication

app/components/app_patient_table_component.rb, app/controllers/cohort_imports_controller.rb, app/controllers/immunisation_imports_controller.rb, app/models/cohort_import.rb, app/models/immunisation_import.rb, app/views/cohort_imports/duplicates.html.erb, app/views/cohort_imports/edit.html.erb, app/views/cohort_imports/errors.html.erb, app/views/cohort_imports/new.html.erb, app/views/cohort_imports/show.html.erb, app/views/cohort_imports/success.html.erb, app/views/immunisation_imports/_breadcrumbs.html.erb, app/views/programmes/patients.html.erb, config/routes.rb, spec/features/cohort_imports_upload_spec.rb, spec/features/e2e_journey_spec.rb, spec/features/immunisation_imports_upload_spec.rb
This updates the various pages related to cohort imports to match the designs we have for immunisation imports, specifically added a two-stage process where the user has to "Check and confirm" the records before they are recorded.
The implementation is based on the existing designs for immunisation import, but I expect these will need to change slightly when the designs for cohorts are finalised. I think once we know more about the similarities and differences between cohort and immunisation imports we could refactor these views in to shared components.
=> Add check and confirm page for cohort imports

config/application.rb, config/environments/production.rb
This updates the production environment configuration to ensure that an API key for GOV.UK Notify is set, and if not will raise an error early to ensure that we're aware of the problem.
=> Ensure GOV.UK API Key is set in production

Dockerfile
In 917d436723231751b9360c801460e104fe4f2223 we ensured that a GOV.UK Notify API key is set in production, but this broke the Docker builds as we need a value to be set when precompiling the assets.
=> Fix Docker build missing GOV.UK Notify API key

app/components/app_patient_details_component.rb, app/controllers/vaccination_records_controller.rb, spec/components/app_patient_details_component_spec.rb
This updates the patient details component to also include any parent details that might be available to show, either via the relationships or from the consent form.
=> Show parents for patients or consent forms

app/controllers/manage_consents_controller.rb
This ensures that if we're editing an existing parent we have the value that they already provided.
=> Pass phone_receive_updates when creating form

app/models/session.rb
This avoids the need to have an additional validation on the enum.
=> Use validate parameter on enum

app/models/programme.rb, spec/models/programme_spec.rb
This adds a method for determining the year groups that a programme is relevant to, for now this is hard coded based on the type but we might want to change this in the future.
=> Add Programme#year_groups

app/models/cohort_import.rb, app/models/cohort_import_row.rb, app/models/team.rb, spec/models/cohort_import_row_spec.rb, spec/models/cohort_import_spec.rb
This adds the functionality to ensure that patients are added to the correct cohort when they're imported. The cohort is determined based on the date of birth of the patient.
=> Add patients to cohorts when importing

app/models/patient.rb, spec/models/patient_spec.rb
This is a more accurate value for the patient's year group as the patient might move between cohorts in certain special cases.
=> Get patient year group from cohort

app/assets/stylesheets/_button.scss, app/views/immunisation_imports/index.html.erb, app/views/programmes/patients.html.erb, spec/features/cohort_imports_upload_spec.rb, spec/features/e2e_journey_spec.rb, spec/features/immunisation_imports_upload_duplicates_spec.rb, spec/features/immunisation_imports_upload_spec.rb
This is to match the designs in the prototype, using a newer button style that's currently being tested but not yet part of the NHS frontend.
See https://github.com/nhsuk/nhsapp-frontend/issues/12 for more details.
=> Use secondary style for upload buttons

app/controllers/cohorts_controller.rb, app/models/cohort.rb, app/views/cohorts/index.html.erb, spec/features/cohort_imports_upload_spec.rb, spec/features/immunisation_imports_upload_spec.rb
This ensures that when looking at the cohorts tab, we show all cohorts that could possibly exist for a particular programme, not just the ones that do exist.
=> Show empty cohorts

app/models/programme.rb
This relationship doesn't exist, there's no `programme_id` column on the triage model, and the line prevents us from being able to delete programmes.
I've also removed the dependent destroy on the other relationships because I think we should make it hard to delete programmes, without this it's possible to destroy a programme in one go without first destroying it's dependencies.
=> Remove triage on programmes

app/models/consent_form.rb, spec/features/parental_consent_authentication_spec.rb, spec/features/parental_consent_change_answers_spec.rb, spec/features/parental_consent_refused_spec.rb, spec/features/parental_consent_spec.rb, spec/models/consent_form_spec.rb
The parental consent form now supports texts, so we can enable this step of the journey for all users.
=> Remove parent_contact_method feature flag

app/components/app_patient_table_component.rb, app/components/app_session_details_component.rb, app/helpers/sessions_helper.rb, app/views/cohorts/index.html.erb, app/views/consents/index.html.erb, app/views/sessions/show.html.erb, app/views/triage/index.html.erb, app/views/vaccinations/index.html.erb, config/locales/en.yml, spec/features/cohort_imports_upload_spec.rb, spec/features/immunisation_imports_upload_spec.rb
This replaces everywhere that we show a number of children to use the phrase "No children" instead of "0 children" but introducing a localisation key and using the `count` feature of `I18n.t`.
=> Show "no children" rather than "0 children"

app/views/parent_interface/consent_forms/deadline_passed.html.erb
This removes any reference to the pilot since the service will be moving in to private beta.
=> Remove reference to pilot on consent deadline page

app/controllers/cohorts_controller.rb, app/models/cohort.rb, spec/factories/example_campaigns.rb, spec/factories/patient_sessions.rb, spec/models/cohort_spec.rb
This uses the `for_year_groups` scope, while also combining a check on the teams, ensuring that we don't expose cohorts for different teams that happen to match the same year groups when looking at a programme.
I've also improves the `example_campaign` trait to associate the cohorts with the team so they're visible.
=> Only show cohorts in the same team as the programme

app/components/app_programme_navigation_component.rb, spec/features/parental_consent_refused_spec.rb, spec/features/parental_consent_spec.rb, spec/features/response_matching_spec.rb, spec/features/self_consent_gillick_competent_spec.rb, spec/features/self_consent_not_gillick_competent_spec.rb, spec/features/user_authorisation_spec.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb
The prototype used to have a "Schools" tab separate to sessions which has been removed and this tab has been renamed back to "School sessions".
=> Rename schools tab

app/components/app_imports_table_component.html.erb, app/components/app_imports_table_component.rb, app/components/app_programme_navigation_component.rb, app/controllers/immunisation_imports_controller.rb, app/controllers/imports_controller.rb, app/controllers/vaccination_records_controller.rb, app/views/cohort_imports/show.html.erb, app/views/immunisation_imports/index.html.erb, app/views/immunisation_imports/new.html.erb, app/views/immunisation_imports/show.html.erb, app/views/imports/index.html.erb, app/views/vaccination_records/index.html.erb, config/locales/en.yml, config/routes.rb, spec/components/app_imports_table_component_spec.rb, spec/factories/cohort_imports.rb, spec/factories/immunisation_imports.rb, spec/features/immunisation_imports_upload_duplicates_spec.rb, spec/features/immunisation_imports_upload_spec.rb, spec/features/import_child_records_spec.rb
This updates the "Imports" tab shown on the programme page to include the cohort imports as well as the immunisation imports it does currently.
=> Show cohorts in imports tab

app/controllers/application_controller.rb, app/controllers/parent_interface/consent_forms/base_controller.rb, app/views/application/_header.html.erb
This ensures that if a nurse is signed in and they visit the consent journey, they don't see the secondary navigation that's part of the main Mavis app.
=> Don't show secondary navigation in consent journey

app/components/app_warning_callout_component.rb, app/views/cohort_imports/edit.html.erb, app/views/immunisation_imports/duplicates/show.html.erb, app/views/immunisation_imports/edit.html.erb, app/views/import_issues/show.html.erb, spec/components/app_warning_callout_component_spec.rb, spec/spec_helper.rb
This adds a component which we can use to render a warning callout in the NHS style, simplifying where we render these. I've updated the places where we render callouts to use this component, and updated RSpec to automatically set the `type` to `:component` for files in the `spec/components` directory.
=> Add AppWarningCalloutComponent

app/components/app_patient_summary_component.rb, app/controllers/vaccination_records_controller.rb, app/models/programme.rb, spec/components/app_patient_summary_component_spec.rb
This is useful to be able to highlight when the cohort has changed (likely due to the date of birth changing) after importing a patient record.
Depends on #1818.
=> Show cohort when displaying patient summary

app/controllers/users/omniauth_callbacks_controller.rb, config/initializers/devise.rb, config/settings.yml, config/settings/development.yml, spec/fixtures/cis2_auth_info.rb
As part of onboarding for CIS2 there are some additional measures we need to implement when performing authorisation with OIDC. The measures in this PR are:
- Check user has level 3 CIS2 identity
- Remove `professionalmemberships` scope from CIS2 auth
- Check `auth_time` in CIS2 callback
- Set the prompt when authenticating user with CIS2
- Check user has authenticated securely to CIS2
There are still some other measures that need to be implemented but they are a bit chunkier and will be spun out into separate PRs.
=> Additional OIDC security measures for CIS2

app/controllers/cohort_imports_controller.rb, app/jobs/process_cohort_import_job.rb, app/views/cohort_imports/edit.html.erb, spec/features/e2e_journey_spec.rb, spec/features/import_child_records_spec.rb, spec/jobs/process_cohort_import_job_spec.rb
This adds a new `ProcessCohortImportJob` that's called from the `CohortImportsController#create` action. The `edit` page is updated to display a holding message while processing is ongoing.
Review without whitespace changes.
TODO:
=> Process cohort imports using background job

app/models/consent_form.rb, app/models/session.rb, app/models/triage.rb, app/models/vaccination_record.rb, spec/components/app_activity_log_component_spec.rb, spec/components/app_session_patient_table_component_spec.rb, spec/components/app_triage_form_component_spec.rb, spec/components/app_triage_notes_component_spec.rb, spec/components/app_vaccination_record_summary_component_spec.rb, spec/components/app_vaccination_record_table_component_spec.rb, spec/components/previews/app_session_patient_table_component_preview.rb, spec/controllers/concerns/patient_sorting_concern_spec.rb, spec/controllers/concerns/vaccination_mailer_concern_spec.rb, spec/factories/patient_sessions.rb, spec/factories/sessions.rb, spec/factories/vaccination_records.rb, spec/mailers/consent_mailer_spec.rb, spec/mailers/vaccination_mailer_spec.rb, spec/models/consent_form_spec.rb, spec/models/patient_session_spec.rb, spec/models/triage_spec.rb, spec/policies/session_policy_spec.rb
For models which have a relation to programmes and sessions, we need to validate that the programme is one of the programmes in the session.
It's difficult to do this purely through the database structure because we have many to many relationships between programmes and sessions and sessions and patients; while the triage and vaccination record model needs a reference to all three in one record.
=> Add validation on programmes

app/components/app_session_table_component.html.erb, app/components/app_session_table_component.rb, app/helpers/address_helper.rb, app/views/programmes/sessions.html.erb, app/views/sessions/index.html.erb, spec/components/app_session_table_component_spec.rb, spec/helpers/address_helper_spec.rb
This adds a new component for rendering a table of sessions, which will be used when looking at the overview of school sessions and when looking at the sessions per programme.
=> Add session table component

app/components/app_session_table_component.html.erb, app/controllers/programmes_controller.rb, app/controllers/sessions_controller.rb, app/models/location.rb, app/models/session.rb, app/views/programmes/sessions.html.erb, app/views/sessions/completed.html.erb, app/views/sessions/scheduled.html.erb, app/views/sessions/unscheduled.html.erb, config/routes.rb, spec/factories/example_programmes.rb, spec/factories/locations.rb, spec/factories/sessions.rb, spec/features/session_management_spec.rb, spec/models/location_spec.rb, spec/models/session_spec.rb
This adds a table showing unscheduled sessions for the team and for an individual programme, based on the table in the designs.
When looking at a team level we see all the locations associated with the team that have no sessions, and when looking at it from a programme level we see only locations with appropriate year groups.
=> Add unscheduled sessions table

app/components/app_session_table_component.html.erb, app/controllers/sessions_controller.rb, app/models/session.rb, app/views/sessions/index.html.erb, config/routes.rb, spec/features/e2e_journey_spec.rb, spec/features/session_management_spec.rb, spec/models/session_spec.rb
This updates the journey for creating sessions by removing the "Add a new session" button and replacing it with the "Unscheduled" tab. When a user clicks on one of these schools, an unscheduled session is automatically created for it and the user is redirected to the session page.
=> Create sessions from schools

app/components/app_session_summary_component.rb, app/components/app_session_table_component.html.erb, app/helpers/sessions_helper.rb, app/views/sessions/show.html.erb, spec/components/app_session_summary_component_spec.rb, spec/helpers/sessions_helper_spec.rb
This adds the summary list sidebar to the session page as per the designs.
=> Add summary list to session page

app/assets/stylesheets/_action_list.scss, app/assets/stylesheets/application.scss, app/helpers/sessions_helper.rb, app/models/session.rb, app/views/sessions/show.html.erb, spec/helpers/sessions_helper_spec.rb, spec/models/session_spec.rb
This adds a new tag shown on the status page which displays the status of the session, either one of completed, in progress or unscheduled.
=> Add session status tag

app/components/app_session_table_component.html.erb, spec/components/app_session_table_component_spec.rb
This updates the session table component to ensure it can render session rows without a location, which is possible when importing vaccination records.
=> Handle sessions with locations in table

app/controllers/sessions_controller.rb, app/views/sessions/edit.html.erb, app/views/sessions/show.html.erb, spec/features/e2e_journey_spec.rb, spec/features/session_management_spec.rb
This adds a button which allows users to start scheduling dates for a session. The button is only shown if the session is unscheduled, if a user wants to add dates to an existing session they will need to use the "Edit session" button.
=> Add button to schedule sessions

config/initializers/devise.rb
This is a requirement of CIS2:
- NHS CIA Sec Req 003
This has been tested by creating a simple Ruby script that configures Faraday similarly (see below) and connecting against `openssl` configured to accept connections but only offering TLS v1.1 (see cmdline below). Running the script results in an error indicating that a version error has occured:
```
.../installs/ruby/3.3.4/lib/ruby/3.3.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=127.0.0.1:8443 state=error: tlsv1 alert protocol version (SSL alert number 70) (Faraday::SSLError)
```
OpenSSL command:
```
openssl s_server -accept 8443 -cert server.crt -key server.key -tls1_1 -www
```
Test ruby script:
```ruby
#!/usr/bin/env ruby
require 'faraday'
http = Faraday.new('https://localhost:8443') do …
```
=> Set minimum TLS version for CIS2 to 1.2

app/models/team.rb
This is not used anywhere anymore so it can be safely removed.
=> Remove Team#programme

config/initializers/devise.rb, config/initializers/session_store.rb
Sets session timeouts according to CIS2 requirements:
- 15 mins of inactivity: NHS CIA Ses Req 005
- session maximum age to 12 hours: NHS CIA Ses Req 007
=> Update session timeouts

app/controllers/concerns/consent_form_mailer_concern.rb, app/mailers/consent_mailer.rb, config/initializers/govuk_notify.rb, spec/controllers/concerns/consent_form_mailer_concern_spec.rb, spec/features/parental_consent_refused_spec.rb, spec/features/parental_consent_spec.rb, spec/mailers/consent_mailer_spec.rb
This content is related to the pilot so we want to remove this until we have a better idea of what survey we might send out for the private beta.
=> Remove feedback email

Gemfile, Gemfile.lock, app/assets/stylesheets/_autocomplete.scss, app/assets/stylesheets/application.scss, app/javascript/application.js, app/javascript/controllers/autocomplete_controller.js, app/javascript/controllers/index.js, app/views/layouts/application.html.erb, app/views/parent_interface/consent_forms/edit/school.html.erb, config/initializers/assets.rb, config/initializers/inflections.rb, package.json, yarn.lock
The custom CSS seems to not be as accessible as the upstream one when using VoiceOver. It doesn't allow choosing from a list of options by swiping left/right in the focus order.
Add an `autocomplete` stimulus controller that's based on the implementation in the prototype.
See commits.
=> Replace dfe-autocomplete with accessible-autocomplete

app/controllers/programmes_controller.rb, app/controllers/sessions/edit_controller.rb, app/controllers/sessions_controller.rb, app/models/cohort.rb, app/models/cohort_import.rb, app/models/patient.rb, app/models/session.rb, app/views/sessions/edit/confirm.html.erb, spec/factories/patients.rb, spec/features/manage_sessions_spec.rb, spec/jobs/consent_reminders_session_batch_job_spec.rb, spec/models/cohort_import_spec.rb
When importing cohorts this ensures that patients are added to any unscheduled or scheduled sessions for the current academic year and school. It also updates the consent request process to ensure that new consent forms are sent out to those new patients.
=> Add cohorts to sessions

app/models/consent_form.rb
The HPV programme has two discontinued vaccines (necessary to support importing old vaccination records), however for new consent forms we should make sure to get the health questions from the active vaccine to ensure users are seeing the right information.
=> Take health questions from active vaccines

app/controllers/dev_controller.rb, app/models/patient.rb, config/routes.rb, spec/features/dev_reset_team_spec.rb, spec/models/patient_spec.rb
This will make it easier to run repeatable black box tests of the app.
I'm not convinced this is the best way to implement it – open to suggestions on alternatives.
=> Add dev tools endpoint for resetting a team's data

app/jobs/session_reminders_job.rb, spec/jobs/session_reminders_job_spec.rb
If the patient was already vaccinated in the session we should not send out a reminder email for any subsequent dates.
=> Only send reminders to unvaccinated patients

app/models/immunisation_import.rb, spec/fixtures/immunisation_import/valid_hpv.csv, spec/models/immunisation_import_spec.rb
Currently this fails as we try and link a location to the immunisation import, but the location will be `nil`. I've updated the fixture to include an example of this case.
=> Ensure unknown school vaccination records can be imported

app/lib/govuk_notify_personalisation.rb, app/models/session.rb, app/models/session_date.rb, spec/lib/govuk_notify_personalisation_spec.rb, spec/mailers/consent_mailer_spec.rb, spec/mailers/session_mailer_spec.rb, spec/models/session_date_spec.rb, spec/models/session_spec.rb
This updates the GOV.UK Notify personalisation to include all the session dates. I've already updated all the templates in GOV.UK Notify to use these new personalisation variables.
=> Send multiple session dates to GOV.UK Notify

app/controllers/manage_consents_controller.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations/edit_controller.rb, app/models/concerns/patient_session_state_concern.rb, app/models/consent.rb
The state functionality was partially removed in
8200353266453e7728cbdc76cdb2e6a35c7bc05f but the transition methods weren't removed. They're not being used anywhere and don't do anything so we can safely remove them.
=> Remove unused state transition methods

app/controllers/sessions_controller.rb, app/models/session.rb, app/models/team.rb
This makes it impossible to create sessions with no programmes, which can lead to bugs down the line as we always expect a session to have at least one programme.
Unfortunately we can't add validation to the session model because of the many-to-many relationship and the way we construct sessions when importing with a find or create.
=> Ensure sessions aren't created with no programmes

app/components/app_import_errors_component.rb, app/views/cohort_imports/errors.html.erb, app/views/immunisation_imports/errors.html.erb, spec/components/app_import_errors_component_spec.rb
This adds a component which can be used to render the validation errors for cohort imports, class imports and immunisation imports in a standard and consistent way.
=> Add AppImportErrorsComponent

app/jobs/remove_import_csv_job.rb, spec/factories/class_imports.rb, spec/jobs/remove_import_csv_job_spec.rb
After 30 days, like we do for other imports, to avoid keeping personal information longer than we need to.
=> Remove ClassImport CSVs

app/controllers/consent_forms_controller.rb, app/models/patient.rb, spec/models/class_import_spec.rb, spec/models/patient_spec.rb
This updates the process for handling when a consent form indicates the patient belongs to a different school to apply the same logic as when importing class lists and cohorts, allowing existing patients to be added to any upcoming sessions automatically.
=> Handle patient moving schools

app/components/app_outcome_banner_component.rb, app/controllers/consents_controller.rb, app/controllers/sessions_controller.rb, app/controllers/triage_controller.rb, app/controllers/vaccinations_controller.rb, app/models/concerns/patient_session_state_concern.rb, app/models/patient_session.rb, spec/models/patient_session_spec.rb
The session page and its various subpages (check consent, vaccinate, triage) were taking several seconds to load for a session with 300-odd patients.
This PR picks off some low-hanging fruit to reduce the load times to sub-second (review commit-by-commit), mostly by temporarily enabling global strict load and seeing what breaks.
I've not touched the patient page, which will require a bunch more work.
This work also unearthed a (now erroneous) assumption baked into `PatientSessionStateConcern` that a `PatientSession` only has one record `VaccinationRecord`. That's now not always going to be true, because sessions span multiple dates:
* a patient can't be vaccinated in the session's first visit for whatever reason, and a non-vaccination outcome is recorded for them
* they come back in the …
=> Session page performance improvements

app/models/class_import.rb, spec/models/class_import_spec.rb
When importing a class list, any patients that didn't appear in the class list should be moved to an unknown school so they can be picked up in a clinic later.
=> Move unknown patients to unknown school

app/models/immunisation_import_row.rb, spec/features/dev_reset_team_spec.rb, spec/features/import_vaccination_records_spec.rb, spec/fixtures/immunisation_import/valid_hpv.csv, spec/models/immunisation_import_spec.rb
If the same patient appears multiple times in a single file we currently get an error because we try and create multiple patients for the same NHS number, and other personal details.
To fix this we can looking for duplicate patients each time we process a row, ensuring that if a patient was created in a previous row, we would now match with it and avoid creating a second patient.
=> Handle importing multiple doses in same file

app/models/patient_import_row.rb, spec/models/cohort_import_row_spec.rb
Currently we only accept "Mother" and "Father" as valid relationship types, but we might see values such as "Mum" and "Dad" (these are given as examples in the prototype) and since it's clear what these means we should import them correctly.
=> Handle importing "mum" and "dad" relationships

app/helpers/sessions_helper.rb, spec/helpers/sessions_helper_spec.rb
This is now showing as "Session scheduled" in the prototype.
=> Rename session in progress status

app/views/class_imports/new.html.erb, app/views/cohort_imports/new.html.erb, app/views/immunisation_imports/new.html.erb, spec/features/import_vaccination_records_spec.rb
This adds a section when importing vaccinations records which lists the columns necessary for a successful import, in a similar way to what we have currently for class lists and cohort imports.
=> Add vaccination record import columns help

app/models/concerns/patient_session_state_concern.rb, app/models/patient_session.rb, app/models/vaccination_record.rb, spec/models/patient_session_spec.rb
This updates the relationships defined on patient sessions to ensure that vaccination records are always recorded, introduces a new separate relationship to draft vaccination records, and fixes a bug with the latest vaccination record where it was actually returning the oldest record.
One question renames over the use of "Delay vaccinations", currently if a triage is marked as this then the parents will get an email saying their child won't be vaccinated in this session, which in this case means all the dates in the session. We're likely to need to change the logic around delayed vaccinations to talk about sending a child to a clinic.
=> Refactor vaccination record relationship on patient sessions 

app/controllers/sessions_controller.rb
This is a useful tool for development and has been broken since we added support for multiple session dates.
=> Fix make_in_progress

app/views/programmes/sessions.html.erb, config/locales/en.yml, spec/features/e2e_journey_spec.rb, spec/features/import_class_lists_spec.rb, spec/features/manage_sessions_spec.rb, spec/features/parental_consent_refused_spec.rb, spec/features/parental_consent_spec.rb, spec/features/response_matching_spec.rb, spec/features/self_consent_gillick_competent_spec.rb, spec/features/self_consent_not_gillick_competent_spec.rb, spec/features/triage_delay_vaccination_spec.rb, spec/features/user_authentication_spec.rb, spec/features/user_authorisation_spec.rb, spec/features/verbal_consent_given_when_previously_refused_spec.rb
This brings the app in line with the prototype.
=> Rename "School sessions" to "Sessions" in the secondary nav

config/application.rb, config/locales/en.yml
This adds locale strings for import classes to ensure that we render errors in a clear way, highlighting the CSV column names with `code` formatting, and with a colon between the name of the column and the message.
The `i18n_customize_full_message` option has been set to allow us to customise the error message formatting in the locale file.
=> Improve import error formatting

app/components/app_session_table_component.html.erb, app/controllers/programmes_controller.rb, app/controllers/sessions_controller.rb, app/lib/unscheduled_sessions_factory.rb, app/models/immunisation_import_row.rb, app/models/location.rb, app/models/session.rb, config/routes.rb, db/seeds.rb, lib/tasks/schools.rake, spec/features/e2e_journey_spec.rb, spec/features/import_class_lists_spec.rb, spec/features/manage_sessions_spec.rb, spec/lib/unscheduled_sessions_factory_spec.rb, spec/models/location_spec.rb, spec/models/session_spec.rb
This changes the mechanism for creating unscheduled sessions to prepopulate all the sessions each year or when a new location is added to a team. Currently these are created dynamically when the user first clicks on a location without a session, but this new approach allows us to include the unscheduled sessions in any statistics, specifically allows us to count the number of children that would be added to a session when the dates are selected.
=> Prepopulate unscheduled sessions

app/controllers/cohorts_controller.rb, app/controllers/programmes_controller.rb, app/controllers/sessions_controller.rb, app/models/session.rb
* sessions with dates are sorted by earliest date and location name
* sessions without dates are sorted by location name
* cohorts are sorted by patient first and last names
=> Add sorting to session and cohort views

README.md, docs/rake-tasks.md, lib/tasks/schools.rake
This improves the `schools:add_to_team` Rake task to allow adding multiple schools to a team in one go by passing in multiple URNs.
=> Allow adding multiple schools to a team in one go

app/assets/stylesheets/application.scss, config/initializers/govuk_components.rb
We need to use the GOV.UK pagination styles to ensure the component renders correctly, the NHS Design System has a different style of pagination, but the GOV.UK component matches our prototype designs.
=> Fix pagination styles

app/models/concerns/csv_importable.rb, app/models/immunisation_import.rb, app/models/immunisation_import_row.rb, app/models/patient_import.rb
Use .import to import records in bulk, while skipping Rails validations.
=> Speed up imports

copilot/webapp/manifest.yml
This ensures that all environments use the same configuration, for consistent performance and staging/prod parity.
=> Use same CPU and server count in staging/production

README.md, app/controllers/dev_controller.rb, app/models/concerns/ods_code_concern.rb, app/models/immunisation_import_row.rb, app/models/location.rb, app/models/team.rb, docs/rake-tasks.md, lib/tasks/clinics.rake, lib/tasks/schools.rake, spec/models/immunisation_import_row_spec.rb, spec/models/location_spec.rb, spec/models/team_spec.rb
These are known when running these tasks whereas getting the ID of the team requires us to look in the database first. I've also normalised the values to ensure they're always uppercase regardless of how the user provides them.
=> Pass team ODS code to Rake tasks 

copilot/webapp/manifest.yml
This setting allows us to use phone number that start with `077009` in these environments.
=> Allow dev phone numbers in staging envs

app/models/concerns/csv_importable.rb
The validation is quite expensive as it checks each row individually, if we've reached the end of the export we can be sure that the rows were already valid as this check is done earlier in the method.
=> Skip validation after finishing an import

app/views/sessions/show.html.erb
The prototype design has moved on but this prevents users getting a broken experience.
=> Remove "Register attendance" link to nowhere, readjust layout

app/models/concerns/csv_importable.rb, app/models/immunisation_import.rb, spec/models/immunisation_import_spec.rb
This uses `link_records_by_type` which uses an `.import` call to speed up the process.
=> Bulk import records link to immunisation imports

app/jobs/consent_form_matching_job.rb, app/models/immunisation_import_row.rb, app/models/patient.rb, app/models/patient_import_row.rb, spec/models/patient_spec.rb
At the moment when we find existing patients, if we haven't found one based on the NHS number we look at three other personally identifiable fields. However, this can lead to a false positive situation where we match on a patient that has a different NHS number but happens to match in other respects. If the NHS numbers don't match we can be sure that they're not the same patient.
https://good-machine.sentry.io/issues/5976469496/
=> Don't match patients if NHS numbers are different

app/models/class_import.rb, app/models/cohort_import.rb, app/models/concerns/csv_importable.rb, app/models/immunisation_import.rb, app/models/immunisation_import_row.rb, app/models/patient_import.rb, app/models/patient_import_row.rb, spec/models/immunisation_import_row_spec.rb
The import process is no longer split up in to two separate steps so we can combine the two and save a little bit of processing time. The whole import is done in a transaction anyway so no records will appear until the whole thing is complete.
=> Remove separate record_rows step

app/models/immunisation_import.rb, app/models/patient_import.rb
This fixes an issue where using `import` expects there to only be unique records to update, and can't handle the case where we ask it to update the same record multiple times. By using a `Set` we can avoid this problem, although now we'll only pick the most recent version of a record and ignore any others.
https://good-machine.sentry.io/issues/5977551439/
=> Use sets to avoid updating rows multiple times

app/models/concerns/csv_importable.rb, spec/features/dev_reset_team_spec.rb, spec/features/import_vaccination_records_spec.rb, spec/fixtures/immunisation_import/valid_hpv.csv, spec/models/immunisation_import_spec.rb
This file was causing an error before fb77b2da1c4aae4d1ad2383a363c1026a7513671 was applied, so adding this test case should help to catch any regressions.
=> Add test case with duplicate surnames

app/jobs/consent_reminders_job.rb, app/jobs/consent_requests_job.rb, app/jobs/process_import_job.rb, app/jobs/remove_import_csv_job.rb, app/jobs/session_reminders_job.rb
This prevents multiple imports from being processed in parallel which could lead to issues related to race conditions and the same records being added at the same time.
I've also added a `notifications` queue for reminders and requests so they can be managed separately.
=> Use an imports queue and set concurrency

Dockerfile
This ensures that even if the URL returns a 301 redirect, that curl will only follow it if it's over an SSL connection.
=> Enforce ssl in Dockerfile curl

app/models/vaccine.rb, spec/models/vaccine_spec.rb
Vaccines don't have types directly any more, these come from the programme the vaccine is attached to.
https://good-machine.sentry.io/issues/5983496059/
=> Fix reference to vaccine type

app/controllers/dev_controller.rb
This is currently failing on staging because the ClassImports records are orphaned when the sessions are destroyed.
=> Delete ClassImports in reset team endpoint

app/controllers/dev_controller.rb
This is currently failing on test because it leaves orphaned consent records when patients and parents are deleted.
=> Delete consents when resetting teams

app/views/sessions/edit.html.erb
=> Fix styling issue on session edit screen

Dockerfile, Gemfile, Gemfile.lock
Instead of locking Ruby in both .ruby-version and the Gemfile, you can read .ruby-version directly in the Gemfile.
Might have to run `bin/bundle update --bundler` for this to work.
=> Reference .ruby-version in Gemfile

Gemfile, Gemfile.lock, app/controllers/dev_controller.rb
These developer endpoints change a lot about the database in one go, and running them in parallel is not safe (for example, when we create unscheduled sessions). For a developer endpoint, a simple solution would be to introduce a lock on these actions so they can only happen one at a time.
https://good-machine.sentry.io/issues/5990891241
=> Prevent parallel resets
