nhsuk/manage-vaccinations-in-schools

docs/architecture.adoc
docs/diagrams/recording-vaccination-while-offline-sequence-diagram.puml
docs/diagrams/saving-campaign-for-offline-sequence-diagram.puml
docs/diagrams/service-worker.puml
docs/diagrams/working-online-sequence-diagram.puml
docs/offline-csrf-security.adoc
docs/offline-support.adoc

Add documentation of how we implement offline working, with relevant security information.

Add offline docs

---

docs/README.md
docs/offline-csrf-security.adoc
docs/offline-support.adoc

Requires #164 be merged first as it references files added there.

Add docs README

---

app/controllers/offline_passwords_controller.rb
app/controllers/pages_controller.rb
app/views/pages/start.html.erb
config/routes.rb
spec/requests/pages_spec.rb
tests/offline.spec.ts

This matches the one from the prototype.
For the start button I ended up adding a class to a regular `link_to` instead of creating a component.

Add start page

---

app/views/sessions/_session_row.html.erb
app/views/sessions/index.html.erb

Remove the card wrapper around the table and set some CSS.

Match design of sessions#index to the prototype

---

app/javascript/controllers/vaccination_controller.js
app/views/vaccinations/_patient_row.html.erb
app/views/vaccinations/index.html.erb
tests/offline.spec.ts

Also some other related fixes. See commits.

Align design of vaccinations index with prototype

---

app/components/app_status_tag_component.rb
app/controllers/triage_controller.rb
app/models/campaign.rb
app/models/patient.rb
app/models/triage.rb
app/views/sessions/show.html.erb
app/views/triage/_patient_row.html.erb
app/views/triage/index.html.erb
config/initializers/inflections.rb
config/routes.rb
db/migrate/20230607163717_create_triage.rb
db/sample_data/example-campaign.json
db/schema.rb
lib/example_campaign_data.rb
lib/tasks/load_campaign_example.rake
spec/factories/sessions.rb
spec/factories/triage.rb
spec/requests/triage_spec.rb
tests/triage.spec.ts

We rename `children` to `patients` everywhere but in the vaccinations controllers and the JavaScript that uses it, as the changes in those files will be more significant.

Add triage list

---

app/controllers/triage_controller.rb
app/views/triage/_patient_row.html.erb
app/views/triage/_patient_triage.html.erb
app/views/triage/show.html.erb
config/routes.rb
tests/triage.spec.ts

This is the basic show page for triage info. It doesn't include bits like consent, updating triage info, etc. Those will be delivered separately.

Triage show

---

Gemfile
Gemfile.lock
app/controllers/triage_controller.rb
app/helpers/triage_helper.rb
app/helpers/vaccinations_helper.rb
app/models/application_record.rb
app/models/consent_response.rb
app/models/patient.rb
app/views/triage/_patient_triage.html.erb
app/views/triage/_patient_triage_consent_response.html.erb
config/initializers/time_formats.rb
db/migrate/20230616103904_create_consent_responses.rb
db/sample_data/example-campaign.json
db/schema.rb
lib/example_campaign_data.rb
lib/tasks/add_consent_to_example_json.rake
lib/tasks/load_campaign_example.rake
spec/models/application_record_spec.rb
spec/requests/triage_spec.rb
tests/triage.spec.ts

Show consent on triage page

---

.github/workflows/test.yml
app/controllers/dev_controller.rb
app/models/patient.rb
bin/offline
bin/online
config/routes.rb
db/sample_data/example-test-campaign.json
lib/example_campaign_data.rb
lib/tasks/load_campaign_example.rake
playwright.config.ts
tests/offline.spec.ts

This changes the e2e tests to use the test Rails env, isolating the tests from any dev data we have. It also loads up a smaller example campaign specific to testing in order to try to make it easier to work with.

Tests in test env

---

app/components/app_patient_card_component.html.erb
app/components/app_patient_card_component.rb
app/controllers/triage_controller.rb
app/helpers/vaccinations_helper.rb
app/views/triage/_patient_triage.html.erb
app/views/vaccinations/_patient.html.erb
spec/components/app_patient_card_component_spec.rb
tests/vaccinations.spec.ts

Update vaccinations show page

---

bin/offline
bin/online
playwright.config.ts

This will allow us to run playwright tests while a dev server is running. However, I'm not 100% sure about the online/offline scripts ... I've added parameterisation to try to help, but without those tests running reliably I'm not 100% sure what needs doing.
@tvararu are you happy to roll forward with this for now?

Use a custom pidfile for the playwright test rails

---

app/helpers/application_helper.rb
app/helpers/campaigns_helper.rb
app/helpers/pages_helper.rb

Remove unused helpers

---

app/assets/stylesheets/application.sass.scss
app/controllers/vaccinations_controller.rb
app/views/vaccinations/confirm.html.erb
app/views/vaccinations/history.html.erb
app/views/vaccinations/index.html.erb
app/views/vaccinations/show.html.erb
config/application.rb
config/routes.rb
tests/vaccinations.spec.ts

This is a small PR that only adds the confirmation card and also implements the `two_thirds` layout. Logic to use this page is coming in a follow-up.
See commits.

Confirm vaccination page

---

app/components/app_health_questions_component.html.erb
app/components/app_health_questions_component.rb
app/models/consent_response.rb
app/views/triage/_patient_triage.html.erb
db/migrate/20230628144627_add_health_questions_to_consent_response.rb
db/sample_data/example-campaign.json
db/sample_data/example-test-campaign.json
db/schema.rb
lib/example_campaign_data.rb
lib/tasks/load_campaign_example.rake
spec/components/app_health_questions_component_spec.rb
spec/factories/consent_responses.rb
spec/factories/vaccines.rb
tests/example_data.ts
tests/triage.spec.ts

Add health questions card

---

app/controllers/vaccinations_controller.rb
app/views/vaccinations/_patient.html.erb
spec/models/consent_response_spec.rb
tests/vaccinations.spec.ts

These changes have been extracted from the health questions work on the triage show page.

Health questions on vaccination page

---

app/controllers/triage_controller.rb
app/views/triage/index.html.erb

Display an empty state when there is nothing to triage.

---

config/initializers/time_formats.rb

Fix typo in time format

---

app/assets/stylesheets/_banner.scss
app/assets/stylesheets/application.sass.scss
app/components/app_banner_component.html.erb
app/components/app_banner_component.rb
app/controllers/vaccinations_controller.rb
app/views/vaccinations/_patient.html.erb
app/views/vaccinations/confirm.html.erb

Banner on record child page

---

app/components/app_banner_component.html.erb
app/components/app_banner_component.rb
app/views/vaccinations/_patient.html.erb

Record vaccs: yellow banner on child page when no consent

---

app/views/triage/_patient_row.html.erb

These were missing from the index page

Add reasons for triage for follow-up

---

app/controllers/triage_controller.rb
app/helpers/triage_helper.rb
app/models/triage.rb
app/views/triage/_patient_row.html.erb
app/views/triage/_patients.html.erb
app/views/triage/_patients_with_dob.html.erb
app/views/triage/_patients_with_triage_reasons.html.erb
app/views/triage/index.html.erb
tests/triage.spec.ts

Tabs for triage

---

app/views/errors/internal_server_error.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unprocessable_entity.html.erb
app/views/layouts/two_thirds.html.erb
app/views/sessions/_session_row.html.erb
app/views/sessions/index.html.erb
app/views/triage/_patient_row.html.erb
app/views/triage/_patients_with_dob.html.erb
app/views/triage/_patients_with_triage_reasons.html.erb
app/views/vaccinations/_patient.html.erb
app/views/vaccinations/_patient_row.html.erb
app/views/vaccinations/_patients_with_actions.html.erb
app/views/vaccinations/_patients_with_outcomes.html.erb

This brings the interface closer in line to the prototype.

Replace CSS govuk classes with nhsuk ones

---

app/controllers/consent_responses_controller.rb
app/models/health_question.rb
app/views/consent_responses/edit_confirm.html.erb
app/views/consent_responses/edit_questions.html.erb
config/routes.rb
playwright.config.ts
tests/consent.spec.ts

Consent: Health questions page

---

db/sample_data/model-office.json
lib/tasks/generate_model_office_data.rake

This change adjusts the model office data to be more appropriate for the next model office:
* update the session date
* update the session school
* fix the generation script so that reasons for refusals are loaded correctly

Update model office data: part 1

---

app/controllers/consent_responses_controller.rb
app/models/consent_response.rb
app/views/consent_responses/edit_agree.html.erb
app/views/consent_responses/edit_who.html.erb
config/locales/en.yml
config/routes.rb
tests/consent.spec.ts

This completes the basic consent response journey.
Depends on https://github.com/nhsuk/record-childrens-vaccinations/pull/361.

Allow users to edit who consented

---

app/views/vaccinations/_patient.html.erb
app/views/vaccinations/confirm.html.erb

This is static information and is misleading at this time.

Remove dose 1 of 2

---

app/views/vaccinations/show.html.erb

We suspect teams move to single dose from the autumn.

Remove reference to HPV 1st dose

---

app/models/triage.rb
app/views/consent_responses/edit_questions.html.erb
app/views/triage/_patient_triage_card.html.erb
app/views/triage/show.html.erb
app/views/vaccinations/show.html.erb

Model office tweaks

---

lib/tasks/generate_model_office_data.rake

We don't need to merge this before the model office.

Haemophilia model office scenario: add to generate script

---

app/controllers/consent_responses_controller.rb
app/controllers/triage_controller.rb
app/controllers/vaccinations_controller.rb
app/views/consent_responses/edit_confirm.html.erb
app/views/consent_responses/edit_who.html.erb
app/views/vaccinations/_form.html.erb
app/views/vaccinations/new.html.erb
app/views/vaccinations/show.html.erb
config/routes.rb
tests/consent_during_vaccination.spec.ts
tests/gillick.spec.ts
yarn.lock

Go to vaccination flow after consenting + triaging from vaccinations page

---

app/avo/resources/consent_resource.rb
app/components/app_consent_card_component.html.erb
app/controllers/consents_controller.rb
app/models/concerns/patient_session_state_machine_concern.rb
app/models/consent.rb
app/views/consents/edit_confirm.html.erb
app/views/consents/edit_consent.html.erb
app/views/triage/show.html.erb
app/views/vaccinations/show.html.erb
db/migrate/20230811114758_rename_consent_consent_to_response.rb
db/sample_data/example-campaign.json
db/sample_data/example-test-campaign.json
db/sample_data/model-office.json
db/schema.rb
lib/example_campaign_data.rb
lib/tasks/generate_model_office_data.rake
spec/factories/consents.rb
spec/models/concerns/patient_session_state_machine_concern_spec.rb
spec/models/consent_spec.rb

Was a straightforward find a replace, but some stragglers left me scratching my head for a while.

Replace consent#consent with consent#response

---

app/controllers/consents_controller.rb
app/views/consents/assessing_gillick.html.erb

Small fixes

---

Procfile
app.json
bin/release

This will be used on review apps and production to decide if we should load the schema, or just migrate.

Add bin/release script

---

app/assets/stylesheets/application.sass.scss
app/controllers/consent_forms/date_of_birth_controller.rb
app/controllers/consent_forms/school_controller.rb
app/models/consent_form.rb
app/views/consent_forms/confirm.html.erb
app/views/consent_forms/school/cannot_consent.html.erb
app/views/consent_forms/school/edit.html.erb
config/locales/en.yml
config/routes.rb
lib/tasks/load_campaign_example.rake
tests/parental_consent.spec.ts

Add school page to parental consent journey

---

app/views/consent_forms/school/edit.html.erb

For the pilot, we don't allow users to pick a different school.

Update wording for "No" school option

---

app/views/consent_forms/edit/parent.html.erb

Make "How to contact me" details open by default

---

app/components/app_consent_card_component.html.erb
app/components/app_patient_card_component.html.erb
app/views/consent_forms/confirm.html.erb
app/views/consent_forms/edit/contact_method.html.erb
app/views/consent_forms/edit/parent.html.erb
app/views/consents/edit_confirm.html.erb
app/views/consents/edit_who.html.erb
tests/parental_consent.spec.ts

This follows the content guidelines.

Replace Telephone with Phone throughout app

---

app/models/consent.rb
spec/components/app_patient_medical_history_card_component_spec.rb
spec/models/consent_spec.rb
tests/triage.spec.ts

Follow the new design from the prototype https://github.com/nhsuk/record-childrens-vaccinations-prototype/pull/133

Change "Notes need triage" to "Health questions need triage"

---

app/views/consent_forms/edit/school.html.erb

Follow the content in the prototype.

Update content for "Not their school" radio

---

app/views/errors/not_found.html.erb

As requested by content design.

Update copy on "not found" error page

---

app/views/consent_forms/confirm.html.erb
config/locales/en.yml

Consent form confirmation page tweaks

---

app/assets/stylesheets/application.sass.scss

Stolen from https://github.com/nhsuk/consent-for-vaccinations-prototype/commit/54e7b9c8d8792283a0c83561ef62aec3575e0529

Improve presentation of health question answers

---

Gemfile
Gemfile.lock
app/models/consent_form.rb
app/validators/postcode_validator.rb
spec/models/consent_form_spec.rb

Add the `uk_postcode` gem and use it in the consent form.

Validate postcodes

---

config/locales/en.yml

Use the shared inbox that we've set up for Notify.

Update contact email

---

app/validators/postcode_validator.rb
config/locales/en.yml

Based on feedback from standup.

Tweak postcode and address validation messages

---

config/initializers/devise.rb
spec/factories/users.rb

Follow the guidelines we proposed.

Bump timeout to 2.hours and minimum password length

---

app/assets/stylesheets/application.sass.scss
app/components/app_consent_component.html.erb
app/components/app_consent_status_component.html.erb
app/components/app_consent_status_component.rb
spec/components/app_consent_component_spec.rb
spec/components/app_consent_status_component_spec.rb

Display consent status on consenst card

---

app/views/dashboard/index.html.erb
app/views/sessions/show.html.erb
app/views/triage/index.html.erb
app/views/vaccinations/index.html.erb
tests/full_journey.spec.ts
tests/nurse_consent_no_response.spec.ts
tests/triage.spec.ts

Updates content strings on the dashboard and session pages that are not aligned with the current prototype.

Content updates

---

app/components/app_backlink_component.html.erb

Correct spacing for back link

---

app/components/app_patient_details_component.html.erb
spec/components/app_patient_details_component_spec.rb
tests/full_journey.spec.ts

Remove parent info from child details

---

app/components/app_triage_form_component.html.erb
config/locales/en.yml
spec/components/app_patient_page_component_spec.rb
tests/full_journey.spec.ts
tests/nurse_consent_during_vaccination.spec.ts
tests/nurse_consent_gillick.spec.ts
tests/nurse_consent_no_response.spec.ts
tests/triage.spec.ts

Update triage card design. Does not include "delay vaccination" status yet, that will be part of another commit.
| Before | Prototype | After |
|---|---|-|
| ![image](https://github.com/nhsuk/manage-childrens-vaccinations/assets/15608/41cdf9c3-8d0f-416f-94dc-e455282bfcd2) | ![image](https://github.com/nhsuk/manage-childrens-vaccinations/assets/15608/a4afecb7-fac7-4807-a298-b1d8d5d6dd2d) | ![image](https://github.com/nhsuk/manage-childrens-vaccinations/assets/15608/5f75c2bb-fbaf-4202-886d-0a3162f4f169) |

Update triage card design

---

app/views/dashboard/index.html.erb
app/views/sessions/_session_row.html.erb
app/views/sessions/index.html.erb

Updates to dashboard, session and patient table views. Incudes links to sections that have not been built yet, but we want to include for the model office so that users can see how the current services works within the intended broader context.

Design snags (Part 1)

---

app/components/app_consent_component.html.erb
app/components/app_consent_component.rb
spec/components/app_consent_component_spec.rb

Display parent name and role in contact link

---

app/components/app_patient_details_component.html.erb
app/components/app_patient_details_component.rb
spec/components/app_patient_details_component_spec.rb

Format NHS number

---

app/assets/stylesheets/_summary-list.scss
app/components/app_health_questions_component.rb
tests/vaccination.spec.ts

Use a dl/dt/dd setup like the prototype.

Update health questions styling and HTML

---

README.md
db/sample_data/example-flu-campaign.json
db/sample_data/example-hpv-campaign.json
db/sample_data/model-office.json
lib/example_campaign_generator.rb
lib/tasks/generate_example_campaign.rake
tests/shared/index.ts
tests/vaccination.spec.ts
tests/vaccination_authorisation.spec.ts

Depends on https://github.com/nhsuk/manage-childrens-vaccinations/pull/684
- Add patients with conflicting consent to generator
- Add some cases of double consent but triage needed

Iterate model office data

---

app/helpers/vaccinations_helper.rb
app/views/vaccinations/confirm.html.erb
config/locales/en.yml

Update vaccination confirmation page

---

app/assets/stylesheets/_dev-tools.scss
app/assets/stylesheets/application.scss
app/components/app_dev_tools_component.rb
app/views/layouts/application.html.erb
app/views/sessions/show.html.erb

Update design for dev tools

---

app/components/app_consent_card_component.html.erb
app/components/app_consent_card_component.rb
app/views/nurse_consents/edit_confirm.html.erb
spec/components/app_consent_card_component_spec.rb

Simplifies the edit_confirm page significantly. This is extracted from the bigger refactor.

Extract AppConsentCardComponent from consent confirm

---

app/controllers/manage_consents_controller.rb
app/models/consent.rb
app/views/manage_consents/agree.html.erb
config/locales/en.yml

Add :agree step to ManageConsent journey

---

app/controllers/manage_consents_controller.rb
app/models/consent.rb
app/views/manage_consents/agree.html.erb
app/views/manage_consents/confirm.html.erb
app/views/manage_consents/reason.html.erb
config/locales/en.yml

Penultimate step before the Health Questions page which is more complex and should be PRed on its own.

Add :reason step to ManageConsent journey

---

Gemfile
Gemfile.lock
app/components/app_tab_component.html.erb
app/components/app_tab_component.rb
app/views/consents/index.html.erb
app/views/triage/index.html.erb
app/views/vaccinations/index.html.erb
spec/components/app_tab_component_spec.rb
spec/govuk_helper.rb
spec/govuk_shared/a_component_that_accepts_custom_classes.rb
spec/govuk_shared/a_component_that_accepts_custom_html_attributes.rb
spec/govuk_shared/a_component_that_supports_custom_branding.rb
spec/govuk_shared/a_component_with_a_slot_that_accepts_custom_classes.rb
spec/govuk_shared/a_component_with_a_slot_that_accepts_custom_html_attributes.rb
spec/govuk_shared/setup.rb
tests/triage_authorisation.spec.ts

Replaces `GovukComponent::TabComponent` with our version where we can customise the id.

Add AppTabComponent

---

app/controllers/schools_controller.rb
app/controllers/sessions_controller.rb
app/models/consent_form.rb
app/models/location.rb
app/views/schools/show.html.erb
app/views/sessions/show.html.erb
config/routes.rb
spec/models/consent_form_spec.rb
tests/schools_match_response.spec.ts
tests/session_authorisation.spec.ts
tests/shared/index.ts

Add school page with link from session page

---

app/assets/stylesheets/_table.scss
app/controllers/schools_controller.rb
app/models/consent_form.rb
app/views/schools/show.html.erb
config/locales/en.yml
db/sample_data/example-flu-campaign.json
db/sample_data/example-hpv-campaign.json
lib/example_campaign_generator.rb
lib/tasks/generate_example_campaign.rake
spec/factories/consent_forms.rb
spec/lib/example_campaign_generator_spec.rb
spec/models/consent_form_spec.rb
tests/shared/index.ts

I've added the tabs even though this it he only tab that's visible. Happy to remove if it's better, I just figured we won't be too far off from adding the other tabs.
Links will come in a following PR.

List unmatched consent responses

---

app/models/concerns/age_concern.rb
app/models/consent_form.rb
app/models/patient.rb
spec/models/concerns/age_concern_spec.rb

This will allow us to re-use AppPatientDetailsComponent more readily.
Split-out from work to add consent form show page.

Create AgeConcern, add to Patient and ConsentForm

---

app/controllers/consent_forms_controller.rb
app/models/concerns/age_concern.rb
app/models/consent_form.rb
app/models/patient.rb
app/views/consent_forms/show.html.erb
app/views/schools/show.html.erb
config/routes.rb
spec/models/concerns/age_concern_spec.rb
tests/schools_match_response.spec.ts
tests/shared/index.ts

Just the basic shell of a show page.

Add consent_form show page

---

app/components/app_consent_details_component.rb
app/components/app_consent_response_component.rb
app/models/consent_form.rb
app/views/consent_forms/show.html.erb
spec/components/app_consent_details_component_spec.rb
spec/components/app_consent_response_component_spec.rb
tests/schools_match_response.spec.ts
tests/shared/index.ts

Add consent details to consent response page.

---

app/controllers/parent_interface/consent_forms/edit_controller.rb
tests/parental_consent.spec.ts

This was missed in the ParentInterface refactor.

Fix cannot consent path and add test for it

---

lib/tasks/add_new_user.rake

Fix add_new_user guard

---

Dockerfile
app/components/app_patient_table_component.rb
app/components/app_status_banner_component.rb
app/controllers/application_controller.rb
app/controllers/patient_sessions_controller.rb
app/javascript/serviceworker/messages.spec.js
app/validators/phone_number_validator.rb
app/views/sessions/index.html.erb
app/views/vaccinations/_patients_with_actions.html.erb
app/views/vaccinations/_patients_with_outcomes.html.erb
lib/example_campaign_generator.rb
spec/components/app_card_component_spec.rb
spec/components/app_details_component_spec.rb

Fix Sonarcloud issues

---

bin/release

Update IS_REVIEW env var reference

---

app/models/consent.rb
app/models/consent_form.rb
app/models/health_answer.rb
app/models/offline_password.rb
app/models/patient_session.rb
app/models/triage.rb
app/models/vaccination_record.rb
config/locales/en.yml
db/migrate/20231214105751_create_flipper_tables.rb

Use 300/1000 which are less likely to confuse beings made of meat.

Tweak upper bound length validations

---

db/migrate/20240108112551_rename_consent_child_common_name.rb

Fix overzealous project-wide replace

---

.tool-versions
README.md

This was missed in https://github.com/nhsuk/manage-childrens-vaccinations/pull/805.

Remove terraform setup

---

Dockerfile
app.json
bin/release
config/initializers/config.rb
copilot/webapp/manifest.yml
docs/aws-copilot.md

We have a better name for the app now.

Rename app prefix from RCVAPP to MAVIS 

---

app/controllers/pilot_controller.rb
app/models/cohort_list.rb
config/locales/en.yml
tests/fixtures/malformed.csv
tests/pilot_cohort.spec.ts

Add validation for missing CSV and invalid CSV

---

app/avo/resources/registration.rb
app/controllers/avo/registrations_controller.rb

Punted along from previous PRs.

Add avo resources for registration

---

app/controllers/pilot_controller.rb
app/models/cohort_list.rb
app/models/registration.rb
app/views/pilot/registrations.html.erb
config/routes.rb
spec/models/cohort_list_spec.rb
tests/pilot_download_cohort.spec.ts

Adds the button to the pilot registrations page.

Allow users to download pilot cohort

---

app/views/layouts/application.html.erb

Fix service name aria-label

---

app/controllers/sessions_controller.rb

| - | - |
| <img width="1000" alt="Screenshot 2024-01-23 at 11 35 37" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/dc900660-4628-4f6d-8e0c-efdaa62d2d92"> | <img width="990" alt="Screenshot 2024-01-23 at 11 39 00" src="https://github.com/nhsuk/manage-childrens-vaccinations/assets/813383/a8333d75-38bc-46de-aa55-7d126bae54ee"> |

Fix layout on session home page

---

app/assets/stylesheets/_button.scss

Add app-specific button styles

---

app/components/app_tab_component.rb
app/controllers/edit_sessions_controller.rb
app/controllers/sessions_controller.rb
app/models/session.rb
app/models/team.rb
app/views/edit_sessions/confirm.html.erb
config/routes.rb

First 2 commits are not related.
Add a new wicked-based controller to handle the wizard journey when adding a new session.

Extract update/confirm methods from SessionsController

---

lib/tasks/add_new_user_securely.rake

Decided to make a new rake task as making the parameter list dynamic will add complication.

Add add new user securely

---

lib/tasks/add_new_location.rake

No URN yet as that's not in the DB, we can add that later.
I've also ommited URL since I'm not sure it's used anywhere. Do we need to add that?
I added optional readline support for convenience and in case we need to enter in fields with commas, which are doable but annoying.

Add rake task to create new locations

---

app/controllers/edit_sessions_controller.rb
app/controllers/sessions_controller.rb
app/models/session.rb
app/policies/location_policy.rb
app/views/edit_sessions/location.html.erb
config/locales/en.yml
spec/models/session_spec.rb
tests/session_create.spec.ts
tests/shared/index.ts

This validates that `location_id` has been submitted, and that it is within the list of locations that are associated with the user's team.

Add location page to new session form

---

app/views/registrations/closed.html.erb
config/locales/en.yml

Nixing the messaging around UR recruitment

---

app/assets/stylesheets/_table.scss
app/controllers/edit_sessions_controller.rb
app/models/patient.rb
app/models/session.rb
app/policies/patient_policy.rb
app/views/edit_sessions/cohort.html.erb
app/views/edit_sessions/confirm.html.erb
app/views/edit_sessions/location.html.erb
app/views/edit_sessions/timeline.html.erb
app/views/edit_sessions/vaccine.html.erb
app/views/edit_sessions/when.html.erb
config/locales/en.yml
db/sample_data/example-flu-campaign.json
db/sample_data/example-hpv-campaign.json
lib/example_campaign_data.rb
lib/example_campaign_generator.rb
lib/load_example_campaign.rb
spec/lib/example_campaign_generator_spec.rb
spec/models/patient_spec.rb
tests/session_create.spec.ts

There are a few (known) issues that should be addressed in follow-up PRs:
- The spacing doesn't quite match the prototype, in particular the space between the checkbox and the patient name is considerably bigger.
- There's no checkbox at the top to select/deselect all patients.
- The validations may need a little bit of tweaking, not sure if there should be a red line next to all the checkboxes for example, or whether the linking should work.
Also, the session create tests are getting pretty big. I'd propose we move the validations to a separate test file.

Session cohort

---

lib/tasks/add_new_location.rake

```
$ rails add_new_location
name> Pool Hayes Primary School
address> Bridgnorth Grove
town> Willenhall
county>
postcode> WV12 4RX
team_id> 1
Location Pool Hayes Primary School (id: 3) added to team SAIS team 672109.
New registration url:
http://localhost:4000/schools/3/registration/new
```

Display registration URL for new location in rake

---

app/views/sessions/_session_row.html.erb
app/views/sessions/show.html.erb
lib/load_example_campaign.rb

Fix display of session dates

---

app/views/content/accessibility_statement.md
app/views/content/privacy_policy.md
app/views/offline_passwords/new.html.erb
app/views/parent_interface/consent_forms/confirm.html.erb
app/views/registrations/new.html.erb
config/locales/devise.en.yml
config/locales/en.yml
config/locales/patient_session_statuses.en.yml
tests/full_journey.spec.ts
tests/nurse_consent_conflicting_consent.spec.ts
tests/nurse_consent_during_vaccination.spec.ts
tests/nurse_consent_gillick.spec.ts
tests/nurse_consent_no_response.spec.ts
tests/parental_consent_change_answers.spec.ts
tests/pilot_registration.spec.ts
tests/triage.spec.ts

Use smart quotes

---

app/controllers/edit_sessions_controller.rb
app/javascript/controllers/check_all_controller.js
app/javascript/controllers/index.js
app/views/edit_sessions/cohort.html.erb

Allow users to select/deselect all patients in the cohort in one go.
The checkbox is hidden by default using CSS and shown if JS is enabled, as it's a progressive enhancement.

Add all select/deselect checkbox for session cohort table

---

lib/task_helpers.rb
lib/tasks/add_new_hpv_team.rake
lib/tasks/add_new_location.rake
lib/tasks/add_new_user.rake
lib/tasks/add_new_user_securely.rake

Add prompting to all pilot ops scripts

---

app/models/cohort_list_row.rb

This field is optional in the expression of interest registration, it should be optional here too.

Make phone optional when uploading cohort

---

copilot/environments/production/manifest.yml
copilot/environments/staging/manifest.yml
copilot/environments/test/manifest.yml
copilot/environments/training/manifest.yml
copilot/webapp/manifest.yml

Make `manifest.yml`s consistent and add blue-green deployment to training and staging. Also update the domain for the `test` env.

Clean up copilot ymls

---

app/controllers/dev_controller.rb
bin/generate_example_campaigns
db/sample_data/example-flu-campaign.json
db/sample_data/example-hpv-campaign.json
db/sample_data/example-pilot-campaign.json
lib/example_campaign_data.rb
lib/example_campaign_generator.rb
lib/load_example_campaign.rb
spec/lib/example_campaign_generator_spec.rb
tests/pilot_journey.spec.ts
tests/shared/index.ts

To facilitate this test a new, empty campaign has been created which only has a location and some registrations linked to it. This also means a new nurse login, Nurse Flo <nurse.flo@example.com>.
Steps taken:
- [As parent]: Register interest
- [As nurse]: Close the registration
- Download registrants, edit out a couple
- Upload cohort list
- Create a new session selecting uploaded children
- Check that the details entered above show up on consent page

Add an end-to-end test for the pilot

---

lib/tasks/add_new_hpv_team.rake

If any of these creates fail, the whole script should roll back.

Add transaction wrapper around add_new_hpv_team

---

lib/tasks/add_new_location.rake
lib/tasks/add_new_user_securely.rake

Make the logging a little bit clearer.

Update script logging

---

.github/workflows/deploy.yml

Staging is now more prod-like so we don't want continuous deployment.
Also rename ci.yml to deploy.yml.

Deploy to test instead of staging

---

Gemfile

We need an easy way to seed the Training environment with multiple registrations.

Allow using factory bot in prod-like environments

---

config/locales/en.yml

Tell the users passwords are min 10 chars not 8

---

app/views/parent_interface/consent_forms/confirm.html.erb

Remove flu reference from  HPV consent form confirmation page

---

app/models/user.rb
lib/tasks/performance.rake

This can help to give us visibility into the overall health of the pilot.
Example local output:
```
Copy and paste the following into Slack:
**:rocket: Pilot performance stats – Monday, 19 February 2024**
*:health_worker: SAIS team 952083*
*Active users: 1/1* users signed in in the last week
*Stanford Primary School:*
- :pencil: Expressions of interest: *5* total, *5* in the last week
*:health_worker: SAIS team 699159*
*Active users: 0/1* users signed in in the last week
*St Patrick's Catholic Primary School:*
- :pencil: Expressions of interest: *5* total, *5* in the last week
*:health_worker: SAIS team 724388*
*Active users: 0/1* users signed in in the last week
*Holy Rosary Catholic Primary Academy:*
- :pencil: Expressions of interest: *5* total, *5* in the last week
```

Add bin/rails performance script

---

lib/tasks/performance.rake

Based on feedback from the team and design.
Example output:
```
:chart_with_upwards_trend: *PILOT PERFORMANCE* _Monday, 19 February 2024_
*:hospital: SAIS team 952083*
:busts_in_silhouette: Active users: 1/1 users signed in in the last week
:pencil: Expressions of interest
- *Stanford Primary School:* 5
*:hospital: SAIS team 699159*
:busts_in_silhouette: Active users: 0/1 users signed in in the last week
:pencil: Expressions of interest
- *St Patrick's Catholic Primary School:* 5
*:hospital: SAIS team 724388*
:busts_in_silhouette: Active users: 0/1 users signed in in the last week
:pencil: Expressions of interest
- *Holy Rosary Catholic Primary Academy:* 5
```

Update performance script output

---

.github/workflows/deploy.yml

Also found a way to update the run name displayed for the job:

Update deploy workflow with test env and adding name of env to job name

---

app/views/parent_interface/consent_forms/confirm.html.erb
config/locales/en.yml

Parent consent confirmation: show what they are agreeing to

---

config/initializers/devise.rb

Our users are butting heads against the short timeout.

Bump reset password timeout

---

README.md
bin/deploy

Ensures that we're always on the `main` branch and that there are no unstaged changes when deploying.

Add bin/deploy script

---

app/views/consents/index.html.erb
app/views/sessions/show.html.erb
app/views/triage/index.html.erb
app/views/vaccinations/index.html.erb

This aligns the app with the prototype designs.

Add session name to session title

---

config/locales/en.yml
lib/tasks/performance.rake

Use emoji numbers for extra emphasis.

Display total EOI count in performance stats

---

config/locales/en.yml

Update error messages after content review

---

app/controllers/edit_sessions_controller.rb
config/locales/en.yml

Quick and dirty, testing will have to be sorted out later

Send consent requests on session create

---

app/models/consent.rb
bin/show-testing-fixtures
db/sample_data/example-flu-campaign.json
db/sample_data/example-hpv-campaign.json
db/sample_data/example-pilot-campaign.json
spec/factories/consents.rb
spec/lib/example_campaign_generator_spec.rb
tests/shared/index.ts

This can be used to convert consent forms to consents.

Add Consent.from_consent_form 

---

app/views/consent_forms/unmatched_responses.html.erb

Unmatched responses page: remove sort from Action column

---

app/views/consents/index.html.erb

Hide the "unmatched consent responses" count if it's zero

---

app/models/consent.rb
db/sample_data/example-flu-campaign.json
db/sample_data/example-hpv-campaign.json
spec/factories/consent_forms.rb
spec/models/consent_spec.rb

Adds tests and fixes a few things wrong that are exposed by the tests.

Add tests for Consent#from_consent_form

---

app/controllers/application_controller.rb
app/controllers/consent_forms_controller.rb
app/controllers/manage_consents_controller.rb
app/controllers/triage_controller.rb
app/controllers/vaccinations_controller.rb

Also, extract a helper to consolidate the flash message setting in a few places.

Success flash after manual matching

---

app/assets/stylesheets/application.scss
app/components/app_compare_consent_form_and_patient_component.html.erb
app/components/app_compare_consent_form_and_patient_component.rb
app/models/consent_form.rb
app/models/patient.rb
app/views/consent_forms/review_match.html.erb
tests/schools_match_response.spec.ts

Useful content to help manual matching

---

app/models/patient.rb
config/application.rb

Depends on: https://github.com/nhsuk/manage-childrens-vaccinations/pull/1057
This fully enables the new encryption scheme and removes support for the old one.

Set deterministic: true on patient fields

---

app/controllers/concerns/consent_form_mailer_concern.rb
app/mailers/consent_form_mailer.rb
spec/controllers/concerns/consent_form_mailer_concern_spec.rb
spec/features/parent_gives_consent_spec.rb
spec/mailers/consent_form_mailer_spec.rb

This will be sent to parents 1 hour after they submit a consent form.

Add give_feedback consent form mailer template

---

app/mailers/application_mailer.rb
spec/mailers/application_mailer_spec.rb

This can be used as personalisation in emails.

Add team name to Notify emails

---

app/controllers/concerns/consent_form_mailer_concern.rb

Temporarily disable parental consent emails

---

app/controllers/concerns/consent_form_mailer_concern.rb
app/controllers/parent_interface/consent_forms_controller.rb

This also fails down the line and is possibly blocking users from finishing.

Disable ConsentFormMatchingJob scheduler

---

.github/workflows/deploy.yml
bin/docker-entrypoint
config/environments/production.rb
copilot/goodjob/manifest.yml

This changes from :async to :external and spins up a new service in our Copilot infrastructure.

Run good_job as an external service

---

app/views/parent_interface/consent_forms/_confirmation_injection.html.erb
app/views/parent_interface/consent_forms/confirm.html.erb
app/views/parent_interface/consent_forms/edit/injection.html.erb
app/views/parent_interface/consent_forms/edit/parent.html.erb

Follow-on to #1095. Paired with @emjhf.

Remove references to 'nurse' in the parent journey

---

app/components/app_status_banner_component.rb
spec/components/app_status_banner_component_spec.rb

The "not vaccinated" contents don't actually have a vaccinator.

Replace "Vaccinator" with "Decided by"

---

lib/tasks/performance.rake

* make sure to include only active sessions
* add a bit of spacing between sessions to improve readability

Fixes to performance task

---

README.md
app/views/layouts/component_preview.html.erb
config/application.rb
spec/components/previews/app_flash_message_component_preview.rb

This will allow to develop or debug some of the more complex view components in the app, without needing to massage the data manually. This becomes increasingly more important as the possible data constellations in the app become more complex.

Enable component previews

---

Gemfile
Gemfile.lock

I deleted my branch at some point which appears to be causing some grief. These changes have been merged into x-govuk's main so that should be good to go until they release.

Point govuk-components to main branch on x-govuk

---

app/assets/stylesheets/_button.scss
app/components/app_patient_table_component.rb
app/views/vaccines/index.html.erb

Updated to use small secondary button variant.

Default batch toggle

---

config/routes.rb
playwright.config.ts

Also show it in every environment.

Protect flipper UI with basic auth

---

app/mailers/consent_form_mailer.rb
app/mailers/vaccination_mailer.rb
config/initializers/email_templates.rb
config/locales/en.yml
spec/mailers/vaccination_mailer_spec.rb

Add mailer for when HPV vaccination didn't happen

---

app/assets/stylesheets/_summary-list.scss

Existing rule achieves the same.

Remove duplicate style rule

---

app/views/layouts/application.html.erb

Very smol, very marginal gains, but updated based on the recommendation from [capo.js](https://rviscomi.github.io/capo.js/)

Update order of elements in head

---

app/javascript/controllers/index.js
app/javascript/controllers/nhsuk_button_controller.js

Doesn't look like this is present in the GOVUK Button JS.

Remove .init from button JS

---

app/views/vaccinations/edit_reason.html.erb
spec/factories/campaigns.rb
spec/factories/health_questions.rb
spec/factories/vaccines.rb
spec/models/health_question_spec.rb

Make the different health questions for the pilot traits on the health question factory.
Then, use these traited health questions in the vaccine factories.

Improve health question and vaccine factories

---

app/models/consent_form.rb
app/models/vaccination_record.rb
lib/tasks/performance.rake

Adds some counts and a bit of extra styling to try to make things clearer.
- Added additional total counts
- Moved icons to the end of lines that start with numbers, for legilibity
- Added indentation to illustrate composition
- Added children in cohort count to each session
Sample output (from my local system, some numbers don't quite add up):
And the generated text:
```
:chart_with_upwards_trend: *PILOT PERFORMANCE* _Friday, 8 March 2024_
:one::five: *Expressions of interest (total)*
:four::seven: *Patients in cohort (total)*
:eight: *Consents returned (total)*
:one: *Vaccination records (total)*
:wavy_dash::wavy_dash::wavy_dash::wavy_dash::wavy_dash::wavy_dash::wavy_dash::wavy_dash::wavy_dash::wavy_dash:
*:hospital: SAIS team 770747*
:busts_in_silhouette: Active users: 1/1 users signed …
```

Update performance dashboard

---

app/controllers/reports_controller.rb
app/models/nivs_report.rb
app/models/nivs_report_row.rb
app/models/vaccination_record.rb
app/policies/vaccination_record_policy.rb
app/views/dashboard/index.html.erb
app/views/layouts/application.html.erb
app/views/reports/index.html.erb
config/initializers/date_time_formats.rb
config/routes.rb
spec/factories/patients.rb
spec/factories/vaccination_records.rb
spec/features/nivs_hpv_report_spec.rb
spec/models/nivs_report_row_spec.rb

From this vaccination:
The following row is produced:
(the missing cells in the report are to do with our fake dataset, rather than the functionality of the report)

NIVS export

---

Gemfile.lock

https://github.com/nhsuk/manage-childrens-vaccinations/security/dependabot/28

Bump Yard to address Dependabot alert

---

app/components/app_consent_card_component.html.erb
app/components/app_consent_card_component.rb
app/views/manage_consents/confirm.html.erb
spec/components/app_consent_card_component_spec.rb

Copy changes after discussion with designers. The patient page will be aligned in a follow-up PR.
Before             |  After
:-------------------------:|:-------------------------:

Verbal consent attempt, no response: update designs

---

docs/aws-copilot.md

Fix the cheat sheet deletion instructions.

Update copilot docs

---

app/assets/stylesheets/_overrides.scss
app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
app/views/pages/start.html.erb

These are some quick fixes that aren't worth carding up.
See commits.

Align application to look more like new prototype

---

app/controllers/users/passwords_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users/unlocks_controller.rb
app/views/layouts/one_half.html.erb

This aligns it closer to the prototype and is better than writing custom CSS code.

Use one_half layout on sign in pages

---

app/components/app_card_component.rb
app/controllers/dashboard_controller.rb
app/views/dashboard/index.html.erb
spec/components/app_card_component_spec.rb
spec/features/batch_management_spec.rb
spec/features/pilot_journey_spec.rb
tests/pilot_download_cohort.spec.ts
tests/pilot_registration_close.spec.ts
tests/pilot_upload_cohort.spec.ts

Use new card layout.
The "Today's sessions" and "Your account" links will be implemented separately.

Align dashboard to prototype 

---

app/views/sessions/show.html.erb

This was forgotten in the previous Today's sessions/campaigns refactor.

Update session show breadcrumbs

---

app/helpers/sessions_helper.rb
app/models/session_stats.rb
app/views/sessions/show.html.erb
spec/features/session_management_spec.rb
spec/models/session_stats_spec.rb

Match it up to the new design in the prototype.

Update session show page

---

app/assets/stylesheets/_header.scss
app/views/application/_header.html.erb
app/views/dashboard/index.html.erb
app/views/layouts/application.html.erb

Remove some of the custom styling.
Also a few other tweaks, see commits.

Align header to prototype 

---

app/assets/stylesheets/_patients.scss
app/assets/stylesheets/application.scss
app/components/app_patient_table_component.html.erb
app/components/app_patient_table_component.rb
app/views/consent_forms/show.html.erb
app/views/consents/index.html.erb
app/views/triage/index.html.erb
app/views/vaccinations/index.html.erb
spec/components/app_patient_table_component_spec.rb
spec/features/parental_consent_refused_spec.rb
spec/features/parental_consent_spec.rb
spec/features/pilot_journey_spec.rb
tests/nurse_consent_no_response.spec.ts
tests/nurse_consent_refused_validations.spec.ts
tests/nurse_consent_validations.spec.ts

This updates the table styling based on the one in the prototype and removes the filters. The filters will be added back in separately and make use of more progressive enhancement.

Implement new patients table design

---

app/components/app_health_questions_component.rb
app/models/consolidated_health_answers.rb
spec/models/consolidated_health_answers_spec.rb

This introduces a ConsolidatedHealthAnswers class with a slightly different implementation and more thorough unit testing.

Extract and refactor logic from AppHealthQuestionsComponent

---

app/assets/stylesheets/_globals.scss
app/components/app_consent_component.html.erb
app/components/app_consent_component.rb
app/components/app_health_questions_component.rb
app/components/app_patient_page_component.html.erb
app/components/app_patient_page_component.rb
spec/components/app_consent_component_spec.rb
spec/components/app_health_questions_component_spec.rb
spec/components/previews/app_health_questions_component_preview.rb

Scenario|Before             |  After
:-------------:|:-------------:|:----------------:
Single consent|<img alt="image" src="https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/7a14a4dc-7a73-45bd-a96e-6b80893bd3e2">|![image](https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/9c9b2479-35cd-4d21-b83d-4d80d183bc34)
Multiple consents|<img src="https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/5ae95d50-2ca6-4ac2-b1af-6955e387ea5d">|![image](https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/d9086b70-b789-42ed-98c6-5ac18e0773ba)
Confirmation when contacting refuser|<img width="734" alt="image" src="https://github.com/nhsuk/manage-vaccinations-in-schools/assets/23801/406512a0-20c4-41c2-b5ba-a78b0886e07a">|<img width="731" …

Patient page: update health question responses to new design

---

app/controllers/application_controller.rb
app/views/sessions/_session_row.html.erb
app/views/sessions/edit.html.erb
config/initializers/flipper.rb

Remove pilot_phase_1 feature flag

---

app/models/cohort_list_row.rb
app/models/patient.rb
db/sample_data/example-flu-campaign.json
db/sample_data/example-hpv-campaign.json
db/sample_data/example-pilot-campaign.json
spec/lib/example_campaign_generator_spec.rb
spec/models/cohort_list_spec.rb

* `Patient#parent_relationship` didn't have an enum defined
* `Father` wasn't mapped consistently with other relationship types and didn't match test data
* Improve the cohort import spec coverage
(Found during an unrelated bug-ception while trying to re-style the patient page)

Cohort upload: import parent relationship correctly

---

app/assets/stylesheets/_patients.scss
app/components/app_patient_table_component.html.erb
app/components/app_patient_table_component.rb
app/controllers/concerns/patient_sorting_concern.rb
app/controllers/consents_controller.rb
app/controllers/triage_controller.rb
app/controllers/vaccinations_controller.rb
app/helpers/application_helper.rb
app/views/consents/index.html.erb
app/views/triage/index.html.erb
app/views/vaccinations/index.html.erb
spec/components/app_patient_table_component_spec.rb
spec/controllers/concerns/patient_sorting_concern_spec.rb
spec/features/patient_sorting_filtering_spec.rb
spec/helpers/application_helper_spec.rb

This implements the `<action-table>` sorting logic server-side in Ruby, and combines with Turbo to offer a similar user experience.
TODO:

Use turbo for table sorting

---

app/controllers/dev_controller.rb
spec/factories/example_campaigns.rb
spec/factories/patient_sessions.rb

Haven't been too careful about the number of patients in what states for either of these example sessions, happy to tweak now or later as appropriate.

Add sessions in the past and the future to example campaign

---

app/models/session.rb
config/locales/en.yml
config/settings.yml
config/settings/development.yml
config/settings/test.yml

The pilot is finished and these only get in the way.

Remove pilot session date restrictions

---

app/models/cohort_list.rb
app/models/team.rb
app/views/cohort_lists/new.html.erb
spec/models/cohort_list_spec.rb

These were only in place for the pilot.

Remove team cohort limits as they're unnecessary

---

spec/factories/patients.rb
spec/support/faker/national_health_service.rb

This returns an NHS number in the range of 999 000 0000 to 999 999 9999
This is an interim solution, I think we should contribute this upstream.

Monkey patch in test_number to Faker::NationalHealthService

---

app/components/app_consent_component.html.erb
app/models/consent.rb
spec/features/add_and_default_batches_spec.rb
spec/features/batch_management_spec.rb
spec/features/self_consent_spec.rb

This PR also does some feature spec clean-up (best review commit by commit).

Bugfix to the patient page for self-consent

---

.github/workflows/deploy.yml
app.json
app/assets/stylesheets/_header.scss
app/controllers/dev_controller.rb
config/database.yml
db/seeds.rb

The interpolation doesn't work.

Fix copilot deploy job title

---

app/components/app_patient_page_component.html.erb
app/controllers/patients_controller.rb
app/views/layouts/three_quarters.html.erb
app/views/patients/show.html.erb

This is split out from https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1355 as it's not exactly related to the work there.
See commits.

Reformat patient view HTML

---

app/components/app_secondary_navigation_component.rb
app/controllers/patients_controller.rb
app/views/patients/log.html.erb
app/views/patients/show.html.erb
config/initializers/date_time_formats.rb
config/routes.rb
spec/features/pilot_journey_spec.rb

This displays created consents, and sets up the initial routes plus a basic test.
Future PRs can add the other types of events, refactor this into a component, and much more.

Build initial activity log page

---

app/controllers/pages_controller.rb
app/views/pages/start.html.erb

Update the bullets and use `two_thirds` in the controller.

Align start page to prototype

---

app/views/gillick_assessments/confirm.html.erb

Gillick assessment: add 'change' links to the confirmation page

---

app/assets/stylesheets/_card.scss
app/assets/stylesheets/_notification-banner.scss
app/components/app_activity_log_component.html.erb
app/components/app_activity_log_component.rb
app/components/app_card_component.rb
app/components/app_flash_message_component.html.erb
app/components/app_flash_message_component.rb
app/controllers/application_controller.rb
app/controllers/consent_forms_controller.rb
app/controllers/dev_controller.rb
app/controllers/manage_consents_controller.rb
app/controllers/triage_controller.rb
app/controllers/vaccinations_controller.rb
config/locales/en.yml
spec/components/app_activity_log_component_spec.rb
spec/components/previews/app_activity_log_component_preview.rb
spec/factories/example_campaigns.rb
spec/factories/triage.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/hpv_vaccination_not_administered_spec.rb
spec/features/pilot_journey_spec.rb
spec/features/self_consent_gillick_competent_spec.rb
spec/features/triage_delay_vaccination_spec.rb
spec/features/verbal_consent_given_do_not_vaccinate_spec.rb
spec/features/verbal_consent_given_keep_in_triage_spec.rb
spec/features/verbal_consent_given_ready_to_vaccinate_spec.rb
spec/features/verbal_consent_given_spec.rb
spec/features/verbal_consent_given_when_previously_refused_spec.rb
spec/features/verbal_consent_refused_spec.rb

Match the prototype content.
Also some unrelated commits to fix `/reset`.
Later edit: See commits, I've kept adding to this PR.

Align triage journey to prototype

---

.github/workflows/lint.yml
.github/workflows/test.yml

We added it to `bin/lint` but didn't add it to GitHub actions.
Also some other misc CI speed and config improvements.

Add rufo linter to CI

---

app/models/parent.rb
spec/models/parent_spec.rb

Some minor alignments of the `Parent` model, ahead of introducing it into the parental consent flow.

Parent model improvements

---

app/controllers/vaccinations/delivery_site_controller.rb
app/controllers/vaccinations_controller.rb
app/views/vaccinations/batch.html.erb
app/views/vaccinations/batches/edit.html.erb

Tweak default batch functionality

---

app/views/consents/show.html.erb
spec/features/parental_consent_spec.rb

This matches the updated prototype designs.

Add home address to consent show page

---

.github/workflows/lint.yml
.github/workflows/test.yml

This ensures that PRs from forks can be merged after they pass the checks.

Run linters and tests on pull_requests

---

app/views/application/_header.html.erb
app/views/campaigns/index.html.erb
app/views/campaigns/show.html.erb
app/views/consents/index.html.erb
app/views/dashboard/index.html.erb
app/views/sessions/edit.html.erb
app/views/sessions/index.html.erb
app/views/sessions/show.html.erb
app/views/triage/index.html.erb
app/views/vaccinations/index.html.erb
app/views/vaccines/index.html.erb
config/locales/en.yml
spec/features/parental_consent_refused_spec.rb
spec/features/parental_consent_spec.rb
spec/features/self_consent_gillick_competent_spec.rb
spec/features/self_consent_not_gillick_competent_spec.rb
spec/features/user_authorisation_spec.rb
spec/features/verbal_consent_given_when_previously_refused_spec.rb

This updates the cards on the dashboard page to match the design in the prototype. It also refactors the page titles of a number of sections to use locale strings.
I've also sorted the locale string file to reduce churn and the size of diffs in the future, but if we're not confident on this change I can remove it from this PR as it does make the number of lines changed very big!

Update dashboard page to match designs

---

config/settings/production.yml
copilot/environments/addons/db.yml
copilot/environments/production/manifest.yml
copilot/webapp/manifest.yml
db/seeds.rb
docs/aws-copilot.md

Tweak the documentation and update the SSL certificate.
See commits.

Provision production environment

---

app/assets/stylesheets/_button-group.scss
app/assets/stylesheets/_button.scss
app/assets/stylesheets/application.scss
app/components/app_patient_table_component.html.erb
app/components/app_patient_table_component.rb

Adds the `.nhsuk-table-responsive` class and the `__heading` span inside each individual cell.
Also adds `.app-button-group` styles that will be used in a future piece of work that adds the attendance buttons.

Implement patient table collapsing on mobile

---

app/assets/stylesheets/_card.scss
config/locales/patient_session_statuses.en.yml
spec/components/app_simple_status_banner_component_spec.rb
spec/features/parental_consent_spec.rb

Update the title, the colour, and the content of the explanation.
Add periods to all the other explanations to make them consistent.

Align "Safe to vaccinate" card

---

app/helpers/application_helper.rb

This is what we're using in the designs.

Use en dash in titles

---

app/controllers/immunisation_imports_controller.rb
app/views/immunisation_imports/new.html.erb
app/views/immunisation_imports/success.html.erb
app/views/reports/index.html.erb
config/locales/en.yml
config/routes.rb
spec/features/immunisation_imports_upload_spec.rb

This adds a controller and some views to support a basic immunisation import upload flow, where the user can upload a CSV file and it will be stored in the `ImmunisationImport` model.
The next steps after this will be to process the CSV file, provide feedback to the user on success/failures and add error validation against invalid files.
This is a dev-lead design based on the pilot cohort upload as we don't have proper designs for this yet, but we can make the necessary changes when those designs come through.

Add initial immunisation import flow

---

app/models/cohort_list.rb
app/models/immunisation_import.rb
spec/models/immunisation_import_spec.rb

Add some missing ones that we are already relying on.

Tweak ImmunisationImport headers

---

README.md

Make the script a one-liner and use `whoami`.

Slightly improve Postgres setup docs

---

Procfile.dev
README.md
bin/dev
package.json
yarn.lock

This reverts commit dbd0c18.
Also document using [`overmind`](https://github.com/DarthSim/overmind#connecting-to-a-process) instead of `foreman` for better handling of TTY echo-issues when running `binding.pry`.

Revert "Replace foreman with concurrently"

---

app/controllers/immunisation_imports_controller.rb
spec/features/immunisation_imports_upload_spec.rb

This connects the upload UI with the immunisation import process allowing users to upload a CSV file and have vaccination records created in the database, with suitable feedback.

Process imports from uploads

---

app/models/immunisation_import.rb
spec/models/immunisation_import_row_spec.rb

Patient date of birth and vaccination dates should be in the past.

Check that imported dates are not in the future

---

app/assets/stylesheets/_header.scss
app/views/application/_header.html.erb
app/views/dashboard/index.html.erb
spec/features/user_cis2_authentication_from_start_page_spec.rb
spec/features/user_cis2_authentication_with_redirect_spec.rb

Brings the application in line with the prototype.

Align header change role/sign out button

---

spec/factories/campaigns.rb
spec/factories/example_campaigns.rb

This has a non-trivial impact on speed. On my machine the specs went from around 50 seconds to 40, so 20% increase.

Don't create as many batches in tests

---

app/models/immunisation_import_row.rb
config/locales/en.yml
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

This ensures that we're importing and creating records for the vaccine batch for each vaccination record. See individual commits for more details.

Import vaccine batches

---

app/components/app_session_details_component.html.erb
app/components/app_session_details_component.rb
app/views/campaigns/sessions.html.erb
spec/components/app_session_details_component_spec.rb

Fewer crashes on sparse sessions

---

app/components/app_vaccination_record_details_component.rb
app/models/vaccine.rb
app/views/vaccination_records/show.html.erb
spec/components/app_vaccination_record_details_component_spec.rb
spec/models/vaccine_spec.rb

Vaccinations page: disambiguate dose (dose volume), show dose number for non-seasonal 

---

app/views/vaccinations/edit/confirm.html.erb
spec/features/hpv_vaccination_administered_spec.rb

Show delivery method on vaccination recording confirmation page

---

app/components/app_dev_tools_component.rb
app/views/immunisation_imports/index.html.erb
app/views/sessions/show.html.erb
config/routes.rb
db/seeds.rb
spec/components/app_dev_tools_component_spec.rb

* Replace the `make_session_in_progress_button` feature flag with `dev_tools`
* Put DPS export reset functionality behind it

Introduce `dev_tools` feature flag

---

app/components/app_patient_details_component.rb
app/components/app_vaccination_record_table_component.html.erb
app/helpers/patients_helper.rb
spec/components/app_patient_details_component_spec.rb
spec/helpers/patients_helper_spec.rb

Vacc records: display "Not provided" when the NHS number is missing.

---

app/models/dps_export_row.rb
app/models/immunisation_import.rb
spec/models/dps_export_row_spec.rb

Imms import: remove fields that are no longer required to be sent downstream

---

Gemfile.lock

I've rebased my fork. This lets us update to Rails 7.2.

Update audited to 5.7.0 fork

---

app/models/immunisation_import.rb
app/models/immunisation_import_row.rb
config/locales/en.yml
spec/features/immunisation_imports_upload_spec.rb
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

This makes a number of small changes to the error messages produced by the importer to make them clearer to the user, see individual commits for more details.

Various improvements to import error messages

---

app/assets/stylesheets/application.scss

Align app signed in page width to prototype

---

app/views/campaigns/index.html.erb

To active programmes, for consistency across the service.

Rename active campaigns

---

app/assets/stylesheets/_action-list.scss
app/assets/stylesheets/application.scss
app/views/immunisation_imports/index.html.erb
app/views/immunisation_imports/new.html.erb
spec/features/immunisation_imports_upload_spec.rb

Adds the missing app-action-list styles and wraps the button in a paragraph.

Align "Upload new vaccination records" design

---

.github/workflows/deploy.yml
README.md

This updates the GitHub Actions workflow to add deployments to the main three environments, and updates the README to make reference to them.

Clarify deployed environments

---

config/settings/staging.yml

Update this mailbox to one we have access to so we can see what gets sent to it for testing purposes.

Update dps mesh mailbox in staging

---

app/controllers/vaccination_records_controller.rb

Broken with an earlier change, this is for dev only and will either be enhanced or removed altogether at a later time.

Update dev functions for DPS exports

---

app/controllers/application_controller.rb
app/controllers/batches_controller.rb
app/controllers/campaigns/new_controller.rb
app/controllers/campaigns_controller.rb
app/controllers/cohort_lists_controller.rb
app/controllers/consent_forms_controller.rb
app/controllers/consents_controller.rb
app/controllers/content_controller.rb
app/controllers/dashboard_controller.rb
app/controllers/edit_sessions_controller.rb
app/controllers/errors_controller.rb
app/controllers/gillick_assessments_controller.rb
app/controllers/immunisation_imports_controller.rb
app/controllers/manage_consents_controller.rb
app/controllers/pages_controller.rb
app/controllers/parent_interface/consent_forms/edit_controller.rb
app/controllers/parent_interface/consent_forms_controller.rb
app/controllers/pilot_controller.rb
app/controllers/sessions_controller.rb
app/controllers/triage_controller.rb
app/controllers/users/accounts_controller.rb
app/controllers/vaccinations/edit_controller.rb
app/controllers/vaccinations_controller.rb
app/controllers/vaccines_controller.rb
app/views/layouts/full.html.erb
app/views/layouts/three_quarters.html.erb

This refactors the layout views to ensure they're consistent and to switch the default layout to `two_thirds` as it's the most commonly used layout.

Refactor layout views

---

app/views/immunisation_imports/errors.html.erb
spec/features/immunisation_imports_upload_spec.rb

This content has been suggested by our content designer to clarify how the row indexing works.

Update import error content

---

app/models/immunisation_import.rb
spec/models/immunisation_import_spec.rb

This fixes a number of issues that were broken in https://github.com/nhsuk/manage-vaccinations-in-schools/commit/ae6f10d38ada480af17e7ec44113e546e6c10229 by ensuring the errors remain attached to the right form field.

Minor fixes to immunisation import error reporting

---

config/locales/en.yml
spec/models/immunisation_import_row_spec.rb

This improves the error messages shown to the user if there's a problem while they are importing the records.

Add immunisation import error messages

---

sonar-project.properties

Reverts nhsuk/manage-vaccinations-in-schools#1718
This didn't seem to work so we're adding the setting in the UI directly.

Revert "Ignore db/schema.rb code duplication"

---

app/components/app_patient_summary_component.rb
app/controllers/immunisation_imports/patients_controller.rb
app/forms/patient_changes_form.rb
app/models/immunisation_import_row.rb
app/models/patient.rb
app/views/immunisation_imports/patients/show.html.erb
config/locales/en.yml
spec/features/immunisation_imports_upload_duplicates_spec.rb
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

Add logic to the #update method in the controller to apply or discard pending changes.
TODO:

Handle duplicate patient review form

---

app/views/immunisation_imports/new.html.erb

The content needs to be slightly different depending on the programme type.

Update vaccination record upload content

---

app/views/application/_header.html.erb
spec/features/user_cis2_authentication_from_start_page_spec.rb

Just noticed that this was missing, I thought we'd had it. ¯\\\_(ツ)_/¯

Add CIS2 "change role" button

---

app/models/programme.rb
spec/models/programme_spec.rb

Flu is given from reception upwards.

Fix year groups for Flu

---

app/views/immunisation_imports/edit.html.erb
spec/features/immunisation_imports_upload_duplicates_spec.rb

This feature is ready to use/test.

Remove :import_review feature flag

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/controllers/sessions/edit_controller.rb
app/javascript/application.js
app/views/sessions/edit/location.html.erb
config/initializers/inflections.rb
package.json
spec/features/e2e_journey_spec.rb
spec/features/session_management_spec.rb
yarn.lock

This replaces the list of radio buttons with a select that is progressively enhanced to an autocomplete when JS is enabled.

Replace locations radio list with autocomplete

---

app/assets/stylesheets/_panel.scss
package.json
yarn.lock

This aligns the headings and line-height to the prototype.

Bump nhsuk-frontend to 9.0.0

---

app/views/dashboard/index.html.erb

This has been removed from the prototype, and needs re-working anyway.

Remove add session link from dashboard

---

app/controllers/cohort_imports_controller.rb
app/controllers/sessions/edit_controller.rb

Instead of arel, we can use native AR queries.
Also two small unrelated changes.

Simplify set_patients query

---

.github/workflows/test.yml
app/components/app_backlink_component.html.erb
db/seeds.rb
package.json
playwright.config.ts
tests/accessibility.spec.ts
yarn.lock

This test logs into the app and checks a few pages for easy to find accessibility issues using Axe.

Add accessibility end to end playwright test

---

.github/workflows/deploy.yml
copilot/environments/accessibility/manifest.yml
copilot/webapp/manifest.yml

This environment will be spun up and then discarded once testing completes.

Set up accessibility environment for testing

---

app/views/parent_interface/consent_forms/edit/school.html.erb
lib/tasks/add_health_questions.rake

This was written back when we had just one programme per team.
Also maintain user's choice of school in consent form.

Fix add_health_questions to work with programmes

---

config/initializers/devise.rb
db/seeds.rb

A couple of small fixes, pulled out of some of the other CIS2 work.

Add CIS2 feature flag and fix minimum TLS version

---

config/locales/en.yml

We missed this when building this out.

Add missing relationship_type blank message

---

spec/components/app_session_table_component_spec.rb

This test needs travel_to in order to not break at some point in the future.

Fix test that's failing on the 2nd of Oct

---

app/views/sessions/show.html.erb

Align "Import class list" link with designs

---

app/components/app_import_tables_component.rb
app/controllers/class_imports_controller.rb
app/models/session.rb
app/policies/class_import_policy.rb
app/views/class_imports/edit.html.erb
app/views/class_imports/errors.html.erb
app/views/class_imports/new.html.erb
app/views/class_imports/show.html.erb
app/views/sessions/show.html.erb
config/routes.rb
spec/features/import_class_lists_spec.rb
spec/fixtures/class_import/valid.csv
spec/models/class_import_spec.rb
spec/models/session_spec.rb

This adds the ability to import a list of children from the session view, allowing teams to add patients to a session that may have been missed from the cohort import.

Import class lists

---

lib/tasks/add_new_user.rake

Use `User#first_name` and `User#family_name` instead of obsolete `User#full_name`

Fix add_new_user rake task

---

app/views/parent_interface/consent_forms/edit/confirm_school.html.erb

This is useful for writing automated tests.

Add data-qa to school name in consent journey

---

app/jobs/text_delivery_job.rb
config/application.rb
spec/jobs/text_delivery_job_spec.rb

This fixes a couple of issues with the queue for the `TextDeliveryJob`, see individual commits for more details.

Fix TextDeliveryJob queue

---

app/models/cohort_import_row.rb
app/models/immunisation_import_row.rb

This is a significant speed-up when compared to doing a brute-force search through all the URNs for all the schools.

Use exists? to validate urn in import validations

---

app/assets/stylesheets/_table.scss
app/assets/stylesheets/_typography.scss
app/views/class_imports/new.html.erb
app/views/cohort_imports/new.html.erb
app/views/immunisation_imports/new.html.erb

This updates the CSV guidance sections to match the latest designs in the prototype and ensure they render correctly.
https://github.com/nhsuk/manage-vaccinations-in-schools-prototype/commit/404fc1e9f6b1496f33b10d08a22317bc18b60d6e

Improve CSV guidance styles

---

copilot/webapp/manifest.yml

Our settings prefix is actually `MAVIS__`.

Fix dev phone numbers settings var

---

app/assets/stylesheets/_table.scss
app/components/app_patient_table_component.html.erb
app/controllers/class_imports_controller.rb
app/controllers/cohort_imports_controller.rb
app/controllers/cohorts_controller.rb

Add an extra row and make the text slightly smaller.

Include schools in patients table

---

.tool-versions

Latest deployment used 1.34.0.

Bump copilot tool version

---

app/components/app_import_errors_component.rb

These will be used by our testing automation.

Add data-qa attributes to import errors

---

app/components/app_imports_table_component.html.erb
app/models/concerns/csv_importable.rb
db/seeds.rb
spec/factories/class_imports.rb
spec/factories/cohort_imports.rb
spec/factories/immunisation_imports.rb

Includes https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1975 which can't be merged for unknown reasons.
This attempts to use the number of rows with our guesstimated performance in the `test` environment to estimate the approximate time it will take to process an import.

Estimate processing time in imports table

---

spec/factories/patients.rb

The default FactoryBot NHS number implementation relies on `rand` and sometimes produces clashing numbers which fail to pass validations and either break the tests or the review apps as a result.
This replaces it with a solution that inlines the logic for generating a test NHS number as well as generating a valid check digit. These NHS numbers are sequential and thus linearly span the entire space of approximately ~1 million possible test numbers.

Ensure generated NHS numbers are always unique

---

app/views/sessions/show.html.erb
spec/features/manage_sessions_spec.rb

This is in the design and was requested by our nurse team.

Show school URN on session page

---

app/assets/stylesheets/_summary-list.scss
app/assets/stylesheets/application.scss
app/components/app_vaccination_check_and_confirm_component.rb
app/views/vaccinations/edit/confirm.html.erb
config/locales/patient_session_statuses.en.yml
spec/components/app_simple_status_banner_component_spec.rb
spec/components/app_vaccination_check_and_confirm_component_spec.rb
spec/features/hpv_vaccination_not_administered_spec.rb
spec/features/parental_consent_spec.rb

This makes a number of changes to the vaccination flow to improve clinical safety. See individual commits for more details.

Clinical safety improvements

---

app/controllers/dev_controller.rb

This fixes a couple of bugs related to the reset endpoint, see commits for more details.

Reset endpoint bug fixes

---

config/locales/en.yml
spec/features/manage_sessions_spec.rb

Make the microcopy in the sessions area talk about locations, rather than schools, like in the prototype.

Sessions can be at clinics as well as schools

---

app/models/patient_import_row.rb
app/views/class_imports/new.html.erb
app/views/cohort_imports/new.html.erb
config/locales/en.yml
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

It matches the allowed values for `Patient#gender_code`

Accept CHILD_GENDER attribute for class and cohort imports

---

app/controllers/pages_controller.rb
config/routes.rb

This includes the dev public key for localhost testing.

Add /oidc/jwks endpoint to disseminate jwt keys

---

db/seeds.rb

Flu and HPV wouldn't run together, and some parts of the service break if both are offered in the same session. We can add Flu back in later, when we've ironed out the multi-programme issues.

When seeding a dev or test environment, only seed the HPV programme

---

.github/workflows/deploy.yml
copilot/environments/pentest/manifest.yml
copilot/webapp/manifest.yml

Configure copilot to deploy a new environment.

Add pentest environment manifest

---

app/components/app_card_component.rb
app/views/dashboard/index.html.erb
spec/components/app_card_component_spec.rb
spec/features/manage_children_spec.rb
spec/features/manage_teams_spec.rb

This updates the cards in the dashboard to match the latest designs in the prototype.

Update dashboard layout

---

app/views/notices/index.html.erb
config/locales/en.yml
spec/features/manage_children_spec.rb

Clearer microcopy when there are no important notices

---

app/components/app_parent_summary_component.rb
app/views/consents/show.html.erb
app/views/manage_consents/confirm.html.erb
spec/components/app_parent_summary_component_spec.rb

This adds a component which renders parent information that we can use in a couple of different views and reuse any related logic.

Add AppParentSummaryComponent

---

app/components/app_activity_log_component.rb
spec/components/app_activity_log_component_spec.rb
spec/factories/consents.rb

Prevent activity log crash for self-consent

---

config/routes.rb
spec/features/cis2_backchannel_logout_spec.rb

Fix backchannel-logout route

---

app/lib/nhs/api.rb

We're still seeing errors where we try and use an access token that's unauthorized, so hopefully this will resolve that, although if not we might need to investigate further.

Increase NHS API safety buffer

---

app/controllers/programmes_controller.rb
app/models/programme.rb
app/views/programmes/index.html.erb

Display only active vaccines for a programme

---

app/jobs/school_session_reminders_job.rb
spec/jobs/school_session_reminders_job_spec.rb

I suspect this is an oversight and how it should work as the content of the template explains that the child is due to receive their vaccine. Currently we send the email to everyone, including patients who's parents have refused consent.

Only send session reminders to patients who will be vaccinated

---

app/models/consent_form.rb
app/views/parent_interface/consent_forms/confirm.html.erb
spec/features/parental_consent_clinic_spec.rb

When provided consent for a community clinic, we always ask for the patient's school as the location will be set to a community clinic.

Update consent flow for clinics

---

app/controllers/dev_controller.rb
app/controllers/parent_interface/consent_forms/base_controller.rb
app/controllers/parent_interface/consent_forms/edit_controller.rb
app/controllers/parent_interface/consent_forms_controller.rb
app/views/parent_interface/consent_forms/edit/confirm_school.html.erb
config/routes.rb

This makes a number of small improvements to the consent forms, similar to #2140.

Small refactors for consent forms

---

config/locales/en.yml
spec/features/e2e_journey_spec.rb
spec/features/parental_consent_refused_spec.rb
spec/features/parental_consent_spec.rb
spec/features/response_matching_spec.rb
spec/features/self_consent_clinic_spec.rb
spec/features/self_consent_gillick_competent_spec.rb
spec/features/self_consent_not_gillick_competent_spec.rb
spec/features/verbal_consent_given_when_previously_refused_spec.rb

Align the content to the prototype.

Update patient table headers

---

app/controllers/parent_interface/consent_forms/edit_controller.rb
app/models/consent_form.rb
app/views/parent_interface/consent_forms/edit/home_educated.html.erb
config/locales/en.yml
spec/features/parental_consent_clinic_spec.rb

When we're submitting a consent form for clinics, we don't know if the patient is home-schooled or unknown school or came from a school, so we need to ask the parent if their child is home-schooled, and if not present them with a list of schools to choose from.

Ask if patient is home-educated for clinics

---

app/controllers/manage_consents_controller.rb
app/models/consent.rb
app/views/manage_consents/confirm.html.erb
spec/factories/teams.rb
spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb
spec/features/verbal_consent_but_no_triage_for_admin_spec.rb

I'm not happy with the cleanliness of the solution and welcome improvement suggestions.

Admins shouldn't be able to record triage when recording consent through Mavis

---

app/controllers/vaccinations_controller.rb

We're currently rendering the view before sorting and filtering the patient sessions meaning the filters aren't working.

Fix filters on vaccinations page

---

app/components/app_consent_component.rb
app/lib/govuk_notify_personalisation.rb
app/models/session.rb
app/models/session_date.rb
spec/features/parental_consent_send_request_spec.rb
spec/lib/govuk_notify_personalisation_spec.rb

This makes two small improvements to the "Send consent requests" button to fix bugs, see individual commits for more details.

Send consent request improvements

---

app/components/app_import_format_details_component.rb

This improves the information provided in the import format details component to specify the date format for all date values.

Specify date formats for import values

---

app/models/patient_import_row.rb

This is in preparation of switching to `stage_changes` which requires exact attribute names.

Pass in school and cohort id in PatientImport

---

app/views/sessions/show.html.erb
spec/features/parental_consent_refused_spec.rb
spec/features/parental_consent_spec.rb
spec/features/user_authorisation_spec.rb

Put "Check consent responses" into Release 1b

---

app/assets/stylesheets/_card.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/helpers/_link.scss
app/components/app_card_component.rb
app/components/app_session_table_component.html.erb
app/controllers/programmes_controller.rb
app/views/programmes/index.html.erb
app/views/programmes/show.html.erb
spec/components/app_session_table_component_spec.rb
spec/features/dev_reset_team_spec.rb
spec/features/edit_vaccination_record_spec.rb
spec/features/import_vaccination_records_spec.rb
spec/features/import_vaccination_records_with_duplicates_spec.rb

This adds three cards to the programme overview page showing basic statistics about the programme.

Add basic programme statistics

---

docs/aws-copilot.md

Just got bit by this. Maybe we'll remember to look at this when we have issues in the future.

Add copilot deployment troubleshooting to docs

---

app/models/user.rb
app/views/application/_header.html.erb
spec/features/e2e_journey_spec.rb
spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb

Display role in the Mavis header, next to staff name

---

app/controllers/session_dates_controller.rb
app/models/session.rb
config/locales/en.yml
spec/factories/sessions.rb
spec/jobs/clinic_session_invitations_job_spec.rb
spec/jobs/school_consent_reminders_job_spec.rb
spec/lib/govuk_notify_personalisation_spec.rb
spec/models/session_spec.rb

This makes a number of changes to the session dates to fix a number of bugs spotted by the testers.

Fix a couple of bugs related to session dates

---

app/controllers/sessions_controller.rb
app/models/patient_session_stats.rb
app/views/sessions/show.html.erb
lib/tasks/performance.rake
spec/models/patient_session_stats_spec.rb

This refactors the class to accept a list of patient sessions, allowing us to customise the list of patient sessions that are passed in, allowing for programme-level stats or a subsection of a session.

Refactor SessionStats

---

db/seeds.rb

Update the seeds to facilitate automated testing.

Add The Ruiz Centre to Nurse Joy's locations

---

package.json
script/encrypt_excel.mjs
yarn.lock

This script will be used in disaster recovery scenarios to encrypt and password protect a generated Excel file that will be sent to a SAIS team.

Add script/encrypt_excel.mjs

---

Gemfile
Gemfile.lock
script/organisation_export.rb

This will be used to generate an export of a SAIS team's data in disaster recovery scenarios.

Add script/organisation_export.rb

---

app/policies/patient_policy.rb

We limit which patients a user can seen, but we need to ensure that any patients with pending changes that brings them in to the organisation are visible to users so they can review and confirm the changes, as currently they won't be accessible and will raise an error.

Ensure pending patients are visible

---

db/seeds.rb

134522 was a closed school so we're replacing it with an open one.
Once this is merged I'll let the testers know of the new school names.

Update URNs in seeds for school used by tests

---

config/settings/development.yml

This was missed in 64e2e6e1feed925bc73b1127059d840591edda02.

Disable CIS2 in development

---

app/components/app_patient_page_component.html.erb
app/components/app_patient_summary_component.rb
app/components/app_vaccination_record_summary_component.rb
app/controllers/vaccination_records_controller.rb
app/views/vaccination_records/edit.html.erb
app/views/vaccination_records/show.html.erb
config/routes.rb
spec/features/edit_vaccination_record_spec.rb

This adds a page that will include all the change links for various parts of a vaccination record that can be changed.

Add "Edit vaccination record" page

---

app/controllers/programmes_controller.rb

This used to be the case but when building the new sessions table design, I inadvertently lost this functionality, meaning we started seeing sessions across all academic years.

Only show sessions and stats for current academic year

---

.github/workflows/deploy-pentest.yml
.github/workflows/deploy-test.yml
.github/workflows/shared/deploy.yml

This DRYs out the test/pentest deploy scripts.

Extract shared deploy template

---

config/locales/en.yml

Small content change spotted by our designers.

Make locations plural in scheduled sessions table

---

.github/workflows/deploy.yml

Just makes it consistent with Deploy (pentest).

Reword deploy run name

---

app/components/app_consent_refused_table_component.rb
app/controllers/programmes_controller.rb
app/views/programmes/index.html.erb
spec/components/app_consent_refused_table_component_spec.rb

This makes a couple of small improvements to the statistics that are shown following feedback from the testers. There's likely more changes to come here when it becomes clear what statistics we want to show.

Small improvements to statistics

---

app/components/app_vaccination_record_summary_component.rb
app/helpers/vaccinations_helper.rb
spec/components/app_vaccination_record_summary_component_spec.rb

This extracts a number of smaller changes from a larger vaccination edit change to get them out and ready to be tested. A proper feature test will be coming with this change as part of editing the vaccination records later.

Small improvements to the vaccination flow

---

app/controllers/dev_controller.rb

Triages have been moved from session-level to programme-level, but this action wasn't updated to reflect this.

Fix crash in DevController#reset_organisation

---

.gitignore
README.md
package.json
tests/load.ts
tests/load.yml
yarn.lock

This follows
https://www.artillery.io/docs/reference/engines/playwright#example-4-aggregate-metrics-by-scenario-name to configure Artillery to run a load test using Playwright for the parental consent journey.

Load test with Artillery and Playwright

---

app/components/app_programme_navigation_component.rb

The import issues counter in the secondary nav was double counting import issues where both the vaccination record and the patient have pending changes.
Because the import issues controller is doing this correctly, there was also a discrepancy between the count and what the user saw when they navigated to the import issues list.

Fix issues count in the secondary nav under Programmes

---

app/models/draft_vaccination_record.rb
app/models/vaccination_record.rb
spec/models/draft_vaccination_record_spec.rb

Display missing dose volume when confirming a vaccination recording

---

app/components/app_vaccination_record_summary_component.rb

You can get to this screen if you edit vaccination outcomes back and forth.

Vaccination check and confirm: tweak when dose volume appears

---

app/models/consent_form.rb
spec/features/parental_consent_inexact_auto_match_spec.rb
spec/features/parental_consent_manual_matching_spec.rb
spec/features/parental_consent_refused_spec.rb
spec/features/parental_consent_spec.rb
spec/models/consent_form_spec.rb
spec/models/patient_spec.rb
spec/spec_helper.rb
spec/support/pds_helper.rb

Best reviewed commit-by-commit.

Normalise first and last name on the consent form, improve spec coverage around matching

---

app/components/app_patient_vaccination_table_component.html.erb
app/components/app_patient_vaccination_table_component.rb
app/controllers/patients_controller.rb
app/views/patients/show.html.erb
spec/components/app_patient_vaccination_table_component_spec.rb

Vaccinations on the global children's view

---

app/controllers/patients_controller.rb

Fix triage strict loading field

---

app/models/immunisation_import_row.rb
spec/models/immunisation_import_row_spec.rb

This fixes an error in the validation where it was expecting a value where it shouldn't.

Fix TIME_OF_VACCINATION validation

---

app/controllers/sessions_controller.rb
app/lib/session_xlsx_exporter.rb
spec/lib/session_xlsx_exporter_spec.rb

This will fix an error where we can't export the patient's school for a community clinic.
https://good-machine.sentry.io/issues/6061770556/

Preload school when exporting a session CSV

---

app/lib/careplus_exporter.rb
spec/lib/careplus_exporter_spec.rb

This will be used to export vaccinations in the CarePlus format.
TODO in follow-ups:
- Figure out what "Suspension end date" is
- Figure out what the "Dose" field should be
- Figure out the coded values for delivery site

Add CarePlus exporter

---

app/controllers/vaccination_reports_controller.rb
app/lib/careplus_exporter.rb
app/models/vaccination_report.rb
spec/features/download_vaccination_reports_spec.rb

This allows users to download reports in CarePlus format using the UI, combining the work in #2427 and #2429.

Integrate CarePlus with reports UI

---

app/controllers/sessions_controller.rb
app/lib/reports/careplus_exporter.rb
app/lib/reports/offline_session_exporter.rb
app/lib/reports/programme_vaccinations_exporter.rb
app/models/vaccination_report.rb
spec/features/download_vaccination_reports_spec.rb
spec/lib/reports/careplus_exporter_spec.rb
spec/lib/reports/offline_session_exporter_spec.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

This adds the functionality allowing users to download a vaccinations report in the Mavis reporting format.

Add Mavis-formatted vaccinations report download

---

bin/aws-account-setup

Updated with fixes and checks from the most recent pentest.
Also updated the script so that it's a bit more modular and so we can run individual fixes or checks. But I think it's missing a "run all" mode now.

Update `aws-account-setup` post-env setup script

---

app/controllers/register_attendances_controller.rb
config/locales/en.yml

Use more messages from the prototype.

Update attendance flash messages

---

app/components/app_import_format_details_component.rb
app/models/immunisation_import_row.rb
spec/models/immunisation_import_row_spec.rb

This is necessary to support uploading of vaccinations recorded offline.

Imms import: allow all Mavis delivery sites

---

app/components/app_import_format_details_component.rb

The validations require it in all cases so best be explicit

Clarify in guidance that imms import DATE_OF_VACCINATION is required

---

app/models/organisation.rb
app/models/team.rb
db/seeds.rb
spec/factories/patient_sessions.rb
spec/models/onboarding_spec.rb
spec/models/organisation_spec.rb

Improve the factories and seeds so that local testing of clinic interactions can be done straight away.

Easier local testing for clinics

---

app/components/app_compare_consent_form_and_patient_component.html.erb
app/components/app_compare_consent_form_and_patient_component.rb
app/controllers/consent_forms_controller.rb
app/helpers/parents_helper.rb
app/helpers/patients_helper.rb
app/views/consent_forms/match.html.erb
spec/components/app_compare_consent_form_and_patient_component_spec.rb

This adds missing fields from the design, although it doesn't completely build the design we've got in the prototype as that would require a bigger refactor to these components.

Add more comparisons between consent forms and patients

---

app/components/app_import_format_details_component.rb
spec/components/app_import_format_details_component_spec.rb

Imms import guidance updates

---

app/models/vaccination_report.rb

This should be a datetime rather than an integer.

Fix VaccinationReport#date_to type

---

config/database.yml

Make all the configs consistent.
Remove the username/password as that's inferred from the DB_SECRET env var in AWS.

Update production database config

---

app/assets/stylesheets/_button.scss
app/assets/stylesheets/_highlight.scss
app/assets/stylesheets/application.scss

Fix Sass color deprecation warnings

---

app/controllers/dev_controller.rb
spec/features/dev_reset_organisation_spec.rb

This refactors the endpoint to make it easier to read, while also making sure that we delete all `NotifyLogEntry`s, adding this to the feature test at the same time.
https://good-machine.sentry.io/issues/6072642994/

Refactor dev organisation reset endpoint

---

app/models/concerns/csv_importable.rb
config/locales/en.yml

Better error messages for imports

---

.github/workflows/_deploy-template.yml

This removes a warning in the actions UI.

Remove url from deploy template environment

---

app/lib/reports/offline_session_exporter.rb

If exporting a session for offline recording, if any of the patients are marked as invalidated, we should show their NHS numbers with a strike through as they would be shown when looking through the patients online.

Strike through invalidated NHS numbers in offline export

---

config/onboarding/smoke-test.yml

Production needs real phone numbers for validations

Use real numbers in smoke test setup

---

config/settings.yml
config/settings/staging.yml

Update NHS API token endpoint for prod

---

app/lib/reports/careplus_exporter.rb

Use the official list we've obtained to align our codes.

Update coded_site in Careplus exporter

---

app/lib/reports/offline_session_exporter.rb

This adds a number of dropdowns for cells where there is a limited set of allowed values, which should make the spreadsheet easier for the nurses to use and avoid validation errors when they come to import the files.

Add dropdowns to offline session export

---

app/controllers/school_moves_controller.rb
app/helpers/patients_helper.rb
app/helpers/school_moves_helper.rb
app/views/school_moves/show.html.erb
config/locales/en.yml
spec/features/parental_consent_manual_matching_spec.rb
spec/helpers/patients_helper_spec.rb

This makes a number of changes to the content for school moves following a demo of the functionality.

Update content related to school moves

---

app/components/app_patient_page_component.html.erb
app/views/patient_sessions/show.html.erb
app/views/sessions/show.html.erb
config/locales/en.yml
spec/components/app_patient_page_component_spec.rb
spec/factories/patient_sessions.rb
spec/factories/patients.rb
spec/features/e2e_journey_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_default_batch_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/invalidate_consent_spec.rb
spec/features/manage_attendance_spec.rb
spec/features/triage_delay_vaccination_spec.rb
spec/features/withdraw_consent_spec.rb

The recording attendance feature is going to be part of the next release so we can remove the feature flag for it.

Remove record_attendance feature flag

---

app/lib/reports/careplus_exporter.rb
spec/lib/reports/careplus_exporter_spec.rb

We've been given these values to use in the Care Plus export for nurses.

Set Care Plus staff code and type values

---

app/models/patient.rb
app/models/pds/patient.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/parental_consent_create_patient_spec.rb
spec/jobs/consent_form_matching_job_spec.rb
spec/jobs/patient_nhs_number_lookup_job_spec.rb
spec/jobs/patient_update_from_pds_job_spec.rb
spec/models/patient_spec.rb
spec/models/pds/patient_spec.rb

This updates the process which looks up data in PDS to set the GP practice on the patient.

Fetch patient GP practice from PDS

---

aws/mavis-splunk-lambda.mjs
script/aws_splunk_setup.rb

This sets up a new IAM role, IAM policy, and a Lambda function that will be used by the Splunk firehose to process the CloudWatch logs before they get sent.
The Lambda script is based on an AWS blueprint.

Add lambda to Splunk setup

---

app/lib/reports/programme_vaccinations_exporter.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

This adds a column which captures whether the record was updated within the date range or created in the date range.

Add record status to vaccinations export

---

config/initializers/semantic_logger.rb
config/settings.yml
copilot/webapp/manifest.yml

We temporarily tested this on accessibility, but test is where we actually want it.

Enable splunk logging on the test environment

---

app/jobs/patient_update_from_pds_job.rb
spec/jobs/patient_update_from_pds_job_spec.rb

This expands upon https://github.com/nhsuk/manage-vaccinations-in-schools/commit/e0aaf91f3e79bc121e52558a235a90c54a049652 to also look up the patient by demographics if the NHS number doesn't exist in PDS. This could help to handle the case where the nurse has entered an NHS number incorrectly.
https://good-machine.sentry.io/issues/6091497694/

Look up patients when NHS number doesn't exist

---

app/views/vaccination_records/show.html.erb

This ensures that they render correctly aligned horizontally.

Put edit and delete links in a button group

---

Gemfile
Gemfile.lock

Group the default Railsy gems together and remove `jbuilder` which we don't need.

Tidy up Gemfile

---

app/models/school_move.rb
spec/models/school_move_spec.rb

When confirming a school move the patient shouldn't be moved to the new school sessions if they've already been vaccinated, otherwise there's a risk of double vaccination.
The diff for the changes to the tests is probably easier to review ignoring white space changes.

Don't move patients if already vaccinated

---

.github/workflows/deploy.yml
README.md
copilot/environments/qa/manifest.yml
copilot/webapp/manifest.yml

We will use this to run manual and automated tests without CIS2.

Provision QA environment

---

app/forms/school_move_form.rb

Bug fix MAVIS-1745
Specs will be added in a follow-up commit.

Allow ignore move from community clinic

---

app/lib/reports/export_formatters.rb

This fixes a bug where the route is exported incorrectly.

Use delivery method for route of vax

---

app/controllers/dev_controller.rb

This is needed by the testers.

Reset PreScreenings

---

.github/workflows/deploy.yml
README.md
copilot/environments/preview/manifest.yml
copilot/webapp/manifest.yml

This will be in between test/qa and training/production.
| Name                                                                                         | URL                                                                                                      | Purpose                      | Care Identity login | Code    | `RAILS_ENV`                                       |
| -------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------- | ---------------------------- | ------------------- | ------- | ------------------------------------------------- |
| [Heroku](https://github.com/nhsuk/manage-vaccinations-in-schools/deployments/heroku)         | …

Set up preview environment

---

Gemfile
Gemfile.lock

This should improve Sentry performance metrics by setting up profiling.

Add stackprof

---

.github/workflows/deploy.yml

We're going to deploy to this environment separately.

Switch off CD on Training

---

app/models/organisation.rb
config/onboarding/coventry-model-office.yaml
config/onboarding/smoke-test.yml
db/migrate/20241211174159_make_organisation_privacy_policy_url_not_null.rb
db/schema.rb
docs/onboarding.md
spec/factories/organisations.rb
spec/fixtures/files/onboarding/valid.yaml
spec/models/onboarding_spec.rb
spec/models/organisation_spec.rb

We're using this value in GOV.UK Notify templates and in the parental consent journey so we need to ensure this is provided as part of the onboarding process.

Validate presence of privacy_policy_url 

---

config/locales/en.yml

Fix notes error message on consents

---

config/routes.rb

This gives the page a default sorting order.

Sort attendances alphabetically by default

---

app/controllers/concerns/patient_sorting_concern.rb
spec/controllers/concerns/patient_sorting_concern_spec.rb

Reverts nhsuk/manage-vaccinations-in-schools#2789
This should've been merged in to `next`.

Revert "Fix bug where nurses can't sort with blank postcodes"

---

app/controllers/application_controller.rb
app/lib/govuk_notify_personalisation.rb
config/initializers/devise.rb
config/initializers/log_public_assets.rb
config/routes.rb

This updates every instance of `Rails.env.development? || Rails.env.test?` with `Rails.env.local?` which does the same thing.

Use `Rails.env.local?`

---

app/lib/nhs/pds.rb

This makes it easier to debug issues by including a breadcrumb containing the response from PDS in Sentry.

Record PDS error responses in Sentry

---

app/components/app_imports_table_component.html.erb
app/components/app_imports_table_component.rb
app/views/imports/show.html.erb
spec/components/app_imports_table_component_spec.rb
spec/features/import_class_lists_spec.rb

|| Before | After |
|--------|--------|--------|
|Upload list| <img width="1121" alt="image" src="https://github.com/user-attachments/assets/ea4764b7-648b-40b0-8dbf-58ba89c8e2c0" /> | <img width="1121" alt="image" src="https://github.com/user-attachments/assets/ad65af72-9a88-449f-b020-be535a15480a" /> |
|Upload page| <img width="1129" alt="image" src="https://github.com/user-attachments/assets/ad085688-cc7a-4c51-99a5-1c20954fc45e" /> | <img width="1152" alt="image" src="https://github.com/user-attachments/assets/89e3a28c-7a07-4461-b48c-d0f5c3617a18" /> |

Class list uploads: make it easier to tell which school the upload is for, and to navigate back to the school

---

app/views/layouts/_header.html.erb
app/views/school_moves/index.html.erb

This adds a few bits on top of #2808 that was found by our testers during testing today, see individual commits for more details.

Small updates to header navigation item counts

---

config/onboarding/coventry-production.yaml
config/onboarding/hertfordshire-training-with-sessions.yaml
config/onboarding/hertfordshire-training.yaml

This allows us to run the `rails onboarding` script successfully.

Update privacy_notice_url for Herfordshire ymls

---

config/onboarding/coventry-production.yaml

This updates the onboarding configuration for Coventry to match the values in production.

Update Coventry onboarding

---

app/jobs/bulk_update_patients_from_pds_job.rb
app/jobs/concerns/nhs_api_concurrency_concern.rb
app/models/concerns/csv_importable.rb

This adds two changes in to the 1.3.0 hotfix branch that we anticipate will fix some problems we're seeing in production with the PDS jobs.

Improvements to NHS job concurency configuration

---

app/controllers/vaccination_records_controller.rb

This should slightly improve the performance of this page by avoiding unnecessary queries, and removes a TODO comment.

Remove duplicate preloading

---

app/components/app_import_format_details_component.rb

Add details of alternative date format to vaccination record upload format advice.
Resolves MAVIS-1828.

Document alternative date format for vaccination record upload

---

app/lib/reports/programme_vaccinations_exporter.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

We might not be in a position to release this feature in 1.5.0 but we can put it behind a feature flag for now.

Add feature flag for GILLICK_NOTIFY_PARENTS

---

.github/workflows/build.yml
terraform/scripts/shell-access.sh

This workflow builds a docker image and uploads it to both prod and non-prod ECR.
It is triggered either manually or by a successful completion of the "Test" workflow, if the "Test" workflow was triggered by a push to main

Mavis-2020 Add build workflow

---

app/components/app_activity_log_component.rb
app/components/app_consent_component.html.erb
app/components/app_consent_component.rb
app/components/app_consent_status_component.rb
app/components/app_outcome_banner_component.rb
app/components/app_patient_page_component.html.erb
app/components/app_patient_page_component.rb
app/components/app_simple_status_banner_component.rb
app/components/app_triage_form_component.rb
app/components/app_vaccinate_form_component.rb
app/controllers/consents_controller.rb
app/controllers/patient_sessions_controller.rb
app/controllers/triages_controller.rb
app/controllers/vaccinations_controller.rb
app/views/patient_sessions/log.html.erb
app/views/patient_sessions/show.html.erb
app/views/triages/new.html.erb
spec/components/app_consent_component_spec.rb
spec/components/app_consent_status_component_spec.rb
spec/components/app_outcome_banner_component_spec.rb
spec/components/app_patient_page_component_spec.rb
spec/components/app_simple_status_banner_component_spec.rb
spec/components/app_triage_form_component_spec.rb
spec/components/app_vaccinate_form_component_spec.rb

In preparation for the new designs to support multiple programmes, this updates the various components that render content according to the current programme to accept the programme as an argument, meaning the parent controller or view is responsible for determining which programme the user has currently selected.

Pass programme to components

---

.github/workflows/deploy_infrastructure.yml
.github/workflows/deploy_mavis.yml
terraform/app/codedeploy.tf
terraform/app/ecs.tf
terraform/app/env/copilotmigration.tfvars
terraform/app/env/poc.tfvars
terraform/app/outputs.tf
terraform/app/variables.tf
terraform/scripts/check_task_definition.sh
terraform/scripts/validate_plan.sh

* Make container environment variables configurable via terraform variables
* Use image digest instead of image tag for task definition ** Ensures consistency across task creations
* Create outputs needed for GitHub workflows
* Create GitHub workflows ** Mavis deployment
*** Validation script for terraform plan to only change limited scope ** Terraform deployment
*** Validation script to limit downtime risk in terraform deployment
* Renaming copilot resources to more suitable terms

MAV-384: Create mavis and terraform deployments

---

db/seeds.rb

So we can use the automatic Heroku deployments to test the doubles changes.

Setup data for multiple programmes when seeding the db

---

app/models/vaccine.rb
spec/models/vaccine_spec.rb

We are expecting to record the 5th dose when vaccinating patients in school.

Increase Td/IPV maximum dose sequence

---

app/assets/stylesheets/_secondary-navigation.scss
app/components/app_secondary_navigation_component.html.erb
app/components/app_secondary_navigation_component.rb
app/views/patient_sessions/_secondary_navigation.html.erb

Following the approach and styles in the prototype.
Adding this now as it's going to be important to make it clear to nurses what programme they're currently looking at for the child they're with.

Make the secondary nav on patient session page sticky

---

app/controllers/consents_controller.rb
app/controllers/triages_controller.rb
app/controllers/vaccinations_controller.rb
app/views/consents/index.html.erb
app/views/triages/index.html.erb
app/views/vaccinations/index.html.erb

This adds pagination when viewing a table of patients for a session, in a similar way to other paginated views. The is mostly for the community clinics which now shows all patients in the cohort.

Paginate session patients

---

lib/tasks/vaccines.rake
spec/factories/vaccines.rb

This updates the health questions following discussion with our SAIS organisation, they would like a question added about severe allergies.

Update health questions for Td/IPV and MenACWY

---

app/views/sessions/invite_to_clinic/edit.html.erb

This content has been updated by our designers to consider the scenario when there are no more reminders to be sent.

Update content when sending reminders

---

.github/workflows/continuous_deployment.yml

- Got removed accidentally in reformatting

MAV-745: Re-insert needed input variable

---

config/locales/en.yml
spec/models/immunisation_import_row_spec.rb

This is the improved content that has been suggested by our content designers.

Update content for date of vaccination inclusion error

---

docs/rake-tasks.md
lib/tasks/organisations.rake

This adds a Rake task that can be used to add a programme to an existing organisation.

Add organisations:add_programme

---

.github/workflows/continuous_deployment.yml
.github/workflows/deploy_application.yml
.github/workflows/deploy_infrastructure.yml
.github/workflows/deploy_mavis.yml

- Artifacts with same name cannot exist in one workflow 
- Therefore the continuous_deployment workflow failed

MAV-745: Give artifacts unique names

---

.github/workflows/deploy_application.yml
.github/workflows/deploy_infrastructure.yml

- File name persists, just artifact name is different
- previous change assumed changed file name as well

MAV-745: Fix file reference

---

app/components/app_programme_session_table_component.html.erb
app/components/app_session_summary_component.rb
app/components/app_session_table_component.html.erb
app/helpers/sessions_helper.rb
spec/helpers/sessions_helper_spec.rb

And also add the year as requested to make it very clear when the consent period closes/opens.

Ensure consent period is capitalised

---

app/components/app_search_component.rb

In the outcome status filters the first option should be "All" rather than "Any".

Change label to "All"

---

app/components/app_search_component.rb

Reverts nhsuk/manage-vaccinations-in-schools#3157
We've decided to stick with "Any" in the end!

Revert "Change label to "All""

---

terraform/app/codedeploy.tf
terraform/app/ecs.tf
terraform/app/env/copilotmigration.tfvars
terraform/app/env/poc.tfvars
terraform/app/loadbalancer.tf
terraform/app/modules/dns/main.tf
terraform/app/modules/dns/variables.tf
terraform/app/monitoring.tf
terraform/app/network.tf
terraform/app/outputs.tf
terraform/app/rds.tf
terraform/app/variables.tf
terraform/scripts/bootstrap.sh

- log retention time
- listener rules
- db isntance naming

Mav 787 implement review changes

---

terraform/app/env/copilotmigration.tfvars
terraform/app/env/poc.tfvars
terraform/app/env/preview.tfvars
terraform/app/env/production.tfvars
terraform/app/env/qa.tfvars
terraform/app/env/test.tfvars
terraform/app/env/training.tfvars
terraform/app/loadbalancer.tf
terraform/app/variables.tf
terraform/scripts/bootstrap.sh

- Ensure all variables are defined for migration and operation with standard parameters
- http_hosts variable is introduced in another ticket

MAV-811: Add production variables

---

app/components/app_session_details_summary_component.rb
config/locales/en.yml
spec/components/app_session_details_summary_component_spec.rb

Instead of "0 vaccinations given".

Show "No vaccinations given"

---

app/views/sessions/record/show.html.erb

This displays the batches using a bullet point list to improve the design of this page and match the prototype.

Improve design of multiple default batches

---

app/assets/stylesheets/_secondary-navigation.scss
app/components/app_secondary_navigation_component.html.erb
app/components/app_secondary_navigation_component.rb
app/models/patient_session/session_outcome.rb
app/views/patient_sessions/_header.html.erb
spec/components/app_secondary_navigation_component_spec.rb

When viewing a patient session, if that programme has an vaccinated outcome for this session, we should show a tick next to the programme so the nurses know that there's nothing further to be done for that programme.

Add ticks to programme tabs

---

README.md

- Mermaid diagrams to illustrate both release and branching flows

Add diagrams to release documentation

---

README.md

Fixup missed from previous PR.

We move the release notes, not just copy them

---

terraform/app/env/copilotmigration.tfvars
terraform/app/env/poc.tfvars
terraform/app/env/preview.tfvars
terraform/app/env/production.tfvars
terraform/app/env/qa.tfvars
terraform/app/env/test.tfvars
terraform/app/env/training.tfvars
terraform/app/modules/dns/main.tf
terraform/app/modules/dns/variables.tf
terraform/app/monitoring.tf
terraform/app/variables.tf
terraform/bootstrap/main.tf

This fixes a number of linting issues related to the Terraform configuration by running `terraform fmt`. In the future we should include this as part of the CI checks to ensure it's always linted correctly.

Fix Terraform linting issues

---

terraform/app/env/production-backend.hcl
terraform/app/env/production.tfvars
terraform/app/variables.tf
terraform/bootstrap/main.tf

Ensuring that production configuration matches what is deployed. Some minor changes related to s3 bucket global naming and proper domain extensions

Prod configuration v2.1.1

---

config/onboarding/leicestershire-production.yaml

This is the config file needed to setup Leicestershire's organisation on Mavis.

Add leicestershire production yaml

---

terraform/resources/github_actions_policy.json

- Updating listener rules was encoutnered in a pipeline and will be needed in the future

Update github policy for use by terraform

---

app/models/cohort_import.rb
app/models/cohort_import_row.rb
app/models/concerns/csv_importable.rb
app/models/immunisation_import.rb
app/models/immunisation_import_row.rb
app/models/patient_import.rb
app/models/patient_import_row.rb
config/locales/en.yml
spec/features/import_child_records_spec.rb
spec/features/import_class_lists_spec.rb
spec/fixtures/class_import/invalid_headers.csv
spec/fixtures/cohort_import/invalid_headers.csv
spec/fixtures/immunisation_import/missing_headers.csv
spec/models/class_import_row_spec.rb
spec/models/class_import_spec.rb
spec/models/cohort_import_row_spec.rb
spec/models/cohort_import_spec.rb
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

This refactors the CSV parsing used when importing files to support future enhancements where we will need to support importing different CSV formats with different header values. See individual commits for more details.

Refactor CSV parsing in preparation for future enhancements

---

.github/workflows/deploy-application.yml

- The arn needs to be used specifically

Update workflow to access right element

---

app/models/immunisation_import_row.rb
app/views/immunisation_imports/new.html.erb
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

We've decided we don't want to go live with this feature in the next release. Rather than reverting the code, we can put it behind a feature flag.

Add feature flag for SystmOne imports

---

terraform/app/autoscaling.tf
terraform/app/ecs.tf
terraform/app/env/copilotmigration.tfvars
terraform/app/env/poc.tfvars
terraform/app/env/preview.tfvars
terraform/app/env/production.tfvars
terraform/app/env/qa.tfvars
terraform/app/env/test.tfvars
terraform/app/env/training.tfvars
terraform/app/iam_policy_documents.tf
terraform/app/variables.tf

- We want to ensure we have 2 tasks for availability reasons
- Make a variable that is easy to tune without config changes

Update number of background tasks

---

.github/workflows/deploy-application.yml

- Causing good-job service not to update
- Essentially we just re-deployed existing image multiple times

There was a typo in the pipeline

---

terraform/app/env/production.tfvars
terraform/app/rds.tf
terraform/app/variables.tf

- Allows us to increase capacity of specific environments
- e.g. production which handles larger/more tasks

Make max ACU capacity for rds a variable amount

---

terraform/resources/github_actions_policy.json

- Needed for increasing the maximum ACU for rds

Modification of cluster capacity for github deploy role

---

.github/workflows/lint.yml
bin/lint

- Ensure proper and consistent formatting for PRs

Add linting to script and ci

---

.github/workflows/lint.yml
bin/lint
terraform/.tflint.hcl
terraform/app/modules/dns/main.tf
terraform/app/modules/dns/outputs.tf
terraform/app/modules/ecs_service/main.tf
terraform/app/modules/vpc_endpoint/main.tf
terraform/bootstrap/main.tf
terraform/hooks/lint.sh

- Also update the bin/lint script to include this feature
- Looping allows for only running tflint against passed file arguments

Include TFLint into the CI pipeline

---

app/lib/feature_flag_factory.rb
config/feature_flags.yml
config/initializers/flipper.rb

This adds a number of small improvements to the feature flag interface, adding descriptions to each flag and a banner in production.

Improve feature flag interface

---

terraform/app/ecs.tf
terraform/app/env/production.tfvars
terraform/app/env/qa.tfvars
terraform/app/variables.tf

- Performance tests are run against QA environment
- Allows deeper insights necessary for properly evaluating performance changes and bottlenecks

Enable enhanced monitoring for containers in qa and prod environments

---

terraform/app/env/qa.tfvars
terraform/app/env/test.tfvars
terraform/app/rds.tf
terraform/app/variables.tf

This PR reverts the DB update. The handling of non-default parameter groups needs to be fixed and tested

Revert db upgrade

---

.github/workflows/build-and-push-image.yml
.github/workflows/continuous-deployment.yml
.github/workflows/deploy-application.yml
.github/workflows/deploy-infrastructure.yml
.github/workflows/deploy.yml
.github/workflows/destroy-infrastructure.yml
.github/workflows/test.yml

This PR will resolve the 12 security warnings reported by CodeQL.
It sets the minimum required permissions for each workflow and thus overrides the default read/write permissions.

Set only necessary permissions for all workflows

---

app/controllers/patients_controller.rb
spec/forms/search_form_spec.rb
spec/models/patient_spec.rb

Order search results by match similarity before alphabetical name
[MAV-951](https://nhsd-jira.digital.nhs.uk/browse/MAV-951)

Improve patient search result ordering

---

.github/workflows/test.yml

Fix naming of variables in testing github workflow

---

terraform/app/outputs.tf

This does not modify the running configuration in any way but paves the way for a future data replication pipeline

Add db secret arn to tf output

---

.github/workflows/lint.yml
db/migrate/20250429140846_remove_move_to_school_from_school_move_log_entries.rb
hk.pkl
spec/lib/reports/school_moves_exporter_spec.rb

This fixes a number of issues in our linting workflow which meant it wasn't working correctly, see individual commits for more details.

Fix issues in linting workflow

---

app/models/immunisation_import_row.rb
app/views/immunisation_imports/new.html.erb
config/feature_flags.yml
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

This feature is ready to be enabled for all users so we can remove the feature flag.

Remove SystmOne import feature flag

---

app/controllers/cohorts_controller.rb
spec/features/cohorts_index_spec.rb

They should show as year 8, year 9, ...

Programme cohorts should be sorted

---

docs/terraform.md
terraform/documentation/resource-modification-strategy.md

Update documentation to reflect process changes/updates

Terraform documentation

---

app/lib/reports/careplus_exporter.rb
spec/lib/reports/careplus_exporter_spec.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

CWPT CHIS requested another column for vaccine codes such as FLU, FLUENZ, HPV, 3IN1, ACWYX4 because they cannot upload via Snomed codes at the moment.
[JIRA Ticket](https://nhsd-jira.digital.nhs.uk/browse/MAV-1015)

Add vaccine code column to CarePlus vaccination reports

---

app/lib/reports/offline_session_exporter.rb

This PR significantly improves the performance of the offline session exporter. It addresses concerns that the "Record offline" function was taking too long (up to 10s) and if sessions get bigger (eg with flu) the threshold to cause timeouts will be reached, and it will not be possible for these spreadsheets to be generated by SAIS teams.
While most sessions will have around 1,000 patients, community clinic sessions could potentially contain up to 60,000 patients. For this special case, we may need to implement a background job in the future to handle the export asynchronously, but hopefully, this optimisation should handle the vast majority of use cases.
[JIRA Ticket](https://nhsd-jira.digital.nhs.uk/browse/MAV-994)
Key improvements:
- Added comprehensive eager loading for all required …

Optimise offline session exporter

---

.github/workflows/continuous-deployment.yml

* Set the required Github permissions

Fix continuous deployment

---

app/assets/stylesheets/_grid.scss

💅
| ------ | ----- |
| ![Before](https://github.com/user-attachments/assets/c029b22d-61e6-4b04-ada5-4555ec6d8d34) | ![After](https://github.com/user-attachments/assets/cd23f38a-33fa-4ab4-a5d1-9e9db32f1395) |

Fix alignment of filters with results

---

lib/generate/cohort_imports.rb
lib/generate/consents.rb
lib/generate/patient_imports.rb
lib/generate/vaccination_records.rb
spec/factories/locations.rb
spec/factories/patients.rb
spec/lib/generate/cohort_imports_spec.rb

Incremental changes as a result of using these recently. See commits for the changes.

Updates to the data generators

---

terraform/data_replication/env/production.tfvars
terraform/resources/github_data_replication_actions_policy.json

Also ensure we can access dynamoDB table for state management

Include account number in production variables

---

adr/00010-autoscaling-for-ecs.md

- Useful to document in repository why we have made specific decisions

Create ADR for autoscaling decisions

---

terraform/app/env/preview.tfvars

* We want to perform backups for at least one development environment to verify that the backup mechanism works as expected

Enable vault backups for Preview

---

terraform/account/README.md
terraform/account/env/development-backend.hcl
terraform/account/env/production-backend.hcl
terraform/account/main.tf

This policy will be linked to an Azure AD group in the https://github.com/NHSDigital/aws-prod-sso-config repository.

Add custom policy for data replication access

---

.github/workflows/deploy-infrastructure.yml

* This ensures that the workflow behaves similar for preview and production and potential issues would be spotted before the production deployment.

Update permissions for preview

---

terraform/app/env/training.tfvars

Use the newly issued certificates for the training environment

Update certificates for training

---

app/models/concerns/request_session_persistable.rb
spec/models/concerns/request_session_persistable_spec.rb

There seems to be an issue when dates are stored in the browser session where they will come back with the time zone information correctly, but when stored in a model object that calls `clear_changes_information` the time zone is stripped and we end up with a date time object in the server time. This is a problem in our deployed environments where the server time is UTC, and in daylight saving the users will see a date that is 1 hour out.
We need `clear_changes_information` as we use that in a number of places to render appropriate yellow tags when values have changed, but in this case when the model object is being first instanced, we don't want to display these as changes.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1002)

Ensure dates are deserialized with time zone

---

app/lib/mavis_cli.rb
app/lib/mavis_cli/gias/check_import.rb
app/lib/mavis_cli/gias/import.rb
spec/features/cli_gias_check_import_spec.rb
spec/features/cli_gias_import_spec.rb
spec/support/capture_output.rb

Predictably, I spotted these things after the initial release. None of these things are severe, however, we should be able to work around them.
[MAV-1257](https://nhsd-jira.digital.nhs.uk/browse/MAV-1257)

Updates and improvements to the gias-related cli commands

---

.github/workflows/deploy-infrastructure.yml
.github/workflows/deploy.yml
terraform/scripts/validate-github-actions-policy.sh

Also reformats the deploy/sub-workflow configuration to ensure scripts are in sync with the calling branch

Ensure output of permission validation action

---

.github/CODEOWNERS

This splits up the ownership of various parts of the repo by application or infrastructure devs.

Update code owners to match new team structure

---

app/controllers/api/organisations_controller.rb
spec/controllers/api/organisations_controller_spec.rb

Reverts nhsuk/manage-vaccinations-in-schools#3727
This made the regression tests more flaky because they're interdependent on each other in unexpected ways.

Revert "Update reset endpoint to delete organisations"

---

.github/dependabot.yml

See individual commits for more details.

Various updates to Dependabot configuration

---

.github/workflows/deploy.yml

- This was already updated for the update-permissions job but not for the validate-permissions job

Update file location in pipeline

---

app/components/app_card_component.rb
app/views/vaccines/index.html.erb
spec/components/app_card_component_spec.rb

This makes a number of small updates to the vaccines page to improve accessibility, by including more structure to the cards and adding more content to the accessible labels of the "Change" and "Archive" links.

Various accessibility updates to vaccines page

---

terraform/app/rds.tf
terraform/app/variables.tf

- When skip_final_snapshot is false an identifier for that snapshot must be given

Specify final snapshot name

---

terraform/app/rds.tf

This reverts commit 0d6f3bb25db97b42dd7b956560dcfebe13b79043 / #3856.

Reapply "Reduce frequency of secret rotation"

---

config/locales/en.yml

These show on the edit as summary screens.
JIRA: [MAV-1440](https://nhsd-jira.digital.nhs.uk/browse/MAV-1440)
Suggested in https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3848#issuecomment-3020255119

Use more accurate delivery method labels

---

app/components/app_activity_log_component.rb
spec/components/app_activity_log_component_spec.rb
spec/features/manage_children_spec.rb

This is https://nhsd-jira.digital.nhs.uk/browse/MAV-1241

Change activity title to "Added to session ____" 

---

app/models/draft_vaccination_record.rb
app/views/draft_vaccination_records/confirm.html.erb
spec/factories/patients.rb
spec/features/flu_vaccination_administered_spec.rb
spec/models/draft_vaccination_record_spec.rb

JIRA: [MAV-1461](https://nhsd-jira.digital.nhs.uk/browse/MAV-1461).

 Show warning when recording a vaccine delivery method that conflicts with the consent or triage

---

.github/workflows/lint.yml
app/components/app_vaccinate_form_component.html.erb
app/components/app_vaccinate_form_component.rb
app/forms/vaccinate_form.rb
spec/features/pre_screening_spec.rb

Ask about recent asthma flare ups in the pre-screening form for flu vaccinations, only when nasal spray is being administered. Also ask the medication question for all flu vaccinations
https://nhsd-jira.digital.nhs.uk/browse/MAV-1495

Add flu pre-screening questions

---

app/components/app_programme_status_tags_component.rb
app/components/app_triage_form_component.rb
app/forms/triage_form.rb
app/helpers/consents_helper.rb
app/models/draft_vaccination_record.rb
app/models/programme.rb
app/models/vaccine.rb

This makes a number of small changes to the code which handles vaccine and delivery methods to improve the readability and maintainability of the code. See individual commits for more details.

Refactor methods related to delivery and vaccine methods

---

app/components/app_patient_session_consent_component.html.erb
spec/components/app_patient_session_consent_component_spec.rb
spec/features/e2e_journey_spec.rb
spec/features/self_consent_spec.rb
spec/features/verbal_consent_but_no_triage_for_admin_spec.rb
spec/features/verbal_consent_change_answers_spec.rb
spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
spec/features/verbal_consent_given_do_not_vaccinate_spec.rb
spec/features/verbal_consent_given_keep_in_triage_spec.rb
spec/features/verbal_consent_given_safe_to_vaccinate_spec.rb
spec/features/verbal_consent_given_spec.rb
spec/features/verbal_consent_given_when_previously_refused_spec.rb
spec/features/verbal_consent_refused_personal_choice_spec.rb
spec/features/verbal_consent_refused_spec.rb

This is https://nhsd-jira.digital.nhs.uk/browse/MAV-1397

Rename get consent button

---

app/lib/reports/systm_one_exporter.rb
spec/lib/reports/systm_one_exporter_spec.rb

This  adds relevant mappings for nasal vaccinations.
The brand-specific vaccine codes have not been published yet, we will need to add these in later.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1114

SystmOne reports for flu

---

spec/features/identity_check_spec.rb
spec/models/organisation_spec.rb

This fixes a number of tests to improve reliability and reduce the need to re-run the test suite before merging in PRs or a deploy.

Fix flaky tests

---

app/controllers/application_controller.rb
app/controllers/batches_controller.rb
app/controllers/class_imports_controller.rb
app/controllers/cohort_imports_controller.rb
app/controllers/immunisation_imports_controller.rb
app/controllers/imports_controller.rb
app/controllers/organisations_controller.rb
app/controllers/patient_sessions/programmes_controller.rb
app/helpers/school_moves_helper.rb

This is a convenience helper method that can be used to determine the current selected organisation of the user who is signed in.

Add `ApplicationController#current_organisation`

---

app/lib/mavis_cli/generate/cohort_imports.rb
lib/generate/cohort_imports.rb
spec/features/cli_generate_cohort_imports_spec.rb

Add some ergonomics like a more sensible generated filename, ods code option and tests! \o/

Update cohort import filename

---

app/components/app_patient_programmes_table_component.rb
app/lib/status_generator/session.rb
app/lib/status_updater.rb
app/models/patient/vaccination_status.rb
db/migrate/20250814154032_add_status_changed_at_to_patient_vaccination_status.rb
db/schema.rb
spec/components/app_activity_log_component_spec.rb
spec/components/app_patient_programmes_table_component_spec.rb
spec/components/app_patient_session_search_result_card_component_spec.rb
spec/factories/patient_vaccination_statuses.rb
spec/factories/vaccination_records.rb
spec/features/vaccination_programmes_spec.rb
spec/lib/status_generator/session_spec.rb
spec/models/patient/vaccination_status_spec.rb
spec/models/patient_session_spec.rb

JIRA: [MAV-1754](https://nhsd-jira.digital.nhs.uk/browse/MAV-1754)

Fix patient programmes component to show same status as in programmes overview

---

app/components/app_patient_programmes_table_component.rb
config/locales/en.yml

This makes a number of small improvements to the vaccination programmes table shown on the patient page. See individual commits for more details.

Small improvements to vaccination programmes table

---

app/jobs/process_patient_changesets_job.rb

Previously, only the final PDS search result was persisted for a patient changeset when a slow import was processed. In-memory updates to `patient_changeset.search_results` will be lost between job executions if not explicitly saved in these cases.

Persist all PDS search results for patient changesets

---

app/forms/vaccinate_form.rb
app/lib/reports/systm_one_exporter.rb
app/models/draft_vaccination_record.rb
app/models/session.rb
app/models/vaccination_record.rb
config/locales/en.yml
spec/features/flu_vaccination_hca_national_protocol_spec.rb
spec/lib/reports/systm_one_exporter_spec.rb
spec/models/session_spec.rb

This is a branch that contains all the work related to delegation in scope for 3.5.0 so it can be deployed and tested together.
Includes:
- #4407 
- #4409

Delegation with national protocol and PSDs

---

app/forms/triage_form.rb
spec/features/triage_spec.rb
spec/features/verbal_consent_given_triage_psd_spec.rb

This fixes two issues related to delegation and the creation of PSDs that have been spotted by the testers, see individual commits for more details.

Small fixes for delegation

---

terraform/app/rds.tf

This PR enables logging and collecting execution plans for the PostgreSQL DB.
* Long-running queries that run longer than 1 second will be logged. The query parameters are excluded from the log message to avoid logging PID.
* The query execution plans are captured only in the Database Insights dashboard within AWS and are not logged, for the same reason. There is an interval of 5min until the same plan will be captured again
[Jira Issue - MAV-933](https://nhsd-jira.digital.nhs.uk/browse/MAV-933)

PostgreSQL logging

---

app/policies/patient_policy.rb

Move include check into a union CTE
- This allows SQL to use HashAggregate for grouping and checking patient_id.
- Previous setup looped over patients scaling as O(N) causing multi-second query times
[Jira Issue - MAV-1944](https://nhsd-jira.digital.nhs.uk/browse/MAV-1944)

Improve patient lookup speed

---

app/policies/vaccination_record_policy.rb

- EXIST makes use of Bitmap Index Scan on subquery eliminating ca. 500k loops
JIRA Ticket - [MAV-2001](https://nhsd-jira.digital.nhs.uk/browse/MAV-2001)

Replace IN loop with EXIST

---

app/jobs/invalidate_self_consents_job.rb
spec/jobs/invalidate_self_consents_job_spec.rb

If the patient was vaccinated after getting self-consent, we shouldn't invalidate that consent as it was valid when the vaccination was given. A future enhancement might be to add a concept of "lifespan" to consents, to capture exactly at which point they are invalid.
At the moment, the nurses see a patient that was vaccinated, with supposedly no valid consent, which is not accurate.
[Jira Issue - MAV-865](https://nhsd-jira.digital.nhs.uk/browse/MAV-865)

Don't invalidate self-consent if vaccinated

---

config/sidekiq.yml

Set incorrectly in original PR.

Fix schedule for enqueueing imms api searches

---

app/helpers/triages_helper.rb
app/lib/reports/offline_session_exporter.rb
spec/factories/patients.rb
spec/factories/triage.rb
spec/features/flu_vaccination_hca_pgd_supply_spec.rb
spec/lib/reports/offline_session_exporter_spec.rb

This brings consistency with the UI, and more importantly includes information about the vaccine method for flu vaccinations which is important for the right vaccination to be given.
JIRA: [MAV-2117](https://nhsd-jira.digital.nhs.uk/browse/MAV-2117)

Align the triage status between the Mavis UI and the offline spreadsheet

---

.github/workflows/deploy-application.yml

-Due to editing typo the app_version was not properly injected as a variable but instead just became a static string
JIRA Ticket: [MAV-1657](https://nhsd-jira.digital.nhs.uk/browse/MAV-1657)
- ...
- ...

fix app_version not properly injected

---

terraform/account/resources/iam_policy_DenyPIIAccess.json.tftpl

Deny deleting the policy as well as changing the policy version

Restrict policy permissions further

---

.github/workflows/deploy-application.yml

- Replace check with simpler solution
- ...
- ...

App_version was not picking up passed values

---

app/components/app_patient_search_form_component.rb

This was an oversight as the tallying feature is not ready to go live yet.

Put "Still to vaccinate" filter under tallying feature flag
