- app/components/app_session_summary_component.rb
- spec/components/app_session_summary_component_spec.rb
This adds a link to allow users to see the parental consent form for a particular session.
> Add link to parental consent form

- app/components/app_import_format_details_component.html.erb
- app/components/app_import_format_details_component.rb
As the content of this component is completely static and authored by us, there are no security implications to doing this by default. This prevents forgetting to mark something HTML-safe and having the formatting break.
> Fix guidance flippy rendering issues

- db/migrate/20240924112619_add_programme_to_consent_forms.rb
- db/migrate/20241002125816_add_team_to_consent_forms.rb
- db/migrate/20241002130716_add_school_to_consent_forms.rb
- db/migrate/20241015090951_add_team_to_batches.rb
The reference to `Team.first.id` breaks on an empty database because there are no teams.
> Update batches only if team exists

- spec/factories/vaccination_records.rb
This fixes an issue where creating vaccination records would end up creating new sessions to access the team, rather than using the patient session already available to us.
https://good-machine.sentry.io/issues/5995332908/
> Fix vaccination record factory creating locations

- app/models/class_import.rb
- app/models/cohort_import.rb
- app/models/concerns/csv_importable.rb
- app/models/immunisation_import.rb
- app/models/patient.rb
- app/models/session.rb
- spec/models/immunisation_import_spec.rb
When importing vaccination records for patients, we should remove those patients from any upcoming sessions so they don't get vaccinated twice.
> Remove patients from sessions if already vaccinated

- app/controllers/concerns/full_name_concern.rb
- app/views/patients/show.html.erb
- spec/models/patient_spec.rb
This is to avoid the patient name appearing in browser histories
> Patient page title: use patient initials instead of full name

- app/lib/nhs/api.rb
Currently the safety buffer is being taken away from the current date/time meaning we have more time available before the expiration than we think, instead we should be applying the safety buffer to the future so we're more likely to have expired.
> Fix NHS API expiration check

- app/lib/govuk_notify_personalisation.rb
- spec/lib/govuk_notify_personalisation_spec.rb
This adds some additional personalisation sent to GOV.UK Notify to allow us to customise the templates according to whether the patient is receiving the vaccine at the earliest year group or later.
> Add catch up personalisation

- spec/jobs/consent_form_matching_job_spec.rb
We get this functionality automatically now that the encrypted given and family name fields are set to ignore case, but it's good to add an explicit test for it.
> Add a test to ensure consent matches are case insensitive

- app/components/app_session_summary_component.rb
- spec/components/app_session_summary_component_spec.rb
Calling `govuk_link_to` with `new_tab: true` already adds "(opens in new tab)" to the link text, so adding it explicitly creates duplicate copy
> Fix microcopy duplication on the session page

- app/components/app_patient_page_component.html.erb
- app/components/app_patient_page_component.rb
- app/controllers/consents_controller.rb
- app/controllers/gillick_assessments_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations_controller.rb
- app/jobs/pds_lookup_job.rb
- app/models/concerns/patient_session_state_concern.rb
- app/models/gillick_assessment.rb
- app/models/patient_session.rb
- spec/factories/patient_sessions.rb
- spec/jobs/pds_lookup_job_spec.rb
If we look up the NHS number for a patient without an NHS number, and we end up finding an NHS number for which we already have a patient for, we need to merge the two patient records otherwise we'll end up with a unique constraint failure when trying to change the NHS number on the original patient.
> Merge patients when looking up NHS numbers

- app/components/app_session_patient_table_component.html.erb
- app/components/app_session_patient_table_component.rb
- app/controllers/concerns/patient_sorting_concern.rb
- app/controllers/consents_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations_controller.rb
- app/views/consent_forms/show.html.erb
- app/views/consents/index.html.erb
- app/views/triages/index.html.erb
- app/views/vaccinations/index.html.erb
- spec/components/app_session_patient_table_component_spec.rb
- spec/components/previews/app_session_patient_table_component_preview.rb
- spec/controllers/concerns/patient_sorting_concern_spec.rb
- spec/factories/patients.rb
- spec/features/patient_sorting_filtering_spec.rb
On tables where we show a list of patients, we want to show the year group and cohort rather than the date of birth as this is more useful for the nursing team, and matches our latest designs.
> Show year groups instead of date of birth

- app/models/patient_session.rb
- app/models/vaccine.rb
- spec/features/hpv_vaccination_administered_spec.rb
When recording a vaccination we should only pick from the active vaccines as nurses wouldn't be recording vaccinations using vaccines which have discontinued.
> Vaccinate using active vaccines

- spec/factories/programmes.rb
- spec/features/hpv_vaccination_default_batch_spec.rb
- spec/features/manage_batches_spec.rb
- spec/features/manage_vaccines_spec.rb
This trait no longer does anything different to hpv as we've removed the `batch_count` attribute on programmes and vaccines as batches are now linked to teams, so they need to be created outside of the vaccine and programmes.
> Remove hpv_no_batches trait

- config/locales/en.yml
> Add missing message for invalid batch name

- app/views/parent_interface/consent_forms/_confirmation_agreed.html.erb
- config/locales/en.yml
The SAIS team might make multiple visits to the school and there's no guarantee that the child will be vaccinated on a particular date.
> Remove the reference to date on consent response confirmation

- app/controllers/concerns/patient_sorting_concern.rb
This method isn't being used so it can be safely removed.
> Remove PatientSortingConcern#deep_send

- app/models/batch.rb
- config/locales/en.yml
- spec/models/batch_spec.rb
There is already an index on these attributes so this prevents a crash.
> Validate for batch uniqueness

- app/jobs/patient_update_from_pds_job.rb
- app/models/concerns/csv_importable.rb
- spec/features/dev_reset_team_spec.rb
- spec/features/e2e_journey_spec.rb
- spec/features/import_vaccination_records_with_duplicates_spec.rb
- spec/jobs/patient_update_from_pds_job_spec.rb
- spec/models/class_import_spec.rb
- spec/models/cohort_import_spec.rb
- spec/models/immunisation_import_spec.rb
When importing patients, if we have an NHS number for the patient already then we can enqueue these jobs to check in PDS that the patient doesn't have any flags set on them such as restricted, or to check that they're not deceased.
To simplify some of the feature tests, I've removed a call to run enqueued jobs, which works because the files we're uploading aren't big enough to trigger the import running in the background.
> Update all patients from PDS when importing

- db/seeds.rb
This helps anchor automated testing to known data
> Add a specific school to seeded teams, if that school exists in the DB

- app/controllers/patients_controller.rb
- app/views/patients/show.html.erb
- config/routes.rb
- spec/features/manage_children_spec.rb
This adds the functionality from the prototype that allows nurses to remove patients from cohorts if they don't belong there.
> Add ability to remove patients from cohorts

- app/jobs/patient_update_from_pds_job.rb
- spec/jobs/patient_update_from_pds_job_spec.rb
See https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir/pds-fhir-technical-conformance---application-restricted-access-mode#invalidated-patient-records
> Skip further PDS checks for invalidated patients, until invalidation cleared

- app/lib/nhs/api.rb
This increases the buffer of time before requesting a new access token when using the NHS APIs to prevent us being caught by forbidden response errors if the connection takes longer than the safety buffer.
> Increase safety buffer when using NHS APIs

- app/components/app_consent_patient_summary_component.rb
- app/models/consent.rb
- app/views/consents/show.html.erb
- app/views/manage_consents/confirm.html.erb
- spec/components/app_consent_patient_summary_component_spec.rb
This follows on from #2068 to hide GP information for any restricted patients as they should not be visible to any users.
> Hide GP information for restricted patients

- app/components/app_patient_page_component.html.erb
- app/controllers/application_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations/edit_controller.rb
- app/controllers/vaccinations_controller.rb
- app/models/user.rb
- app/policies/application_policy.rb
- app/policies/batch_policy.rb
- app/policies/class_import_policy.rb
- app/policies/cohort_import_policy.rb
- app/policies/cohort_policy.rb
- app/policies/consent_form_policy.rb
- app/policies/consent_policy.rb
- app/policies/immunisation_import_policy.rb
- app/policies/location_policy.rb
- app/policies/patient_policy.rb
- app/policies/patient_session_policy.rb
- app/policies/programme_policy.rb
- app/policies/session_policy.rb
- app/policies/triage_policy.rb
- app/policies/user_policy.rb
- app/policies/vaccination_record_policy.rb
- app/policies/vaccine_policy.rb
- spec/components/app_patient_page_component_spec.rb
Users receive a role from the CIS2 callback that gives them certain privileges in Mavis. This sets up the controller to assign the `session` hash to an `attr_accessor` on the user that we can then parse to figure out a user's role.
Then the `is_nurse?` and `is_medical_secretary?` methods can be used in the policies to decide if a user is allowed to perform certain actions.
Parts that are missing in this initial implementation:
- Restricting Mavis so that users with *only* the R8001 or R8006 role have access (currently access control is only enforced for Triage and Vaccination routes)
- Restricting access by `org_code` from `session["cis2_info"]`
> Use session CIS2 roles to authorize user

- app/controllers/patients_controller.rb
- spec/features/manage_children_spec.rb
Removing a patient from the cohort could mean that the patient is no longer visible to the team. In those cases, redirect to the list of patients rather than showing a 404 page.
> Avoid redirecting to 404 after cohort removal

- app/views/sessions/show.html.erb
This aligns the design of the cards to the prototype.
> Stretch sessions show cards to full width

- app/models/class_import.rb
- app/models/consent_form.rb
- app/models/immunisation_import.rb
- app/models/patient.rb
- app/models/patient_session.rb
- app/models/session.rb
- spec/models/class_import_spec.rb
If the patient session has been interacted with in some way (either consent received, or triaged, or even vaccinated) we can't safely remove the patient from the session as it's unclear what state they're in.
https://good-machine.sentry.io/issues/5990842901
> Don't always remove patients from sessions

- app/components/app_patient_summary_component.rb
- app/models/parent.rb
- app/views/manage_consents/who.html.erb
- spec/models/parent_spec.rb
This updates the wording to match the latest designs in the prototype.
> Update wording when parent name is unknown

- app/lib/unscheduled_sessions_factory.rb
- app/models/immunisation_import_row.rb
- app/models/location.rb
- db/seeds.rb
- lib/tasks/teams.rake
- spec/components/app_session_summary_component_spec.rb
- spec/factories/locations.rb
- spec/factories/patient_sessions.rb
- spec/factories/teams.rb
- spec/lib/unscheduled_sessions_factory_spec.rb
- spec/models/dps_export_row_spec.rb
- spec/models/location_spec.rb
- spec/models/patient_spec.rb
This makes a number of changes to the clinic locations to split them up in to two types (generic clinics as we had before and community clinics), this distinction doesn't necessarily change the behaviour but it makes it easier for us to track the two types of clinics in the future. I've also ensured that when creating a team we get one generic clinic, and that a unscheduled session is created for it each academic year.
This replaces #2085.
> Create a single generic clinic per team

- app/controllers/users/omniauth_callbacks_controller.rb
- config/initializers/devise.rb
- config/settings.yml
- config/settings/staging.yml
- db/seeds.rb
Enables MS Authentication by default when requesting authentication from CIS2.
Additionally, this changes the ODS code we use in seeds to line up with the testing ODS code NHS recomments, `A9A5A`. UUIDs should be associated with this Org in CIS2.
Deployment plan:
- Deploy to test environment (automatic on PR merge)
- Configure and enable CIS2 in the test environment to test that it works
- Update ODS code `Y51` -> `A9A5A`
- Deploy to pentest env
- Configure in pentest env
- Update ODS code `Y51` -> `A9A5A`
- Confirm with pentesters that they've setup their CIS2 UUIDs
- Enable in pentest env
> Allow users to be authenticated with MS Auth

- copilot/webapp/manifest.yml
This allows us to make a distinction between the different deployed environments that all use the same `RAILS_ENV` when looking at issues in Sentry as they will show that they are coming from the correct environment.
Once deployed we'll need to update our alerting to send a message from these new environments rather than `staging` which will no longer exist.
> Specify Sentry environment

- app/lib/nhs/pds.rb
- spec/fixtures/files/pds/invalid-nhs-number-response.json
- spec/lib/nhs/pds_spec.rb
If we get this error from the PDS API, this raises a more approriate exception that we can then choose to handle ourselves or ignore.
https://good-machine.sentry.io/issues/6001980138/
> Handle INVALID_RESOURCE_ID error

- app/controllers/pages_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- config/routes.rb
- spec/features/cis2_backchannel_logout_spec.rb
The logout and jwks endpoints will be called by CIS2 and should not be behind basic auth.
Also tidies up the routes a little:
```
user_cis2_omniauth_authorize GET|POST /users/auth/cis2(.:format)                                                                        users/omniauth_callbacks#passthru
user_cis2_omniauth_callback GET|POST /users/auth/cis2/callback(.:format)                                                               users/omniauth_callbacks#cis2
users_auth_cis2_backchannel_logout POST     /users/auth/cis2/backchannel_logout(.:format)                                                     users/omniauth_callbacks#cis2_logout
```
> OIDC wants to be free! (unauthenticated)

- app/controllers/programmes_controller.rb
- app/controllers/sessions_controller.rb
- app/helpers/sessions_helper.rb
- app/models/session.rb
- app/views/programmes/sessions.html.erb
- app/views/sessions/closed.html.erb
- app/views/sessions/completed.html.erb
- app/views/sessions/index.html.erb
- app/views/sessions/scheduled.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/factories/sessions.rb
- spec/helpers/sessions_helper_spec.rb
- spec/models/class_import_spec.rb
- spec/models/cohort_import_spec.rb
- spec/models/session_spec.rb
This partially reverts eabbb6c6c95eeecbe5fbe790d24d09a90caafdc4 by splitting the "Completed" state in to two separate "Completed" and "Closed" states. Completed means that there are no more upcoming dates, but only once someone has pressed the "Close session" button does it move to the closed state.
> Split completed sessions in to completed and closed

- app/models/consent.rb
- app/models/consent_form.rb
- app/models/parent.rb
- app/models/patient_import_row.rb
- spec/models/consent_spec.rb
This updates how we match on existing parents to make the process more robust by looking for matching email addresses, names and phone numbers both when importing new records and when matching consent forms with patients.
> Make parent duplication matching more robust

- app/models/class_import.rb
- app/models/immunisation_import_row.rb
- app/models/location.rb
- app/models/session.rb
- app/models/team.rb
- lib/tasks/teams.rake
- spec/models/class_import_spec.rb
- spec/models/session_spec.rb
This adds the functionality to add home educated and unknown patients to the generic clinic under the following circumstances:
- When importing the cohort
- When importing a class list and moving unknown patients out of the school
- When closing a session
> Add home educated and unknown patients to the generic clinic

- app/models/patient_import_row.rb
- app/models/patient_session.rb
- app/models/session.rb
- db/migrate/20241022064010_add_proposed_session_id_to_patient_sessions.rb
- db/schema.rb
- spec/factories/patient_sessions.rb
- spec/models/class_import_spec.rb
- spec/models/patient_session_spec.rb
- spec/models/session_spec.rb
This updates the `Session#create_patient_sessions!` method so that instead of destroying the patient sessions for patients in this cohort that are in other sessions, it proposes their transfer to the new session.
A follow-up PR will implement the interface from the prototype on the actual sessions to surface and handle these `proposed_session`s.
> Transfer patients from other sessions

- app/controllers/sessions_controller.rb
- app/models/patient.rb
- app/models/session.rb
- app/views/sessions/close.html.erb
- app/views/sessions/show.html.erb
- config/routes.rb
- db/seeds.rb
- spec/features/manage_sessions_spec.rb
- spec/models/session_spec.rb
This adds a button which is shown when a session is complete that allows the user to close the session, and if necessary, move any outstanding patients to the generic clinic for that team.
> Add "Close session" functionality

- app/models/patient_import.rb
This should fix https://good-machine.sentry.io/issues/6012276805/ where if we import a file that contains the same parent relationship multiple times we end up raising an error. This was unlikely to happen before, but we no longer require parent names and relationships to be in the import so it's more likely to occur now.
This effectively re-implements the same behaviour from before we switched to `activerecord-import`, where only the latest row is saved to the database. We don't have this problem with patients and parents as we use a `Set` which prevents the same objects from being imported, however for the `ParentRelationship` model we have a unique constraint on the parent and patient IDs, which isn't de-duplicated by using a `Set` so we have to do it manually.
> Only import unique relationships

- app/lib/unscheduled_sessions_factory.rb
- lib/tasks/clinics.rake
- spec/lib/unscheduled_sessions_factory_spec.rb
Although these location types exist in the service we don't currently handle them correctly and shouldn't be creating sessions for them.
> Don't create sessions for community clinics

- script/generate_model_office_data.rb
This updates the scripts for the model office to generate class lists, and fixes a bug where importing the class list would remove the NHS numbers (and other attributes) of any patients that we already know about.
> Generate class lists for model office

- app/models/patient_import_row.rb
- spec/models/class_import_row_spec.rb
When we importing patient information, we should keep any information that we already know about patients, like their NHS number, rather than deleting it if the NHS numbers aren't provided in the import.
This is already handled correct when importing immunisations as the `stage_changes` method checks if there's a value before proposing it as a change.
> Keep information already known about patients

- app/controllers/session_moves_controller.rb
- app/models/patient_session.rb
- app/models/session.rb
- app/views/session_moves/index.html.erb
- app/views/sessions/show.html.erb
- config/routes.rb
- spec/features/import_class_lists_move_spec.rb
- spec/models/patient_session_spec.rb
This allows nurses to transfer patients from one session to another after they upload a class list.
TODO:
> Add UI to handle proposed sessions 

- README.md
- app/controllers/concerns/authentication_concern.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
- app/views/application/_header.html.erb
- app/views/pages/start.html.erb
- config/initializers/devise.rb
- config/routes.rb
- config/settings.yml
- spec/features/cis2_backchannel_logout_spec.rb
- spec/features/user_cis2_authentication_from_start_page_spec.rb
- spec/features/user_cis2_authentication_with_redirect_spec.rb
- spec/features/user_cis2_authentication_with_wrong_role_spec.rb
- spec/features/user_cis2_authentication_with_wrong_team_spec.rb
- spec/spec_helper.rb
This has wider reaching changesa as it means only one of database_authenticatable or omniauth_authenticatable is in effect at any one time, depending on whether CIS2 is on or off. The benefit is when in CIS2 mode Mavis should be more secure.
> Control cis2 with a setting vs feature flag

- app/controllers/gillick_assessments_controller.rb
- app/controllers/vaccinations/edit_controller.rb
- app/models/concerns/location_name_concern.rb
- app/models/gillick_assessment.rb
- app/models/patient_session.rb
- app/models/vaccination_record.rb
- app/views/gillick_assessments/location.html.erb
- app/views/vaccinations/edit/location.html.erb
- config/locales/en.yml
- spec/factories/locations.rb
- spec/factories/patients.rb
- spec/features/hpv_vaccination_clinic_spec.rb
- spec/features/manage_sessions_spec.rb
- spec/features/self_consent_clinic_spec.rb
This updates the vaccination workflow to ask the user to specify where the vaccination happened if it's being recorded against a generic clinic. They are presented with a list of community clinics for that team, and required to pick from the list.
This flow is also applied to gillick assessments, although not currently in the designs, and there's still a question around whether we'll actually need this functionality, but we can remove it later.
I've based the feature tests on the existing ones but they could probably be refactored and tidied up at some point later.
> Allow users to specify location when recording vaccinations

- app/components/app_activity_log_component.rb
- app/components/app_consent_component.html.erb
- app/components/app_consent_component.rb
- app/controllers/patient_sessions_controller.rb
- app/jobs/consent_reminders_job.rb
- app/jobs/consent_requests_job.rb
- app/jobs/session_reminders_job.rb
- app/models/session.rb
- config/routes.rb
- spec/components/app_activity_log_component_spec.rb
- spec/components/app_consent_component_spec.rb
- spec/components/app_patient_page_component_spec.rb
- spec/factories/sessions.rb
- spec/features/parental_consent_send_request_spec.rb
- spec/jobs/consent_reminders_job_spec.rb
- spec/jobs/consent_requests_job_spec.rb
- spec/jobs/session_reminders_job_spec.rb
This adds the ability to manually send a consent request to the parents of a patient, this is most relevant for clinics but will also be available in school sessions.
We show to the user if a request has already been sent out, and when that was, so they can make a decision on whether to re-send the request.
> Add "Send consent request" functionality

- app/views/patient_sessions/log.html.erb
The name is PII that shouldn't be left in SAIS team's browser history
> Display patient's initials instead of full name in activity log page title

- app/models/patient_import_row.rb
- spec/models/class_import_row_spec.rb
This follows on from 350e97cc4cfda1c492d46fc5fb442f615714139d to ensure that we don't replace the gender code of a patient if we're importing new information and we match with an existing patient and there's no gender information available.
> Don't replace patient's gender if already known

- app/mailers/consent_mailer.rb
- app/models/consent_notification.rb
- config/initializers/govuk_notify.rb
- spec/features/parental_consent_send_request_spec.rb
- spec/mailers/consent_mailer_spec.rb
- spec/models/consent_notification_spec.rb
This adds a custom email that we send when request consent for a clinic, which is triggered manually once someone has booked on to the clinic.
The template already exists in GOV.UK Notify.
> Add consent requests for clinics

- config/routes.rb
This was configured accidentally in connection manager, and changes are only applied during business hours. So in order to test this tonight, this is being temporarily added.
> Add /oidc/jwks_uri endpoint

- app/controllers/manage_consents_controller.rb
- spec/features/verbal_consent_refused_spec.rb
When a SAIS team member was recording a refusal from a parent/guardian (likely verbal or paper), Mavis was inappropriately displaying that that staff member had made a decision not to vaccinate that patient, when in fact the staff member had not actually taken that decision.
Under the hood, this was happening as a result of a 'do not vaccinate' triage decision being recorded automatically, in addition to the consent refusal.
This change aligns Mavis consent refusals with refusals through the parent form. 
It reverses the change introduced in https://github.com/nhsuk/manage-vaccinations-in-schools/pull/1108 (commit 8a7c186c41496c740de2fd09b28d64c3b13aaa11) – I'm not sure why we made that decision at the time.
> Incorrect status shown when a SAIS team member records a refusal

- app/models/class_import.rb
- app/models/patient_session.rb
- app/views/session_moves/index.html.erb
- spec/models/class_import_spec.rb
- spec/models/patient_session_spec.rb
When users upload a class list, instead of automatically moving patients to the generic clinic, propose their move to that session.
Also update the heading/content for the column to be accurate (before it was always "School joined from" in both tabs which is wrong).
> Propose move to generic clinic when uploading class list

- app/controllers/parent_interface/consent_forms_controller.rb
- app/views/parent_interface/consent_forms/cannot_consent_responsibility.html.erb
The consent form session is dynamic depending on when the parent is filling out consent, so it's safer to get the team from the consent form directly.
> Tidy references to consent form session

- app/models/pds/patient.rb
- spec/models/pds/patient_spec.rb
In rare scenarios this is not available to us and can lead to an error. Since we're not currently using it anywhere we can safely remove it from the `PDS::Patient` model.
https://good-machine.sentry.io/issues/6016479502/
> Don't get given name from PDS

- app/models/concerns/csv_importable.rb
- config/settings/development.yml
- config/settings/production.yml
- config/settings/staging.yml
- config/settings/test.yml
This stops us from queueing jobs to PDS in the development environment as we likely don't have an API key configured and it's going to fail anyway.
> Don't queue PDS jobs in development

- app/jobs/concerns/merge_patients_concern.rb
- spec/jobs/patient_nhs_number_lookup_job_spec.rb
We were calling `update_all` and passing in a patient session which is not supported, and there was no test for this scenario so it wasn't caught.
https://good-machine.sentry.io/issues/6016479286/
> Fix patient merge when patient session already exists

- app/jobs/clinic_session_invitations_job.rb
- app/jobs/school_session_reminders_job.rb
- app/models/patient_session.rb
- app/models/session.rb
- spec/jobs/clinic_session_invitations_job_spec.rb
Instead of only sending the invitations exactly 3 weeks before each date, we will instead repeatedly try to send these notifications each day, which allows patients that have been newly added to the community clinic to receive an invitiation as soon as possible (i.e. the next morning).
The reminders will be sent automatically once a session date has passed, meaning we should know by then if a patient was vaccinated or not and avoid sending unnecessary emails.
> Change logic for clinic invitations

- app/components/app_outcome_banner_component.rb
- app/models/vaccination_record.rb
- spec/components/app_outcome_banner_component_spec.rb
Sometimes this won't be available, specifically for historical records, if we've imported HPV records we don't always have a record of who performed the vaccination so we should handle this gracefully.
https://good-machine.sentry.io/issues/5858514071/
> Render outcome banner with no clinician

- app/controllers/vaccinations/edit_controller.rb
- app/controllers/vaccinations_controller.rb
It could have been archived in the mean time, and that would result in it not being found, instead we can return `nil` which requires the nurse to choose a new batch.
> Don't return 404 is today's batch not found

- app/views/session_dates/show.html.erb
This updates the view to manage session dates to allow deleting the first date if it's been added to the session, whereas currently the delete button is hidden.
> Make it possible to delete all session dates

- app/components/app_activity_log_component.rb
- app/models/session_notification.rb
- spec/components/app_activity_log_component_spec.rb
We already show session notifications, but the wording is incorrect for clinic invitations.
> Show clinic invitations in activity log

- app/components/app_activity_log_component.rb
- spec/components/app_activity_log_component_spec.rb
This follows on from 2c352edb7fbe35bef370ae93ffe87077df5070af to support rendering the activity log when we don't have a clinician available.
> Handle no clinician for vaccination events

- app/models/consent_notification.rb
- app/models/session_notification.rb
- config/initializers/govuk_notify.rb
- spec/features/parental_consent_send_request_spec.rb
- spec/models/consent_notification_spec.rb
- spec/models/session_notification_spec.rb
This adds three text messages that are sent when we send out invitations for booking in to a clinic, and when manual requests for consent are sent.
> Add texts for clinics

- app/views/manage_consents/who.html.erb
This avoids the word "or" appearing on its own which looks odd.
> Hide radio divider if there are no parents

- app/components/app_consent_component.html.erb
- app/components/app_consent_component.rb
The "Send consent request" button currently shows even in situations where it doesn't necessarily make sense to. Even though we wouldn't send an email in these cases, it doesn't make sense to give the user the option to.
> Hide "Send consent request" button if approriate

- app/components/app_triage_form_component.html.erb
- app/controllers/concerns/triage_mailer_concern.rb
- app/controllers/manage_consents_controller.rb
- app/controllers/triages_controller.rb
- app/mailers/triage_mailer.rb
- app/models/triage.rb
- config/initializers/govuk_notify.rb
- spec/controllers/concerns/triage_mailer_concern_spec.rb
- spec/features/triage_delay_vaccination_spec.rb
- spec/features/triage_spec.rb
- spec/mailers/triage_mailer_spec.rb
- spec/models/triage_spec.rb
If a nurse chooses a "Delay vaccination" outcome, this triggers an email to go out to the parents requesting them to book in to a clinic, and adds the patient to the session for the generic clinic.
> Handle delay vaccination by inviting the patient to a clinic

- spec/factories/consent_forms.rb
> Fix typo in consent forms factory

- app/models/consent_form.rb
- config/initializers/i18n_nhs_design_system_date_interpolation.rb
- config/locales/en.yml
- spec/models/consent_form_spec.rb
* Format dates in ActiveRecord validation error messages; show D MMM YYYY format, instead of YYYY-MM-DD. This is applied globally
* Some attribute-specific validation fixes on children's dates of birth on the consent form, and on session date validations
Best reviewed commit-by-commit.
> Date validation fixes

- app/lib/govuk_notify_personalisation.rb
- spec/lib/govuk_notify_personalisation_spec.rb
If the parent has told us that their child goes to a different school, we need to show that new school (and it's approriate session) in the emails and texts.
> Use actual session in consent notifications

- app/controllers/application_controller.rb
- app/controllers/concerns/authentication_concern.rb
- app/models/user.rb
- spec/controllers/concerns/authentication_concern_spec.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/support/cis2_context_helper.rb
This commit has been pulled out of a larger piece of work to make team-based authorisation work in CIS2-mode.
This is a small refactoring designed to make things a little clearer. We only have one SSO at the moment, so calling it CIS2 makes it clear what that means. This may change if we ever adopt another SSO.
Also adds testing around the related functionality with accomodation for CIS2 being enabled.
> Refactor sso_session into cis2_info, add specs

- app/models/user.rb
- app/policies/application_policy.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
This commit has been pulled out of a larger piece of work to make team-based authorisation work in CIS2-mode.
We generally use "admin" instead of "medical secretary", so this change brings it closer to that. But also, medical secretary may be only one of the NHS RBAC roles that qualifies for the "admin [staff]" role in Mavis.
> Rename medical_staff to admin_staff

- app/models/concerns/csv_importable.rb
- spec/features/import_child_records_spec.rb
- spec/features/import_class_lists_spec.rb
- spec/fixtures/class_import/valid.csv
- spec/fixtures/cohort_import/valid.csv
- spec/fixtures/immunisation_import/valid_flu.csv
- spec/fixtures/immunisation_import/valid_hpv.csv
If the CSV import encounters a trailing row that's completely blank then it's likely that this was an attempt to remove the row by the user, but rather than remove the row they removed all the values in the row. We should treat this as though the row isn't there and not import it.
> Ignore trailing blank rows when importing CSV files

- lib/tasks/vaccines.rake
- spec/factories/health_questions.rb
- spec/factories/vaccines.rb
- spec/features/e2e_journey_spec.rb
- spec/features/verbal_consent_but_no_triage_for_admin_spec.rb
- spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
- spec/features/verbal_consent_given_do_not_vaccinate_spec.rb
- spec/features/verbal_consent_given_keep_in_triage_spec.rb
- spec/features/verbal_consent_given_safe_to_vaccinate_spec.rb
- spec/features/verbal_consent_given_spec.rb
- spec/features/verbal_consent_given_when_previously_refused_spec.rb
This adds the health question "Does your child need extra support during vaccination sessions?" that exists in the prototype and paper consent form but not yet in the service.
> Add extra support health question

- app/controllers/batches_controller.rb
- app/controllers/class_imports_controller.rb
- app/controllers/cohort_imports_controller.rb
- app/controllers/immunisation_imports_controller.rb
- app/controllers/imports_controller.rb
- app/controllers/teams_controller.rb
- app/models/user.rb
- app/policies/batch_policy.rb
- app/policies/class_import_policy.rb
- app/policies/cohort_import_policy.rb
- app/policies/cohort_policy.rb
- app/policies/consent_form_policy.rb
- app/policies/consent_policy.rb
- app/policies/immunisation_import_policy.rb
- app/policies/location_policy.rb
- app/policies/patient_policy.rb
- app/policies/patient_session_policy.rb
- app/policies/programme_policy.rb
- app/policies/session_policy.rb
- app/policies/triage_policy.rb
- app/policies/vaccination_record_policy.rb
- app/views/cohorts/index.html.erb
- app/views/import_issues/index.html.erb
- app/views/imports/index.html.erb
- app/views/programmes/sessions.html.erb
- app/views/programmes/show.html.erb
- app/views/vaccination_records/index.html.erb
- spec/features/parental_consent_send_request_spec.rb
- spec/models/user_spec.rb
This commit has been pulled out of a larger piece of work to make team-based authorisation work in CIS2-mode.
Users select a team when they authenticate with CIS2, and should only see data related the selected team. We don't have a mechanism to do this with the current password login, so we still support the old 'teams.first' in those (non-production) environments where we don't use CIS2. We can decide whether we want to be smarter about that later.
> Authorise CIS2 users based on their team

- app/controllers/cohort_imports_controller.rb
- app/controllers/cohorts_controller.rb
- app/controllers/immunisation_imports/duplicates_controller.rb
- app/controllers/immunisation_imports_controller.rb
- app/controllers/import_issues_controller.rb
- app/controllers/imports_controller.rb
- app/controllers/parent_interface/consent_forms_controller.rb
- app/controllers/programmes_controller.rb
- app/controllers/vaccination_records/edit_controller.rb
- app/controllers/vaccination_records_controller.rb
- app/models/programme.rb
- app/views/parent_interface/consent_forms/start.html.erb
- config/routes.rb
- spec/features/user_authorisation_spec.rb
- spec/lib/govuk_notify_personalisation_spec.rb
This improves the readability of our URLs by using the programme type (which is a unique string either `hpv` or `flu`) instead of the ID which is an auto-incrementing integer.
The main advantage of this is when it comes to sharing links to consent forms for patients, the phrase `hpv` or `flu` will appear in the URL, meaning they're easier to type out if they're copying the link from a text.
> Use programme type instead of ID in URLs

- app/controllers/session_dates_controller.rb
This applies a similar change to 9ae1c594b904c2f5826027e3e6dcc64db7f5f969 to session dates to avoid a crash and instead show a validation error.
> Handle invalid session dates gracefully

- app/jobs/patient_update_from_pds_job.rb
This makes it explicit that we can safely discard this job on a number of errors from the PDS API where retrying the job is guaranteed not to succeed, specifically where the NHS number is invalid or doesn't exist.
> Discard PatientUpdateFromPDSJob on errors

- app/controllers/users/omniauth_callbacks_controller.rb
We've had some issues where an exception is raised while we process smartcard logisn. This should help us debug them better.
> Log id token when cis2 auth errors

- app/jobs/bulk_update_patients_from_pds_job.rb
- app/jobs/patient_update_from_pds_job.rb
- app/lib/nhs/pds.rb
- app/models/concerns/csv_importable.rb
- app/models/patient.rb
- config/environments/production.rb
- config/environments/staging.rb
- spec/fixtures/files/pds/not-found-patient-response.json
- spec/jobs/bulk_update_patients_from_pds_job_spec.rb
- spec/lib/nhs/pds_spec.rb
This adds a job which regularly queues jobs to fetch information from PDS about patients to ensure they stay up to date and accurate.
> Add BulkUpdatePatientsFromPDSJob

- app/jobs/school_consent_reminders_job.rb
The ordering on the association doesn't work when the association is included when requesting the parent object.
> Order session dates in consent reminder job

- app/controllers/session_dates_controller.rb
- app/controllers/sessions/edit_controller.rb
- app/models/session.rb
- app/views/sessions/edit.html.erb
- app/views/sessions/edit/send_consent_requests_at.html.erb
- app/views/sessions/edit/weeks_before_consent_reminders.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/manage_sessions_spec.rb
This adds the ability to edit the consent request and reminder dates of a session after the dates have been added to the session, beyond the defaults.
> Allow editing consent request and reminder dates

- app/jobs/clinic_session_invitations_job.rb
- app/jobs/school_consent_reminders_job.rb
We can't join on the dates as there can be more than one which would result in the same session being returned multiple times for different dates.
> Force preload on session dates rather than a join

- app/jobs/clinic_session_invitations_job.rb
- app/jobs/school_consent_reminders_job.rb
- app/jobs/school_consent_requests_job.rb
- app/jobs/school_session_reminders_job.rb
- config/environments/staging.rb
- spec/jobs/clinic_session_invitations_job_spec.rb
- spec/jobs/school_consent_reminders_job_spec.rb
- spec/jobs/school_consent_requests_job_spec.rb
- spec/jobs/school_session_reminders_job_spec.rb
This ensures the configuration for our scheduled emails is set up in all our deployed environments, not just production, allowing us to easily test the scheduled emails.
> Schedule emails in staging environments

- app/models/session.rb
- spec/models/session_spec.rb
This allows users to submit consent on the last day of the consent period, which is the day before the last session date. This matches up with the wording in our email which implies the user has until this date to submit consent.
> Allow submitting consent on last day of consent period

- app/lib/nhs/api.rb
- spec/lib/nhs/api_spec.rb
This refactors the implementation to rely on our server time, in case there's a mismatch between the API server time and our local server time. It also simplifies the code by using seconds everywhere rather than needing to convert between seconds and milliseconds.
I'm hoping this will fix the 401 errors we've been seeing when using the API.
> Refactor access token expiration calculation

- app/jobs/application_job.rb
If we get this error it means the object that the job was queued for no longer exists in the database, so we can safely discard the job as it will never succeed.
> Discard jobs on ActiveJob::DeserializationError

- app/models/class_import.rb
- spec/models/class_import_spec.rb
This handles the situation where a patient already has a proposed move from a different import that hasn't been confirmed yet, we wouldn't want to overwrite that proposed move to the generic clinic when it's likely they're being moved to a school.
> Don't propose moves if already proposed

- app/models/consent_form.rb
- app/models/patient.rb
- spec/models/consent_form_spec.rb
This updates how school moves are handled after the consent forms, to propose the move rather than actually perform the move. This means the nurses are required to confirm the move as it will be shown in the "moves in" and "moves out" tabs on the sessions.
> Propose moves from consent forms

- app/models/patient_session.rb
There's a unique constraint on patient sessions which means this will fail if the patient was added to the proposed session in the meantime before the move was confirmed.
> Find or create patient sessions

- app/components/app_consent_refused_table_component.html.erb
- app/components/app_consent_refused_table_component.rb
- app/controllers/programmes_controller.rb
- app/views/programmes/show.html.erb
- spec/components/app_consent_refused_table_component_spec.rb
This adds a table showing the reasons for consent refusal.
> Add table of consent refused statistics

- app/models/session.rb
- app/views/sessions/edit.html.erb
- spec/features/e2e_journey_spec.rb
This allows users to see when the next consent reminder is going to be sent rather than just the first one. I have changed the label from `First` to `Next` which is different to how this appears in the designs.
> Show next consent reminder instead of first

- app/controllers/concerns/full_name_concern.rb
- spec/models/patient_spec.rb
This updates the `order_by_name` scope used in a few places to be case-insensitive which is more useful for users. This is possible now that the fields are no longer encrypted (#2226).
> Order names ignoring case

- app/assets/stylesheets/_patients.scss
- app/assets/stylesheets/_search.scss
- app/assets/stylesheets/application.scss
- app/components/app_patient_table_component.rb
- app/controllers/patients_controller.rb
- app/models/patient.rb
- app/views/patients/index.html.erb
- spec/features/patient_search_spec.rb
This adds a form and updates the index action to use a new `Patient#search_by_name` method. The method uses [trigram indexing](https://www.postgresql.org/docs/current/pgtrgm.html) to do fuzzy match searching if there are 3 or more letters, and regular `ILIKE` if not.
> Add patient search functionality

- app/views/patients/index.html.erb
This enhances the form to replace the content of the page using Turbo, which makes the interaction feel snappier. It still requires manually hitting enter or submitting.
> Use turbo for patient search form

- app/components/app_programme_session_table_component.html.erb
- app/components/app_programme_session_table_component.rb
- app/controllers/programmes_controller.rb
- app/models/session.rb
- app/views/programmes/sessions.html.erb
- spec/components/app_programme_session_table_component_spec.rb
This adds a new table component which is rendered on the sessions page for each programme as per the designs in the prototype. It allows the user to see useful headline stats about each session.
> Add programme session table

- config/initializers/devise.rb
This will require that users re-authenticate with CIS2 every time they logout from Mavis.
> Disable the max-age=300 with CIS2 auth

- app/controllers/programmes_controller.rb
- app/models/patient_session_stats.rb
- app/views/programmes/show.html.erb
- spec/models/patient_session_stats_spec.rb
This adds a new statistics box on the programme overview tab showing the percentage of responses that have been received and triaged (the idea being that this number should be as close to 100% as possible).
I'd quite like to refactor the programme-level statistics code, but at the moment we're not sure exactly which statistics we're going to show so I'll leave it for now and we refactor when we're more confident.
> Show responses received and triaged

- app/javascript/controllers/autosubmit_controller.js
- app/views/patients/index.html.erb
Prerequisite: https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2236.
This builds on `data-turbo=true` by adding the autosubmit module, which will submit the form on behalf of the user automatically 250ms after they stop typing.
> Autosubmit patient search form 

- app/controllers/patients_controller.rb
- app/views/patients/index.html.erb
- config/routes.rb
This moves the `q` parameter to POST params which are hidden from the URL and won't end up in the browser history. This is necessary to prevent the leaking of patient PII.
It adds a `POST /patients` route that returns with a `201 CREATED` status to comply with some Turbo caveats: https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission
One interesting bit of this is that it makes the JS version perform better than non-JS, as the JS version does not trigger the "Confirm form resubmission" browser dialog.
> Use POST for search endpoint 

- app/components/app_programme_navigation_component.rb
- app/controllers/programme/patients_controller.rb
- app/views/programme/patients/index.html.erb
- config/routes.rb
This adds a link within a programme to view the children that are part of it. The table isn't aligned to the prototype yet, that's coming in a follow-up PR.
> Add basic programme patients view

- app/models/patient_session.rb
- spec/factories/gillick_assessments.rb
- spec/models/patient_session_spec.rb
Patients may have draft gillick assessments or vaccination recrods which need to be removed before they can be moved to a new session.
This replaces the previous PR (#2229) which would copy patient record instead of moving it if it had any draft records. (didn't realise renaming the branch would close it)
> Remove draft records when moving patient

- app/components/app_programme_session_table_component.html.erb
- app/components/app_session_summary_component.rb
- app/components/app_session_table_component.html.erb
- app/controllers/dev_controller.rb
- app/controllers/programmes_controller.rb
- app/controllers/session_dates_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/vaccination_records_controller.rb
- app/jobs/clinic_session_invitations_job.rb
- app/jobs/school_consent_reminders_job.rb
- app/models/immunisation_import_row.rb
- app/models/session.rb
- app/views/session_dates/show.html.erb
- app/views/sessions/edit.html.erb
- db/seeds.rb
- script/generate_model_office_data.rb
- spec/factories/session_notifications.rb
- spec/factories/sessions.rb
- spec/features/import_vaccination_records_with_duplicates_spec.rb
- spec/features/self_consent_clinic_spec.rb
- spec/features/self_consent_gillick_competent_spec.rb
- spec/features/self_consent_not_gillick_competent_spec.rb
- spec/jobs/clinic_session_invitations_job_spec.rb
- spec/jobs/school_consent_reminders_job_spec.rb
- spec/jobs/school_consent_requests_job_spec.rb
- spec/lib/govuk_notify_personalisation_spec.rb
- spec/models/immunisation_import_spec.rb
- spec/models/session_notification_spec.rb
- spec/models/session_spec.rb
This refactors the relationship between sessions and session dates to provide a convenience method `dates` which returns `Date` objects rather than instances of `SessionDate` which in most cases is most useful.
> Refactor Session#dates

- app/controllers/programmes_controller.rb
- app/controllers/sessions_controller.rb
- app/models/patient_session.rb
When loading the patient sessions, to determine the state and avoid N+1 issues we should preload various related records. I've put this in a common scope as it's used in a few places.
> Fix N+1 issue on programme overview page

- app/controllers/sessions/edit_controller.rb
- app/models/session.rb
- app/views/sessions/edit.html.erb
- app/views/sessions/edit/send_invitations_at.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/manage_clinic_sessions_spec.rb
This adds the ability to edit the date when invitations are sent out for clinics, based on the designs for editing when consent requests are sent out.
> Add ability to edit invitation date

- app/components/app_programme_session_table_component.rb
- app/controllers/consents_controller.rb
- app/controllers/programmes_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations_controller.rb
- app/jobs/school_session_reminders_job.rb
- app/models/patient_session.rb
- app/models/user.rb
The new sessions and programmes pages now show more statistics than before which has lead to more queries to the database, this tries to reduce that number and improve performance. See individual commits for more details.
> Small reductions in queries to the database

- db/seeds.rb
Because CIS2 isn't enabled, `database_authenticable` is missing and `password=` fails to run when running the seeds.
> Don't create Nurse Joy's org on a CIS2 env

- db/migrate/20241030125117_add_session_to_consent_notifications.rb
`Session.first.id` fails if `Session` is empty.
> Don't update ConsentNotifications if no sessions

- app/components/app_activity_log_component.rb
- app/models/patient.rb
- app/views/patient_sessions/log.html.erb
- app/views/patients/log.html.erb
- app/views/patients/show.html.erb
- config/routes.rb
- spec/components/app_activity_log_component_spec.rb
- spec/components/previews/app_activity_log_component_preview.rb
- spec/features/manage_children_spec.rb
This allows the user to see an activity log for a child record separate from the sessions view.
> Show activity log on global child view

- app/jobs/concerns/nhs_api_concurrency_concern.rb
This helps the jobs which look up information in PDS to be more robust by retrying in the case of intermittent network or server errors.
> Retry PDS jobs on server errors

- app/jobs/school_consent_reminders_job.rb
- app/jobs/school_consent_requests_job.rb
This is an unlikely scenario where patients are added to a session after the consent period has closed and would end up receiving an email that they then can't use. It's possible to construct this scenario by scheduled a session for today and then tomorrow an email goes out to all patients with a link that doesn't work, although in reality it's unlikely this would ever happen.
> Don't send emails for closed sessions

- app/components/app_patient_summary_component.rb
- app/helpers/patients_helper.rb
- app/models/concerns/pending_changes_concern.rb
- app/models/consent_form.rb
- app/models/immunisation_import_row.rb
- app/models/patient.rb
- app/models/patient_import_row.rb
- spec/helpers/patients_helper_spec.rb
- spec/models/concerns/pending_changes_concern_spec.rb
- spec/models/patient_spec.rb
This makes it possible to stage a `nil` value in the pending changes for a particular record, this is needed to handle when a patient moves out of schools (either because they're home-schooled, or because the school is unknown).
> Allow staging nil values

- app/components/app_patient_cohort_table_component.html.erb
- app/components/app_patient_cohort_table_component.rb
- app/components/app_patient_session_table_component.html.erb
- app/components/app_patient_session_table_component.rb
- app/controllers/patients_controller.rb
- app/views/patients/show.html.erb
- spec/components/app_patient_cohort_table_component_spec.rb
- spec/components/app_patient_session_table_component_spec.rb
- spec/factories/cohorts.rb
- spec/features/manage_children_spec.rb
This adds a new table when looking at a patient that shows the sessions they belong to, matching the designs in the prototype.
> Show patient sessions on global patient view page

- app/controllers/patients_controller.rb
- app/models/immunisation_import_row.rb
- app/models/patient.rb
- config/locales/en.yml
- spec/models/immunisation_import_row_spec.rb
- spec/models/patient_spec.rb
This changes how we find duplicates to use the full name (both given and family name) to avoid a situation where twins would be treated as the same person, because their family name, date of birth and postcode would match.
To compensate for the duplicate matching to require a match on more values, we use trigram fuzzy matching to handle spelling errors or other slight variations in names.
> Find duplicates using full name

- app/models/session.rb
- config/locales/en.yml
This improves the validation around editing when the consent requests and invitations are sent out to prevent the user from choosing a value that's not within a reasonable limit.
3 months was picked arbitrarily, happy for other suggestions.
> Ensure session notifications sent date is validated

- app/components/app_patient_summary_component.rb
- app/controllers/patients/edit_controller.rb
- app/controllers/patients_controller.rb
- app/views/patients/edit.html.erb
- app/views/patients/edit/nhs_number.html.erb
- app/views/patients/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/manage_children_spec.rb
This adds a page that allows users to edit the NHS number of a patient. If the NHS number already exists for another patient, the user is presented with a validation error, which will be replaced with the ability to merge the patient records.
> Add ability to edit NHS number 

- app/jobs/patient_nhs_number_lookup_job.rb
- app/jobs/patient_update_from_pds_job.rb
- app/lib/patient_merger.rb
- spec/lib/patient_merger_spec.rb
This refactors how the patient merging logic is implemented to provide a separate service class rather than being a job concern. This allows us to use it as the result of an action by a nurse.
> Add PatientMerger

- .github/workflows/deploy-pentest.yml
This is horrible, but also the fastest way to implement this for now. The horribleness is that it will have to build and deploy out the artifact a second time, in addition to the "test" env deploy, in fact there may be a race condition as a result of having two of these. However, reusing the image from the other deploy is non-trivial.
Creating as draft so we can discuss if it might be better to:
- Trigger this deploy to pentest on the completion of the main deploy workflow triggered by PR merge, but we probably want to not deploy to pentest if the main deploy was manually triggered.
- Add the deploy to the existing deploy workflow, but we probably want to disable deploying to pentest when triggered manually.
- Something fancier like trigger this deploy workflow again at the end of the …
> Auto-deploy to pentest

- .github/workflows/deploy-pentest.yml
When starting up in "test" we cancel out the other "test" deploy job.
> Use pentest not test for concurrency group

- app/controllers/patients/edit_controller.rb
- app/views/patients/edit/nhs_number_merge.html.erb
- config/routes.rb
- spec/features/manage_children_spec.rb
This adds the functionality to allow users to edit NHS numbers, and if it matches with an existing patient, to merge the two patient records by deleting the one without an NHS number and keeping the existing patient.
> Allow merging records when editing NHS numbers

- app/components/app_card_component.rb
- app/views/dashboard/index.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- Adds link to service guidance from footer (opens in a new tab)
- Adds link to service guidance from dashboard
- Fix appearance of secondary card (shouldn’t have content padding), and use smaller heading size for secondary cards
> Link to service guidance

- app/components/app_activity_log_component.rb
- spec/components/app_activity_log_component_spec.rb
This ensures that we are only show consents and vaccination records that have been fully recorded in the database.
https://good-machine.sentry.io/issues/6033335850/?environment=test&project=4505625073876992&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=2
> Only show recorded items in activity log

- app/controllers/patients_controller.rb
- app/models/patient.rb
- spec/models/patient_spec.rb
This reverts #2264 which has a few specific problems that causes more problems, specifically related to streets with similarly named children. Instead we're going to introduce a match against all four datapoints first, to hopefully reduce the risk of the multiple matching validation error.
The introduction of #2276 also helps to avoid problems related to twins being considered duplicates.
> Revert fuzzy name matching

- .github/workflows/deploy-pentest.yml
- .github/workflows/deploy.yml
Only to be merged when we're ready to start the change freeze.
We may need to also disable the deploys to pentest depending on whether all the testers are able to authenticate with CIS2, currently one of the testers is still unable to do so and relies on testing in the pentest env without CIS2.
> Disable the auto-deploy for test

- app/components/app_programme_session_table_component.rb
- app/controllers/programmes_controller.rb
- app/models/concerns/patient_session_state_concern.rb
- app/models/patient_session.rb
- app/models/patient_session_stats.rb
This is shown in a number of places now and it can take a while to calculate statistics on lots of patient sessions. This makes a number of small improvements, specifically around reducing unnecessary calculations and memoizing values already calculated.
> Improve performance of calculating statistics

- docs/disaster-recovery.md
These can be used to spin up a new database from a dump of a live database. Then we can run a new Rails server against it, or export data for offline or disaster scenario use.
> Add disaster recovery instructions

- app/views/session_dates/show.html.erb
"Cancel" in this context could mean subtly different things:
* cancel the session completely
* revert the changes you are making to session dates without saving them
* cancel any further changes to the session dates
"Back" should hopefully be more obvious, and is consistent with the "Back" link at the top of the page.
> Edit session dates page: rename "Cancel" link to "Back"

- spec/features/scheduled_consent_requests_spec.rb
Scheduling is a really key, non-trivial part of the service. I couldn't find a feature spec that covered scheduling explicitly, so I added this one. If this is a good approach and there aren't anything similar I'm overlooking, I can add more for school session reminders, clinics etc.
> Explicit feature spec for scheduled consent requests

- app/models/consent.rb
- app/models/consent_notification.rb
- app/models/parent.rb
- app/models/session_notification.rb
- spec/factories/parents.rb
- spec/models/consent_spec.rb
- spec/models/parent_spec.rb
- spec/models/session_notification_spec.rb
This refactors how the emails are sent to avoid trying to send emails to parents who we don't have an email address for, which ends up raising an error recorded in Sentry. We [already do this for text messages](https://github.com/nhsuk/manage-vaccinations-in-schools/blob/2f244f1e4ab3e0e47b3875ba2be22433a0fb1cca/app/jobs/text_delivery_job.rb#L21-L23).
I've also made a change to the way `SessionNotification` and `ConsentNotification`s are recorded, to only record them if we have parent contact details and therefore sent an email. This improves the accuracy of the record, making it clear that these only exist when they were sent, but it also means the system will automatically send emails that were missed once we have contact details. For example, if a consent request was attempted but we …
> Don't send emails to parents without an email address

- app/models/class_import_row.rb
- app/models/cohort_import_row.rb
- app/models/patient_import_row.rb
- spec/models/class_import_row_spec.rb
- spec/models/cohort_import_row_spec.rb
Currently only class lists are likely to contain the child's registration, and that leads to a situation where once the cohort has been uploaded, when the class list is uploaded and matched against existing patients, they're all flagged needing review because the registration is added.
Instead we've decided that for class lists we will always take the registration from the file without staging the changes, even if it's different to the one we already have in the record.
> Always accept registration from class lists

- app/models/session.rb
- config/locales/en.yml
- spec/jobs/school_consent_reminders_job_spec.rb
Currently the user is preventing from setting a consent request date _after_ the first consent reminder, however the validation error isn't clear. Currently the user will see an error about the reminders being not enough weeks before the consent requests, on the page where you can edit the consent requests, which is confusing.
> Improve validation messages for consent requests

- app/models/parent.rb
- spec/components/app_parent_summary_component_spec.rb
- spec/features/scheduled_consent_requests_spec.rb
- spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
- spec/jobs/text_delivery_job_spec.rb
- spec/models/class_import_row_spec.rb
- spec/models/class_import_spec.rb
- spec/models/cohort_import_row_spec.rb
- spec/models/cohort_import_spec.rb
- spec/models/consent_spec.rb
- spec/models/parent_spec.rb
* format national numbers with spaces
* save non-GB numbers in an international format
* handle leading zeros being stripped (when handling CSVs in Excel, for instance)
> Normalise parent phone numbers with Phonelib

- app/models/patient_session.rb
This should improve performance by removing the need to have a reference to the patient session when performing the join, which prevents Rails from being able to run a single query to avoid N+1 issues. This does slightly break functionality, but since we're only running with one programme at the moment, and other functionality is broken with regards to multiple programmes, it seems like a reasonable fix for now.
> Don't filter consents and triage on programme 

- app/lib/patient_merger.rb
- spec/lib/patient_merger_spec.rb
When the parent already exists and is attached to both patients, we can safely destroy the relationship rather than try and update it which leads to a unique constraint error.
https://good-machine.sentry.io/issues/6044038875/
> Handle merging patients when parent exists in both

- app/jobs/patient_update_from_pds_job.rb
- spec/jobs/patient_update_from_pds_job_spec.rb
If the NHS number itself is invalid we can mark the patient as invalid. This extends the definition of an invalid patient from the definition in PDS to include these cases.
An advantage of this is that we can avoid checking PDS for patients we know will never succeed by excluding all types of invalid patients. A potential disadvantage is that these patients will appear in the notices, although I’d argue they are still "invalid".
> Mark patients as invalid when NHS number is invalid

- copilot/environments/addons/db.yml
- docs/disaster-recovery.md
This makes use of the optional `SnapshotIdentifier` option that can be specified in `db.yml`.
Also bump Aurora postgres engine version to align to what's being used (otherwise the snapshot restore fails).
> Document restoring a snapshot to an environment

- app/components/app_session_patient_table_component.rb
- app/controllers/concerns/patient_sorting_concern.rb
- app/controllers/consents_controller.rb
- app/controllers/programme/patients_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations_controller.rb
- app/models/patient_session.rb
- app/views/programme/patients/index.html.erb
This switches the programme patients view to use the `AppSessionPatientTableComponent` to allow users to filter and sort patients. I haven't added tests for this specific component since it's covered elsewhere, and we have a feature test for this page already.
> Add filters to programme patients view

- app/components/app_patient_page_component.html.erb
- spec/features/hpv_vaccination_administered_spec.rb
When looking at the details for a patient, we should be showing the vaccination details if a vaccination has been recorded for that patient.
> Show recorded vaccination records

- config/settings/test.yml
It turns out we do run a server and use the `/reset` endpoint in `RAILS_ENV=test` for the Playwright tests, so these are in use.
Should fix the Playwright tests on CI.
> Configure fast_reset and web_concurrency in test

- config/settings.yml
When building the docker container, RAILS_MASTER_KEY does not exist, so asset precompilation fails because it can't read certain secrets.
> Use safe navigation in settings 

- .github/workflows/deploy-pentest.yml
- .github/workflows/deploy.yml
Makes it easier to differentiate in the list of checks on `main`.
> Rename pentest deploy task

- app/models/vaccination_record.rb
- spec/factories/vaccination_records.rb
- spec/lib/govuk_notify_personalisation_spec.rb
- spec/models/vaccination_record_spec.rb
This handles the situation where going back to edit previously set values on a vaccination record and this method ensures the record is consistent.
To support the tests I've had to set a `create` strategy on the associations to ensure that building a vaccination record has a valid state, without this various `has_one` through associations end up being `nil` which leads to validation errors.
> Reset unused vaccination record fields

- app/controllers/vaccination_records/edit_controller.rb
- config/locales/en.yml
When editing the date and time of a vaccination record we should validate that it makes sense and is a valid value.
> Validate date and time when editing

- lib/tasks/pds.rake
I do like the idea of having these, they do make PDS testing easier (and other NHS API things). For example the `nhs:access_token` task made it convenient to diagnose the NHS API key issue we had earlier. But at the same time not entirely sure of the value of them.
In any case here's a fix that makes them continue to work. Here's how they work:
Pulling up a patient using their NHS number:
```
$ rails pds:patient:find[9449306540]
https://int.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9449306540
date: Tue, 05 Nov 2024 22:21:12 GMT
content-type: application/fhir+json
content-length: 3256
connection: keep-alive
server: XXXXXX
etag: W/"21"
strict-transport-security: max-age=31536000; includeSubDomains
x-request-id: 8165136d-8395-4875-9077-d43087969a2c
{
"address": [
{
"id": …
```
> Fix PDS rake tasks

- app/controllers/vaccination_records/edit_controller.rb
- app/views/vaccination_records/edit/date_and_time.html.erb
- config/locales/en.yml
- spec/features/edit_vaccination_record_spec.rb
Improvements to the vaccination administration editing form:
* handle when the entered time is invalid
* show minutes with leading zeros, so they appear in a more recognisable format
* add missing error message
> Vaccination administration time validations

- app/jobs/school_session_reminders_job.rb
This wasn't caught by the tests because we stub `create_and_send!`, I think it probably is a good idea to add some feature tests for this, but that can be done in a follow up PR.
https://good-machine.sentry.io/issues/6046554728/
> Fix strict load error on session reminders job

- app/views/programmes/index.html.erb
We don't want to show draft vaccinations as they're not visible anywhere and means the numbers are confusing.
> Only show recorded vaccinations on programme index

- copilot/webapp/manifest.yml
These environments all contain fully synthetic data that won't exist on PDS anyway.
> Disable PDS jobs on non-test envs

- app/controllers/vaccination_records/edit_controller.rb
- app/controllers/vaccinations_controller.rb
- app/models/batch.rb
- app/models/immunisation_import_row.rb
- spec/components/app_vaccination_record_summary_component_spec.rb
- spec/factories/batches.rb
- spec/features/e2e_journey_spec.rb
- spec/features/hpv_vaccination_administered_spec.rb
- spec/features/import_vaccination_records_with_duplicates_spec.rb
- spec/models/batch_spec.rb
- spec/models/immunisation_import_row_spec.rb
This adds a number of restrictions on batches to prevent the creation of invalid batches and to prevent invalid batches from being chosen when recording a vaccination.
> Add restrictions on batches

- lib/tasks/consent_forms.rake
When populating the Training environment, we had to add consents to an existing empty session to make it look more believable. This is a script to help accomplish that in the future.
> Add rake task to generate consent forms

- lib/tasks/consent_forms.rake
The desc didn't match up to the actual usage.
> Namespace consent_forms:generate task correctly

- app/models/user.rb
- spec/models/user_spec.rb
We need to allow users in the Training environment to access nurse-related functionality, but their emails don't contain the word `nurse`. So this is a stopgap to fix that.
> Default user role to Nurse if CIS2 is disabled

- app/models/patient.rb
This removes Patient#programmes which is not used anywhere and isn't correctly defined anyway since it depends on `sessions` which is defined below it.
> Remove unused patient relationship

- app/views/consent_forms/index.html.erb
Currently we show only the number visible on the page whereas we would want to show the total across all pages.
> Show total unmatched consent forms

- app/controllers/concerns/triage_mailer_concern.rb
- spec/controllers/concerns/triage_mailer_concern_spec.rb
- spec/factories/patient_sessions.rb
- spec/factories/patients.rb
Currently we send an email and a text saying consent was given if the user has selected the consent not provided option which is incorrect and could lead to confusion.
> Don't send email if consent is not provided

- app/models/concerns/patient_session_state_concern.rb
- app/models/consent.rb
- app/models/consent_form.rb
- app/views/manage_consents/agree.html.erb
- config/locales/en.yml
- spec/controllers/concerns/triage_mailer_concern_spec.rb
- spec/factories/patient_sessions.rb
- spec/factories/patients.rb
This response on consent and consent forms was used in the pilot but no longer exists in the prototype and should be removed. This also avoids a problem where consent given emails were being sent out if consent was recorded as "not provided".
Replaces #2352
> Remove "not provided" response

- app/components/app_activity_log_component.rb
- spec/components/app_activity_log_component_spec.rb
In the activity log, currently vaccinations are recorded as having been given even if they weren't administered which is incorrect.
> Update content when vaccination is not administered

- app/controllers/concerns/patient_tabs_concern.rb
- app/models/concerns/patient_session_state_concern.rb
- app/models/patient_session.rb
- app/models/patient_session_stats.rb
- config/locales/patient_session_statuses.en.yml
- spec/controllers/concerns/patient_tabs_concern_spec.rb
- spec/factories/patient_sessions.rb
- spec/features/self_consent_not_gillick_competent_spec.rb
- spec/models/concerns/patient_session_state_concern_spec.rb
1. Find a patient with given consent from a parent
2. Start recording a Gillick competency assessment
3. Record that the child isn’t Gillick compentent
Child’s status is shown as: “Not vaccinated - no-one responded to our requests for consent. When assessed, the child was not Gillick competent.”
This is wrong in a number of ways:
* A failed Gillick competency assessment shouldn’t override the parent’s consent – it should just be ignored in the determination whether consent is present or not
* A failed Gillick competency assessment shouldn’t prevent vaccination recording.
* The message “no-one responded to our requests for consent” is inaccurate, as there’s definitely a consent response from a parent
Gillick assessment result recorded, child’s vaccination can still be recorded as there is …
> A failed Gillick assessment does not automatically mean the patient can't be vaccinated

- config/environments/production.rb
Start a PDS check from 8am ahead of scheduled comms going out at 9am.
> Reduce a potential gap between PDS updates and comms being sent

- app/models/concerns/patient_session_state_concern.rb
- app/models/consent.rb
- app/models/patient_session.rb
- app/views/consents/edit/agree.html.erb
- config/locales/en.yml
- spec/controllers/concerns/triage_mailer_concern_spec.rb
- spec/factories/patient_sessions.rb
- spec/factories/patients.rb
This reverts commit 915d58367b1a44ac60b1eca0a3121c370390011f.
We actually do need this feature to avoid the nursing team from repeatedly contacting a parent who might not be available.
I think it would be good to add some feature test coverage to this, but we can do that in a later PR.
> Revert "Remove "not provided" response"

- app/models/immunisation_import_row.rb
- spec/features/import_vaccination_records_with_duplicates_spec.rb
- spec/models/immunisation_import_row_spec.rb
- spec/models/immunisation_import_spec.rb
To prevent obsolete details (like the child's old address if they've moved) from being flagged as import issues, don't stage any patient changes from vaccination uploads that have been matched to an existing patient in the cohort.
This change is part of a broader strategy around what updates happen when something is imported against an existing cohort patient:
This PR also includes some technical work:
- Fix `ImmunisationImportRow` specs - they were not testing anything
- Improve spec coverage around the "Immunisation import duplicate resolution" spec
Best reviewed commit-by-commit.
> Ignore changes on the patient record when uploading vaccinations for existing patients

- app/models/consent.rb
- spec/models/consent_spec.rb
In the consent model these aren't allowed to be `nil`, instead we store them as a blank string.
https://good-machine.sentry.io/issues/6051539334/
> Correctly handle consent form notes being `nil`

- app/controllers/draft_vaccination_records_controller.rb
- app/controllers/vaccinations_controller.rb
- app/models/draft_vaccination_record.rb
- app/views/draft_vaccination_records/confirm.html.erb
- app/views/draft_vaccination_records/outcome.html.erb
- config/locales/en.yml
- spec/features/edit_vaccination_record_spec.rb
- spec/features/hpv_vaccination_administered_spec.rb
- spec/features/hpv_vaccination_not_administered_spec.rb
This makes it possible to change the outcome of a vaccination, specifically from not administered to administered and the reverse.
> Allow editing vaccination outcome

- app/models/patient_import_row.rb
- spec/models/class_import_row_spec.rb
- spec/models/cohort_import_row_spec.rb
This prevents admins from having to review and accept every one of those changes if vaccs history was uploaded first (which creates the patients with unknown schools) and then the cohort was added later (which sets the school)
The change also covers the home-educated status as well, as it's inextricably linked to school.
This change is part of a broader strategy around what updates happen when something is imported against an existing cohort patient:
> Update unknown => known school automatically for patient imports

- app/policies/patient_policy.rb
- spec/policies/patient_policy_spec.rb
This code was introduced in https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2293 but SQL had a subtle issue with it. This prevented all patients showing up in the children list and led to 404s when trying to review certain import issues.
> Fix visibility of pending patients

- app/components/app_outcome_banner_component.rb
- spec/components/app_outcome_banner_component_spec.rb
- spec/factories/patient_sessions.rb
Before this fix, the outcome banner was showing the time of creation of the record, not when the vaccination was administered. This is an issue if vaccs records are back-dated due to delays in recording.
> Patient page: show the right date on vaccination outcome

- app/components/app_activity_log_component.rb
- spec/components/app_activity_log_component_spec.rb
Not the creation time of the record, that can potentially be years afterwards.
> Show administration time of vaccinations on the activity log

- app/assets/stylesheets/application.scss
This was updated in the prototype a couple of weeks ago.
> Align page container width to prototype

- app/controllers/consents/edit_controller.rb
- app/controllers/consents_controller.rb
- app/models/consent.rb
- app/views/consents/edit/who.html.erb
- config/locales/en.yml
- spec/features/self_consent_spec.rb
Currently for self-consent, if the child is Gillick competent then we assume that's who will be providing consent and don't allow the nurse to choose a parental contact.
> Require selecting child for self-consent

- app/models/patient.rb
- spec/models/session_spec.rb
This ensures that patients who have already had the vaccine are treated as administered, which means we don't move them to clinic when sessions are closed, for example.
> Treat already had vaccination records as administered

- app/components/app_import_format_details_component.rb
- app/models/immunisation_import_row.rb
- config/locales/en.yml
- spec/models/immunisation_import_row_spec.rb
This adds a new column that we can optionally parse when importing immunisations to allow the user to provide the time of vaccination. This will mostly be used for offline recording, but could also be used when importing historical records.
To account for different ways of formatting times we parse a number of different formats, but in the documentation I've only written one explicit format that's the most unambigious.
> Add TIME_OF_VACCINATION immunisation import column

- app/components/app_import_format_details_component.rb
- app/models/immunisation_import_row.rb
- app/models/user.rb
- config/locales/en.yml
- spec/features/import_vaccination_records_with_duplicates_spec.rb
- spec/models/immunisation_import_row_spec.rb
This adds a new optional column that can be parsed allowing the uploader to specify the email address of the user who performed the vaccination. This allows us to create a direct link in our database between vaccinations and users rather than filling in the free text family/given name fields.
> Add PERFORMING_PROFESSIONAL_EMAIL immunisation import column

- app/models/immunisation_import_row.rb
- config/locales/en.yml
- spec/features/import_vaccination_records_spec.rb
- spec/models/immunisation_import_row_spec.rb
When importing immunisations, we now validate that the date of vaccination matches an existing session date if we're importing records for the current academic year rather than creating new session dates.
To support this the `location` and `school` method can now be used even if the row doesn't validate (as they're used in this validation).
> Prevent creation of session dates in current academic year

- app/models/draft_vaccination_record.rb
- spec/features/edit_vaccination_record_spec.rb
- spec/models/draft_vaccination_record_spec.rb
When changing the outcome of a vaccination record, if changing to vaccinated, we can automatically choose the vaccine for the user if there's only one possible option which saves time.
It also fixes an issue we have for HPV where the batches and delivery site/methods are unavailable, however this problem will come again for Flu where there are multiple vaccines.
https://good-machine.sentry.io/issues/6057331062/
> Automatically pick vaccine if one exists

- app/controllers/concerns/consent_form_mailer_concern.rb
- app/mailers/consent_mailer.rb
- config/initializers/govuk_notify.rb
- spec/controllers/concerns/consent_form_mailer_concern_spec.rb
- spec/features/parent_consent_school_session_completed_spec.rb
- spec/mailers/consent_mailer_spec.rb
If the parent fills out a consent form and tells us that their child is in a different school, and that school has no more session dates coming up we need to tell the parent that either new dates will be added or they need to book in to a clinic.
> Send clinic confirmation email when no session dates exist

- app/components/app_session_patient_table_component.rb
- app/controllers/programme/patients_controller.rb
- app/views/programme/patients/index.html.erb
- config/locales/patient_session_statuses.en.yml
- spec/components/app_session_patient_table_component_spec.rb
When using the `AppSessionPatientTableComponent` on the children overview page for a programme, we want to show all patients in the cohort, not just patients who also belong to a session.
> Show patients not in sessions

- app/components/app_patient_vaccination_table_component.rb
- spec/components/app_patient_vaccination_table_component_spec.rb
This currently breaks as we try and show the administered at date and vaccine on a record that won't have that information. Perhaps we might want to improve this component to show details about unadministered vaccinations in the future.
https://good-machine.sentry.io/issues/6059157719/
> Don't try to show patient's unadministered vaccination records

- app/views/draft_vaccination_records/confirm.html.erb
- spec/features/edit_vaccination_record_spec.rb
This fixes the back link when editing an existing vaccination record which wasn't leading to the right place and instead users were seeing an error page.
> Fix edit vaccination back link

- Dockerfile
This is necessary to use the `charlock_holmes` Gem that was added in 40612f2734121483501d0b05a3020474c56b7430.
> Install libicu-dev

- app/controllers/batches_controller.rb
- app/models/batch.rb
This checks that the batch is valid before performing the unarchive step to ensure we don't get any validation errors when trying to unarchive the batch.
https://good-machine.sentry.io/issues/6059349186/
> Refactor how batches are unarchived

- Dockerfile
The builder image needs this package, but so does the app image.
> Add libicu-dev to deployed packages

- app/controllers/patients_controller.rb
This fixes a strict loading error when displaying the log for a patient.
> Preload notify_log_entries sent_by

- app/components/app_activity_log_component.rb
- app/controllers/patients_controller.rb
This fixes a different issue that has come up regarding the patient activity log, follows up from 60a5a57896b05aed796e00b49b105dc39e145acf.
> Preload more for patient activity log

- app/models/draft_vaccination_record.rb
- app/models/immunisation_import_row.rb
- app/models/vaccination_record.rb
- config/locales/en.yml
- spec/models/draft_vaccination_record_spec.rb
- spec/models/immunisation_import_row_spec.rb
- spec/models/vaccination_record_spec.rb
This extends the validation added in 337795f99291568bef9869f38a53cd8102121d2f to add the same validation to the immunisation import rows, meaning that import users will see a suitable validation error. Without this currently users see a broken import that never succeeds.
https://good-machine.sentry.io/issues/6059825084/
> Validate TIME_OF_VACCINATION is not in the future

- app/controllers/dev_controller.rb
Without this we get foreign key constraint errors when the organisation is reset.
https://good-machine.sentry.io/issues/6060092945/
> Delete notifications when reseting organisation

- app/controllers/vaccinations_controller.rb
- app/models/concerns/vaccination_record_performed_by_concern.rb
- app/models/draft_vaccination_record.rb
- app/models/vaccination_record.rb
- spec/features/edit_vaccination_record_spec.rb
Historical vaccination records don't have a performed by user, so we need to handle this by mapping the same fields we have on vaccination records across to the draft vaccination record. To avoid duplicating code I've introduced a `VaccinationRecordPerformedByConcern` that handles the common logic across the two models.
https://good-machine.sentry.io/issues/6060365840/
> Allow editing historical vaccination records

- app/controllers/application_controller.rb
- config/initializers/flipper.rb
This ensures that the first time an environment is deployed, it's behind basic auth.
We then override this on some of our environments, like training.
However, if you then:
- Clear the database
- Redeploy at some point
The flag will get re-initialised to `true` and users will lose access.
Since this has happened twice on the training environment, this initializer is doing more harm than good.
> Remove FLIPPER_INITIALIZERS for basic_auth

- app/components/app_session_patient_table_component.rb
- app/controllers/register_attendances_controller.rb
- app/models/patient_session.rb
- app/models/patient_session_stats.rb
- app/views/register_attendances/index.html.erb
- app/views/sessions/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/manage_attendance_spec.rb
- spec/models/patient_session_stats_spec.rb
This adds a "Register attendance" card to the sessions show page. It takes the user to a dev-designed table which allows nurses to register attendance for today for all the patients attending a session.
> Add Register attendance functionality

- app/lib/session_xlsx_exporter.rb
- spec/factories/vaccination_records.rb
- spec/features/hpv_vaccination_offline_spec.rb
- spec/lib/session_xlsx_exporter_spec.rb
The offline spreadsheet wasn't including the REASON_NOT_VACCINATED column.
> Offline recording: fix upload of "not vaccinated" outcomes

- app/components/app_patient_page_component.html.erb
- app/controllers/vaccinations_controller.rb
- app/policies/vaccination_record_policy.rb
- app/views/vaccinations/destroy.html.erb
- config/routes.rb
- db/seeds.rb
- spec/components/app_activity_log_component_spec.rb
- spec/factories/organisations.rb
- spec/factories/patient_sessions.rb
- spec/factories/users.rb
- spec/features/delete_vaccination_record_spec.rb
- spec/lib/session_xlsx_exporter_spec.rb
- spec/models/immunisation_import_spec.rb
- spec/models/user_spec.rb
- spec/policies/batch_policy_spec.rb
- spec/policies/patient_policy_spec.rb
- spec/policies/patient_session_policy_spec.rb
- spec/policies/session_policy_spec.rb
- spec/policies/triage_policy_spec.rb
- spec/policies/vaccination_record_policy_spec.rb
This adds the basic functionality that allows users to delete vaccination records for sessions that are still open. There's no design for this in the prototype so the interface might need changing in the future.
Some further improvements required include soft-deletion so old vaccination records can be shown in the activity log and a feature test to ensure the records can only be deleted for open sessions. I'll add those in a separate PR.
> Add ability to delete vaccination records

- app/components/app_activity_log_component.rb
- app/controllers/vaccinations_controller.rb
- spec/components/app_activity_log_component_spec.rb
- spec/features/delete_vaccination_record_spec.rb
Instead of destroying vaccination records, if it's a different day to when the session is being held, we should keep a record of what the vaccination record used to be and display it in the activity log.
> Discard vaccination records

- app/controllers/concerns/wizard_controller_concern.rb
- app/controllers/vaccination_reports_controller.rb
- app/models/concerns/request_session_persistable.rb
- app/models/vaccination_report.rb
- app/views/programmes/show.html.erb
- app/views/vaccination_reports/dates.html.erb
- app/views/vaccination_reports/file_format.html.erb
- config/locales/en.yml
- config/locales/helpers.en.yml
- config/routes.rb
- spec/features/download_vaccination_reports_spec.rb
This adds a basic two question interface allowing the user to start downloading vaccination reports by choosing the date range and the file format they'd like the export to be in.
Currently the download step does nothing, but we expect this to link in to #2427 and another exporter for the Mavis format.
> UI to download vaccination reports

- app/lib/reports/careplus_exporter.rb
If the consent route is self-consent, there won't be a parent but instead a patient which we need to preload.
https://good-machine.sentry.io/issues/6064050500/
> Preload consent patient

- app/lib/reports/programme_vaccinations_exporter.rb
- spec/features/download_vaccination_reports_spec.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
This adds a number of missing fields to match the spec. A lot of these fields are untested at the moment, but I thought it would make sense to get this in and improve the tests later.
> Update programme vaccination export to match spec

- app/lib/reports/careplus_exporter.rb
- app/models/vaccination_report.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
We've confirmed that the Suspension end date field isn't used. We also found out some more information about the Dose and Site fields that help us get them closer to correct, but they still need some more tweaking.
> Tweak Careplus exporter

- app/lib/reports/programme_vaccinations_exporter.rb
- spec/lib/reports/offline_session_exporter_spec.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
This adds a number of tests to ensure we're exporting consents, triage and gillick assessments correctly.
> Improve programme vaccinations tests

- app/models/immunisation_import_row.rb
- spec/models/immunisation_import_row_spec.rb
This extends our date parsing to handle another common date format that we might sometimes see in the files provided by our users.
> Add support for parsing ISO 8601 dates

- app/lib/reports/offline_session_exporter.rb
When including dates in an Excel file format, we can specify a format code for the dates. I can't test this locally, but I'm hoping this ensures that when the file is exported, it uses the format specified here rather than the user's system date formatting preferences.
> Specify an Excel date format

- app/components/app_programme_session_table_component.rb
We show "None" in a few other places, but in a table with numerical values we should show "0" instead.
> Use '0' instead of 'None' on session table

- app/models/vaccination_record.rb
- spec/features/hpv_vaccination_already_had_spec.rb
- spec/features/hpv_vaccination_delayed_spec.rb
This should be allowed in the case where the child refused the vaccine and then later on in the day decided they were happy to receive the vaccine, which we know can happen.
More context on this is available in the bug report: https://trello.com/c/tV9y34Qx/1511-nurse-is-not-allowed-to-record-a-vaccine-if-child-already-has-an-outcome-where-the-reason-not-given-is-they-refused-it-other-rea
> Allow vaccination if child refused

- app/models/location.rb
- app/models/onboarding.rb
- app/models/organisation.rb
- config/onboarding/coventry-model-office.yaml
- lib/tasks/onboard.rake
- script/set_up_coventry.sh
- spec/components/app_session_summary_component_spec.rb
- spec/fixtures/files/onboarding/invalid.yaml
- spec/fixtures/files/onboarding/valid.yaml
- spec/models/dps_export_row_spec.rb
- spec/models/onboarding_spec.rb
- spec/models/patient_spec.rb
This introduces a new Rake task `onboard` and a YAML configuration file that needs to contain all the information required to onboard an organisation (teams, schools, clinics, programmes, etc) and only if it is all valid does it create the database records.
This helps to avoid situations where the organisations can be partially created, which in the case of missing clinics can be clinically unsafe.
I'm raising this to get a review on the approach taken, but I think there are a number of follow tasks required:
- Document this onboarding process
- Set up our test environments using this process rather than seeds
- Remove Rake tasks which should no longer be used
```
❯ bundle exec rails onboard[spec/fixtures/files/onboarding/invalid.yaml]
Programmes can't be blank
Clinics can't be blank …
```
> Refactor how organisations are onboarded

- docs/onboarding.md
This adds some documentation explaining how to onboard a new organisation and the format of the configuration YAML file.
> Add documentation for onboarding process

- app/controllers/pages_controller.rb
This ensures we use a standardised implementation to generate the KIDs that will be used by JWTs we generate for CIS2 and NHS API.
> Generate rfc-standard kids on the jwks endpoint

- spec/factories/vaccination_records.rb
This manifests itself when trying to download offline and re-upload a seeded session.
> Vaccination Record factory: don't set delivery method when not administered

- app/components/app_import_format_details_component.rb
- app/models/immunisation_import_row.rb
- spec/models/immunisation_import_row_spec.rb
Without this, the offline export is incomplete and offline recording wouldn't allow the same reasons for refusal as online recording.
> Imms import: allow all Mavis reasons within REASON_NOT_VACCINATED

- app/components/app_import_format_details_component.rb
- app/models/immunisation_import_row.rb
- config/locales/en.yml
- spec/models/immunisation_import_row_spec.rb
For current academic year:
* make sure the site is appropriate for the administered vaccine (e.g. disallow importing HPV injections into the buttocks or nose, nasal flu into the thigh)
* skip that validation for previous academic years to be more permissive of past data quality issues.
> Imms import: extra validations on anatomical site

- app/controllers/sessions_controller.rb
- app/models/session.rb
- app/policies/application_policy.rb
- app/policies/session_policy.rb
- app/views/sessions/show.html.erb
- config/brakeman.ignore
- spec/features/manage_school_sessions_spec.rb
- spec/policies/session_policy_spec.rb
This refactors the session actions to use a policy class, and ensures we're not allowing users to edit or close sessions when that action shouldn't be available.
> Use SessionPolicy for session actions

- app/components/app_patient_page_component.html.erb
- app/components/app_vaccinate_form_component.rb
- spec/components/app_patient_page_component_spec.rb
- spec/factories/patient_sessions.rb
- spec/features/hpv_vaccination_cannot_record_closed_spec.rb
This shouldn't be allowed if the session has been closed, so this prevents the users from being able to.
> Prevent vaccination and triages on closed sessions

- app/models/patient_import_row.rb
- spec/models/class_import_row_spec.rb
- spec/models/cohort_import_row_spec.rb
If we're importing a patient that doesn't already have a cohort we can set it without the user needing to review since there's been no change on the patient, their year group will be the same but internally the cohort will have been set.
> Don't review cohort if not already set

- app/controllers/patients_controller.rb
- spec/features/manage_children_spec.rb
If the patient hasn't been vaccinated in a session and the nurse asks for the patient to be removed from the cohort, they should also be removed from the sessions.
> Remove patients from sessions when removing from cohorts

- app/models/immunisation_import_row.rb
- spec/features/hpv_vaccination_offline_spec.rb
- spec/fixtures/immunisation_import/valid_flu.csv
- spec/models/immunisation_import_row_spec.rb
* For this academic year:
* email address is mandatory
* first and last name will be ignored if provided
* For previous years:
* for HPV, don't validate the presence of a vaccinator as it's unnecessary
* for flu, validate that either email or both first name and last name are present
* 'Administered' and 'not administered' outcomes are treated the same
I've separated out a couple of pre-factor commits.
> Imms import: tweaks to vaccinator validation and field logic

- app/models/session.rb
- spec/models/session_spec.rb
This ensures that the consent isn't available to be used in the clinic that the patient is moved to as self-consent can only be considered valid at a specific location.
> Invalidate self-consent when closing a session

- app/controllers/consents_controller.rb
- app/models/concerns/invalidatable.rb
- app/models/session.rb
- spec/features/invalidate_consent_spec.rb
- spec/features/withdraw_consent_spec.rb
If consent is withdrawn or invalidated, we need to invalidate any triages that were performed on the patient using the old consent responses. Currently this invalidates all triages, which works in most situations, however could be unnecessary if, for example, both parents consent and then one parent withdraws their consent, in that case you'd still expect the patient to be safe to vaccinate. However this seemed like a simpler solution for now, especially while we don't surface the invalidated triages, and we can iterate on this in the future.
> Invalidate triage after consent

- app/jobs/consent_form_matching_job.rb
- spec/jobs/consent_form_matching_job_spec.rb
This makes the job more readable while maintaining the same behaviour.
https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2454 will update this with an additional case as a follow-up.
> Refactor ConsentFormMatchingJob

- app/components/app_triage_notes_component.html.erb
- app/models/patient_session.rb
- spec/components/app_triage_notes_component_spec.rb
- spec/models/patient_session_spec.rb
This allows users to see invalidated triage notes if a consent is withdrawn or invalidated, while showing that they're no longer accurate with the strikethrough formatting.
> Show invalidated triage notes with a strikethrough

- app/models/session.rb
- spec/models/session_spec.rb
This was missed in d62ed3d278f3224f1fe43cfce2c88d5ab5bcb04e to cover the situation where a session has been closed, self-consents have been invalidated and therefore any associated triages must be invalidated too.
If we encounter a similar bug it might be worth refactoring this code to handle the invalidation in the consent model rather than in the controllers.
I also think it's worth adding a feature test for this in the future.
> Ensure self-consent triages are invalidated

- app/components/app_patient_summary_component.rb
- app/controllers/consent_forms_controller.rb
- app/models/patient.rb
- app/views/consent_forms/index.html.erb
- app/views/consent_forms/new_patient.html.erb
- config/routes.rb
- db/seeds.rb
- spec/features/parental_consent_create_patient_spec.rb
- spec/features/parental_consent_manual_matching_spec.rb
- spec/support/pds_helper.rb
When an unmatched consent form doesn't map to any existing patient, we want to allow users to create a new patient record. This record should use an NHS number that's looked up via PDS, have a consent attached to it that matches the consent from the parent form, and a parent that also uses the details from the form.
We don't display the option to create patient records for consent forms without an NHS number (e.g. where the PDS lookup didn't find any records).
TODO:
Prerequisites:
- https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2473
- https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2475
> Add link to create patients from consent forms

- app/models/session.rb
We have two different mechanisms that are both handling similar functionality:
- The `patient.pending_changes` hash can contain a `school_id` which can be applied to:
- update their location
- The `patient_session.proposed_session` id that can be applied to:
- update a patient's session
- update their location
The latter `proposed_session` mechanism is preferable in situations where the only thing that's changed as the result of a class list import is the patient's school. The patient shouldn't appear in the list of duplicate records to review, and instead appear in the session moves UI.
To prevent them from appearing in the duplicate records list, we can remove the `pending_changes["school_id"]` if a session is successfully proposed on their existing patient sessions.
> Remove pending school_id if session is proposed

- app/components/app_patient_summary_component.rb
- app/components/app_patient_table_component.html.erb
- app/components/app_vaccination_record_table_component.html.erb
- app/helpers/patients_helper.rb
- spec/helpers/patients_helper_spec.rb
When rendering an NHS number for a patient, we should render it as striked through if the patient is marked as invalid so the nurses are able to see from the patient page that the patient is invalid.
> Strikethrough invalid NHS numbers

- app/components/app_patient_page_component.html.erb
- app/components/app_patient_summary_component.rb
- app/views/consent_forms/new_patient.html.erb
- app/views/patients/edit.html.erb
- app/views/patients/show.html.erb
- app/views/vaccination_records/show.html.erb
- spec/components/app_patient_summary_component_spec.rb
- spec/features/import_child_records_with_duplicates_spec.rb
- spec/features/import_class_lists_with_duplicates_spec.rb
Various parts of the patient's address can change when importing from class lists and cohort lists so we should ensure this is all visible to the user rather than just showing the postcode.
In all cases where the patient summary component is used we are now showing the full address and preferred name, so these options can be removed and we can show it in all cases.
> Show patient address when comparing duplicates

- app/models/immunisation_import_row.rb
- spec/models/immunisation_import_row_spec.rb
If a vaccinator email address has been provided, even if it's for historical records, we should validate that the email address exists otherwise we currently silently ignore these errors.
> Validate vaccinator email address if provided

- app/models/draft_consent.rb
- app/views/draft_consents/notes.html.erb
- spec/features/verbal_consent_refused_personal_choice_spec.rb
- spec/models/draft_consent_spec.rb
When refusing consent for personal reasons, we don't require notes to be provided, but this causes a validation error when trying to save the consent as we require this field to be `not null`. Instead we should save this as a blank string.
> Ensure consent refused can be given without notes

- app/controllers/dev_controller.rb
Leaving these behind will raise foreign key constraint errors when deleting patients.
> Remove triage objects on reset

- app/controllers/vaccinations_controller.rb
- spec/features/delete_vaccination_record_spec.rb
The current behaviour seems to be confusing for users, where we don't always show vaccination records as having been deleted in the activity log. This changes that to be consistent and always show the information in the log, as suggested by our designer.
> Show all vaccination deletions in activity log

- app/models/immunisation_import_row.rb
- config/locales/en.yml
- spec/models/immunisation_import_row_spec.rb
If the row is marked as not vaccinated, we should ensure that a batch, vaccine, delivery site is not provided. Similarly, if a row is marked as vaccinated, we should ensure that a reason not vaccinated is not provided.
> Make immunisation row validation stricter

- app/controllers/vaccinations_controller.rb
- app/models/draft_vaccination_record.rb
- config/locales/en.yml
If the user is answering the question "Did they get the vaccine?" and the user doesn't select an item, we currently assume this to mean no, but instead we should show an error message.
> Show error message if no radio button for vaccine selected

- app/components/app_activity_log_component.rb
- spec/components/app_activity_log_component_spec.rb
This is particularly useful if a nurse is recording verbal or paper consent, if the parent gives consent via online then this won't be shown.
> Include who recorded consent in activity log

- app/controllers/concerns/vaccination_mailer_concern.rb
- app/controllers/vaccinations_controller.rb
- app/lib/govuk_notify_personalisation.rb
- app/mailers/vaccination_mailer.rb
- config/initializers/govuk_notify.rb
- spec/features/delete_vaccination_record_spec.rb
- spec/lib/govuk_notify_personalisation_spec.rb
- spec/mailers/vaccination_mailer_spec.rb
This sends an email to the parents explaining that the email they would have received for the vaccination when it was recorded was incorrect and they can ignore it.
> Send email after deleting a vaccination record

- app/lib/reports/export_formatters.rb
- app/lib/reports/offline_session_exporter.rb
- spec/lib/reports/offline_session_exporter_spec.rb
It seems like Excel is not interpreting the new line character correctly, so we need to add some styles to the cells to ensure the content is word wrapped.
I don't have Excel to test this works correctly, but it's based on reading through: https://stackoverflow.com/questions/25770025/rails-axlsx-new-line-in-cell
> Render offline health questions on individual lines

- spec/factories/consents.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
It should take the questions from the programme when that's set. This manifests itself in specs and in the seeded consent responses.
> Consent factory should generate more realistic health questions

- app/components/app_session_patient_table_component.rb
- app/controllers/concerns/patient_sorting_concern.rb
- app/views/programme/patients/index.html.erb
- app/views/register_attendances/index.html.erb
- app/views/vaccinations/index.html.erb
- config/locales/patient_session_statuses.en.yml
- spec/components/app_session_patient_table_component_spec.rb
The outcome column isn't used in the patient's table anywhere in the prototype anymore.
> Replace outcome column with status

- app/lib/reports/offline_session_exporter.rb
- app/lib/reports/programme_vaccinations_exporter.rb
- app/models/immunisation_import_row.rb
- spec/features/hpv_vaccination_offline_spec.rb
- spec/lib/reports/offline_session_exporter_spec.rb
- spec/models/immunisation_import_row_spec.rb
This is necessary to support restricted patients, ones where the postcode is not allowed to be seen by the nurse. We need to update the offline recording spreadsheet to not include the postcode for any restricted patients, and similarly, we need to make it possible to upload a vaccination file without a postcode.
> Allow downloading and uploading vaccinations without postcodes

- README.md
When running through the readme for getting Mavis running locally, and being new to `asdf` I spotted an omission in getting `asdf` working properly. Namely, sourcing it in your shell environment.
> Add missing instruction to complete `asdf` installation

- app/controllers/draft_consents_controller.rb
The consent column can also include self-consents, where the parent will be `nil`, so we should filter those out.
> Avoid showing nil parents

- app/controllers/draft_consents_controller.rb
- spec/features/verbal_consent_given_spec.rb
We won't always have the name for a parent so we should be sorting on the label instead which handles the case when the name isn't there.
https://good-machine.sentry.io/issues/6078125818/
> Sort parent options by label rather than name

- app/views/draft_consents/triage.html.erb
- spec/features/verbal_consent_given_keep_in_triage_spec.rb
This is a bug that was introduced when we switched to creating consents in the browser session.
> Ensure triage notes are saved correctly

- app/helpers/application_helper.rb
This ensures that we HTML escape the characters correctly so the titles render properly.
> Safe join page titles

- app/controllers/programmes_controller.rb
- app/views/programmes/show.html.erb
This will be replaced with something more useful in future.
> Remove confusing and non-performant dashboard squares

- app/controllers/dev_controller.rb
- spec/features/dev_reset_organisation_spec.rb
Consents have a relationship to consent forms, so consent forms need to be deleted first to avoid foreign key constraint errors.
https://good-machine.sentry.io/issues/6079915091/
> Delete consent forms first in dev reset endpoint

- app/controllers/draft_consents_controller.rb
- app/controllers/draft_vaccination_records_controller.rb
- app/controllers/vaccinations_controller.rb
- app/controllers/vaccines_controller.rb
- app/models/batch.rb
- app/policies/batch_policy.rb
- spec/features/edit_vaccination_record_spec.rb
- spec/models/batch_spec.rb
- spec/policies/batch_policy_spec.rb
When editing a vaccination record, it's possible that the batch has expired or been archived since the vaccination record was created. In that case we should still show this batch as an option if the user chooses to edit the record.
I've also refactored the policies and controllers to simplify the code slightly.
> Show archived or expired batches when editing records

- app/controllers/vaccines_controller.rb
- app/views/vaccines/index.html.erb
- spec/features/manage_batches_spec.rb
Brings pages a little closer to design used in prototype:
- Make pages full width within this controller
- Use secondary button style for ‘Add a new batch’ (adding ‘new’ to this text)
- Use normal paragraph style for manufacture
I haven’t update the card header to the design used in the prototype, as the prototype doesn’t currently provide for a link to vaccine details, and I don’t want to change the scope of what’s shown/not shown here.
|-|-|
| <img width="1160" alt="Screenshot before" src="https://github.com/user-attachments/assets/871e2f7b-bc2d-4ed0-a42c-88577e575568"> | <img width="1190" alt="Screenshot after" src="https://github.com/user-attachments/assets/2d41d986-776e-4dc3-8534-86ab1383e169"> |
> Vaccines page layout

- app/controllers/draft_consents_controller.rb
- app/jobs/text_delivery_job.rb
- app/models/draft_consent.rb
- spec/jobs/text_delivery_job_spec.rb
Currently when queuing a `TextDeliveryJob` the details of the parent can come from three places, the `consent_form`, the `consent` or a `parent` directly. When passing it only a `consent`, we weren't correctly checking the value of `phone_receive_updates` on the parent meaning that the parent would receive a text even if they didn't request one.
> Handle sending texts from a consent correctly

- app/models/draft_consent.rb
- spec/models/draft_consent_spec.rb
When the parent fills out a consent form, we allow the email address to be optional, so we should do the same when a nurse fills in verbal consent. However, if a nurse doens't provide an email address we need to ensure that a phone number is provided instead.
> Validate that either parent phone or email is present

- app/components/app_patient_page_component.html.erb
- app/views/vaccination_records/show.html.erb
- spec/features/edit_vaccination_record_spec.rb
An admin doesn't have permission to edit vaccination records, so we shouldn't show this button if permission is not allowed.
> Hide "Edit vaccination record" button for admins

- .github/workflows/deploy-production.yml
Because our prod account is different from the non-prod ones, this is the quickest way to setup deploys to production via GitHub Actions.
Note that this will require that we setup the GitHubActionsRole in the production environment.
> Add prod deploy workflow

- app/views/parent_interface/consent_forms/edit/address.html.erb
- app/views/parent_interface/consent_forms/edit/parent.html.erb
Add relevant `autocomplete` values to the following fields in the consent journey:
- Parent name
- Parent email
- Parent telephone
- Parent address
> Add autocomplete values to relevant consent form fields

- app/controllers/application_controller.rb
- app/controllers/parent_interface/consent_forms/base_controller.rb
- app/views/dashboard/index.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- Service guidance should only be shown to users of ‘Manage vaccinations in schools’
- The privacy policy should only be shown to users of ‘Give or refuse consent for vaccinations’ (if a privacy policy URL has been set for the organisation)
This PR makes the existence of values for `@service_guide_url` and `@privacy_policy_url` determine whether links to these resources are shown in the footer, with controllers setting either the appropriate values for these resources, or `false`.
This also fixes an issue with an empty `li` being shown if no `@privacy_policy_url` is set.
Also renames the remaining `guide.show.title` locale string, moving it alongside the other `service` locale key to `service.guide.title`.
> Conditionally show links in footer

- app/controllers/patients_controller.rb
The patient is marked as strict loading and this is shown in the activity log so we need to ensure this is available.
https://good-machine.sentry.io/issues/6082397978/
> Pre-fetch consent recorded_by

- app/jobs/patient_nhs_number_lookup_job.rb
- app/jobs/patient_update_from_pds_job.rb
- spec/jobs/patient_nhs_number_lookup_job_spec.rb
- spec/jobs/patient_update_from_pds_job_spec.rb
If we look up a patient from their NHS number and we get a response from PDS saying either the NHS number is invalid or the patient is invalidated, we should try once to look up their new NHS number from their demographic data (names, postcode, date of birth). This could help to handle the case where the nurse has entered an NHS number incorrectly.
> Look up NHS numbers for invalidated patients

- app/controllers/class_imports_controller.rb
- app/controllers/cohort_imports_controller.rb
- app/controllers/immunisation_imports_controller.rb
- spec/features/hpv_vaccination_offline_spec.rb
- spec/features/import_child_records_spec.rb
- spec/features/import_child_records_with_duplicates_spec.rb
- spec/features/import_class_lists_move_spec.rb
- spec/features/import_class_lists_spec.rb
- spec/features/import_class_lists_with_duplicates_spec.rb
- spec/features/import_vaccination_records_spec.rb
- spec/features/import_vaccination_records_with_duplicates_spec.rb
If the file is small and can be processed immediately, we can take the user directly to the page showing the results of the import, and avoid showing a potentially confusing message of "Import completed" when there could actually be validation errors.
> Redirect user to import page if file is small

- app/controllers/draft_consents_controller.rb
- app/controllers/draft_vaccination_records_controller.rb
- spec/features/edit_vaccination_record_spec.rb
We previously used to reset the session after the user confirms changes, this was mostly to handle the limited size of the session when it was stored in cookies. However, now that we're storing these in the database we can leave the session and allow the user to go back without raising an error.
https://good-machine.sentry.io/issues/6072791861/
> Allow navigating back to draft consent/vaccination record

- .github/workflows/deploy.yml
The default is `true` which is causing 1 failed deploy to an environment to cancel deploying to all other environments.
> Don't fail fast when running deploy task

- copilot/webapp/manifest.yml
Previously we had the root domain, 'manage-vaccinations-in-schools.nhs.uk', CNAMEd to our app so that users can hit it and be redirected to the 'www.'. This is not RFC compliant, and we've been told by NHS's DNS team that we can't do that. Apparently there are ways to do this, but it can depend on the provider and in our case, they simply setup A records to point to the IPs of our LBs at the time, which can go (and have gone) stale.
Until we find a way to properly CNAME the root domain we need to change our settings to use the 'www' hostname.
> Add www. to hostnames

- config/onboarding/smoke-test.yml
- db/seeds.rb
- docs/onboarding.md
- lib/tasks/schools.rake
- script/set_up_coventry.sh
Once this is deployed to production the next steps are:
- Run the rake task to add the smoke-test school
- Run the rake task to onboard the smoke-test org
- Then login to org `Y90128` should work and sessions should be visible
> Add smoke test onboarding yaml

- app/controllers/dev_controller.rb
This avoids the list of batches growing and growing, as they belong to each organisation.
> Remove batchs when reseting organisations

- script/delete_old_review_apps.sh
We had ~3k review app environments in GitHub which made the environment settings UI impossible to use in order to add deploy conditions to the production environment (28+ pages):
This script facilitates deleting review apps 100 at a time.
We can later add a GitHub action to run this ~once a week.
```
$ bash script/delete_old_review_apps.sh --help
Usage: bash script/delete_old_review_apps.sh [-h|--help]
Delete GitHub review app environments older than 7 days.
Requires GitHub CLI (gh) to be installed and authenticated.
Options:
-h, --help    Show this help message
$ bash script/delete_old_review_apps.sh
Fetching review apps older than 7 days (max: 100)...
Deleting review app: mavis-pr-1924
Deleting review app: mavis-pr-1925
Deleting review app: mavis-pr-1926
Deleting review app: …
```
> Add script to delete old review apps

- app/jobs/bulk_update_patients_from_pds_job.rb
- app/jobs/concerns/nhs_api_concurrency_concern.rb
- app/models/concerns/csv_importable.rb
This changes how the jobs to update patient information in PDS are scheduled to introduce gaps between the jobs as part of the enqueue process rather than relying only on Good Job to handle the concurrency throttling.
Due to the way Good Jobs concurrency throttling works, we end up with lots of job failures from `ThrottleExceeded` exceptions, where the jobs are then enqueued at a later date. This approach works but is very resource intensive, given our rate of 5 requests per second and the fact that the majority of our jobs will fail.
I'm also seeing race condition issues when we have lots of jobs they don't seem to be able to succeed, and I reckon this is down to the fact that by the time the jobs are ready to run, they're no longer part of the active jobs.
These jobs are run on a …
> Refactor PDS background jobs to improve performance and possible race conditions

- app/lib/reports/careplus_exporter.rb
- spec/lib/reports/careplus_exporter_spec.rb
We were calling `hash[string]` and getting a `nil` coded_site, leading to the field being empty.
> Fix delivery sites in Careplus export

- app/views/vaccination_reports/dates.html.erb
It looks like you can omit both fields, and it still works as you'd expect.
> Add "optional" to the vaccination export dates

- app/models/patient.rb
- spec/features/parent_consent_school_session_completed_spec.rb
- spec/features/parental_consent_clinic_spec.rb
If we're trying to move a patient between the same session we don't need to propose a change since there's no move to take place. This also fixes a bug where confirming the move would remove the patient from the session because we end up with a single patient session that ends up being deleted by `confirm!` rather than two patient sessions.
I've also improved our clinic parental consent feature test to ensure this scenario is fully tested, including the nurse logging in and checking for any moves and the patient school details.
> Don't move patient if sessions are the same

- app/lib/unscheduled_sessions_factory.rb
This is unnecessary as we want to create the sessions well before an organisation has any patients, as part of onboarding. This also helps us in preparation for the removal of the `create_patient_sessions!` method as we decouple school moves with session moves.
> Don't create patient sessions in UnscheduledSessionsFactory

- app/models/patient.rb
- app/policies/patient_policy.rb
- spec/models/patient_spec.rb
This adds a scope for getting patients that belong to a particular organisation, so it can be used in multiple places.
> Add Patient#in_organisation scope

- app/components/app_compare_consent_form_and_patient_component.rb
- app/models/class_import_row.rb
- app/models/cohort_import_row.rb
- app/models/consent_form.rb
- app/models/immunisation_import_row.rb
- app/models/patient.rb
- app/models/patient_session.rb
- app/views/parent_interface/consent_forms/confirm.html.erb
- db/migrate/20241128081013_consolidate_patient_school_home_educated.rb
- db/schema.rb
- spec/factories/patient_sessions.rb
- spec/factories/patients.rb
- spec/models/class_import_row_spec.rb
- spec/models/cohort_import_row_spec.rb
- spec/models/consent_form_spec.rb
This consolidates the values of `school` and `home_educated` to use them in a consistent way across the service. This means that there will be three possible combinations of these values:
- `school` present and `home_educated` `nil`
- `school` `nil` and `home_educated` `true`
- `school` `nil` and `home_educated` `false`
I've also fixed a bug where a school move for a home-schooled patient wouldn't update their home-schooled status, which would lead to them staying in the community clinic when they should instead be added to the school.
> Consolidate school and home_educated values

- app/assets/stylesheets/_button-group.scss
- app/assets/stylesheets/_button.scss
- app/assets/stylesheets/_summary-list.scss
- app/assets/stylesheets/_table.scss
- app/components/app_consent_component.html.erb
- app/components/app_consent_component.rb
- app/components/app_consent_form_summary_component.rb
- app/components/app_consent_patient_summary_component.rb
- app/components/app_consent_status_component.rb
- app/components/app_consent_summary_component.rb
- app/components/app_health_questions_component.rb
- app/components/app_import_format_details_component.html.erb
- app/components/app_matching_criteria_component.html.erb
- app/components/app_outcome_banner_component.rb
- app/components/app_vaccination_record_summary_component.rb
- app/views/draft_consents/confirm.html.erb
- app/views/imports/show.html.erb
- app/views/parent_interface/consent_forms/confirm.html.erb
- app/views/sessions/edit.html.erb
- config/locales/en.yml
- spec/components/app_consent_component_spec.rb
- spec/components/app_consent_status_component_spec.rb
Few design-related fixes and updates, bring a few areas inline with the prototype:
- Remove `.app-summary-list--no-bottom-border` class (we previously added a CSS-only fix)
- Remove unused `.app-table--patients` style
- Remove unused `.app-table--select-cohort` style
- Use `app-table--csv` and `app-table--small` styles in combination
- Remove margin from `.nhsuk-button` when inside a `.button_to` Rails form button (which will have inherited any contextual margins)
- Fix alignment within button groups (due to presence of `.button_to` Rails form buttons) 
- Fix colours and micro copy used for overall consent status
- Add status colours to consent responses
| - | - |
| ![consent-card-before](https://github.com/user-attachments/assets/12d74ff6-3bde-4cb0-a712-f30aa0ca426b) | …
> Design fixes

- db/migrate/20241128081013_consolidate_patient_school_home_educated.rb
This migration is failing and we're not sure why, so this should give us a clue as to why the patients are still invalid.
> Print first invalid patient errors

- app/lib/reports/offline_session_exporter.rb
- app/lib/reports/programme_vaccinations_exporter.rb
- spec/lib/reports/offline_session_exporter_spec.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
This adds a `PROGRAMME_NAME` column to the offline session and "Mavis format" programme exports as otherwise this has to be inferred from the name of the vaccine.
This also adds a `PERSON_ADDRESS_LINE_1` column to the offline session and "Mavis format" programme exports to make these files more useful to nurses.
> Add programme and first line of address to exports

- app/controllers/school_moves_controller.rb
- app/helpers/school_moves_helper.rb
- app/models/location.rb
- app/models/session.rb
- app/views/application/_header.html.erb
- app/views/dashboard/index.html.erb
- app/views/school_moves/index.html.erb
- app/views/sessions/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/seeds.rb
- spec/features/import_class_lists_move_spec.rb
- spec/features/parental_consent_clinic_spec.rb
This replaces the existing school moves section on each session to instead be a single global school moves which displays all moves across the organisation.
> Global school moves

- script/aws_splunk_setup.rb
Prerequisite: https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2581
This encapsulates all the necessary AWS CLI steps to wire up an existing log group to Splunk.
The script is idenmpotent and can be run multiple times to ensure everything is set up in case it fails/times out on one run.
Usage:
```bash
$ RAILS_ENV=staging bin/rails runner script/aws_splunk_setup.rb
Usage: RAILS_ENV=staging bin/rails runner script/aws_splunk_setup.rb <environment>
Needs RAILS_ENV to be set to staging or production, and an active AWS
session with the necessary permissions.
Arguments:
environment    - The Copilot environment name (test, training, etc)
$ RAILS_ENV=staging bin/rails runner script/aws_splunk_setup.rb test
S3 bucket mavis-splunk-firehose-errors already exists
IAM role …
```
> Create aws_splunk_setup script 

- app/controllers/school_moves_controller.rb
- app/forms/school_move_form.rb
- app/views/school_moves/index.html.erb
- app/views/school_moves/show.html.erb
- config/locales/en.yml
- config/locales/helpers.en.yml
- config/routes.rb
- spec/features/import_class_lists_move_spec.rb
- spec/features/parental_consent_clinic_spec.rb
This changes how school moves are confirmed or ignored to add a new page which gives the user the option to choose from radio buttons on what action to take.
This will be extended in the future to allow the user to choose whether to keep the patient in the community clinic or not.
> Add school move confirmation page

- app/components/app_import_format_details_component.rb
- app/lib/reports/offline_session_exporter.rb
- app/models/immunisation_import_row.rb
- spec/features/hpv_vaccination_offline_spec.rb
- spec/lib/reports/offline_session_exporter_spec.rb
- spec/models/immunisation_import_row_spec.rb
This adds the ability to upload vaccination records offline with notes by adding a `NOTES` column to the immunisations import CSV file.
> Allow recording notes offline 

- app/lib/reports/offline_session_exporter.rb
- spec/lib/reports/offline_session_exporter_spec.rb
The nurses won't be vaccinating these patients and by keeping them in the spreadsheet they either have to record them as unvaccinated or remove the rows which isn't intuitive.
> Hide refused consent patients from offline export

- app/lib/reports/offline_session_exporter.rb
This refactors the offline session exporter to move the types and styles on a `Cell` class, meaning they can be controlled at an individual cell level, while also keeping a cache of styles to ensure the same style isn't created multiple times in the same sheet.
This change will also make it easier to implement row-level styles, such as coloured backgrounds which we need for patients without consent.
> Refactor OfflineSessionExporter

- app/lib/reports/offline_session_exporter.rb
If the patient doesn't have consent, this highlights the row in a light red colour (the same used as the background of red tags in the GOV.UK Design System) to help the nurse using the spreadsheet.
> Highlight offline rows without consent

- app/controllers/school_moves_controller.rb
- app/forms/school_move_form.rb
- app/models/consent_form.rb
- app/models/school_move.rb
- app/views/school_moves/show.html.erb
- config/locales/en.yml
- config/locales/helpers.en.yml
- spec/factories/patients.rb
- spec/features/parental_consent_clinic_spec.rb
- spec/models/school_move_spec.rb
This adds an option when confirming a school move that allows the nurses to confirm whether to keep the patient in the community clinic or move them to an upcoming school session if that's available.
This is necessary to handle the situation where a parent fills in the consent form for a community clinic and tells us that their child belongs to a school, however we can't move them to the school in case the parent has already booked them in to a clinic.
> Allow moving community clinic patients to school

- app/lib/reports/offline_session_exporter.rb
- spec/lib/reports/offline_session_exporter_spec.rb
When exporting the offline session spreadsheet this ensures that the header row, and the first two columns (the patient first name and last name) are frozen, meaning that they are always visible when scrolling and navigating around the spreadsheet. This should make it easier for nurses to use.
> Freeze header and patient name cells

- app/controllers/gillick_assessments_controller.rb
If the user submits the Gillick assessment form with no changes, we want to avoid creating unnecessary duplicate records (which also leads to them showing in the activity log).
This was supposed to be working before but wasn't because `dup` creates a duplicate record with changes so the new record was always being saved.
> Avoid creating duplicate gillick assessments

- app/assets/stylesheets/_button-group.scss
- app/assets/stylesheets/_button.scss
- app/components/app_patient_page_component.html.erb
- app/views/imports/index.html.erb
- app/views/programmes/show.html.erb
- app/views/vaccination_records/index.html.erb
Bring across updated CSS styles from the prototype:
- Updates secondary buttons so that they don’t shift surrounding layout when active/pressed
- Updates button groups to fix alignment for table variant (and be clearer to read)
Also:
- Fix button margins on various buttons spotted in the app (containing `button_to` forms are a bit of a pain 🫤)
> Design fixes, part 2

- db/seeds.rb
When seeding the database for the first time, this helps to avoid issues where the same location is shared by sessions across the two organisations.
> Only attach unknown schools to organisations

- app/controllers/programmes_controller.rb
- app/views/programmes/patients.html.erb
- spec/features/patient_sorting_filtering_spec.rb
This fixes an issue where the status wasn't filtering because it was showing a list of patients which don't have a status. We had previously changed this to show patients who aren't in sessions, but because of the new school moves work, a patient should always belong to at least one session, and if not then a bug has happened elsewhere in the service.
> Use patient sessions in children view

- app/views/draft_consents/route.html.erb
Online consent means it came from the parental consent form directly, we shouldn't be giving the nurses the option to record consent via this route.
Having this route here could also be confusing, as the nurses will be using an online service to record consent.
> Don't allow nurses to submit online consent

- app/controllers/patient_sessions_controller.rb
- app/controllers/register_attendances_controller.rb
- app/controllers/session_attendances_controller.rb
- app/models/patient_session.rb
- app/models/patient_session_stats.rb
- app/policies/session_attendance_policy.rb
- app/views/patient_sessions/show.html.erb
- app/views/session_attendances/edit.html.erb
- config/locales/en.yml
- spec/features/e2e_journey_spec.rb
- spec/policies/session_attendance_policy_spec.rb
This updates the logic around session attendance to prevent the attendance record from being edited once a patient has been vaccinated, or an un-administered vaccination record has been recorded.
> Prevent attendance being edited after vaccination

- app/lib/reports/careplus_exporter.rb
- spec/lib/reports/careplus_exporter_spec.rb
We don't need to include these records in the Care Plus export and they're not being sent currently.
> Exclude unadministered vaccinations records from Care Plus

- app/javascript/serviceworker/online-status.js
- config/environments/production.rb
This was forgotten in https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2621.
> Don't force SSL on healtcheck endpoint

- Gemfile
- Gemfile.lock
> Remove silencer dependency

- app/lib/reports/programme_vaccinations_exporter.rb
- spec/factories/locations.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
When exporting information using the Mavis-format, we want to include the GP information about the patient, if it's available. This will be included in a `GP_ORGANISATION_CODE` and `GP_NAME` column.
> Include GP information in Mavis-format export

- app/models/location.rb
- spec/lib/reports/careplus_exporter_spec.rb
- spec/models/location_spec.rb
Although presented this way on the GIAS website, it looks like the CarePlus format doesn't include the slash, since this is the only place we're using this number we can safely remove it.
> Remove slash in DfE number

- app/models/vaccination_report.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
I've decided to do this by removing the settings configuration as we're unlikely to need to disable individual exports again, we can always revert this change if necessary.
> Enable CarePlus export in all environments

- app/controllers/dev_controller.rb
Currently we're deleting school moves within or out of the organisation, but not moves where the patient is moving in to the organisation.
> Delete incoming schools for an organisation when resetting

- app/models/school_move.rb
- spec/models/school_move_spec.rb
When confirming a school move we should remove any others for the same patient to avoid the nurses needing to manually ignore any other school moves per patient.
> Delete all patient school moves when confirming

- app/models/concerns/patient_session_status_concern.rb
- spec/factories/consents.rb
- spec/models/patient_session_spec.rb
This method is used in a number of places to determine the status of a patient session. In the case where one consent was invalidated and one consent was not provided, this method was returning `false` which would then lead to consent being shown as given when this was not the case.
I've added some unit tests for this method to make sure we cover this scenario.
> Fix bug related to PatientSession#no_consent?

- app/components/app_patient_page_component.html.erb
- app/components/app_patient_page_component.rb
- app/components/app_vaccinate_form_component.html.erb
- app/components/app_vaccinate_form_component.rb
- app/controllers/patient_sessions_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations_controller.rb
- app/forms/vaccinate_form.rb
- app/views/draft_vaccination_records/delivery.html.erb
- app/views/parent_interface/consent_forms/edit/name.html.erb
- app/views/patient_sessions/show.html.erb
- config/locales/en.yml
- spec/components/app_patient_page_component_spec.rb
- spec/components/app_vaccinate_form_component_spec.rb
- spec/features/e2e_journey_spec.rb
- spec/features/hpv_vaccination_administered_spec.rb
- spec/features/hpv_vaccination_already_had_spec.rb
- spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb
- spec/features/hpv_vaccination_cannot_record_closed_spec.rb
- spec/features/hpv_vaccination_clinic_spec.rb
- spec/features/hpv_vaccination_default_batch_spec.rb
- spec/features/hpv_vaccination_delayed_spec.rb
- spec/features/invalidate_consent_spec.rb
- spec/features/manage_attendance_spec.rb
- spec/features/triage_delay_vaccination_spec.rb
- spec/features/withdraw_consent_spec.rb
This adds a new form which represents the form shown on the vaccination section of the patient page and updates the UI to match the latest version in the prototype, in preparation for adding the new pre-screening questions.
> Add VaccinateForm

- app/controllers/gillick_assessments_controller.rb
- app/controllers/register_attendances_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations_controller.rb
This ensures that the user will see a 404 error if they try to access a page for a patient session that doesn't exist, rather than a 500 error they would see currently.
> Use find_by! when looking up patient sessions

- app/views/draft_vaccination_records/outcome.html.erb
- config/locales/en.yml
The user shouldn't be able to get to this page if they've marked the patient as absent for the session so we no longer need this options available. This matches the designs in the prototype.
> Remove absent not vaccinated reasons

- config/application.rb
Rails 7.2 defaults toggle this to `true` when running Ruby 3.3 or newer. Since we are still using 7.1 defaults, we need to manually toggle it on.
yjit brings significant performance improvements to Ruby.
> Enable Ruby yjit

- tests/load.yml
Add more users in the sustained load phase to prevent running out.
Increase the delay between each action so that one user finishes a journey in around 1 minute, now that the GP step has been removed.
> Update load test

- app/controllers/users/omniauth_callbacks_controller.rb
- spec/factories/users.rb
This allows us to access the workgroups when determining what permissions a user might have. I'd like to deploy this first to ensure we start to populate this value before using it.
> Include workgroups in cis2_info

- app/controllers/import_issues_controller.rb
- app/controllers/patients_controller.rb
- app/controllers/vaccination_records_controller.rb
The patient is marked for strict loading meaning we need to load this from the query to avoid an exception being raised.
> Eager load GP pratice

- app/controllers/concerns/triage_mailer_concern.rb
- spec/controllers/concerns/triage_mailer_concern_spec.rb
- spec/features/self_consent_spec.rb
These consent instances won't have a parent attached to them so the subsequent emails and texts won't be able to be sent anyway so there's no need to try, and this reduces errors that we might see in Sentry.
https://good-machine.sentry.io/issues/5990496051/
> Don't send emails for self-consent

- app/lib/reports/programme_vaccinations_exporter.rb
- app/models/dps_export_row.rb
- app/models/vaccine.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
These `CSDS` columns are used by the reporting team so they need to be included in the export.
> Add additional columns to programme export 

- app/views/patients/index.html.erb
We're currently submitting this form with a `POST` request, which means that the pagination resets the filters as these are plain links and we lose the filter parameters. Switching to `GET` means the filters work with the pagination links.
> Use GET when filtering patients

- app/controllers/notices_controller.rb
- app/models/user.rb
- app/policies/notices_policy.rb
- app/policies/vaccination_record_policy.rb
- app/views/application/_header.html.erb
- app/views/dashboard/index.html.erb
- db/seeds.rb
- spec/factories/users.rb
- spec/features/delete_vaccination_record_spec.rb
- spec/features/manage_children_spec.rb
- spec/features/user_cis2_authentication_with_wrong_workgroup_spec.rb
- spec/models/user_spec.rb
- spec/policies/vaccination_record_policy_spec.rb
- spec/support/cis2_auth_helper.rb
This adds the concept of a user with superuser access (via the `mavissuperusers` workgroup in CIS2) and restricts access to the important notices and deleting vaccinations records to superusers.
> Add superusers and restrict access

- app/lib/reports/programme_vaccinations_exporter.rb
- app/models/dps_export.rb
- app/models/dps_export_row.rb
- app/models/programme.rb
- app/models/vaccine.rb
These seem to be the same per vaccine across a programme so we can move these to the programme model, which allows us to get these for vaccination records even if there's no vaccine (because the vaccination wasn't administered), to include them in the vaccinations report export.
https://good-machine.sentry.io/issues/6115142159/
> Move SNOMED codes to programme

- README.md
- docs/rake-tasks.md
- lib/tasks/access_log.rake
This displays the access logs either for a patient or for a user depending on the Rake task and the argument passed in. For now this just displayes the date/time, the controller and action, and the user or patient name.
```
❯ bundle exec rails access_log:for_user[nurse.joy@example.com]
2024-12-06T09:42:40+00:00 - patients/show - Alejandro Schuster
2024-12-06T09:43:53+00:00 - patients/show - Alejandro Schuster
2024-12-06T10:25:34+00:00 - patients/show - Alejandro Schuster
```
> Add Rake task for displaying access logs

- .github/workflows/test.yml
- .tool-versions
- README.md
- config/settings/development.yml
- config/settings/test.yml
We were using version 13.5 which is relatively old now, the latest version is 17.2. In production we're using a 16.3 compatible version via AWS Aurora, which auto updates and should catch up eventually.
> Upgrade PostgreSQL in local development

- app/models/user.rb
- spec/models/user_spec.rb
This can sometimes happen, if the user has no workgroups, so we need to handle this case gracefully rather than raising an exception.
> Handle nil workgroups in User#is_superuser?

- app/controllers/pages_controller.rb
- spec/features/import_child_records_with_duplicates_spec.rb
- spec/features/scheduled_consent_requests_spec.rb
Without this, the user sees the "Sign in" button even if they're already signed in.
> Redirect to dashboard path if signed in

- app/controllers/dev_controller.rb
This is necessary as without it we cannot delete the patients.
https://good-machine.sentry.io/issues/6115900064/
> Delete access log entries in dev reset endpoint

- Dockerfile
This ensures the Docker build doesn't attempt to log to Splunk.
> Disable Splunk when precompiling assets

- app/controllers/concerns/patient_sorting_concern.rb
If the patient has no registration it can return `nil`, and we using `try(:registration)` which also returns `nil` if the object doesn't respond to that method. This lead to us thinking the object wasn't a patient, and instead tried to call `.patient` on it which would then fail. Instead we need to first check if the object responds to the method before calling it.
https://good-machine.sentry.io/issues/6092014304/
> Handle sorting by year group with no registration

- app/models/user.rb
- spec/models/user_spec.rb
This applies only in non-CIS2 environments (local development and testing) to partially mimic the behaviour of CIS2 where a user has a role and a superuser status that are independent from each other. Currently in a non-CIS2 environment, the superuser status acts as its own role, which means users with that status have very limited access (they're able to access superuser actions only). To aid with testing, we can assume that if the user is a superuser they should also have admin permissions.
It's not currently possible to log in as a nurse user with superuser permissions at the same time.
> User should have admin permissions if they're a superuser

- spec/factories/consent_forms.rb
In this case, the location would be the community clinic, but the user would've been forced to choose a school so it would be different to the location of the community clinic.
This should have no impact on the existing tests, but will fix an issue in the `consent_forms:generate` Rake task.
https://good-machine.sentry.io/issues/6047022099/
> Handle generating consent forms for community clinics

- app/controllers/vaccination_reports_controller.rb
This can happen if the user navigates directly to one of the URLs without going through the normal UI flow, so a `programme` won't be stored in the session and we get an exception. The best alternative would be to redirect the user to the dashboard page.
https://good-machine.sentry.io/issues/6074722817/
https://good-machine.sentry.io/issues/6115196006/
> Handle accessing vaccination report with no programme

- app/lib/reports/offline_session_exporter.rb
Currently the order is not specified so the patients can appear in a random order, it probably makes sense to order these by name so they're easier to find.
> Order offline export spreadsheet by patient names

- .github/workflows/deploy.yml
The name is a bit redundant currently. ("Deploy / Deploy")
> Rename deploy job

- app/models/patient.rb
- spec/models/patient_spec.rb
Currently we raise an `ActiveRecord::RecordNotFound` error, but this causes the job to be discarded by ActiveJob without an exception being raised in Sentry as this kind of error can occur in other scenarios.
Instead, we can raise a specific error which is good practice anyway as it ensures these get treated in a special way which allows us to get a good idea of how often these happen anyway.
> Raise UnknownGPPractice if GP practice doesn't exist

- app/lib/reports/offline_session_exporter.rb
- spec/lib/reports/offline_session_exporter_spec.rb
This reverts commit fbde8a18c7a7d1c1b10764f8cb7866d33e046637.
We think these should be included in the offline export to handle cases where a Gillick assessment would be done instead.
> Revert "Hide refused consent patients from offline export"

- app/models/patient.rb
- config/settings.yml
- config/settings/staging.yml
- spec/models/patient_spec.rb
This also records the error in Sentry directly rather than raising an exception, which ensures that the patient is still updated from PDS even if the GP practice couldn't be located.
> Don't raise UnknownGPPractice errors in staging

- bin/brakeman
- bin/lint
- bin/rubocop
- bin/setup
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/puma.rb
This upgrades the default configuration values we're using to Rails version 7.2, matching the version of Rails we're using, and making any future upgrade to 8.0 slightly easier by reducing the number of potential changes.
> Upgrade to Rails 7.2 configuration defaults

- app/controllers/import_issues_controller.rb
Without this when the patient is displayed we get an error due to the strict loading requirements.
> Ensure `gp_practice` is loaded with join query

- app/controllers/concerns/authentication_concern.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- spec/features/user_cis2_authentication_with_empty_role_spec.rb
- spec/support/cis2_auth_helper.rb
We had a Sentry error where our logging showed that in some scenarios (we assume Smartcard native app use) CIS2 will send a user payload with an empty selected role. Since we can't match their selected role to an existing role and org, we should show an error in this scenario.
https://good-machine.sentry.io/issues/6122678933
> Handle situation where cis2 returns empty role

- app/controllers/application_controller.rb
We need to fall back to the `root_path` if the `referer` is on a different host.
Turns out there's a built-in helper in Rails for this:
- https://api.rubyonrails.org/v7.2.2/classes/ActionController/Redirecting.html#method-i-redirect_back_or_to
> Use redirect_back_or_to instead of redirect_to

- app/lib/reports/programme_vaccinations_exporter.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
To vaccinations export. This allows the user to see when the record was last created or updated, according to the record status.
> Add RECORD_DATE_TIME column

- .github/workflows/test.yml
- .tool-versions
- README.md
Our team is using it instead, it's a near drop-in replacement, so it makes sense to update our docs.
Latest postgres also requires some new deps/env vars but less workarounds now with `mise`.
> Switch from asdf to mise

- package.json
- yarn.lock
This silences the warning from `axe-core` that depends on `playwright-core`.
> Add explicit dependency on playwright-core

- app/components/app_patient_page_component.html.erb
- app/controllers/vaccination_records_controller.rb
- app/controllers/vaccinations_controller.rb
- app/views/vaccination_records/destroy.html.erb
- app/views/vaccination_records/show.html.erb
- config/routes.rb
- spec/features/delete_vaccination_record_spec.rb
When looking at an individual vaccination record for a patient this adds a "Delete vaccination record" button similar to the one we have when deleting a vaccination record from a session.
> Add ability to delete from vaccination record page

- app/lib/govuk_notify_personalisation.rb
- spec/lib/govuk_notify_personalisation_spec.rb
This allows the privacy policy to be included in any email communication sent to parents.
> Pass privacy policy URL to GOV.UK Notify templates

- app/models/vaccination_record.rb
- spec/models/vaccination_record_spec.rb
A vaccine that isn't administered doesn't have a batch, which means it doesn't have a vaccine. Without the vaccine, `maximum_dose_sequence` defaults to 1. If the `dose_sequence` is > 1, this breaks the validation.
We can also remove the `vaccine& || 1` default with this change.
> Don't validate dose_sequence if not administered

- .github/workflows/deploy.yml
The `accessibility` env has been torn down, and `pentest` is next.
> Don't auto-deploy accessibility and pentest

- app/controllers/import_issues_controller.rb
- app/models/patient.rb
- spec/features/import_child_records_with_duplicates_spec.rb
- spec/models/patient_spec.rb
When resolving a duplicate patient by keeping both patients, we need to ensure that the new patient is also included in any sessions that the old patient was part of, otherwise the patient will end up in the global children view but without any sessions.
This also ensures that any outstanding school moves for the old patient are also copied to the new patient, this is necessary because a nurse might resolve the duplicate before confirming the school move, so the old patient might not be in the right session when it is duplicated.
> Add new patients to upcoming sessions

- bin/docker-entrypoint
Because we're running `bin/thrust` before `bin/rails server`, we have to update the conditional for `db:prepare` to take this into account.
Also add the `jemalloc` bit which should significantly improve memory usage.
> Align docker-entrypoint to Rails 8 conventions

- db/seeds.rb
The testers need a different URN.
Also don't re-attach the same URNs to a different organisation - this messes up the setup.
> Update seed schools for automated testing

- app/lib/reports/programme_vaccinations_exporter.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
This makes it more obvious that the field is not whether the record was created or updated at all, but why it's present in the current export.
Also return `new` instead of `updated`, and simplify the logic.
We also include the `CREATED` and `UPDATED` timestamps for clarity. The updated timestamp is only shown if it's different from created_at.
> Simplify `RECORD_STATUS` to `REASON_FOR_INCLUSION` 

- app/lib/reports/careplus_exporter.rb
- app/models/vaccination_record.rb
- db/migrate/20241212145341_remove_left_and_right_arm_delivery_sites.rb
- db/schema.rb
- spec/features/edit_vaccination_record_spec.rb
- spec/features/hpv_vaccination_administered_spec.rb
- spec/features/hpv_vaccination_clinic_spec.rb
- spec/features/hpv_vaccination_default_batch_spec.rb
- spec/features/hpv_vaccination_pre_screening_spec.rb
- spec/models/draft_vaccination_record_spec.rb
These are not used and were forgotten from an earlier design of Mavis.
> Remove left and right arm delivery sites

- db/seeds.rb
Our testers need at least 2 fixed schools for the automation scenarios.
> Add Barn End Centre to seeds

- app/assets/stylesheets/_status.scss
- app/assets/stylesheets/_warning_text.scss
- app/assets/stylesheets/application.scss
- app/components/app_notice_status_component.rb
- app/components/app_patient_card_component.rb
- config/initializers/govuk_components.rb
Use a new `AppNoticeStatusComponent` (possibly too similar to `AppConsentStatusComponent` to suggest some broader refactoring needed given they both share the same style (`app-status`), that replaces the need to use GOVUK Warning Text component.
> Add and use `AppNoticeStatusComponent`, remove GOVUK Warning Text component

- .rubocop.yml
- spec/controllers/concerns/patient_sorting_concern_spec.rb
- spec/controllers/concerns/patient_tabs_concern_spec.rb
- spec/lib/govuk_notify_personalisation_spec.rb
- spec/lib/nhs/cis2_spec.rb
- spec/models/batch_spec.rb
- spec/models/concerns/wizard_step_concern_spec.rb
- spec/models/consent_form_spec.rb
- spec/models/consolidated_health_answers_spec.rb
- spec/models/immunisation_import_row_spec.rb
This refactors the final tests that don't use named subjects which then allows us to re-enable this linting rule.
> Re-enable RSpec/NamedSubject

- app/models/patient_session.rb
- db/migrate/20241213102755_add_foreign_key_on_patient_sessions.rb
- db/schema.rb
- spec/factories/patient_sessions.rb
- spec/models/patient_session_spec.rb
This adds a foreign key to patients and sessions from the patient sessions table, ensuring that patient sessions always refer to patients and sessions that exist.
It seems like this was missed when the table was set up originally.
> Add foreign key on patient sessions

- app/models/patient_session.rb
- db/migrate/20241213104730_update_patient_session_indexes.rb
- db/schema.rb
- spec/factories/patient_sessions.rb
- spec/models/patient_session_spec.rb
This updates the indexes on the patient session model to remove an unnecessary unique index and add missing indexes on the patient and session column.
The index on the individual columns should improve performance when looking up individual patient sessions for a patient or a session, related to the foreign key added in
b350c8eebae2097e008ee39f14db29d72ce55412.
The unique index on `session_id` and `patient_id` is unnecessary as we already have an index on `patient_id` and `session_id`.
> Update PatientSession indexes

- config/locales/en.yml
Without the fix, the screen reads "Cohort record record":
> Fix typo on school movers confirmation screen

- app/assets/stylesheets/_status.scss
- app/components/app_notice_status_component.rb
- app/components/app_patient_card_component.rb
- app/components/app_patient_page_component.html.erb
- app/components/app_patient_summary_component.rb
- app/controllers/consent_forms_controller.rb
- app/views/consent_forms/new_patient.html.erb
- app/views/patients/edit.html.erb
- app/views/patients/edit/nhs_number_merge.html.erb
- app/views/patients/show.html.erb
- app/views/vaccination_records/show.html.erb
- db/seeds.rb
- spec/components/app_patient_card_component_spec.rb
- spec/components/app_patient_page_component_spec.rb
This adds a number of flags to the component when viewing a "child record" allowing the nurses to see clearly if there are any flags on the patient.
> Add flags to child records

- app/models/patient_session.rb
When determining the `latest_triage` for a patient session, and therefore the status of a patient session. With a scope it forces the query to re-run even if the triages were preloaded, whereas doing it in Ruby means we avoid an extra query to the database. Because there are unlikely to be lots of triages for a particular patient session, this should improve performance.
> Don't use not_invalidated scope

- app/components/app_patient_table_component.html.erb
- app/components/app_patient_table_component.rb
- app/policies/school_move_policy.rb
- app/views/cohorts/show.html.erb
- app/views/imports/show.html.erb
- app/views/patients/index.html.erb
- spec/components/app_patient_table_component_spec.rb
If a user clicks on this link they are taken to a 404 error page which is not a good user experience, we should instead hide the link and explain why the patient is not available.
> Don't link to patients out of the organisation

- app/views/notices/index.html.erb
- spec/features/manage_children_spec.rb
This fixes a bug were notices were only visible if there was at least one deceased patient, and wouldn't show if there were only restricted or invalidated patients.
> Ensure notices are always visible

- spec/controllers/concerns/vaccination_mailer_concern_spec.rb
- spec/factories/consents.rb
- spec/factories/patients.rb
- spec/features/invalidate_consent_spec.rb
- spec/features/parental_consent_send_request_spec.rb
- spec/features/verbal_consent_but_no_triage_for_admin_spec.rb
- spec/features/verbal_consent_given_do_not_vaccinate_spec.rb
- spec/features/verbal_consent_given_keep_in_triage_spec.rb
- spec/features/verbal_consent_given_safe_to_vaccinate_spec.rb
- spec/features/verbal_consent_given_spec.rb
- spec/features/verbal_consent_refused_personal_choice_spec.rb
- spec/features/verbal_consent_refused_spec.rb
- spec/features/withdraw_consent_spec.rb
- spec/jobs/school_consent_reminders_job_spec.rb
- spec/lib/patient_merger_spec.rb
- spec/mailers/consent_mailer_spec.rb
- spec/mailers/session_mailer_spec.rb
- spec/models/patient_spec.rb
This simplifies the patient factory to not create parents by default to improve test performance and match production where patients won't necessarily always have parents attached to them.
> Don't create parents by default in tests

- tests/accessibility.spec.ts
These were commented out previously.
> Re-enable accessibility tests on release 1B pages

- spec/helpers/consent_forms_helper_spec.rb
- spec/jobs/mesh_dps_export_job_spec.rb
- spec/jobs/remove_import_csv_job_spec.rb
- spec/models/vaccine_spec.rb
- spec/routing/vaccinations_routing_spec.rb
- spec/spec_helper.rb
The type can be inferred from the filename so we don't need to specify a type in any of these files.
> Remove remaining explicit type from specs

- spec/spec_helper.rb
We use Google Chrome (via Cuprite) to run feature tests with client-side JavaScript. This updates the `spec_helper` to first detect whether Chrome is available, and if not, disable `:js` tests. This is because not all developers will have Chrome available on their machine.
We've only got one test that requires JavaScript so I thought this would be a simpler approach for now, if we add more then we might want to consider adding a Selenium WebDriver for Firefox or Safari as an alternative.
> Disable `:js` tests if Chrome is unavailable

- db/seeds.rb
- docs/rake-tasks.md
- lib/tasks/gp_practices.rake
- lib/tasks/schools.rake
This adds a Rake task which creates a GP practice suitable for smoke testing in production. We're using an ODS code that doesn't exist but is used by the smoke test patient in PDS in production.
I've also fixed an issue in the equivalent task for schools.
> Add gp_practices:smoke Rake task

- app/assets/stylesheets/_card.scss
- app/controllers/application_controller.rb
- app/controllers/concerns/authentication_concern.rb
- app/controllers/users/organisations_controller.rb
- app/models/user.rb
- app/views/users/organisations/new.html.erb
- config/routes.rb
- spec/models/user_spec.rb
- tests/accessibility.spec.ts
We currently default to `current_user.organisations.first` if users aren't signed in using CIS2 when deciding their `selected_organisation`.
This makes testing certain features harder, as there is no way for users to sign into multiple organisations. Amongst other things, we could use this capability in the training environment to set up 2 different organisations; one that is a blank slate, one that has data in it, to train on different scenarios.
This adds a page that simulates the "Select a role" page that users see when they login via CIS2. However, it asks the users to choose an organisation, not a role. The user is only asked on login, or during their current session if they haven't chosen one already. In environments where CIS2 is enabled, this functionality should not affect …
> Choose an organisation on login without CIS2

- app/models/onboarding.rb
- config/onboarding/hertfordshire-training-with-sessions.yaml
- config/onboarding/hertfordshire-training.yaml
These will be used to set up the training environment.
Also make some updates to the onboarding script to allow running two different orgs in parallel with the same `nurse.x` user.
> Add hertfordshire onboarding ymls

- app/controllers/register_attendances_controller.rb
This enables `.strict_loading` and includes the missing relationships to reduce the N+1 queries. 2-3x improvement locally.
The `.select` at the end still causes an N+1, and will be fixed separately.
> Improve performance on register attendance page

- app/components/app_consent_patient_summary_component.rb
- app/models/consent.rb
- app/models/draft_consent.rb
- spec/components/app_consent_patient_summary_component_spec.rb
If the consent form is attached to a consent (because it came from a parent), we should be showing the response from the parent, rather than the details of the patient that was eventually linked to the consent.
> Show details from consent form if available

- app/components/app_patient_card_component.rb
- db/seeds.rb
- spec/components/app_patient_card_component_spec.rb
This is in scope for the 1.1.1 release, so we can remove the feature flag, merge in to `main` and then it's ready for the testers.
https://trello.com/c/vBFF9W7B/1723-show-on-a-childs-record-that-they-have-a-flag
> Show patient flags without a feature flag

- app/controllers/draft_vaccination_records_controller.rb
- spec/features/edit_vaccination_record_spec.rb
- spec/features/hpv_vaccination_administered_spec.rb
When using the vaccinate flow it's possible to inadvertently record two vaccinations for the same patient by navigating back to the confirmation after submitting it and then submitting it again. Instead, once recorded, we associate the draft vaccination record with the saved one so this changes to the edit vaccination record flow.
> Prevent double-vaccination by navigating back

- app/assets/stylesheets/_status.scss
Using `inline-flex` for `.app-status` means several consecutive status items can appear inline, when they should appear stacked. Using `inline-flex` also adds unwanted spacing when this component appears in a table cell, which upcoming design changes may require.
> Prevent consecutive statuses appearing inline

- spec/features/manage_attendance_spec.rb
Instead of picking the last patient (which doesn't have a guaranteed order) we can pick the patient that will be left on the page, i.e. the patient that's missing attendance information.
This has been extracted from #2771.
Example failures:
- https://github.com/nhsuk/manage-vaccinations-in-schools/actions/runs/12389409160/attempts/2
- https://github.com/nhsuk/manage-vaccinations-in-schools/actions/runs/12389403286/attempts/2
> Fix flaky manage attendance feature test

- app/controllers/register_attendances_controller.rb
This fixes a bug that was inadvertently introduced in ddbd6b96507cbf86388754fa72843c72adcc605d where users could no longer sort and filter on the register attendances page. This was happening because we try and call `select!` on an `ActiveRecord::AssociationRelation` which doesn't have such a method, instead we have to first convert the list of patients to an array.
https://good-machine.sentry.io/issues/6161232701
> Fix sort/filter not working on attendances page

- app/jobs/bulk_update_patients_from_pds_job.rb
This fills up the job queue and breaks PDS lookup.
> Don't bulk queue PDS lookup jobs on staging envs

- app/models/consent.rb
- spec/models/consent_spec.rb
If the consent is linked to a consent form we should get the `responded_at` date/time from when the consent form was submitted, not when it was linked with the patient.
This has been spotted as a bug and the testers would like it included as part of the work to fix inconsistent data between the consent and the consent form (https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2772).
https://trello.com/c/2yk5lEkG/1769-linked-patient-details-shown-on-consent-response-page-instead-of-consent-form-responses
> Calculate `Consent#responded_at` from consent form

- app/components/app_patient_page_component.html.erb
This avoids showing health answers for consents that have been invalidated or overridden by a newer consent response from the same person.
> Show health answers from latest consents

- spec/features/import_child_records_with_duplicates_spec.rb
- spec/features/patient_sorting_filtering_spec.rb
The `main` branch is failing because two feature specs rely on being run in a given date range.
> Fix specs that assume a specific patient age so they pass in 2025

- app/lib/reports/offline_session_exporter.rb
In Excel spreadsheets when the list of available options for data validation is too large this can cause issues.
https://stackoverflow.com/questions/16017403/maximum-drop-down-list-formula-length-in-excel
To avoid this we can move the list of options to another sheet, table or named range.
https://contextures.com/xldataval11.html
This change moves the list of emails of the performing professionals to it's own sheet and adds a formula to use them as the source data for the data validation for the PERFORMING_PROFESSIONAL_EMAIL field of the offline spreadsheet.
[Fixes MAVIS-1800](https://trello.com/c/FZvpVCEk/1800-offline-spreadsheet-opens-with-errors-when-many-vaccinators-present-in-the-organisation?filter=offline)
> Fix performing professionals dropdown in offline spreadsheets

- app/lib/patient_merger.rb
- spec/lib/patient_merger_spec.rb
This fixes a bug where if a patient has a consent or session notification it is unable to be merged with another patient because the original patient cannot be destroyed (due to the foreign key constraints).
https://good-machine.sentry.io/issues/6157197172/
> Include consent and session notifications when merging patients

- app/controllers/concerns/patient_sorting_concern.rb
- spec/controllers/concerns/patient_sorting_concern_spec.rb
This fixes a bug where if a user tries to sort on a table by postcode and some of the rows don't have a postcode, the sorting fails.
https://good-machine.sentry.io/issues/6164317867/
> Fix bug where nurses can't sort with blank postcodes

- app/lib/reports/careplus_exporter.rb
- spec/lib/reports/careplus_exporter_spec.rb
This change ensures the Careplus report behaves like the Mavis report by filtering vaccination records based on their _technical dates_ (creation or last update) rather than the actual vaccination date. Specifically, any record whose creation or last update date falls within the specified date range is returned, regardless of when the vaccination itself was administered.
This primarily impacts records that were uploaded to Mavis on a different day than the actual vaccination (where the creation date is later than the vaccination date). Records added on the same day as the vaccination should remain unaffected.
[Fixes MAVIS-1804](https://trello.com/c/QY3Gmfs8/1804-fix-the-date-filtering-inconsistencies-between-the-careplus-and-mavis-reports)
> Align Careplus report date filtering with Mavis report logic

- Gemfile.lock
- config/brakeman.ignore
Version 7.0.0 was released on the 30th December with the main change being switching to the Prism Ruby parser made default in Ruby 3.4.
This also resolves a warning about Brakeman being out of date when running it locally.
> Upgrade Brakeman

- app/components/app_outcome_banner_component.rb
This refactors the component to correctly handle the situation where a patient was vaccinated in a session, and then a not administered vaccination record was recorded _after_ the administered vaccination record.
In reality this situation won't happen, but it can happen during training, so we should update the component to handle this and avoid presenting users with an internal server error.
https://good-machine.sentry.io/issues/6202199115/
> Refactor AppOutcomeBannerComponent

- config/initializers/i18n_nhs_design_system_date_interpolation.rb
This ensures that when importing a file with invalid characters that we try and encode as UTF-8, instead of raising an error we present the characters back to the user as `?`.
https://good-machine.sentry.io/issues/6202471696/
This adds a further improvement on top of https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2782 which is already merged in to `main`.
> Handle invalid characters when encoding as UTF-8

- app/components/app_compare_consent_form_and_patient_component.html.erb
- app/components/app_compare_consent_form_and_patient_component.rb
This is not necessary as the `ConsentForm` has the same interface as the `Patient` in the context of this component.
> Remove consent_form_patient

- app/models/immunisation_import_row.rb
- config/locales/en.yml
- spec/models/immunisation_import_row_spec.rb
When importing vaccination records we should validate that the date of birth for the patient is in the past, it doesn't make sense for the date to be in the future.
This validation was covered implicitly by the year group being in the programme which was removed to handle customising the year groups of the patients in https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2780 so this is just a small amendment to that change to avoid a regression.
> Validate date of birth in past

- app/models/cohort.rb
- app/models/concerns/year_group_concern.rb
- app/models/immunisation_import_row.rb
- app/models/patient.rb
- app/models/patient_import_row.rb
- config/locales/en.yml
- spec/models/class_import_row_spec.rb
- spec/models/cohort_import_row_spec.rb
- spec/models/immunisation_import_row_spec.rb
This fixes a few minor visual issues spotted by the testers when testing https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2780 where if the date of birth is missing the same error will appear twice for each row, and similarly an issue where the year group wouldn't render correctly.
This fixes are already in place for a future release (in https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2783 and https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2784), however including them now makes the testing easier and avoids needing to record additional defects.
> Avoid duplicate `DATE_OF_BIRTH` errors

- app/lib/govuk_notify_personalisation.rb
- spec/lib/govuk_notify_personalisation_spec.rb
- spec/mailers/session_mailer_spec.rb
This is an optional personalisation variable that we send to GOV.UK Notify and is used in the session reminder emails. Previously we were not sending this variable when not present, but that was causing a bug where the emails couldn't be sent as GOV.UK Notify would raise a client bad request error when the template variable was missing. Instead we can send it to GOV.UK Notify as a blank string.
https://good-machine.sentry.io/issues/5805756718/?environment=production&project=4505625073876992
> Ensure `subsequent_session_dates_offered_message` is present

- app/controllers/concerns/patient_sorting_concern.rb
- spec/controllers/concerns/patient_sorting_concern_spec.rb
- spec/features/patient_sorting_filtering_spec.rb
This prevents information about restricted patients being leaked inadvertently, as although the information itself was not shown, by using the sorting and filtering functionality it's possible to guess what the value might be.
Instead we now treat restricted patients as having no postcode for the purpose of filtering and sorting.
> Ignore restricted patients from sorting and filtering

- app/controllers/batches_controller.rb
- app/controllers/consents_controller.rb
- app/controllers/gillick_assessments_controller.rb
- app/controllers/offline_passwords_controller.rb
- app/controllers/session_attendances_controller.rb
- app/controllers/session_dates_controller.rb
- app/controllers/sessions/edit_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccination_reports_controller.rb
- app/controllers/vaccinations_controller.rb
This changes any instance of `params.require(...).permit(...)` to use `params.expect(...)` instead which is new in Rails 8. There are number of uses of `params.fetch` remaining which we should look at replacing eventually but the behaviour is quite the same.
> Use `params.expect`

- app/lib/email_address_normaliser.rb
- app/lib/phone_number_normaliser.rb
- app/models/consent_form.rb
- app/models/organisation.rb
- app/models/parent.rb
- app/models/team.rb
- app/models/user.rb
- spec/components/app_consent_form_summary_component_spec.rb
- spec/features/parental_consent_refused_spec.rb
- spec/features/parental_consent_spec.rb
- spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
- spec/jobs/text_delivery_job_spec.rb
- spec/mailers/session_mailer_spec.rb
- spec/models/consent_form_spec.rb
- spec/models/organisation_spec.rb
- spec/models/parent_spec.rb
- spec/models/team_spec.rb
- spec/models/user_spec.rb
- spec/support/shared_examples/a_model_with_a_normalised_email_address.rb
- spec/support/shared_examples/a_model_with_a_normalised_phone_number.rb
This improves how the email addresses and phone numbers are normalised to make it easier to perform string comparisons on the values to match up consent form email addresses and phone numbers with parent email addresses and phone numbers. This is necessary to support the work to match failed email/phone number attempts in Notify with consent forms, where don't have a reference to the parent or patient instance.
The existing email addresses and phone numbers that weren't previously normalised won't be updated by this. We may choose not to modify those existing values and only apply this going forward, or we can add a Rake task to fix those not normalised values later.
> Improve email address and phone number normalisation

- app/jobs/text_delivery_job.rb
- app/models/notify_log_entry.rb
- db/migrate/20250113142937_add_delivery_id_to_notify_log_entries.rb
- db/schema.rb
- spec/factories/notify_log_entries.rb
- spec/jobs/text_delivery_job_spec.rb
- spec/models/notify_log_entry_spec.rb
This ensures that when sending a text message we store the ID of the message returned to us from GOV.UK Notify. This allows us to link up text message delivery failures with the original delivery request that triggered the response, allowing for this to be shown to users in the future.
> Link text delivery with GOV.UK Notify IDs

- app/assets/stylesheets/_count.scss
- app/assets/stylesheets/_header.scss
- app/components/app_header_navigation_item_component.rb
- app/models/patient.rb
- app/models/user.rb
- app/policies/consent_form_policy.rb
- app/policies/patient_policy.rb
- app/policies/school_move_policy.rb
- app/views/layouts/_header.html.erb
- config/locales/en.yml
- spec/features/import_class_lists_move_spec.rb
- spec/features/manage_children_spec.rb
- spec/features/parental_consent_clinic_spec.rb
- spec/features/parental_consent_create_patient_spec.rb
This adds counts to the navigation bar for the consent form responses, important notices and school moves items so hopefully given some indication that there's action to be taken in those pages.
> Add counts to navigation bar items

- Dockerfile
It looks like `psych` and `charlock_holmes` depend on `libyaml-dev` and `zlib1g-dev` to build native extensions. It's unclear why the build worked before without them.
> Update docker build step packages

- app/controllers/consent_forms_controller.rb
- app/controllers/consents_controller.rb
- app/models/consent_form.rb
- app/views/consent_forms/index.html.erb
- app/views/consent_forms/invalidate.html.erb
- app/views/layouts/_header.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20250114113856_add_invalidated_at_to_consent_forms.rb
- db/migrate/20250114150405_add_notes_to_consent_forms.rb
- db/schema.rb
- spec/factories/consent_forms.rb
- spec/features/invalidate_consent_spec.rb
- spec/features/parental_consent_manual_matching_spec.rb
- spec/models/consent_form_spec.rb
This adds some new functionality allowing nurses to mark unmatched consent forms as invalid, meaning that they will disappear from the list of unmatched consent responses reducing work for the SAIS team who need to look through the list.
We know that sometimes consent responses are provided for patients who aren't in the cohort, so the only action to take with these is to mark them as invalid. Although we will stop showing them on the page, we will continue to store the information internally so we can surface them later.
> Add ability to mark unmatched consent forms as invalid

- app/controllers/consent_forms_controller.rb
- app/models/batch.rb
- app/models/concerns/archivable.rb
- app/models/consent_form.rb
- app/views/consent_forms/archive.html.erb
- app/views/consent_forms/index.html.erb
- app/views/layouts/_header.html.erb
- config/routes.rb
- db/migrate/20250115123804_rename_consent_form_invalidated_at_to_archived_at.rb
- db/schema.rb
- spec/factories/consent_forms.rb
- spec/features/parental_consent_manual_matching_spec.rb
- spec/models/consent_form_spec.rb
We'd like to change the wording around invalidating consent forms to instead refer to archiving consent forms.
This improves upon #2846 and will be included in 1.3.0 as part of that feature.
> Reword consent form "Mark as invalid"

- app/controllers/draft_consents_controller.rb
- app/models/concerns/patient_session_status_concern.rb
- spec/factories/patients.rb
- spec/features/triage_then_parenal_consent_refused_spec.rb
- spec/models/concerns/patient_session_status_concern_spec.rb
When calculating the overall status of a patient session, we should only consider the status of the `latest_triage` if the consent is given.
This is to handle a scenario where consent was given, then the nurse triaged the patient, and then consent was refused. Currently, the status of the patient would remain "ready to vaccinate" whereas instead the status should reflect the fact that consent has been withdrawn (even though the patient was triaged at one point).
> Only consider triage status if consent is given

- config/locales/patient_session_statuses.en.yml
- spec/components/app_simple_status_banner_component_spec.rb
This renames the "Safe to vaccinate" status after a triage to be "Ready for nurse" to match the naming we use when the patient is ready for the nurse after consent has been received and no triage was required.
> Rename "Safe to vaccinate"

- README.md
We're finding it makes more sense if the release branch is just used as a pointer to what's in production. This means we merge hot-fix changes into it, we simply reset it to whatever was released after it's been tagged.
> Clarify use of release branch

- app/mailers/application_mailer.rb
- app/models/team.rb
- db/migrate/20240214115829_add_reply_to_id_to_teams_old.rb
- db/migrate/20241213195932_add_reply_to_id_to_teams.rb
- db/schema.rb
- docs/onboarding.md
- spec/factories/teams.rb
- spec/fixtures/files/onboarding/valid.yaml
- spec/mailers/application_mailer_spec.rb
- spec/models/onboarding_spec.rb
- spec/models/team_spec.rb
This adds the ability to customise the GOV.UK Notify Reply-To ID per team like we already do with contact details (phone and email) to ensure that if users reply to the email they will go to the right place.
> Add Reply-To IDs to teams

- app/assets/stylesheets/_environment.scss
- app/assets/stylesheets/_tag.scss
- app/assets/stylesheets/application.scss
- app/components/app_hosting_environment_component.rb
- app/views/layouts/_header.html.erb
- config/initializers/inflections.rb
- config/locales/en.yml
Styles and markup for an `AppHostingEnvironmentComponent` that renders a banner above the header on all staging environments, giving an environment’s name and assigned colour, default to staging/grey if this cannot be determined.
- Largely inspired by what was used on Apply, meaning parts of this are likely incorrect; do we use `HOSTING_ENVIRONMENT_NAME` variable? If not, where can I get the named environment?
- Do we also have an Heroku review environment that needs to be accounted for?
- Does it need any tests?
Also deleted the custom styling for white tags as we don’t use that anymore.
> Show environment banner on staging environments

- config/locales/en.yml
- spec/features/parental_consent_create_patient_spec.rb
This is being renamed to "Unmatched responses" to make it clearer what this refers to.
> Rename "Responses" header link

- app/models/location.rb
- config/onboarding/coventry-model-office.yaml
- config/onboarding/coventry-production.yaml
- config/onboarding/hertfordshire-training-with-sessions.yaml
- config/onboarding/hertfordshire-training.yaml
- spec/fixtures/files/onboarding/valid.yaml
- spec/models/location_spec.rb
- spec/models/onboarding_spec.rb
When onboarding Coventry we became aware that not all of the community clinics will have an ODS code, so we need to allow these to be optional. When optional, we would use the ODS code of the organisation when sending data downstream.
> Allow community clinic ODS codes to be optional 

- app/controllers/consent_forms_controller.rb
- app/models/patient.rb
- app/views/consent_forms/index.html.erb
- spec/features/parental_consent_create_patient_spec.rb
This makes it possible for a nurse to create a patient record from a consent form, even if the consent form was unable to be matched with patient record details in PDS.
The workaround currently would be to create a cohort record for that child and then manually match the consent response to that record.
> Allow creating patients from consent without NHS numbers

- app/models/notify_log_entry.rb
- db/migrate/20250116090241_add_delivery_status_to_notify_log_entries.rb
- db/schema.rb
- spec/factories/notify_log_entries.rb
- spec/models/notify_log_entry_spec.rb
This adds a new enum integer column to `notify_log_entries` that we can use to track the status of a message delivery. This commit just adds the column, but the next steps will be to integrate with the GOV.UK Notify callback mechanism to ensure this value is accurate. This will allow us to display this information to the user either via the UI or in a report.
> Add `delivery_status` column to `notify_log_entries`

- app/models/location.rb
- spec/models/location_spec.rb
The generic clinic location will use the ODS code of the organisation, so the community clinics cannot use this ODS code as there's a unique index on the column.
> Validate community clinic ODS code doesn't match organisation

- app/jobs/notify_delivery_job.rb
If the text could not be delivered due to a server error, i.e. an issue with GOV.UK Notify, then we should keep trying to send these to avoid needing to manually re-send them via the Good Job dashboard.
> Retry text delivery server errors

- app/controllers/notifications_controller.rb
- app/models/notify_log_entry.rb
- config/routes.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- db/migrate/20250116093944_add_index_on_notify_log_entries_delivery_id.rb
- db/schema.rb
- spec/controllers/notifications_controller_spec.rb
- spec/factories/notify_log_entries.rb
- spec/models/notify_log_entry_spec.rb
This adds a controller which handles GOV.UK Notify callbacks, updating the status of the entry in the log which we can then use to display to the user.
Once deployed, the next step will be to configure this in GOV.UK Notify so that we start to receive callbacks for every email and text sent. This will require setting a bearer token, which I'll add in a separate PR.
> Add controller to handle GOV.UK Notify callbacks 

- Gemfile
- Gemfile.lock
- app/lib/reports/offline_session_exporter.rb
- spec/lib/reports/offline_session_exporter_spec.rb
This change to the offline spreadsheet protects against Excel's 256 char limit for validation values by putting batch numbers into a separate sheet and looking them up there. This builds on the work done for the performing professionals validations.
https://trello.com/c/PVjQ6E6B/1826-refactor-batch-ids-drop-down-in-offline-spreadsheet
Batch number drop-down:
New data validation for batch numbers:
New sheet added for the specific programme (normally this sheet is hidden):
> Validate batch numbers using separate worksheet(s)

- .rubocop.yml
- app/controllers/concerns/consent_form_mailer_concern.rb
- app/controllers/concerns/triage_mailer_concern.rb
- app/controllers/concerns/vaccination_mailer_concern.rb
- app/jobs/email_delivery_job.rb
- app/models/consent_notification.rb
- app/models/session_notification.rb
- spec/controllers/concerns/consent_form_mailer_concern_spec.rb
- spec/controllers/concerns/triage_mailer_concern_spec.rb
- spec/controllers/concerns/vaccination_mailer_concern_spec.rb
- spec/features/delete_vaccination_record_spec.rb
- spec/features/edit_vaccination_record_spec.rb
- spec/features/scheduled_consent_requests_spec.rb
- spec/jobs/email_delivery_job_spec.rb
- spec/models/consent_notification_spec.rb
- spec/models/session_notification_spec.rb
- spec/spec_helper.rb
- spec/support/email_expectations.rb
- spec/support/matchers/have_delivered_email.rb
This adds a new job, similar to the `SMSDeliveryJob` that allows us to send emails using GOV.UK Notify directly rather than going via `ActionMailer`. Using the API directly allows us to record the delivery message ID, which we can then use to get the status of the receipt later on and present this information to users.
By switching to this job we get automatic retry behaviour on GOV.UK Notify server errors, and tracking of message IDs.
> Use GOV.UK Notify directly to send emails

- app/jobs/email_delivery_job.rb
- app/jobs/sms_delivery_job.rb
- app/models/notify_log_entry.rb
- app/models/parent.rb
- db/migrate/20250121112644_add_parent_to_notify_log_entries.rb
- db/schema.rb
- spec/factories/notify_log_entries.rb
- spec/jobs/email_delivery_job_spec.rb
- spec/jobs/sms_delivery_job_spec.rb
- spec/models/notify_log_entry_spec.rb
This ensures that when recording a notify log entry, it's linked with the parent that the email or text message was sent to, allowing us to easily show the status of the messages to nurses.
> Link parents with notify log entries

- app/lib/patient_merger.rb
- app/models/pre_screening.rb
- spec/lib/patient_merger_spec.rb
This fixes an issue where patients with a pre-screening record cannot be merged with another using the `PatientMerger` class as the old patient record cannot be deleted due to the foreign key persisting and not being updated to refer to the new patient.
> Ensure patients with pre-screenings can be merged

- app/jobs/email_delivery_job.rb
- spec/jobs/email_delivery_job_spec.rb
This updates the `EmailDeliveryJob` to ensure that we don't pass a reply-to UUID if the value is `nil`, as this results in an error when making the call to GOV.UK Notify.
> Don't pass GOV.UK Notify reply-to if nil

- spec/lib/reports/offline_session_exporter_spec.rb
This updates the test to use `match_array` instead of `eq` when comparing the values of the two arrays as the order of the arrays isn't relevant to the test, and isn't guaranteed.
> Fix flaky offline session report test

- README.md
- docs/ops-tasks.md
This adds a document in the `docs` directory outlining the operations tasks that we've already got documented in Confluence, but putting it in the repo helps to keep it available to those who don't have NHS access.
> Add a document of ops tasks

- app/models/patient_import_row.rb
- spec/models/class_import_row_spec.rb
If the postcode has changed, as this means the entire address is likely to be incorrect. Even if we don't have the other parts of the address (line 1, line 2 and town) we should blank those out as they will no longer be correct if the postcode has changed.
> Stage entire address as a pending change

- app/controllers/patients/edit_controller.rb
This ensures that if the patient has parents we're including these in the query and avoid N+1 issues when renderingt the parents.
> Preload parents with merging NHS numbers

- app/models/concerns/patient_session_status_concern.rb
- spec/models/patient_session_spec.rb
When calculating the overall status of a patient session, if consent has been given by the patient themselves via Gillick assessment, then it should override any refused or conflicting consent from the parents.
This fixes a bug where patients who had self-consenting were remaining in the "conflicting consent" status where they should instead have been in "safe to vaccinate".
> Ensure self-consent overrides parental consent

- app/components/app_parent_summary_component.rb
- app/components/app_patient_card_component.rb
- app/components/app_patient_summary_component.rb
- app/views/consents/show.html.erb
- app/views/draft_consents/confirm.html.erb
- spec/components/app_parent_summary_component_spec.rb
- spec/components/app_patient_card_component_spec.rb
- spec/components/app_patient_page_component_spec.rb
- spec/components/app_patient_summary_component_spec.rb
- spec/features/import_vaccination_records_spec.rb
This updates the patient card used in a number of pages to match the latest designs in the prototype. Specifically this replaces how the parents are shown to instead have them in their own summary list with a heading.
> Update patient card to match latest designs

- app/models/notify_log_entry.rb
- spec/components/app_parent_summary_component_spec.rb
- spec/models/parent_spec.rb
This reverts commit 61a8f29720c5cea8311d9d9056ea3da8166346ef.
This was added in #2882 but unfortunately this approach doesn't work because it breaks the previous encrypted values and we were seeing Sentry errors for it:
https://good-machine.sentry.io/issues/6250337106/
I'll have to find a backwards compatible way of converting this column to be deterministic.
> Revert "Make NotifyLogEntry#recipient deterministic"

- copilot/webapp/manifest.yml
We're testing this out ahead of rolling it out to production, in preparation for adding more SAIS teams.
> Set node count to 3 in qa and test

- app/models/concerns/patient_session_status_concern.rb
- app/models/patient_session.rb
- spec/models/patient_session_stats_spec.rb
This extends #2883 to ensure that when calculating the stats for a list of patient sessions we're correctly exclusing consent conflicted results when the consent has actually been given, via self-consent.
> Refactor how conflicting consent status is calculated

- app/jobs/email_delivery_job.rb
- app/jobs/sms_delivery_job.rb
- app/mailers/application_mailer.rb
- app/models/notify_log_entry.rb
- app/models/parent.rb
- db/migrate/20250127133639_add_recipient_deterministic_to_notify_log_entries.rb
- db/schema.rb
- lib/tasks/notify_log_entries.rake
- spec/components/app_parent_summary_component_spec.rb
- spec/factories/notify_log_entries.rb
- spec/jobs/email_delivery_job_spec.rb
- spec/jobs/sms_delivery_job_spec.rb
- spec/models/notify_log_entry_spec.rb
- spec/models/parent_spec.rb
This adds a new column `recipient_deterministic` to the `NotifyLogEntry` model with the intention of eventually replacing the `recipient` column. This is necessary to change the encryption configuration of the column from non-deterministic to deterministic which isn't backwards compatible.
This is the first step, to add the new column, backfill the values and start using this column. Once this is in production, we can start to remove the old `recipient` column, starting by making it nullable and stop writing to it, removing it from the list of Rails columns, and then removing and renaming the new column back to `recipient`.
> Add deterministic recipient column

- spec/factories/sessions.rb
This improves the session factory to generate session slugs with alphanumeric characters to make it clear that these are slugs and not integer IDs, avoiding any potential confusiong and making them more realistic.
> Improve session slug string sequence generation

- app/lib/patient_merger.rb
- spec/lib/patient_merger_spec.rb
When merging patients it's possible to end up with duplicate school moves (if both the patient to keep and patient to destroy had the same school move). This results in a database error on the unique constraints, so we should handle this by deleting one of the school moves.
> Ensure duplicate school moves are removed when merging

- app/models/consent.rb
When displaying the label for a consent response, sometimes the `parent_relationship` will be `nil`. This can happen if an ops task manually removes the relationship, or if a patient is merged. Currently when trying to view this patient we will see a server error whereas we should instead display the name of the parent even if the relationship no longer exists.
This will also be relevant in the future where we will give the ability for nurses to remove parental contacts, but might still want a record of the consent.
https://good-machine.sentry.io/issues/6254607593/
> Handle consent label without a relationship

- copilot/webapp/manifest.yml
We are increasing the total capacity of the service to better support new teams that are joining next week.
> Bump number of containers from 2 to 3

- app/controllers/dev_controller.rb
- app/controllers/school_moves_controller.rb
- app/forms/school_move_form.rb
- app/models/patient.rb
- app/models/school_move.rb
- app/models/school_move_log_entry.rb
- db/migrate/20250122155821_create_school_move_log_entries.rb
- db/schema.rb
- spec/factories/school_move_log_entries.rb
- spec/models/school_move_log_entry_spec.rb
- spec/models/school_move_spec.rb
This creates a new model that will be used to capture when a school move is confirmed, by which user and outcome of the school move. I've only added columns to capture the minimum we need to answer questions not available in our existing audit logs, but this could be extended in the future.
The model has been created using a similar pattern to other actions that we log, specifically the `NotifyLogEntry` and `AccessLogEntry`. It might be time to consider if we can build a more generic way of recording actions taken in the service. For now, the approach taken in this commit will allow us to answer the question of why a number of patients have ended up in the community clinic when there are still school sessions scheduled.
We already record database changes using the `audited` Gem, but this …
> Record school move log entries 

- app/lib/govuk_notify_personalisation.rb
- spec/lib/govuk_notify_personalisation_spec.rb
This adds a new personalisation variable that is sent up to GOV.UK Notify when sending an email or text message, allowing the date of birth to be used in any templates.
We're not going to update the templates yet but this allows us to update them in the future without needing to make a code change at the time.
> Add patient_date_of_birth personalisation

- app/models/school_move_log_entry.rb
- db/migrate/20250131153531_remove_school_move_log_entries_foreign_keys.rb
- db/schema.rb
- spec/factories/school_move_log_entries.rb
- spec/models/school_move_log_entry_spec.rb
This record is intended to be used as part of an activity log, and any of it's associated entities may be removed without affecting the activity log trail. For example, a patient record could be removed when merging with another patient record in the case of duplication.
This very issue was blocking a bug fix for [MAVIS-1877](https://trello.com/c/f1FEuzMF/) because when merging the patients the `school_move_log_entries` record generated as part of the import was triggering a foreign key constraint error.
This is a follow-up to the #2880
> Remove foreign keys from school moves log entries

- app/lib/patient_merger.rb
- app/models/school_move_log_entry.rb
- db/migrate/20250201201237_add_school_move_log_entries_foreign_keys.rb
- db/schema.rb
- spec/factories/school_move_log_entries.rb
- spec/lib/govuk_notify_personalisation_spec.rb
- spec/lib/patient_merger_spec.rb
- spec/models/school_move_log_entry_spec.rb
This reverts the change that was made in https://github.com/nhsuk/manage-vaccinations-in-schools/commit/6d8880d3c5b4810b7851614fdf30ce365a163f6e to remove these foreign keys to fix a bug where patients couldn't be merged due to the school move log entries existing.
Instead, we can handle the school move log entries by modifying the `patient_id` value, ensuring that the foreign keys continue to be valid. Removing the foreign keys means we can no longer rely on this model to generate activity logs which is one of the reason it was added.
It's true that it also prevents us from being able to delete any schools or users, but we already have this problem or more crucial models (like vaccination records, triage, sessions, etc) so when if we come to a situation where we need to handle that we …
> Handle school move log entries when merging patients 

- app/jobs/bulk_update_patients_from_pds_job.rb
- app/models/concerns/csv_importable.rb
We're seeing a problem in production where the queues for PDS jobs gets full with jobs that are not succeeding, likely related to the rate limit.
Some potentially related issues:
- https://github.com/bensheldon/good_job/issues/838
- https://github.com/bensheldon/good_job/issues/1278
- https://github.com/bensheldon/good_job/issues/1353
This wait time was added to artifically slow down the queues and prevent them from needing to be retried, so increasing this wait time should reduce the changes of the jobs ending up in this stuck state.
This is a temporary measure until we can either move away from Good Job or resolve the underlyling issue which is still not 100% clear.
> Increase wait time between PDS jobs

- app/jobs/concerns/nhs_api_concurrency_concern.rb
This increases the wait time between jobs that interact with the NHS API depending on the number of executions that we've already tried for that job. If the number is high, it suggests that jobs aren't suceeding and that we should throttle the number of jobs getting through.
> Increase wait time per executions

- app/components/app_vaccination_record_summary_component.rb
- app/controllers/draft_vaccination_records_controller.rb
- app/controllers/vaccinations_controller.rb
- app/models/draft_vaccination_record.rb
- app/views/draft_vaccination_records/confirm.html.erb
- app/views/draft_vaccination_records/notes.html.erb
- spec/components/app_vaccination_record_summary_component_spec.rb
- spec/features/edit_vaccination_record_spec.rb
This adds the ability to edit the notes of a vaccination record after the record has been created, matching the designs in the prototype. This works by adding a new "notes" step which is only used when editing, rather than when first recording a vaccination.
> Add ability to edit vaccination record notes

- app/controllers/patients/edit_controller.rb
- app/lib/patient_merger.rb
- spec/lib/patient_merger_spec.rb
This updates the tests for the `PatientMerger` class (and the implementation of the class) to ensure that it works when called from a controller, with `audited` and with parents and parent relationships already pre-loaded.
https://good-machine.sentry.io/issues/6259221555/
> Ensure patient merging works with audited and strict loading

- copilot/webapp/manifest.yml
This will lead to 2x3x1 = 6 max threads instead of 2x3x5 = 30, which could in theory help with the PDS rate limit.
> Decrease the number of good job threads to 1 in test

- app/jobs/bulk_update_patients_from_pds_job.rb
- app/models/concerns/csv_importable.rb
- config/environments/production.rb
We're still seeing the issue in production where the PDS jobs get stuck in a state where none of them can process successfully. Running some experiments by queueing the jobs manually via a Rails console suggests a 2 second interval between the jobs is handled much better, although it means that it'll take ~11 hours to process all the patients.
> Increase interval between PDS jobs

- copilot/webapp/manifest.yml
This aligns it to the other environments for consistency.
We might choose to add this back in to all environments, but we're instead trying to bump the rate limit from 5 to higher, which should improve performance.
> Remove max threads override for test environment

- app/controllers/patients/edit_controller.rb
- spec/features/manage_children_spec.rb
When assigning the NHS number to a patient manually, we should make sure it's no longer marked as invalid and trigger a new job to fetch the latest information from PDS. This allows us to correct the NHS number of a patient that is marked as invalid due to the old NHS number not existing.
> Remove patient invalidating when editing NHS number

- app/lib/reports/programme_vaccinations_exporter.rb
- spec/lib/reports/programme_vaccinations_exporter_spec.rb
This adds a new column to the programme vaccinations CSV report which captures whether the child wants their parent to be informed about the vaccination.
> Add GILLICK_NOTIFY_PARENTS column to report

- app/models/concerns/csv_importable.rb
- spec/features/import_child_records_spec.rb
- spec/features/import_vaccination_records_spec.rb
- spec/models/cohort_import_spec.rb
- spec/models/immunisation_import_spec.rb
Changes the import issues feedback to report row numbers that correspond to what a user sees in the spreadsheet, i.e. including the header row.
Resolves MAVIS-1785.
> Fix CSV line number in import errors

- app/components/app_import_format_details_component.rb
- app/models/immunisation_import_row.rb
- spec/features/hpv_vaccination_offline_spec.rb
- spec/fixtures/immunisation_import/valid_flu.csv
Currently we only require this to be provided when importing administered records, but in the future we will allow importing a file containing records across multiple programmes. To support this we need a way of inferring the programme, and this comes from the vaccine.
> Require VACCINE_GIVEN when importing immunisations

- app/controllers/vaccinations_controller.rb
- app/forms/vaccinate_form.rb
- app/models/draft_vaccination_record.rb
- app/models/immunisation_import_row.rb
- app/models/vaccination_record.rb
- app/policies/vaccination_record_policy.rb
- config/locales/en.yml
- db/migrate/20250207091449_add_organisation_to_vaccination_records.rb
- db/schema.rb
- spec/factories/vaccination_records.rb
- spec/features/import_vaccination_records_spec.rb
- spec/models/immunisation_import_row_spec.rb
- spec/models/vaccination_record_spec.rb
This adds a new column to vaccination records which tracks the ODS code of the organisation that performed the vaccination (whether that's a school immunisations team, a hospital or a GP). This is necessary to support importing historical vaccinations that weren't performed by the SAIS organisation directly.
I've chosen to go with a ODS code column rather than something more structured (perhaps a foreign key to the organisations or the locations) because we won't always have a reference, for example if a vaccination took place in a hospital we don't have those in our locations table currently.
In the future we might want to make the data more structured, particularly if we introduce a foreign key on locations to replace the `location_name` column.
> Handle vaccination records outside the organisation

- app/models/programme.rb
- app/models/vaccine.rb
- config/locales/en.yml
- spec/factories/programmes.rb
- spec/models/class_import_spec.rb
This adds the two new programme types needed for doubles and updates the various parts of the code that rely on the programme type to work for Td/IPV and MenACWY.
In a future commit we'll need to add the vaccines for these two programmes, and then the health questions.
> Add Td/IPV and MenACWY programmes

- config/vaccines.yml
- spec/factories/programmes.rb
- spec/factories/vaccines.rb
This adds the vaccines suitable for the doubles programmes (Td/IPV and MenACWY). This will need to be followed up with adding the health questions suitable for the vaccines.
> Add Td/IPV and MenACWY vaccines

- app/controllers/sessions_controller.rb
- app/models/session.rb
- app/views/sessions/close.html.erb
- spec/models/session_spec.rb
When closing a school session, we move all unvaccinated patients to the clinic so they can be vaccinated outside the school. However, if the parents have refused consent for the patient to be vaccinated in school, we don't want to move them to the clinic.
[Trello Card](https://trello.com/c/OOVetSlY/1918-children-with-consent-refused-being-mistakenly-proposed-to-move-to-community-clinic-when-closing-session)
> Don't move patients to clinic if consent is refused

- app/controllers/patients/edit_controller.rb
- app/lib/patient_merger.rb
- spec/lib/patient_merger_spec.rb
This prevents a bug where a user cannot be merged with a patient that has been moved out of the cohort as they can't be found by the policy scope.
To support this, we've slightly updated the logic around the patient merging to move the patient back in to the cohort if they are not currently part of any cohort as this is likely to be the expected behaviour.
There is an outstanding question about what happens if we're merging two patients from two different organisation's cohorts, it's unclear which organisation's cohort the merged patient should belong to.
[Trello Card](https://trello.com/c/LIFt9GVO/1821-for-some-patients-when-you-try-to-add-an-nhs-number-to-a-duplicate-record-so-that-you-can-merge-them-you-get-an-error-saying-nhs)
> Search globally for patients when merging

- app/components/app_activity_log_component.rb
- app/components/app_outcome_banner_component.rb
- app/components/app_patient_page_component.html.erb
- app/components/app_simple_status_banner_component.rb
- app/controllers/patient_sessions_controller.rb
- app/controllers/patients_controller.rb
- app/controllers/session_attendances_controller.rb
- app/jobs/clinic_session_invitations_job.rb
- app/lib/reports/careplus_exporter.rb
- app/lib/reports/offline_session_exporter.rb
- app/models/concerns/patient_session_status_concern.rb
- app/models/immunisation_import.rb
- app/models/organisation.rb
- app/models/patient.rb
- app/models/patient_session.rb
- app/models/session.rb
- app/policies/session_attendance_policy.rb
- spec/components/app_outcome_banner_component_spec.rb
- spec/components/app_simple_status_banner_component_spec.rb
- spec/models/patient_session_spec.rb
This follows up on #2939 to ensure that vaccination records are filtered by the current programme. At the moment this is the first programme administered in a session but in the future this will come from a selection by the user.
At the same time, this also fixes a bug where vaccination records administered outside of the current session weren't shown on a patient's record. Now we show all vaccination records for a particular patient.
[Trello Card](https://trello.com/c/cfPtR6Am/2000-if-a-child-is-added-to-a-clinic-and-vaccinated-in-school-you-cant-see-in-the-clinic-area-that-they-are-already-vaccinated)
> Filter vaccination records by programme

- app/models/immunisation_import_row.rb
- spec/models/immunisation_import_row_spec.rb
When validating an immunisation import row we only need to check for presence if we're not already checking the value is equal to the current organisation, as that check already checks for the presence of the value.
> Avoid double ORGANISATION_CODE errors

- app/models/concerns/full_name_concern.rb
- app/models/patient_session.rb
- spec/models/patient_spec.rb
Order all patients by surname first, then given name.
[Trello Card](https://trello.com/c/olP60HCo/2012-always-sort-tables-of-children-by-surname-not-first-name)
> Sort patients by surname

- app/models/immunisation_import.rb
- app/models/immunisation_import_row.rb
- spec/models/immunisation_import_spec.rb
This fixes a regression that was added in a01aa7f5632344c45f0d517d3184bd9466faa7d2 which meant that when importing vaccination records for the current academic year (where a session must exist) we weren't adding the patients to that session if they weren't already in the session.
Although the data model allows patients to be vaccinated and doesn't require them to be in the session at that point in time, in this case it's important that the patients are visible in the session so their status is represented accurately.
> Add patient to sessions when importing vaccinations

- app/components/app_hosting_environment_component.rb
- Use purple banner for Heroku review apps (training environment doesn’t show a banner as its a production environment so we can reassign this colour)
- Show PR number in tag text for Heroku review apps
> Update environment banner for Heroku review apps

- app/controllers/draft_vaccination_records_controller.rb
- app/policies/vaccination_record_policy.rb
- spec/policies/vaccination_record_policy_spec.rb
To vaccination records that are associated with a session (i.e. managed within Mavis and not historical) and were performed by the current organisation.
> Restrict editing vaccination records

- app/controllers/class_imports_controller.rb
- app/controllers/draft_class_imports_controller.rb
- app/models/class_import.rb
- app/models/class_import_row.rb
- app/models/draft_class_import.rb
- app/views/draft_class_imports/year_groups.html.erb
- app/views/imports/show.html.erb
- config/locales/en.yml
- db/migrate/20250211092238_add_year_groups_to_class_imports.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/class_imports.rb
- spec/features/import_class_lists_move_spec.rb
- spec/features/import_class_lists_spec.rb
- spec/features/import_class_lists_with_duplicates_spec.rb
- spec/models/class_import_row_spec.rb
- spec/models/class_import_spec.rb
This is a new feature that allows the nurses to choose the year groups they are going to import in the class list. Depending on the year groups selected, patients not in the year group won't be removed from the session.
For now this is behind a feature flag (`class_import_year_groups`) so we can deploy the code sooner and only enable the feature once it's ready to be tested.
> Add year group selection when importing class lists

- app/jobs/email_delivery_job.rb
- app/jobs/sms_delivery_job.rb
- app/models/notify_log_entry.rb
- db/migrate/20250128111046_remove_recipient_from_notify_log_entries.rb
- db/migrate/20250128111223_add_recipient_to_notify_log_entries.rb
- db/schema.rb
- lib/tasks/notify_log_entries.rake
- spec/factories/notify_log_entries.rb
- spec/jobs/email_delivery_job_spec.rb
- spec/jobs/sms_delivery_job_spec.rb
- spec/models/notify_log_entry_spec.rb
This follows on from https://github.com/nhsuk/manage-vaccinations-in-schools/pull/2899 to support replacing the `recipient_deterministic` column with the `recipient` column.
This stage removes the old `recipient` column and replaces it with a new deterministic `recipient` column and starts writing to it. The next stage will be to stop writing to the `recipient_deterministic` column so it can eventually be removed.
> Replace recipient_deterministic with recipient

- app/controllers/programmes_controller.rb
- app/views/programmes/index.html.erb
When displaying the stats for a programme, we should ensure that the query is filtered by the programme to make sure the right numbers are shown.
> Filter programme stats by programme

- app/components/app_session_summary_component.rb
- spec/components/app_session_summary_component_spec.rb
The MenACWY and Td/IPV links don't work at the moment, but it brings us closer to the eventual design and resolves a usage of `session.programmes.first` which we need to remove to support multiple programmes.
> Update consent links to show per programme

- app/components/app_programme_tags_component.rb
- app/components/app_session_summary_component.rb
- app/components/app_session_table_component.html.erb
- app/controllers/sessions/edit_controller.rb
- app/models/session.rb
- app/views/sessions/edit.html.erb
- app/views/sessions/edit/programmes.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/manage_school_sessions_spec.rb
- spec/models/session_spec.rb
This makes it possible to edit the programmes that a session administers after the session dates have been scheduled, as long as all the dates are in the past and the session is still open.
> Add ability to assign programmes to sessions 

- app/jobs/invalidate_self_consents_job.rb
- app/models/session.rb
- config/environments/production.rb
- spec/jobs/invalidate_self_consents_job_spec.rb
This adds a new job which handles the logic related to invalidating self-consents after the day of the session. Currently this behaviour is triggered when a session is closed, but that isn't quite right. Self-consent is only valid in the particular session date that it was captured in, and it becomes invalid the day after.
Right now, self-consent transfers between dates in a single session and this is not correct. As we're removing the functionality to close a session, we need a different way of invalidating these self-consents, and putting it in a scheduled job seemed like the quickest way to achieve that, and it resolves the issue described above.
There are a number of problems with this approach that I would want to fix in the future, but these problems exist with the current solution …
> Invalidate self-consents on a schedule 

- app/components/app_programme_selection_form_component.html.erb
- app/components/app_programme_selection_form_component.rb
- app/components/app_session_patient_table_component.rb
- app/controllers/concerns/patient_sorting_concern.rb
- app/controllers/consents_controller.rb
- app/controllers/register_attendances_controller.rb
- app/controllers/session_attendances_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations_controller.rb
- app/views/consent_forms/show.html.erb
- app/views/consents/index.html.erb
- app/views/patient_sessions/show.html.erb
- app/views/register_attendances/index.html.erb
- app/views/sessions/show.html.erb
- app/views/triages/index.html.erb
- app/views/vaccinations/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/concerns/patient_sorting_concern_spec.rb
This updates the session page to support doubles while making the minimal number of changes. See https://github.com/nhsuk/manage-vaccinations-in-schools-prototype/pull/60#issuecomment-2654614711 for the original design ideas.
I haven't added any feature tests for this feature, but the tests we've got for HPV continue to pass so we can be confident that nothing has broken for HPV. I wanted to get this feature out to the testers and then I will add feature tests in the mean time while they can start on the manual testing.
> Add minimum doubles session page design

- config/application.rb
* The credentials for autogenerated secrets by aurora RDS is different
** To not be reliant on copilot in the future we should be able to handle terraform native setups
> MAV-384: Modify application configuration

- app/models/immunisation_import_row.rb
- config/locales/en.yml
- spec/models/immunisation_import_row_spec.rb
This changes how we validate the date of vaccination when importing vaccination records to ensure it comes after the date of birth. This is necessary for doubles where some patients will have received vaccinations before starting school.
> Validate date of vaccination is after date of birth

- app/components/app_programme_session_table_component.html.erb
- app/controllers/sessions/invite_to_clinic_controller.rb
- app/controllers/sessions_controller.rb
- app/jobs/clinic_session_invitations_job.rb
- app/jobs/concerns/send_clinic_invitations_concern.rb
- app/jobs/send_clinic_initial_invitations_job.rb
- app/jobs/send_clinic_subsequent_invitations_job.rb
- app/lib/govuk_notify_personalisation.rb
- app/models/session.rb
- app/views/sessions/invite_to_clinic/edit.html.erb
- app/views/sessions/show.html.erb
- config/routes.rb
- db/seeds.rb
- spec/features/manage_clinic_sessions_spec.rb
- spec/features/manage_school_sessions_spec.rb
- spec/jobs/send_clinic_initial_invitations_job_spec.rb
This changes how invitations to get patients in to a clinic works to make it a manual process where the nurses have to trigger the invitation emails manually when the school session is completed, and similarly the nurses have to manually send the reminder emails from the community clinic session page.
> Invite patients to clinics

- app/views/parent_interface/consent_forms/start.html.erb
- config/locales/en.yml
This updates the content from the consent form journey to match the prototype by adding the missing paragraphs with links.
`html_safe` is a little bit controversial here, but given that this is designed to be static content and shouldn't get variables passed into it from the `t` helper, it should be okay.
> Add links to consent form start page

- app/components/app_activity_log_component.rb
- app/components/app_log_event_component.rb
- spec/components/app_activity_log_component_spec.rb
This makes it clear which programme the activity log entry is referring to now that a patient can be vaccinated across multiple programmes. Not all activity log events have a programme, but for those that do it is shown next to the date.
> Add programme to activity log entries

- lib/tasks/vaccines.rake
- spec/factories/health_questions.rb
- spec/factories/vaccines.rb
This adds the health questions for the MenACWY and Td/IPV vaccines and updates the factories to be a realistic representation of the health questions.
Like HPV, the health questions are hard coded in the vaccines seed Rake task, but I expect in the future we'll want these to be more customisable.
> Add MenACWY and Td/IPV health questions

- app/models/organisation.rb
- app/models/programme.rb
- app/models/session.rb
- app/models/session_programme.rb
- db/migrate/20250221080758_create_session_programmes.rb
- db/schema.rb
- spec/models/session_spec.rb
When displaying the programmes for a patient or a session we want to ensure they appear in the same order very time. At the moment the order is not guaranteed as we have a join table with no other reference points.
To add this feature, I've reworked the join table to be an explicit `SessionProgramme` model, like the `OrganisationProgramme` model and that allow for an order to be specified on the `has_many` relationship.
> Order programmes by name

- config/application.rb
* The DB_NAME should be an environment variable
*  In the autogenerated configuration it is not included in the db secret
> MAV-384: Fix bug in getting DB_NAME

- app/models/location.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- db/seeds.rb
- spec/models/location_spec.rb
This simplifies how the seeds are generated to avoid a potential never ending loop, by only creating locations when we're setting up the sessions. This does mean that we can no longer generate the seeds from real school data, but we generally weren't doing that anyway since importing all the schools takes a relatively long time and it's useful that the seeds run quickly.
For the QA environment, we should be moving towards using the onboarding process anyway to ensure consistency, whereas the seeds are useful for quickly setting up a development environment.
> Simplify seeds generation

- app/models/session_notification.rb
- spec/models/session_notification_spec.rb
If a patient is part of a programme and they're being administered a vaccine, we should send the session reminder email to all the parents who consents for any of the programmes in the session. In most cases, this will be only the two parents of the child, but it's possible for a situation where one parent consented to one programme and another parent consented to the other.
> Send session notifications for all programmes

- app/views/layouts/_header.html.erb
The overflow dropdown navigation currently appears at the bottom of the viewport.
This adds an extra `div.nhsuk-navigation-container` wrapper with `position:relative` like on the [NHS design system](https://service-manual.nhs.uk/design-system) so that `top: 100%` on the dropdown has the desired effect.
(Make sure to hide whitespace changes when reviewing: https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3017/files?diff=unified&w=1)
> Fix main navigation overflow dropdown positioning

- app/models/consent_form.rb
Without this, `original_session` only has the specified `programme` as the proxy association doesn't fetch all the records for efficiency.
We need all the associated `programme` records for the consent form page that lets parents choose which vaccine to give consent for.
> Preload programmes for original_session

- app/components/app_session_summary_component.rb
- app/controllers/parent_interface/consent_forms/base_controller.rb
- app/controllers/parent_interface/consent_forms_controller.rb
- app/jobs/email_delivery_job.rb
- app/jobs/sms_delivery_job.rb
- app/lib/govuk_notify_personalisation.rb
- app/lib/programme_grouper.rb
- app/models/consent_notification.rb
- app/views/parent_interface/consent_forms/edit/name.html.erb
- app/views/parent_interface/consent_forms/start.html.erb
- config/routes.rb
- spec/features/parental_consent_doubles_spec.rb
- spec/jobs/email_delivery_job_spec.rb
- spec/jobs/sms_delivery_job_spec.rb
- spec/lib/govuk_notify_personalisation_spec.rb
- spec/lib/programme_grouper_spec.rb
- spec/models/consent_notification_spec.rb
When rendering the consent links on a session page, this now ensures that Td/IPV and MenACWY are grouped together a single link is shown for that particular consent form as consent for these programmes is collected together.
To support this I've made the consent form start link accept a `-` separated list of programme types, which are then used together to generate the consent form. For HPV the links continue to work as they do currently, and for doubles the programmes slug will look like `menacwy-td_ipv` or `td_ipv-menacwy`.
> Show consent form link for doubles

- app/components/app_consent_component.rb
- app/controllers/consents_controller.rb
- app/controllers/programmes_controller.rb
- app/jobs/school_consent_reminders_job.rb
- app/jobs/school_consent_requests_job.rb
- app/models/consent_notification.rb
- app/models/consent_notification_programme.rb
- app/models/programme.rb
- db/migrate/20250221155425_create_consent_notification_programmes.rb
- db/schema.rb
- spec/factories/consent_notifications.rb
- spec/factories/patients.rb
- spec/jobs/school_consent_reminders_job_spec.rb
- spec/jobs/school_consent_requests_job_spec.rb
- spec/lib/patient_merger_spec.rb
- spec/models/consent_notification_spec.rb
This is to support sending consent requests and reminders for multiple programmes in one go, we can record the programmes that were associated with the consent notification.
This is necessary to support doubles where the consent forms are sent for Td/IPV and MenACWY together.
> Associate consent notifications with multiple programmes

- config/vaccines.yml
- spec/factories/programmes.rb
This adds two more vaccines for MenACWY that we expect to be able to import historical vaccination records for, but won't be administering when recording new vaccination records.
In the first commit I've sorted the vaccines alphabetically, the new vaccines are added in the second commit.
> Add historical MenACWY vaccines

- app/lib/programme_grouper.rb
- app/lib/vaccinated_criteria.rb
- app/models/concerns/age_concern.rb
- app/models/concerns/patient_session_status_concern.rb
- app/models/programme.rb
- spec/lib/vaccinated_criteria_spec.rb
For the MenACWY and Td/IPV programmes, a patient is only considered vaccinated if a vaccination record exists with the required dose sequence (1 for MenACWY and 5 for Td/IPV), and the vaccination was administered after the patient was 10 years old.
> Add vaccination criteria for doubles

- app/components/app_consent_component.rb
- app/components/app_session_patient_table_component.rb
- app/controllers/consent_forms_controller.rb
- app/controllers/consents_controller.rb
- app/controllers/dev_controller.rb
- app/controllers/gillick_assessments_controller.rb
- app/controllers/patient_sessions_controller.rb
- app/controllers/patients_controller.rb
- app/controllers/session_attendances_controller.rb
- app/controllers/triages_controller.rb
- app/controllers/vaccinations_controller.rb
- app/jobs/school_session_reminders_job.rb
- app/lib/reports/careplus_exporter.rb
- app/lib/reports/offline_session_exporter.rb
- app/models/patient.rb
- app/models/patient_session.rb
- app/models/patient_session_stats.rb
- app/views/patient_sessions/_secondary_navigation.html.erb
- app/views/session_attendances/edit.html.erb
- spec/lib/reports/careplus_exporter_spec.rb
- spec/lib/reports/offline_session_exporter_spec.rb
Where we display a list of programmes, or where we select a single programme, we now ensure that we're only selecting programmes that the patient is eligible for, by selecting from the patient session rather than the session.
This is possible by removing the `has_many :programmes` on the patient session, and instead fetching all the programmes for a particular session and then filtering by eligible year groups. We can be confident that this change has been applied across the service as we're forced to update the strict loading rules for everything.
In the future, this approach might be reworked such that patients belong to multiple cohorts and we fetch the programmes via that model. This is necessary to make it possible to easily remove patients from a cohort even if we don't have the …
> Fetch programmes from patient session

- app/jobs/concerns/send_clinic_invitations_concern.rb
- app/jobs/school_consent_reminders_job.rb
- app/jobs/school_consent_requests_job.rb
- app/jobs/send_clinic_initial_invitations_job.rb
- app/models/session_notification.rb
- spec/jobs/clinic_session_invitations_job_spec.rb
- spec/jobs/school_consent_requests_job_spec.rb
- spec/jobs/send_clinic_initial_invitations_job_spec.rb
- spec/jobs/send_clinic_subsequent_invitations_job_spec.rb
- spec/models/session_notification_spec.rb
This is necessary for the MenACWY and Td/IPV programmes which aren't administered to Year 8s, however the HPV programme is administered for Year 8s.
As all three vaccines might be administered at the same time as a single session, there might be Year 8 patients in a session, and we have to make sure that only consent requests for HPV are sent out for these patients, not ones for Td/IPV and MenACWY as well.
> Ensure consent requests are only sent to eligible patients

- app/lib/govuk_notify_personalisation.rb
- spec/lib/govuk_notify_personalisation_spec.rb
So that the emails and texts read better we want this variable to be pluralised when we're talking about more than one vaccine.
> Pluralise GOV.UK Notify vaccination personalisation

- app/components/app_vaccination_record_summary_component.rb
- spec/components/app_vaccination_record_summary_component_spec.rb
When showing the summary of a vaccination record we need to highlight the programme separately to the vaccine or batch because some historical records won't have a vaccine associated with them.
> Show programme separate to vaccine

- app/components/app_vaccination_record_summary_component.rb
- app/controllers/draft_vaccination_records_controller.rb
- app/models/draft_vaccination_record.rb
- app/models/immunisation_import_row.rb
- app/models/vaccination_record.rb
- db/migrate/20250224200603_make_vaccination_record_dose_sequence_null.rb
- db/schema.rb
- spec/factories/vaccination_records.rb
- spec/models/vaccination_record_spec.rb
When importing historical records or when uploading not administered records, the dose sequence can be unknown and therefore isn't required in all cases, so the column must be nullable.
> Allow dose_sequence to be optional

- app/lib/reports/offline_session_exporter.rb
- app/models/immunisation_import_row.rb
- spec/features/import_vaccination_records_with_duplicates_spec.rb
- spec/lib/reports/offline_session_exporter_spec.rb
- spec/models/immunisation_import_row_spec.rb
- spec/models/immunisation_import_spec.rb
This adds a new column used when importing offline vaccination records, to tell Mavis which session the offline records are being imported for, ensuring that we associate them within Mavis to the correct session.
We can use the presence of this value to know if the file is being uploaded from an offline recording and therefore the validation is stricter than in other cases.
This is necessary because we want to be able to import vaccination records in the current academic year that happened outside Mavis, and currently we use that to determine whether the upload is from offline recording or not.
> Add SESSION_ID column when importing vaccination records

- app/models/consent_form.rb
- config/vaccines.yml
- spec/models/consent_form_spec.rb
If there are multiple vaccines, this ensures that we use all the available health questions.
> Combine health questions when giving consent

- app/components/app_import_format_details_component.rb
- app/models/immunisation_import_row.rb
- app/models/programme.rb
- spec/models/immunisation_import_row_spec.rb
- spec/models/programme_spec.rb
The special values for dose sequences are different per programme so we need to customise the functionality to allow this. At the same time, we only require dose sequence to be present if we're uploading a file for a current session.
> Add custom dose sequence values per programme

- app/components/app_import_format_details_component.rb
- app/models/immunisation_import_row.rb
This value was currently only required for HPV, but we want it to be optional across all programmes as it won't always be available when uploading the file.
> Make CARE_SETTING optional for all programmes

- app/controllers/parent_interface/consent_forms/edit_controller.rb
- app/models/consent_form.rb
- app/views/parent_interface/consent_forms/edit/consent.html.erb
- db/migrate/20250224195511_add_chosen_vaccine_to_consent_form.rb
- db/schema.rb
- spec/factories/consent_forms.rb
- spec/features/parental_consent_doubles_spec.rb
- spec/models/consent_form_spec.rb
This updates the `response` enum to include a new `given_one` option that is used when the user only gave consent for one vaccine.
In this case, a new `chosen_vaccine` field is populated which is also used to filter the health questions.
The "Check your answers" page looks off currently, but will be updated in a follow-up PR.
> Allow parents to consent to just one vaccine

- config/initializers/govuk_notify.rb
These have been added to GOV.UK Notify so we're in a position to start sending out these emails now.
> Add Td/IPV and MenACWY email templates

- app/models/immunisation_import_row.rb
- app/models/vaccination_record.rb
- spec/features/import_vaccination_records_spec.rb
- spec/fixtures/immunisation_import/valid_hpv.csv
- spec/models/immunisation_import_row_spec.rb
When uploading historical vaccination records, or those that happened outside of Mavis, we may not always know the delivery site so we need to allow it to be optional.
> Allow delivery site to be optional

- app/views/parent_interface/consent_forms/confirm.html.erb
- config/locales/en.yml
This adds new cards for the cases where users choose to consent to only one vaccine.
The refusal reason step is missing - that's coming in a follow-up PR.
> Update check answers page for doubles

- app/components/app_vaccination_record_summary_component.rb
This is necessary when uploading historical vaccination records not tied to a session, the school name will be present in the `location_name` column, and we should display it to the nurses.
> Use location_name when there's no session

- app/components/app_import_format_details_component.rb
- app/models/immunisation_import_row.rb
- app/models/vaccination_record.rb
- db/migrate/20250224221219_make_vaccination_record_performed_ods_code_null.rb
- db/schema.rb
- spec/factories/vaccination_records.rb
- spec/fixtures/immunisation_import/valid_hpv.csv
- spec/models/immunisation_import_row_spec.rb
- spec/models/vaccination_record_spec.rb
In some cases this value won't be available when importing the historical vaccinations so we need to allow files to be uploaded that don't contain an ODS code.
> Allow performed_ods_code to be optional

- app/components/app_vaccination_record_summary_component.rb
- app/controllers/patient_sessions_controller.rb
- app/jobs/school_consent_reminders_job.rb
- app/jobs/school_consent_requests_job.rb
- app/models/concerns/patient_session_status_concern.rb
- app/models/draft_vaccination_record.rb
- app/models/patient_session.rb
- app/views/draft_vaccination_records/confirm.html.erb
- app/views/patient_sessions/show.html.erb
- config/routes.rb
- spec/features/td_ipv_already_had_spec.rb
This replaces the ability to triage a patient the moment they're in a session with a feature that instead allows a patient to be marked as having already had the vaccine, which records a vaccination record against the patient for that programme, and prevents any consent request emails from going out if they haven't already.
> Add "Record as already vaccinated" functionality

- app/models/consent_form.rb
- spec/features/parental_consent_doubles_spec.rb
When parents only give consent to one vaccine in a doubles campaign, we need to ask them for a reason.
> Ask for reason when parent consents to one vaccine

- app/views/parent_interface/consent_forms/edit/consent.html.erb
The session might have more programmes than the consent form, and we don't want to show "HPV" next to doubles, for example.
> Get the programmes from the consent form

- config/locales/en.yml
When getting verbal consent these strings were missing and was causing an error.
> Add missing doubles translation strings

- app/models/consent_form.rb
- lib/tasks/vaccines.rake
- spec/factories/health_questions.rb
- spec/factories/vaccines.rb
- spec/features/parental_consent_doubles_spec.rb
- spec/features/parental_consent_flu_spec.rb
- spec/models/consent_form_spec.rb
This ensures that all the health questions are shown for the Td/IPV and MenACWY vaccines, and any duplicates are ignored. This works by re-indexing the questions, and doesn't work properly if the health questions have follow up answers, but none of them do at the moment.
To make this work okay, I've had to re-order the health questions to ask about previous vaccinations at the end.
> Handle doubles health questions 

- app/models/immunisation_import_row.rb
When importing vaccination records, we need to ensure that the vaccine is approriate for the programme. It shouldn't be possible to, for example, set the programme to HPV and then specify a vaccine from Td/IPV.
> Validate vaccine for programme

- app/models/consent.rb
- app/models/consent_form.rb
- spec/models/consent_spec.rb
When submitting a consent form it's possible to consent to only one vaccination programme, so we need to make sure the generated `Consent` objects reflect that.
> Create consent responses per programme

- app/controllers/cohorts_controller.rb
- app/policies/patient_policy.rb
- app/policies/vaccination_record_policy.rb
- spec/policies/patient_policy_spec.rb
If a patient was vaccinated by the organisation, even if that happened historically and the patient is no longer part of the organisation cohort, we still want the organisation to have visibility of the patients so they can be searched for.
> Show patients if we have a vaccination record

- app/models/immunisation_import_row.rb
The comparison check is also checking for the presence of a value, but since the conditions are the same, we can split them up in to two separate checks, and only perform the comparison check if there's a value.
> Avoid duplicate TIME_OF_VACCINATION errors

- app/components/app_activity_log_component.rb
- app/components/app_log_event_component.rb
- app/jobs/email_delivery_job.rb
- app/jobs/sms_delivery_job.rb
- app/lib/govuk_notify_personalisation.rb
- app/models/notify_log_entry.rb
- db/migrate/20250225161342_add_programme_i_ds_to_notify_log_entries.rb
- db/schema.rb
- spec/components/app_activity_log_component_spec.rb
- spec/factories/notify_log_entries.rb
- spec/features/delete_vaccination_record_spec.rb
- spec/features/parental_consent_send_request_spec.rb
- spec/jobs/email_delivery_job_spec.rb
- spec/jobs/sms_delivery_job_spec.rb
- spec/lib/govuk_notify_personalisation_spec.rb
- spec/models/notify_log_entry_spec.rb
When rendering the emails and text messages that have been sent for a particular patient, we can now show the programmes associated with that email or text message.
To implement this I've created a cache of programmes which can be used across all the activity log entries to avoid needing multiple queries each time and for each type of record.
> Show notify log entry programmes in activity log 

- app/controllers/concerns/consent_form_mailer_concern.rb
- app/models/consent.rb
- app/models/consent_form.rb
- spec/controllers/concerns/consent_form_mailer_concern_spec.rb
If a user has consent to one vaccine programme, but not the other, we need to make sure we sent them two emails, confirming the consent given and the consent refused on each.
> Send consent confirmation emails per programme 

- app/views/parent_interface/consent_forms/edit/reason.html.erb
- spec/features/parental_consent_doubles_spec.rb
- spec/features/parental_consent_refused_spec.rb
- spec/features/triage_then_parental_consent_refused_spec.rb
This updates the content shown on one of the questions when refusing consent to ask specifically which programme the parent is refusing consent for. For HPV this doesn't change much, but for doubles it makes clear that we're only asking about the vaccination that the parent doesn't want to consent to.
> Update content when refusing consent

- config/onboarding/coventry-production.yaml
This adds the two programmes to the onboarding configuration for Coventry. Although we're unlikely to use this to add the programmes in production, it allows us to create a local version of Coventry's set up.
> Add MenACWY and Td/IPV to Coventry

- app/models/concerns/patient_session_status_concern.rb
- spec/factories/programmes.rb
- spec/features/menacwy_vaccination_administered_spec.rb
- spec/features/td_ipv_vaccination_administered_spec.rb
This is a feature that shouldn't be going live yet, so we need to put it behind a feature flag so we can test locally but we don't need to enable it in production.
> Add feature flag for vaccinating doubles
