nhsuk/manage-vaccinations-in-schools

lib/graph_records.rb
spec/lib/graph_records_spec.rb

This can be used to output a mermaid-style flow diagram to visualise connections between records: patients, parents, consents, etc. The output data does not contain any pii, complete or partial, from these records.
For now this can be used through the console to generate these graphs to understand the structure and relationships connected to a patient, or other records. The next step will be to make this available in the non-prod envs through the browser on a page that will load in mermaid and render the graphs out.
Example from `test`:
```rb
manage-vaccinations(staging)> puts GraphRecords.new.graph(patients: [Patient.all.sample])
flowchart TB
classDef patient_focused fill:#c2e598,stroke:#000,stroke-width:3px
classDef parent fill:#faa0a0
classDef consent fill:#fffaa0
classDef …
```

Add GraphRecords module.

---

terraform/bootstrap/main.tf
terraform/bootstrap/variables.tf
terraform/scripts/bootstrap.sh

Remove code that is no longer needed as part of the terraform bootstrap setup.
* Remove ECR repository from terraform config. Every environment pulls images from mavis/webapp now
* Remove creation of docker build scripts from bootstrap script. The docker build is done by the build.yml Github workflow now and the images don't need to be pushed to container registries with different names anymore

Bootstrap cleanup

---

app/models/immunisation_import_row.rb

This improves how we determine whether a file is being uploaded as part of offline recording by checking for the presence of a value in `SESSION_ID`, bypassing the `session_id` method which tries to parse the value in to an integer and returns `nil` if it's not an integer.
This ensures that if a non-integer value is in the `SESSION_ID` column, the file will be treated as offline recording and will be validated as a valid session ID.

Improve offline recording detection

---

db/migrate/20250211092238_add_year_groups_to_class_imports.rb
lib/tasks/class_imports.rake

This part of the migration doesn't run successfully as part of the 2.0.0 release because the model has changed too much since then.
We can replace this with a Rake task that we can run post-deployment.

Remove data migration

---

app/components/app_consent_confirmation_component.rb
spec/components/app_consent_confirmation_component_spec.rb

Bug in initial implementation, only one of the vaccines was mentioned on confirmation of refusal.
New version:
This change also fixes the dates so the last two are separated with " or " instead of ", and ".

Mention both vaccines when doubles refused

---

app/components/app_consent_confirmation_component.rb
spec/components/app_consent_confirmation_component_spec.rb

When displaying the dates for a session after confirming consent we only want to show dates happening in the future as those are the only ones where the patient can be vaccinated.

Only show future dates on consent confimrmation

---

app/controllers/register_attendances_controller.rb
app/views/register_attendances/index.html.erb

This is the only page left in the sessions view where we don't paginate the list of patients. In most cases the list won't be too long, but for the community clinic it could be very long and therefore might require pagination.

Add pagination to register attendances page

---

app/lib/vaccinated_criteria.rb
spec/lib/vaccinated_criteria_spec.rb

For MenACWY, the patient is considered vaccinated if there are any vaccination records regardless of dose sequence. Currently we were only considering the patient vaccinated if there was a vaccination record with a dose sequence of 1.

Fix vaccinated criteria for MenACWY

---

app/components/app_consent_confirmation_component.rb
spec/components/app_consent_confirmation_component_spec.rb
spec/features/parental_consent_change_answers_spec.rb
spec/features/parental_consent_spec.rb

Updates consent confirmation panels to say "Consent confirmed" not "Consent given".

Change given to confirmed on confirmation pages

---

app/models/immunisation_import_row.rb
config/locales/en.yml
spec/models/immunisation_import_row_spec.rb

Currently this was failing as the `session` method was raising an exception if the `SESSION_ID` was present but didn't match one of the session IDs of the organisation. Instead we can refactor this method to return `nil` and then it can be used in other validations, specifically when checking that the date of vaccination matches one of the dates in the session.

Ensure validation against SESSION_ID works

---

.github/workflows/build.yml
.github/workflows/continuous_deployment.yml
.github/workflows/deploy_infrastructure.yml
.github/workflows/deploy_mavis.yml
.github/workflows/test.yml

- Call infrastructure deploy workflow
- Also remove explicit github.sha inputs
-- From documentation: `When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow.`

MAV-745: Deploy infrastructure on push to main

---

app/models/consent_form.rb
spec/models/consent_form_spec.rb

If the parent originally decided to consent to only one vaccine and then went back to refuse or give consent, we need to make sure that the `chosen_vaccine` value is `nil` to accurately represent this state.

Reset chosen_vaccine if changing response

---

app/lib/reports/offline_session_exporter.rb
spec/lib/reports/offline_session_exporter_spec.rb

This is important to include as a record of previous vaccinations so that the nurses have all the information they need in a context where access to Mavis is unavailable due to a lack off Internet connection.
The `SESSION_ID` will not be provided for these, which allows them to be re-imported successfully, and there's no risk of the records being duplicated as we rely on the `UUID` column to uniquely reference the records.

Include historical records in offline reporting

---

app/models/immunisation_import_row.rb
spec/features/import_vaccination_records_with_duplicates_spec.rb
spec/models/immunisation_import_row_spec.rb

When recording a vaccination record not associated to a session in Mavis we need to ensure that the location on the vaccination record is stored as the name of the school.
This refactors the logic to make sure it was working in all cases.

Make sure school name is stored on vaccination record

---

app/assets/stylesheets/_secondary-navigation.scss
app/components/app_secondary_navigation_component.html.erb
spec/components/app_secondary_navigation_component_spec.rb

- Aligns with updated navigation design in the NHS header (no padding either side)
- Uses same method of highlighting current item, using `<strong>` element as a fallback
- Items appear linearised on smaller screens
| ------ | ----- |
| ![before](https://github.com/user-attachments/assets/cd31987a-b700-499b-8837-27043187d664) | ![after](https://github.com/user-attachments/assets/07e0252a-a6c1-4162-b5c6-6df98efacf8c) |
| ------ | ----- |
| ![before-desktop](https://github.com/user-attachments/assets/a8c6d42c-5f91-4c48-91c5-2111641ba412) | ![after-desktop](https://github.com/user-attachments/assets/a58739bd-d1ab-41c1-aabc-1b8ed263a1a3) |

Update design of secondary navigation component

---

config/locales/en.yml
spec/forms/session_programmes_form_spec.rb

This was a typo in the content.

Fix spelling of programme

---

lib/tasks/patient_sessions.rake

This adds a Rake task that helps with the post-deploy tasks for version 2.0.0 where all patients are expected to be found in the community clinics session. Once this has been run in all environments we can delete this Rake task.

Add patient_sessions:add_to_clinic

---

app/models/immunisation_import_row.rb
spec/features/import_vaccination_records_with_duplicates_spec.rb
spec/models/immunisation_import_row_spec.rb

When importing vaccination records, if we have a school URN and no school name, we can try and get the school name from the school by looking up the URN.

Get location name from school if available

---

config/locales/en.yml
spec/models/immunisation_import_row_spec.rb

When importing vaccination records, the current error messages weren't clear enough and we've been given some improved content.

Improve vaccine and programme error messages

---

app/controllers/parent_interface/consent_forms_controller.rb
app/views/parent_interface/consent_forms/confirm.html.erb
spec/features/parental_consent_change_answers_spec.rb

The back link wasn't working correctly, it was taking the user to the `consent` question rather than taking the user to the last step in the wizard flow.
There's also the potential for the previous question to have been a health question, in which case we need to take the user to the correct one.

Fix back link on parental consent confirm page

---

app/assets/stylesheets/_secondary-navigation.scss

Reinstate the sticky navigation variant (used on the patient session page) to the secondary navigation component, that was removed in #3102.
(Note that for 2.1, the design of this will change further so that the sticky navigation appears across the full width of the page, and displays a shadow when stuck)

Reinstate sticky secondary navigation on patient session page

---

app/components/app_vaccinate_form_component.html.erb
app/views/draft_vaccination_records/batch.html.erb
app/views/draft_vaccination_records/date_and_time.html.erb
app/views/draft_vaccination_records/delivery.html.erb
app/views/draft_vaccination_records/location.html.erb
app/views/draft_vaccination_records/outcome.html.erb
app/views/draft_vaccination_records/vaccine.html.erb
spec/components/app_patient_page_component_spec.rb
spec/components/app_vaccinate_form_component_spec.rb
spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb
spec/features/invalidate_consent_spec.rb
spec/features/manage_attendance_spec.rb
spec/features/triage_delay_vaccination_spec.rb
spec/features/withdraw_consent_spec.rb

This updates various pages of the vaccination journey to include the name of the programme in the heading to make it clear to the nurses which programme they're recording a vaccination for.

Update vaccination journey content

---

app/forms/search_form.rb
spec/forms/search_form_spec.rb

This ensures that when entering an invalid date in the search form the user won't see an unhandled exception page, instead the date will be left blank.
https://good-machine.sentry.io/issues/6359085868?project=4505625073876992

Ensure invalid dates don't raise an error

---

app/models/patient.rb
spec/models/patient_spec.rb

When searching for patients by name, we can return the results in order of similarity to the original query to help the nurses find the right patient when looking for patients.

Sort patients when fuzzy searching

---

app/components/app_search_component.rb
app/controllers/sessions/consent_controller.rb
app/controllers/sessions/register_controller.rb
app/controllers/sessions/triage_controller.rb
app/forms/search_form.rb
app/views/sessions/consent/show.html.erb
app/views/sessions/register/show.html.erb
app/views/sessions/triage/show.html.erb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/hpv_vaccination_pre_screening_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/parental_consent_create_patient_spec.rb
spec/features/parental_consent_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb

This changes how the list of patients in the triage tab is filtered to only display patients that need triage, or have been triaged already. Patients that don't need triage are available immediately in the register tab.
This also changes how the list of patients in the register tab is filtered to only display patients that are ready to be vaccinated, specifically they've got consent and either don't need triage or have been triaged.
I will add some feature tests in a follow up PR that covers the entire flow, once the record and outcome tabs are in place.

Filter session triage and register tabs

---

app/components/app_outcome_banner_component.rb
app/components/app_patient_page_component.html.erb
app/components/app_patient_session_search_result_card_component.rb
app/components/app_search_component.rb
app/components/app_simple_status_banner_component.rb
app/controllers/concerns/search_form_concern.rb
app/controllers/sessions/outcome_controller.rb
app/controllers/sessions/register_controller.rb
app/forms/search_form.rb
app/lib/reports/offline_session_exporter.rb
app/models/concerns/patient_session_status_concern.rb
app/models/patient_session.rb
app/models/patient_session/outcome.rb
app/models/patient_session/record.rb
app/models/patient_session/triage.rb
app/views/sessions/_secondary_navigation.html.erb
app/views/sessions/outcome/show.html.erb
config/locales/patient_session.en.yml
config/routes.rb
spec/components/app_outcome_banner_component_spec.rb
spec/components/app_simple_status_banner_component_spec.rb
spec/features/delete_vaccination_record_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/parental_consent_clinic_spec.rb
spec/features/parental_consent_create_patient_spec.rb
spec/features/parental_consent_refused_spec.rb
spec/features/parental_consent_spec.rb
spec/forms/search_form_spec.rb
spec/models/patient_session/outcome_spec.rb
spec/models/patient_session_spec.rb

This updates the design of the session outcome page to match the latest designs in the prototype, where a single tab for vaccinations are shown and the nurses are able to filter the patients by vaccination status and see the value per programme.

Build new session outcome tab

---

app/controllers/patient_sessions_controller.rb

This parameter is used to redirect the user and because we're using it to generate a path by executing a method name we should validate that it's an expected value to prevent a user providing a value that redirects the user elsewhere.

Restrict return_to parameter

---

app/lib/reports/careplus_exporter.rb
spec/lib/reports/careplus_exporter_spec.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

Extend spec coverage for both programme vaccinations exporter and careplus exporter.
Extends #3130.

Change the CarePlus exporter to redact patient address_line_1 if patient is restricted

---

app/models/patient_session/outcome.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/models/patient_session/outcome_spec.rb

This outcome status should only be used when it's not possible to continue attempting to vaccinate the patient. This is only the case where the parents have refused consent, or a nurse has triaged the patient as unsafe to vaccinate, or a vaccination record exists with a reason that's not retryable.
The outcome rules are specified here: https://docs.google.com/document/d/1RkyibohJEV7V4ywv-52GKgfyfuDiFqfjvRYWwwYGO7U/edit?usp=sharing

Fix could not vaccinate outcome

---

app/components/app_patient_session_search_result_card_component.rb
app/components/app_programme_status_tags_component.rb
app/components/app_search_component.rb
app/controllers/patient_sessions_controller.rb
app/controllers/sessions/outcome_controller.rb
app/controllers/sessions/record_controller.rb
app/controllers/sessions/triage_controller.rb
app/views/sessions/_header.html.erb
app/views/sessions/outcome/show.html.erb
app/views/sessions/record/show.html.erb
config/locales/status.en.yml
spec/components/app_programme_status_tags_component_spec.rb
spec/features/e2e_journey_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/hpv_vaccination_pre_screening_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/parental_consent_clinic_spec.rb
spec/features/parental_consent_create_patient_spec.rb
spec/features/parental_consent_refused_spec.rb
spec/features/parental_consent_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/features/triage_delay_vaccination_spec.rb

This updates the tabs on the session page to match the latest designs in the prototype. The record tab has been renamed to "Record vaccinations" and now shows only patients that have been registered as attending, and don't have a vaccinated session outcome. The outcome tab has been renamed to "Session outcomes" and shows the outcome of the patients in the session, the overall programme outcome will be displayed in the programme children tab.

Update session record and outcome tabs

---

app/components/app_outcome_banner_component.rb
app/models/patient/programme_outcome.rb
spec/components/app_outcome_banner_component_spec.rb
spec/factories/patient_sessions.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/models/patient/programme_outcome_spec.rb

When recording a vaccination, if the reason is set to "already had", we should treat the patient as having a programme outcome of vaccinated.

Consider already had as vaccinated

---

app/components/app_patient_session_search_result_card_component.rb
app/models/patient.rb
app/models/patient/next_activity.rb
config/locales/activity.en.yml
spec/components/app_patient_session_search_result_card_component_spec.rb
spec/models/patient/next_activity_spec.rb

When displaying the patient sessions on the register tab, we want to show the next action required to be taken to help the nurses with registering the patients.

Show next activity on register tab

---

app/components/app_patient_session_search_result_card_component.rb
spec/components/app_patient_session_search_result_card_component_spec.rb

This is needed to match the designs in the prototype where the action required is shown on the search results.

Show action required on record tab

---

app/components/app_search_component.rb
app/controllers/concerns/search_form_concern.rb
app/forms/search_form.rb
app/models/patient.rb
app/models/patient_session.rb
spec/forms/search_form_spec.rb

When searching for patients by date of birth, this allows the user to only specify part of the date of birth (year, month and day) and search across the patients only on that part of the date of birth.

Allow search on partial date of birth

---

app/models/batch.rb
app/models/consent.rb
app/models/consent_form.rb
app/models/consent_form_programme.rb
app/models/consent_notification_programme.rb
app/models/gillick_assessment.rb
app/models/location.rb
app/models/organisation.rb
app/models/organisation_programme.rb
app/models/parent_relationship.rb
app/models/patient.rb
app/models/patient_session.rb
app/models/pre_screening.rb
app/models/programme.rb
app/models/session.rb
app/models/session_attendance.rb
app/models/session_date.rb
app/models/session_programme.rb
app/models/team.rb
app/models/triage.rb
app/models/vaccine.rb

This updates the auditing setup on our models. By associating models for audits, it makes it easier for us to get a more complete picture of the changes done to a record with the `own_and_associated_audits`. Here's a minor example of a patient that has been removed from a cohort:
The general approach used to decide how and what auditing to add:
- Typically auditing is for tracking updates to records or, in rarer cases, deletion of records.
- Only enable auditing for those records where we want to track those activities.
- Join tables don't typically need auditing.
- Models can be associated with one of their `belongs_to` relationships, with a view on usefulness in operational settings, where it's most useful to see associated changes easily.

Add audit associations

---

spec/features/parental_consent_refused_spec.rb

When a parent refuses consent, the programme outcome should be marked as "Could not vaccinate".

Add missing test for could not vaccinate

---

app/controllers/patient_sessions_controller.rb
app/views/cohorts/index.html.erb
app/views/cohorts/show.html.erb
app/views/imports/issues/show.html.erb
app/views/imports/show.html.erb
app/views/patient_sessions/_breadcrumbs.html.erb
app/views/patient_sessions/log.html.erb
app/views/patient_sessions/show.html.erb
app/views/patients/log.html.erb
app/views/patients/show.html.erb
app/views/programmes/patients.html.erb
app/views/programmes/sessions.html.erb
app/views/programmes/show.html.erb
app/views/school_moves/show.html.erb
app/views/sessions/_header.html.erb
app/views/sessions/consent/show.html.erb
app/views/sessions/outcome/show.html.erb
app/views/sessions/record/show.html.erb
app/views/sessions/register/show.html.erb
app/views/sessions/show.html.erb
app/views/sessions/triage/show.html.erb
app/views/vaccination_records/index.html.erb
app/views/vaccination_records/show.html.erb
config/locales/en.yml
spec/features/e2e_journey_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/parental_consent_spec.rb

This updates the various pages where breadcrumbs are shown to match the latest designs in the prototype:
- A "Home" entry is always shown, which takes the user to the dashboard page.
- When looking at a patient session, the tab that the user came from is shown as an item in the breadcrumbs.

Update breadcrumbs to match designs

---

app/lib/reports/systm_one_exporter.rb
app/models/vaccination_report.rb
app/views/vaccination_reports/file_format.html.erb
config/locales/helpers.en.yml
db/seeds.rb
spec/features/download_vaccination_reports_spec.rb
spec/lib/reports/systm_one_exporter_spec.rb
spec/models/vaccination_report_spec.rb

The exporter has been tested and confirmed working by Hertfordshire. It's hidden behind a feature flag for the time being, and only available on HPV programmes.
Worth noting the current export format is fairly bespoke to Hertfordshire's needs, and there are a few areas we'll need to review for new teams or even new vaccines:
-  **vaccination field** - This maps from the vaccine brand and dose sequence to a code. We only have mappings for "Gardasil 9" at the moment, and we don't even know if maybe these codes change depending on provider.
- **practice code** - The URN or ODS code of where the vaccination was performed. Hertfordshire has only defined how to do this for vaccinations in schools (URN) or in GP practices (ODS code), we've just assumed that for clinics this is also the ODS code, …

Add SystmOne exporter

---

app/components/app_import_format_details_component.rb
app/components/app_vaccinate_form_component.rb
app/components/app_vaccination_record_summary_component.rb
app/controllers/draft_vaccination_records_controller.rb
app/forms/vaccinate_form.rb
app/lib/reports/offline_session_exporter.rb
app/models/draft_vaccination_record.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb

Td/IPV (or other multi-dose vaccines) shouldn't have a dose sequence number recorded on them by default as we can't be sure which dose sequence will be being administered on the day.

Don't record a dose sequence for Td/IPV

---

app/models/patient/consent_outcome.rb

This updates the ordering of the consent filters to match the designs in the prototype.

Update ordering of consent filters

---

app/components/app_patient_session_search_result_card_component.rb
app/components/app_register_status_tag_component.rb
app/views/patient_sessions/show.html.erb
config/locales/status.en.yml
spec/features/manage_attendance_spec.rb

This adds a component that renders a patient registration status and updates the two places where this is shown to use the same component.
At the same time, I've also fixed the colours to match the latest ones in the prototype where "Not registered yet" is grey and "Attending session is blue".

Add AppRegisterStatusTagComponent

---

app/components/app_activity_log_component.rb
app/components/app_patient_page_component.rb
app/components/app_vaccinate_form_component.html.erb
app/controllers/vaccinations_controller.rb
app/forms/vaccinate_form.rb
app/models/pre_screening.rb
app/models/programme.rb
config/locales/en.yml
config/locales/pre_screening.en.yml
db/migrate/20250307161252_add_programme_to_pre_screenings.rb
db/migrate/20250307163053_add_questions_to_pre_screening.rb
db/schema.rb
spec/components/app_activity_log_component_spec.rb
spec/factories/pre_screenings.rb
spec/features/doubles_vaccination_administered_spec.rb
spec/features/e2e_journey_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/hpv_vaccination_pre_screening_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/features/vaccination_todays_batch_spec.rb
spec/lib/patient_merger_spec.rb
spec/models/pre_screening_spec.rb

This makes a number of changes to the pre-screening form to match the latest designs in the prototype. Specifically this changes the radio buttons to checkboxes, adds two new questions asking about medication and pregnancy, and pre-populates the answers when vaccinating a patient for multiple vaccines in the same session.

Build new pre-screening designs

---

app/controllers/patient_sessions_controller.rb
spec/features/td_ipv_already_had_spec.rb

The "Record as already vaccinated" feature currently doesn't work on community clinic sessions as we need to ask the nurse which clinic they are recording this for. This is asked during the normal vaccination flow, but is missing in this scenario.
https://good-machine.sentry.io/issues/6334292237/

Allow recording already had vaccination for a clinic session

---

app/models/concerns/patient_session_status_concern.rb
app/models/patient_session/session_outcome.rb
spec/features/parental_consent_refused_spec.rb
spec/models/patient_session/session_outcome_spec.rb

If the patient has consent refused, or they've been triaged as "do not vaccinate", then they should have a session outcome of "refused" or "had contraindications" respectively. Currently they would show as "No outcome yet" which is confusing and not correct.

Update "could not vaccinate" session outcome

---

app/lib/vaccinated_criteria.rb
app/models/patient/programme_outcome.rb
spec/lib/vaccinated_criteria_spec.rb

This updates the vaccinated criteria for Td/IPV to allow the patient to be considered vaccinated if they have an administered vaccination record that was recorded by a SAIS nurse in a school or community clinic session.
The criteria in the functional spec is written as:
> If a child has a Td/IPV vaccination record which is administered after the age of 10 and:
> a) recorded as a fifth dose / second booster, OR
> b) administered by a SAIS team
> then they will be considered already vaccinated for the Td/IPV programme in Mavis and will not be added to any future sessions.

Update vaccinated criteria for Td/IPV

---

app/controllers/dev_controller.rb
app/controllers/parent_interface/consent_forms/edit_controller.rb
app/models/consent_form.rb
app/models/health_question.rb
spec/features/parental_consent_change_answers_spec.rb
spec/models/consent_form_spec.rb

This allows us to ensure that we're only seeding the health questions for the relevant vaccines, for example if a parent only consents to one vaccine then we will only show the health questions relevant for that vaccine.
This attempts to save any previously submitted answers, if the question title is the same.
I think there is scope to improve the feature test coverage here, which I will do in a follow up PR, but it requires a wider refactor of how the health questions are tested. A number of parental consent feature tests rely on Flu, which is currently broken due to it having follow-up questions that are currently not supported.

Seed health questions when consent is given

---

app/lib/reports/offline_session_exporter.rb
app/models/immunisation_import.rb
spec/lib/reports/offline_session_exporter_spec.rb

This isn't used when re-importing the file as the location is determined from the `SESSION_ID`, and having it present could cause confusion if the nurse tries to edit the value for a different school session.
This is proposed as a solution to: https://nhsd-jira.digital.nhs.uk/browse/MAV-755 (discussion: https://screening-discovery.slack.com/archives/C055LFS48RM/p1740754413297729)

Remove SCHOOL_URN from offline export

---

app/controllers/draft_vaccination_records_controller.rb
app/controllers/patient_sessions_controller.rb
app/models/vaccination_record.rb
spec/features/td_ipv_already_had_spec.rb

If an "already had" vaccination record is created, and the patient needs triage, we should record a "do not vaccinate" triage to make sure the patient isn't double vaccinated.

Triage patients when recording vaccination already had

---

app/models/patient.rb
spec/features/patient_search_spec.rb
spec/models/patient_spec.rb

This should improve the reliability and predictability of the search by comparing the similarity of the patient name as displayed to the user, rather than comparing only the first and last name separately. In most cases, nurses will search using the full name of the patient and the fuzzy search is designed to avoid typos or small errors from making it difficult to find a patient.
A few tests locally suggests this works better than our current approach.

Make fuzzy search work on full name

---

spec/lib/reports/careplus_exporter_spec.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

This ensures that we're testing the reports in all 3 programmes that we currently support: HPV, MenACWY and Td/IPV.
Best reviewed hiding whitespace changes.

Improve test coverage for reports

---

app/controllers/sessions/triage_controller.rb

At the moment, patients are only shown in the triage list if all the programmes need triage, whereas the logic should be that if any programme needs triage the patient should appear in the list.

Ensure patients are shown in triage list

---

config/locales/patient_session_statuses.en.yml
config/locales/status.en.yml
spec/components/app_outcome_banner_component_spec.rb
spec/components/app_simple_status_banner_component_spec.rb

Update status colours used on patient session summary to more closely align with the status colours used on session lists.
Also update the 2 finite outcomes for a session (Refused, Contraindications) to use `red`, instead of `dark-orange` for their status colouring.

Updated status colours

---

app/controllers/draft_vaccination_records_controller.rb
spec/features/doubles_vaccination_administered_spec.rb
spec/features/e2e_journey_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/features/vaccination_todays_batch_spec.rb

After vaccinating a patient, the user should be taken back to the patient page in the session, so they can record another vaccination if necessary (for example with doubles).

Return to patient session page

---

app/components/app_patient_session_search_result_card_component.rb

When passing it to the attendance buttons. This doesn't have any effect on the functionality, but avoids an error being logged related to the `session_slug` being unpermitted.

Permit search_form parameter

---

app/components/app_patient_session_search_result_card_component.rb
app/models/patient_session.rb
app/policies/session_attendance_policy.rb
spec/components/app_patient_session_search_result_card_component_spec.rb

This ensures that we're not showing the buttons when the attendance cannot be changed, for example if a vaccination record has been created against that patient and session for the particular date.

Only show attendance buttons if allowed

---

app/controllers/concerns/vaccination_mailer_concern.rb
config/initializers/govuk_notify.rb
spec/controllers/concerns/vaccination_mailer_concern_spec.rb
spec/features/doubles_vaccination_administered_spec.rb
spec/features/edit_vaccination_record_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb

This updates the vaccination administered emails and texts to send one appropriate for the programme that was vaccinated. We need this as the content will be different for each programme.
I've also added the Td/IPV and MenACWY templates in to the service so we can start to test these, although the content is not quite finalised.

Send vaccination administered per programme

---

app/models/immunisation_import_row.rb
config/locales/en.yml
spec/models/immunisation_import_row_spec.rb

For Td/IPV and MenACWY, the dose sequence should not be provided when a nurse is uploading a file containing vaccination records for a session (i.e. for offline recording).
This is because we don't currently allow the nurses to set the dose sequence while using the service normally, and it can lead to a confusing situation where the nurse uploads a vaccination record that's not the fifth dose, leading to the patient not being marked as vaccinated in the service.

Don't allow dose sequence to be provided

---

app/models/immunisation_import_row.rb
spec/models/immunisation_import_row_spec.rb

This fixes a bug where we would end up looking for a location with a `nil` `urn` when importing a vaccination record. We weren't properly filtering the locations meaning we would end up finding a community clinic (since they have no URNs) and assigning the location to the name of the community clinic.

Don't fetch school if no URN is provided

---

app/lib/reports/offline_session_exporter.rb
spec/lib/reports/offline_session_exporter_spec.rb

When downloading the offline export for a school session, we include all vaccinations records for the patient to ensure the nurses can see all details about the patients. This means that some of those vaccination records may have come from a clinic, therefore when downloading the school spreadsheet we need to include `CLINIC_NAME` as a column to handle those records.
https://good-machine.sentry.io/issues/6390050513/

Ensure clinic records are included in school session offline exports

---

app/models/immunisation_import_row.rb
spec/features/import_vaccination_records_with_duplicates_spec.rb
spec/models/immunisation_import_row_spec.rb

If a `TIME_OF_VACCINATION` is not specified, the default is set to midday (`12:00`). This causes a problem if the file is uploaded in the morning for sessions that happened that day (which could occur for an offline recording), as the `performed_at` date/time ends up being in the future which fails the validation on the `VaccinationRecord`.
Setting the time to midnight ensures that this will always pass those validation checks.
Preferrably, I think we should treat the date and time separately, and allow for the scenario where the time of the vaccination is unknown and present that to the user rather than needing to pick a default. However, this would require changes to the data model.
Alternatively, my first implementation was to use the current time, which passes the validation checks, …

Change default TIME_OF_VACCINATION to midnight

---

app/models/patient_session.rb
app/views/patient_sessions/_header.html.erb
spec/features/doubles_vaccination_cannot_record_as_admin_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb

This makes a number of small improvements to the banner listing outstanding programmes to ensure that only programmes without an outcome are shown and only to nurse users.

Small improvements to outstanding programmes banner

---

app/views/imports/issues/show.html.erb

This was incorrect as the user won't have come from the programmes section to get here.

Fix import issue breadcrumb

---

app/models/immunisation_import_row.rb
spec/fixtures/immunisation_import/valid_hpv.csv
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

When importing immunisation records, if the batch details are not provided we shouldn't try to create a batch instance because that fails validation errors on the batch.
It's valid to try and upload a vaccination record with a vaccine, but without batch details.
https://good-machine.sentry.io/issues/6390859317/

Don't try to create a batch if not provided

---

app/components/app_consent_component.html.erb
app/components/app_consent_component.rb
app/components/app_programme_session_table_component.rb
app/components/app_session_actions_component.rb
app/controllers/consents_controller.rb
app/models/patient/consent_outcome.rb
app/models/patient/next_activity.rb
app/models/patient/programme_outcome.rb
app/models/patient_session.rb
app/models/patient_session/register_outcome.rb
app/models/patient_session/session_outcome.rb
config/locales/status.en.yml
spec/models/patient/consent_outcome_spec.rb
spec/models/patient/programme_outcome_spec.rb
spec/models/patient_session/session_outcome_spec.rb

This renames the consent "none" status to "no_response" and the programme/session status from "none" to "none_yet". This won't change how it looks to users on the frontend.
This avoids potential confusion with the built in Rails `none?` method and helps to clarify exactly what this status is for.
I've also removed the label and colour for the "partially vaccinated" status as this status doesn't exist in the service.

Rename none outcome statuses

---

spec/features/doubles_vaccination_administered_spec.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

- **spec/features/doubles_vaccination_administered_spec.rb** - The two "vaccination administered" emails for doubles can come in different order, as has been demonstrated with intermittent failures of specs in CI. I don't see why these need to be ordered, since sending emails can happen out-of-order.
- **spec/lib/reports/programme_vaccinations_exporter_spec.rb** - Timestamps are generated within the tests so we need to freeze time for the entire spec.

Fix intermittently failing specs

---

app/views/patient_sessions/_header.html.erb

If a patient was vaccinated in a clinic and they are being viewed in the context of a school session, the programme navigation item should be ticked to show that the patient is vaccinated, even if it wasn't in that session.

Show ticks according to programme outcome

---

app/lib/reports/careplus_exporter.rb
app/lib/reports/programme_vaccinations_exporter.rb
app/lib/reports/systm_one_exporter.rb
app/models/organisation.rb
spec/lib/reports/careplus_exporter_spec.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb
spec/lib/reports/systm_one_exporter_spec.rb

When requesting a report, we should only be returning vaccination records for the programme the user requested the report for. At the moment, the programme is being ignored in the CarePlus report and we're instead returning all the vaccination records for the organisation.
I've also refactored the code to make it clearer where the vaccination records are coming from.

Filter reports by programme

---

app/controllers/school_moves_controller.rb

By preloading the patient's school, and the school move's school, we avoid needing a query to the database for each school move rendered on this page.

Reduce N+1 queries on school move index

---

app/views/patient_sessions/_header.html.erb
spec/features/td_ipv_already_had_spec.rb

Only certain users are allowed to record a vaccination, and currently we show this link to all users. This means admins can potentially click on this link.
Although they won't be able to complete the form (as they don't have permission to record a vaccination), they shouldn't be shown this link in the first place.

Hide "Record as already vaccinated" without permission

---

app/jobs/vaccination_confirmations_job.rb
app/lib/vaccinated_criteria.rb
app/models/vaccination_record.rb

This avoids an N+1 issue when checking whether a patient is vaccinated by checking only if `session_id` is present rather than checking if `session` is present.
I've also tided up a few other places where we do this check in a scope for consistency.

Avoid N+1 issue in vaccination criteria

---

config/locales/status.en.yml
spec/features/parental_consent_refused_spec.rb

This updates the label to match the wording in the designs.

Fix "Refused vaccine" label

---

app/components/app_outcome_banner_component.rb
app/models/patient_session/register_outcome.rb
app/models/patient_session/session_outcome.rb
spec/features/manage_attendance_spec.rb
spec/models/patient_session/session_outcome_spec.rb

If the patient's attendance has been marked as absent, the session outcome for that day should show as "absent from session".
Currently, the only way for a patient outcome to be "absent from session" would be if the vaccination was recorded as not administered for that reason, however we don't present "Absent from session" as one of the options available to the nurses. Instead, the expectation is that they would use the registration status.
In theory, you could import a vaccination record with this status, so we still need to support that, but it's not the usual way this would work.
Potentially we could remove "absent from school" and "absent from session" as vaccination record outcomes.

Set session outcome to absent from session

---

.github/workflows/deploy-application.yml
terraform/app/env/qa.tfvars
terraform/scripts/check_task_definition.sh

- Should use bucket name output not hardcoded value
- Digest was in tfvars file which overwrote command-line argument
- Remove from tfvars and restructure order to avoid overwrite in the future
- Script to exit on failed grep

Patch application deployment workflow

---

app/models/notify_log_entry.rb
db/migrate/20250128112422_remove_recipient_deterministic_from_notify_log_entries.rb
db/schema.rb

This column can be safely removed after version 2.1.0 is deployed as we will no longer being using this column anywhere. In version 2.1.0 it's marked as ignored anyway.

Remove recipient_deterministic column

---

lib/tasks/performance.rake

This adds a Rake task which we can use to quickly generate fake data suitable for some basic performance testing. It skips the import process and instead generates data directly in the database.

Add a Rake task for generating fake data

---

.github/workflows/deploy-application.yml
.github/workflows/deploy-infrastructure.yml
.github/workflows/deploy-mavis.yml

* Only one instance of deploy-mavis.yml can run at any time
* In the rare case where deploy-application.yml or deploy-infrastructure.yml is run directly, still prevent multiple concurrent workflows of the same type

Prevent concurrent deployment workflows targeting same environment

---

app/controllers/school_moves_controller.rb

Instead of querying the organisation, we can instead just compare the IDs which avoids an unnecessary query to the database.

Avoid N+1 issue on school moves page

---

app/lib/reports/careplus_exporter.rb
app/lib/reports/export_formatters.rb
app/lib/reports/offline_session_exporter.rb
app/lib/reports/programme_vaccinations_exporter.rb
app/lib/reports/systm_one_exporter.rb
app/models/patient_session.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

This avoids preloading (via `includes`) and instead fetches the data directly from the database where possible, using a more optimised version of the query to avoid preloading data which is then never used.
For example, preloading `patient.consents` gets all the consents across all the programmes, whereas for reporting we only care about the programme being reported on. It's not possible to nicely preload these using `includes` as the programme would need to be passed in as a parameter. Instead we can execute the query ourselves ensuring we only pull the necessary information.

Improve performance reporting by avoiding unnecessary preloading

---

.github/workflows/build-and-push-image.yml
.github/workflows/continuous-deployment.yml
.github/workflows/deploy-mavis.yml
terraform/resources/github_actions_policy.json

By including the build step into `deploy-mavis.yml`, it's possible to deploy branches within a single workflow. Previously, this required to run two workflow, first the build-and-push-image workflow and then the deploy-mavis workflow.
The `build-and-push-image.yml` workflow now checks if an image already exists and only builds it if it's not yet present in both ECR repositories. Apart from general efficiency, this allows us to run the workflow as part of production deployments where we generally don't want to build a new image and rather deploy an image that already exists and was tested on other environments.

Allow build and deployment with single workflow

---

app/models/patient_session/session_status.rb
spec/models/patient_session/session_status_spec.rb

This fixes a regression that was added in the performance work where a patient's session status was being set to "Refused" if the consent is conflicting, which is not correct. Instead, the patient should be left as "No outcome yet", because the consent needs to be resolved as either given or refused.

Ensure conflicting consent has correct session status

---

config/onboarding/leicestershire-training.yaml

This is based on the production configuration that we will eventually need, but adds test users that will allow users to sign in and test Mavis without needing to be set up with CIS2.
This is based on #3305 but I needed to raise it as a branch in the repo (rather than a fork) so it can be deployed.

Add training onboarding configuration for Leicestershire

---

terraform/resources/github_actions_policy.json

* This permission is needed for training deployment because training has two certificates instead of one

Add required permission for training deployment

---

app/jobs/school_consent_reminders_job.rb
app/jobs/school_consent_requests_job.rb

This reduces the amount of preloading performed in the school consent request and reminders jobs to try and fix out-of-memory issues we're seeing in production. This has been run once in production and the job has ran successfully.

Reduce preloading in school consent jobs

---

terraform/app/env/copilotmigration.tfvars
terraform/app/env/preview.tfvars
terraform/app/env/production.tfvars
terraform/app/env/qa.tfvars
terraform/app/env/test.tfvars
terraform/app/env/training.tfvars
terraform/app/variables.tf

This makes a number of small changes to the three variables related to enabling/disabling features in various environments to improve the maintainability and understandability of the variables.
Specifically, this changes the data type to boolean, and inverses the logic such that all the features are enabled by default (ready for production) and need to be explicitly disabled in non-production environments.

Refactor Terraform feature enable variables

---

app/models/concerns/csv_importable.rb

When importing patient records, we enqueue a job to PDS to ensure the patients are up to date with their equivelant record in PDS.
Currently, these jobs end up with the same priority as all other jobs (`0`) which leads to them being picked up ahead of other higher priotity jobs (such as sending emails, matching consent, or other imports).
Instead, we can set the priority to a lower value (arbritarily picked as `25`) to ensure they are only processed after all other jobs.

Set PDS job priority when importing records

---

app/jobs/bulk_update_patients_from_pds_job.rb
app/models/concerns/csv_importable.rb
config/settings.yml
config/settings/development.yml
terraform/app/env/copilotmigration.tfvars
terraform/app/env/preview.tfvars
terraform/app/env/training.tfvars
terraform/app/variables.tf

This name wasn't very clear as to exactly what would be enabled/disabled by setting the value. Instead, I've renamed the variable in Terraform and the associated variable in Rails to make it clear that it's referring only the jobs which update patients in bulk to reduce the number of unnecessary PDS API calls.

Rename `disable_pds` variable 

---

app/controllers/consent_forms_controller.rb
app/controllers/patients_controller.rb
app/controllers/sessions/consent_controller.rb
app/controllers/sessions/outcome_controller.rb
app/controllers/sessions/register_controller.rb
app/controllers/sessions/triage_controller.rb
app/jobs/school_session_reminders_job.rb
app/jobs/send_clinic_initial_invitations_job.rb
app/models/patient_session.rb

This adds a convenience scope that preloads the necessary associated models on a `PatientSession` that are required to fetch the programmes for that patient session (the programmes offered at the session that the patient is eligible for).

Add `PatientSession#includes_programmes`

---

Gemfile.lock

Updates Brakeman to the latest version to resolve bin/lint warnings of packages being out of date.

update Brakeman gem to 7.0.2

---

app/assets/stylesheets/_button.scss
app/assets/stylesheets/_filters.scss
app/components/app_patient_session_table_component.rb
app/components/app_search_component.rb

💅
- Fix wrapping of date input in patient search sidebar filters
- Fix size of icon and padding for search submit button
- Fix excessive bottom margin appearing in search filters
- Use tag for programmes in patient sessions table

Design tweaks

---

config/initializers/sentry.rb

In non-production environments, this is an exception we get fairly regularly as the GOV.UK Notify API key that we use is limited to team members only.
This adds a new filter to the Sentry handler which filters out these exceptions, unless the environment is production, to avoid sending unnecessarily high numbers of errors to Sentry.

Ignore exceptions related to team-only API keys

---

config/initializers/sentry.rb

When sending transactions to Sentry for profiling and performance monitoring, we don't need to sent transactions related to health checks as these will be happening fairly regularly and don't provide much benefit being in Sentry.
Instead, we can skip these to ensure we're only sending useful information to Sentry.

Ignore health check transactions

---

app/controllers/school_moves/exports_controller.rb
app/lib/reports/csv_school_moves.rb
app/lib/reports/export_formatters.rb
app/models/school_move_export.rb
app/views/school_moves/exports/confirm.html.erb
app/views/school_moves/exports/dates.html.erb
app/views/school_moves/index.html.erb
config/routes.rb
spec/features/download_school_moves_spec.rb
spec/lib/reports/csv_school_moves_spec.rb
spec/models/school_move_export_spec.rb

This PR introduces functionality to export school moves data to a CSV format. This feature is designed to assist new users in keeping their existing systems up-to-date during the transition period to full adoption.
- New service object to generate CSV exports of school move data
- New controller and views to handle date range input and confirmation page
| School Moves (1) | Date Range Input (2) | Confirmation and download (3) |
|------------------|---------------------------|---------------------|
|  <img width="1122" alt="Screenshot 2025-04-04 at 09 55 36" src="https://github.com/user-attachments/assets/76d2ed06-c2a3-4b8f-9f74-9fdaf56cf041" /> | <img width="1004" alt="Screenshot 2025-04-04 at 09 57 20" src="https://github.com/user-attachments/assets/99f1e03c-678d-414c-b9aa-7e11cf0a3820" …

Download school moves

---

terraform/app/modules/ecs_service/main.tf
terraform/app/modules/ecs_service/outputs.tf
terraform/app/modules/ecs_service/variables.tf

Create a new module for ecs services. This allows us to simply add additional service types, e.g. such as a background service for good-job

Create ecs service module

---

app/jobs/bulk_update_patients_from_pds_job.rb
app/models/concerns/csv_importable.rb
config/settings.yml

We're modifying the way Good Job is deployed to hopefully reduce contention by reducing the number of parallel jobs processing at any one time. This should allow us to reduce the artificial gap we've imposed between PDS jobs and process patients at a quicker rate.
By making the value configurable we can change the gap between jobs without needing to deploy changes to the code.

Make gap between PDS jobs configurable

---

terraform/app/ssm_parameters.tf
terraform/app/variables.tf

This adds a new environment variable to the task definition that allows us to configure the wait time between when PDS jobs are enqueued without needing a deployment, by storing the value in the parameter store.
https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3329 is the change to the application code which added the setting.

Set `MAVIS__PDS__WAIT_BETWEEN_JOBS` environment variable

---

Dockerfile
bin/docker-entrypoint
bin/docker-start
config/application.rb
config/environments/development.rb
config/puma.rb
terraform/app/autoscaling.tf
terraform/app/codedeploy.tf
terraform/app/ecs.tf
terraform/app/iam_policy_documents.tf
terraform/app/modules/ecs_service/outputs.tf
terraform/app/outputs.tf
terraform/app/rds.tf
terraform/app/variables.tf

Create service to handle background tasks as well as create a user-facing service (thrust). This is also used as an opportunity to rename the existing service and move it into the module setup.
This is part of a PR chain with https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3321 as parent

Create modularized ecs services

---

app/components/app_vaccination_record_summary_component.rb
app/controllers/batches_controller.rb
app/forms/batch_form.rb
app/models/batch.rb
app/models/dps_export_row.rb
app/models/immunisation_import_row.rb
app/models/vaccine.rb
app/views/batches/edit.html.erb
app/views/batches/new.html.erb
app/views/draft_vaccination_records/batch.html.erb
app/views/sessions/record/batch.html.erb
app/views/vaccines/index.html.erb
config/locales/en.yml
db/migrate/20250402093102_change_batch_expiry_not_null.rb
db/schema.rb
spec/factories/batches.rb
spec/factories/vaccination_records.rb
spec/features/doubles_vaccination_administered_spec.rb
spec/features/edit_vaccination_record_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/features/vaccination_todays_batch_spec.rb
spec/forms/batch_form_spec.rb
spec/lib/reports/offline_session_exporter_spec.rb
spec/models/batch_spec.rb
spec/models/immunisation_import_row_spec.rb

When uploading historical vaccination records it's not guaranteed that the batch expiration date will be provided with the batch number. Therefore, we need to handle batches without expiration dates.
This makes a number of changes to the service to allow for batches without expiration dates (specifically to ensure they will render correctly without the user seeing an error) and also updates the import process to support importing historical vaccination records without batches. Offline recording of vaccinations still requires a batch expiration date to be provided.
We also can't be sure that batches with the same number won't be reused, so we allow batches to exist with the same number, one with an expiration date and one without an expiration date. In the future we might be able to …

Support batches without expiration dates

---

app/lib/csv_parser.rb
app/lib/reports/offline_session_exporter.rb
app/models/cohort_import_row.rb
app/models/concerns/csv_importable.rb
app/models/immunisation_import_row.rb
app/models/patient_import_row.rb
spec/lib/csv_parser_spec.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb
spec/models/cohort_import_spec.rb
spec/models/immunisation_import_row_spec.rb
spec/support/shared_examples/a_csv_importable_model.rb

This adds a new struct which handles the parsing of CSV fields (converting values to integers, dates and times) and stores additional information about the field (the row index, the column index, and the original header). This additional information will be used in a follow up PR to improve the error handling and validation by showing the original header to the user, which allows to easily handle multiple different file formats while presenting to the user the correct headers.
This follows on from #3317.

Add `CSVParser` and `CSVParser::Field`

---

terraform/app/iam_policy_documents.tf

- We have created a configuration variable for an ECS task but not given the task access
- This commit rectifies this

Allow ECS task access

---

app/lib/vaccination_description_string_parser.rb
app/models/immunisation_import_row.rb
spec/fixtures/immunisation_import/systm_one.csv
spec/lib/vaccination_description_string_parser_spec.rb
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

This updates the import process to allow users to upload a file in the SystmOne format which has a different set of fields to the existing format. We haven't got a real example of this type of file for testing, so this is a best guess at how the format should be parsed.
We haven't updated any parts of the UI in this change, we might want to do this in a follow up PR to describe the two different formats.
To build this, the import mechanism required a substantial refactor, which is covered by:
- https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3312
- https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3317
- https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3318
- https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3325
- …

Add support for uploading SystmOne vaccination records

---

.github/workflows/continuous-deployment.yml
.github/workflows/deploy-application.yml
.github/workflows/deploy-mavis.yml
terraform/app/codedeploy.tf
terraform/scripts/check_task_definition.sh
terraform/scripts/validate_plan.sh

- Option to deploy all or only one type of services
- When deploying all deploy in parallel to speed up process
- Default to deploy all for deploying mavis
- Always deploy all for continuous deployment
This is part of a PR chain with https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3322 as parent

Update deployment pipeline to work with modularized services

---

terraform/app/ecs.tf
terraform/app/env/preview.tfvars
terraform/app/loadbalancer.tf
terraform/app/variables.tf

* In cases where a new ECS service is deployed, while the loadbalancer target group that is controlled by Codedeploy points to the "wrong" target group, terraform apply would result into an error that the new service is not attached to a valid target group.
* This can be taken care of by assigning the currently active target group to this variable
Previously, this could already be done by changing it temporarily in the terraform configuration, but having this as a variable allows for different values per environment
This is part of a PR chain with https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3323 as parent

Extract default target group to variable

---

config/onboarding/leicestershire-production.yaml
config/onboarding/leicestershire-training.yaml

The correct code for Leicestershire should be `RT5` and not `RT5YA`.

Correct Leicestershire ODS code

---

terraform/bootstrap/main.tf
terraform/bootstrap/variables.tf

- Production has production suffix in names
- This was hard-coded for release but should be versitile enough to support non-prod environments

Update bootstrap config

---

app/models/immunisation_import_row.rb
spec/models/immunisation_import_row_spec.rb

When the SystmOne import feature is not enabled, the errors messages about missing columns should not reference the columns that are part of the SystmOne format as adding them won't fix the issue.

Ensure errors messages don't reference SystmOne

---

app/models/patient_session.rb
spec/features/manage_attendance_spec.rb

There seems to be a scenario where the programmes for a session end up being duplicated if we rely only on `includes`. I haven't investigated exactly what's going on with the queries.
Instead, if we specify explicitly that we want to do a `preload`, this ensures that the programmes only appear once per programme.
This fixes a regression that was added in #3301 which manifests itself on the session registration page where the actions required end up being duplicated. I think it could be related to the fact that the programmes have an implicit order on the scope, and therefore need to be preloaded to avoid an outer join returning patients in different orders.

Specify preloading rules explicitly

---

.github/workflows/deploy-application.yml

- Validation script should in any case catch any invalid resource modifications 
- With this change we lose the ability to only deploy application via github workflow in the case of infrastructure changes. This is considered an unlikely edge case and therefore worth the risk.

Targeting was preveing output updates

---

script/shell.sh

Addresses a couple issues:
- `getopt` on macos isn't compatible with GNU `getopt`
- minor stylistic things such as using lower-casing script variables and dasherising cmdline options

Update `script/shell.sh` for connecting to running servers.

---

app/models/patient_import_row.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

This ensures that when the user uploads a cohort or class list with a custom year group, we validate that the year group value is a valid integer rather than just ignoring.
This fixes a regression that was added in 5b88061e6ae26c94f1bd19571383d57755f0c4b2, although the error message is now clearer (previously it would have said "is not part of the programme").

Ensure year group integer value is validated

---

app/models/immunisation_import_row.rb
app/models/patient_import_row.rb
spec/models/immunisation_import_row_spec.rb

This reverts the content when a field has been provided and shouldn't have a value to use the previous content "must be blank" was which changed in 72f65e36aacd6c0dc480dff47b200f2856c0f8d5.

Revert "must be blank" content

---

app/jobs/bulk_update_patients_from_pds_job.rb
app/models/concerns/csv_importable.rb
config/settings.yml

This allows us to specify the wait time between PDS jobs in fractional seconds to give us more flexibility in terms of controlling this.

Allow fractional wait time between PDS jobs

---

terraform/app/iam_policy_documents.tf
terraform/app/ssm_parameters.tf
terraform/app/variables.tf

This makes this variable configurable by adding it as a parameter and then exposing the variable as an environment variable.
This should allow us to customise the Good Job configuration without needing a code change and deploy.

Make GOOD_JOB_MAX_THREADS configurable

---

terraform/app/env/copilotmigration.tfvars
terraform/app/env/preview.tfvars
terraform/app/env/qa.tfvars
terraform/app/env/training.tfvars
terraform/app/iam_policy_documents.tf
terraform/app/ssm_parameters.tf
terraform/app/variables.tf

This makes this variable configurable by adding it as a parameter and then exposing the variable as an environment variable.
This would then allow us to enable/disable this part of the service per environment while also being able to temporarily turn it on and off.
This will start by enabling it in all environments and then we can turn it off.

Make `MAVIS__PDS__ENQUEUE_BULK_UPDATES` configurable

---

app/jobs/send_clinic_initial_invitations_job.rb
app/models/patient_session.rb
spec/features/patient_search_spec.rb

This fixes a bug where searching for patients on the session tabs which results in no patients being returned, the user would see an error page instead of no results.
This was happening as the `includes` statement on the patient was incorrectly generating a SQL query that relied on a parameter being present but wasn't passing the parameter in. I haven't got to the bottom of exactly why this was wrong, but it seems to me to potentially be a bug in ActiveRecord.
Fixing this involves switching to using `preload` instead of `includes`, and putting an explicit `joins` where we need to query on the patient directly.
The original bug was present in version 2.1.2, but was only present on the session outcome tabs, this was made worse in https://github.com/nhsuk/manage-vaccinations-in-schools/commit …

Fix bug where searching with no results would raise an error

---

config/onboarding/hertfordshire-production.yaml

This adds the Essex school URNs to the Hertfordshire organisation via the onboarding configuration, however in production we won't be able to use this file as the organisation is already onboarded.
To support this, we've split the organisation in two separate teams which handles the different schools.

Add Essex schools to Hertfordshire onboarding

---

app/components/app_patient_session_table_component.rb
app/helpers/sessions_helper.rb
spec/components/app_patient_session_table_component_spec.rb
spec/helpers/sessions_helper_spec.rb

This updates the design of the table of sessions shown on the patient page to match the latest designs in the prototype.

Update design of patient session table

---

app/components/app_activity_log_component.rb
spec/components/app_activity_log_component_spec.rb
spec/features/manage_children_spec.rb

This updates the design of the activity log entry where the patient is added to the session to match how it looks in the prototype.

Update session activity log entry

---

spec/fixtures/immunisation_import/systm_one.csv

This was only needed temporarily before we supported batches without expiration dates and shouldn't be present in any SystmOne files that we import.

Remove BATCH_EXPIRY_DATE from SystmOne fixture

---

app/jobs/school_consent_reminders_job.rb
app/models/consent_notification.rb
spec/jobs/school_consent_reminders_job_spec.rb

When patients join a session half way through a number dates, currently the parents will receive reminders for any session dates prior to when the patient joined. In some cases, this can lead to reminders being sent daily for a number of days.
Instead, we can ignore any session dates that exist prior to the patient being added to the session, and in this case, "added to the session" means when the patient received their first consent request.
This means that patients won't receive unnecessary reminders in most cases, but I think there is the opportunity for further improvements later with regards to the reminders schedule.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1003)

Avoid sending consent reminders to new patients

---

terraform/app/env/copilotmigration.tfvars
terraform/app/env/poc.tfvars
terraform/app/env/preview.tfvars
terraform/app/env/qa.tfvars
terraform/app/env/training.tfvars
terraform/app/iam_policy_documents.tf
terraform/app/ssm_parameters.tf
terraform/app/variables.tf
terraform/scripts/bootstrap.sh

- Ensure we use variable configs to be unique to an environment
- For code to reflect deployed configurations
- One resource with for-each instead of multiple blocks (DRY)
- Remove lifecycle ignore_changes
- Ensures regular sync between code and deployed configuration
- Any persisted changes will end up being version controlled
- Disable PDS/CIS2/SPLUNK for POC environment

Refactor use of ssm parameters

---

app/lib/feature_flag_factory.rb
bin/docker-entrypoint
config/feature_flags.yml
db/seeds.rb
lib/tasks/feature_flags.rake
spec/lib/feature_flag_factory_spec.rb

This ensures that all the feature flags that are possible to be enabled/disabled are shown in the Flipper UI in all environments by adding a class which manages the creation and deletion of feature flags according to a YAML file stored in the repo.

Maintain a list of supported feature flags

---

app/components/app_patient_page_component.rb
app/forms/vaccinate_form.rb
app/models/pre_screening.rb
app/models/session_date.rb
db/migrate/20250403155909_add_session_date_id_to_pre_screenings.rb
db/schema.rb
spec/components/app_patient_page_component_spec.rb
spec/factories/pre_screenings.rb
spec/features/doubles_vaccination_administered_spec.rb
spec/models/pre_screening_spec.rb

This change updates the logic for initialising VaccinateForm so that it only considers PreScreening records with a SessionDate of Date.current. Only vaccine-independent questions will be copied over from previous pre-screenings, the others (and the notes field) will be blank. 
If no PreScreening from today's session is available, the form will remain blank.
Changes include:
• Implementing a data migration to associate PreScreening with a SessionDate.
• Updating the query logic to join on session_date and filter by today's date.
• Being selective about which fields of the PreScreening to copy over.
• Tests to verify that only today's screening data is used.

Use only today's prescreening data for VaccinateForm initialisation

---

lib/generate/consents.rb
lib/generate/patient_imports.rb
lib/generate/triages.rb
lib/generate/vaccination_records.rb
spec/lib/generate/consents_spec.rb
spec/lib/generate/patient_imports_spec.rb
spec/lib/generate/triages_spec.rb
spec/lib/generate/vaccination_records_spec.rb
spec/models/patient/vaccination_status_spec.rb

The generators here were used for generating large volumes of data for importing into Mavis, and for automatically giving consents, performing triage and recording vaccinations for data in Mavis. This was used for the performance tests but can also be useful for other areas where test data is required. These generators include specs to try to ensure that they stay up-to-date with any code changes.

Add mock data generators for testing

---

app/lib/csv_parser.rb
spec/lib/csv_parser_spec.rb

When importing a CSV file we can replace these characters with a normal space character and then strip any trailing and leading whitespace. This will help to normalise the data coming in to the service, and avoids issues where users upload files in non-breaking space characters in the column headers and the file fails to import. This was discovered by one of our testers where Excel seems to include these characters when generating CSV files in certain situations.

Replace non-breaking space characters

---

app/models/immunisation_import_row.rb
spec/models/immunisation_import_row_spec.rb

If the file which has been uploaded has a `VACCINE_GIVEN` or `Vaccination type` column, we can assume that the record has been administered.
This was already the case, but only the vaccine that the user provided is valid. If the vaccine was invalid, this lead to a confusing scenario where the user would see a validation error about the vaccine being invalid and a validation error about missing `VACCINATED`. This is wrong, once the vaccine has been fixed, the second validation error about the `VACCINATED` column would go away, so there's no need to show it to the user in the first place.

Don't require VACCINATED column

---

app/components/app_patient_page_component.html.erb
app/components/app_patient_page_component.rb
app/components/app_vaccinate_form_component.html.erb
app/components/app_vaccinate_form_component.rb
app/controllers/vaccinations_controller.rb
app/forms/vaccinate_form.rb
app/models/pre_screening.rb
config/locales/en.yml
spec/components/app_vaccinate_form_component_spec.rb
spec/features/hpv_vaccination_pre_screening_spec.rb
spec/models/pre_screening_spec.rb

When recording a vaccination, this ensures that each answer to the pre-screening questions is validated individually so the user understands why a child cannot be vaccinated if the pre-screening requirements are not valid.

Validate individual pre-screening questions

---

.github/workflows/deploy-application.yml
.github/workflows/deploy-infrastructure.yml
.github/workflows/destroy-infrastructure.yml

- Using `set -e` consistently will ensure we detect the failure of a job at the right location

Ensure pipeline jobs exit with failure

---

app/assets/stylesheets/_timeline.scss
app/assets/stylesheets/application.scss
app/components/app_timeline_filter_component.html.erb
app/components/app_timeline_filter_component.rb
app/components/app_timeline_table_component.html.erb
app/components/app_timeline_table_component.rb
app/controllers/inspect/timeline/patients_controller.rb
app/views/inspect/timeline/patients/show.html.erb
config/routes.rb
lib/timeline_records.rb
spec/features/timeline_records_spec.rb
spec/lib/timeline_records_spec.rb

An endpoint which serves a UI used to view events related to a patient record.
This is a tool designed for use by the Ops Support people, to visualise the patient data without having to use the console.
The information that can be displayed for each 'event' is as follows:
```
cohort_imports: %i[rows_count status uploaded_by_user_id],
class_imports: %i[rows_count year_groups uploaded_by_user_id session_id],
patient_sessions: %i[session_id],
school_moves: %i[source school_id home_educated],
school_move_log_entries: %i[user_id school_id home_educated],
consents: %i[programme_id response route parent_id withdrawn_at invalidated_at],
triages: %i[status performed_by_user_id programme_id invalidated_at],
vaccination_records: %i[outcome performed_by_user_id programme_id session_id vaccine_id]
``` …

Timeline records UI

---

.github/workflows/deploy-application.yml

Approving the deployment of each individual service is overkill
- Move approval into prepare-deployment stage to only approve once

Only approve deployment of services once

---

app/components/app_patient_table_component.html.erb
app/components/app_patient_table_component.rb
app/components/app_vaccination_record_table_component.html.erb
app/components/app_vaccination_record_table_component.rb
app/views/imports/show.html.erb
app/views/vaccination_records/index.html.erb
spec/components/app_vaccination_record_table_component_spec.rb

If the user doesn't have permission to see those vaccination records.
If a user clicks on this link they are taken to a 404 error page which is not a good user experience, we should instead hide the link.
This follows on from similar functionality that was added to the patient table in a055b1a5646e0c5a309dc7430b5e0da9060f4fc5.

Don't link to vaccination records

---

app/models/location.rb
app/models/onboarding.rb
db/migrate/20250414092500_add_status_to_locations.rb
db/schema.rb
lib/tasks/schools.rake
spec/factories/locations.rb
spec/fixtures/files/onboarding/invalid.yaml
spec/models/location_spec.rb
spec/models/onboarding_spec.rb

This adds a new column on the locations table for tracking the status of the location (either open, close, opening and closing) which maps closely with the DfE GIAS data, but could also be applied to other location types so there's no need to name the enum specific to schools.
Adding this allows us to validate that all the schools are open before onboarding an organisation.
This is a proposed alternative to #3391 which runs when an onboarding process runs rather than checking the YAML files against the DfE data in the repo.

Track school open/closed status

---

app/jobs/enqueue_update_patients_from_pds_job.rb
app/lib/update_patients_from_pds.rb
app/models/concerns/csv_importable.rb
spec/lib/update_patients_from_pds_spec.rb

This adds a service class that handles logic related to queuing PDS update jobs to avoid code duplication. Currently we run similar code in two places, during an import and during the bulk enqueue job.
Instead, we can move this code in to a single class which handles all the logic related to scheduling the correct jobs to reduce duplication and improve maintainability.
I also think this will make performance testing easier by being able to use this class in a Rails console.

Refactor how PDS update jobs are queued

---

lib/tasks/schools.rake

When downloading the latest version of the schools data we should make sure to overwrite the version already contained in the repo otherwise running, for example, `schools:import` will use the file in the repo and not the latest version just downloaded.

Overwrite db/data/dfe-schools.zip

---

app/controllers/inspect/timeline/patients_controller.rb

Previously, the sample_patient function raised an exception when no comparison option was selected. This has been replaced with a return of nil for blank or "on" values, preventing unnecessary exceptions.

Handle no comparison option in sample_patient function

---

app/components/app_patient_page_component.rb

Update pre-screening initialisation logic to retrieve the most recent answer for each question from the same day, instead of only using the last pre-screening performed. This ensures that relevant answers are translated across pre-screenings, even if a specific vaccine does not have a particular question.

Use last available answer from today for initialising pre-screening questions

---

app/jobs/concerns/send_clinic_invitations_concern.rb
spec/jobs/send_clinic_initial_invitations_job_spec.rb

This fixes a bug where patients who are eligible for multiple programmes were being sent clinic invitations where they shouldn't have been. The specific scenario is where a patient is vaccinated for one programme and consent refused for another, therefore the parents shouldn't receive an invitation to the clinic, but the code was incorrectly deciding that the patient should.
The code wasn't treating the programmes individually, so it was seeing one programme as unvaccinated and another programme as consent given and deciding therefore that the patient should be sent the invitation.

Don't send clinic invitations incorrectly

---

.github/workflows/build-and-push-image.yml
.github/workflows/deploy-application.yml
.github/workflows/deploy-infrastructure.yml
.github/workflows/deploy.yml
README.md

We want to restrict the IAM role used by the Github workflows such that it can only be assumed by workflow runs from the main and release branches. This causes the problem that deployment workflows run from tags could not assume the role anymore.
To mitigate this issue and still allow deploying specific tags, this PR allows to specify the git tag that shall be deployed in a dedicated field. While the workflow can be run from main or release, this still allows to deploy a specific git tag. If no value is set, it defaults to the regular behaviour.

Prepare restriction of AWS permissions for github workflows

---

app/models/immunisation_import_row.rb
spec/fixtures/immunisation_import/systm_one.csv
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb

This makes a number of small fixes to the SystmOne import to ensure users can upload files without vaccines and to hide dose sequence validation if a programme isn't present.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1046)

Small validation improvements to SystmOne import

---

terraform/app/env/qa.tfvars
terraform/app/env/test.tfvars
terraform/app/rds.tf
terraform/app/variables.tf

* Update QA and Test to use the latest available DB engine version, 16.8.
* The upgrade will be applied during the next maintenance window
* Also change maintenance window for sooner execution

Upgrade DB version for QA and Test

---

app/models/immunisation_import_row.rb
spec/fixtures/immunisation_import/systm_one.csv
spec/models/immunisation_import_spec.rb

Dose sequence is optional for some vaccination types, notably MenACWY and Td/IPV. In the SystmOne file format, the programme is determined from the `Vaccination type` column.
This column contains is a single value containing a combination of the programme, vaccine and dose sequence. Therefore we can't check for the existence of this value to validate the dose sequence, instead we need to check for the presence of the dose sequence component of this value.
[Jira issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1046)

Allow programme vaccination types without dose sequence

---

config/environments/production.rb

This was referring the wrong job class and the wrong time, resulting in no consent reminders being sent out. This fixes a regression that was added in 3ce129ae53521ed61d25af1da8b02396e3ae2255.
Good Job doesn't current report an error if the cron jobs are misconfigured, this is tracked here: https://github.com/bensheldon/good_job/issues/1261

Fix school consent reminders cron job 

---

app/lib/reports/school_moves_exporter.rb
app/models/school_move_export.rb
app/models/school_move_log_entry.rb
app/views/school_moves/exports/confirm.html.erb
db/migrate/20250429140846_remove_move_to_school_from_school_move_log_entries.rb
db/schema.rb
spec/factories/school_move_log_entries.rb
spec/features/download_school_moves_spec.rb
spec/lib/reports/school_moves_exporter_spec.rb
spec/models/school_move_export_spec.rb
spec/models/school_move_log_entry_spec.rb

This updates the school moves export functionality to include patients who used to be within the remit of the organisation but have since moved outside of the organisation.
We don't currently have a good way of getting a list of patients who used to be in an organisation at a particular period of time, but we can look at the school move log entries for patients who are no longer in the organisation but was at some point moved to a school that was in the organisation.
I think in the future we might want to improve this by having an explicit way of tracking which school a patient went to a particular point in time, but I think this relates to potential future work on cohorting so we can handle it then.
[Jira issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1060)

Include moves out in school moves export

---

config/cron_jobs.rb
config/environments/production.rb
config/environments/staging.rb
spec/lib/cron_jobs_spec.rb

This adds a test to ensure that the class names references in the cron job configuration are valid and refer to classes that exist.
We're adding this to catch any potential issues in the future where the cron jobs classes are invalid (as was fixed recently in https://github.com/nhsuk/manage-vaccinations-in-schools/commit/623a1e63809ed51e27028a369a526696947aec2c). This is necessary because Good Job itself doesn't check that the classes are valid and will fail silently.

Ensure cron jobs reference valid classes

---

app/models/immunisation_import_row.rb
app/models/patient.rb
app/models/patient_import_row.rb
app/validators/nhs_number_validator.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb
spec/models/immunisation_import_row_spec.rb
spec/validators/nhs_number_validator_spec.rb

When importing historical immunisation records, we should ensure that the NHS number is validated in the same way that it would be if a patient was being created with that NHS number.
This has been implemented by adding a common NHS number validator which can be used in every model that needs to validate an NHS number.

Add NHS number format validation to imports

---

.tool-versions
hk.pkl

- Adding a custom check to ensure we do not initiate commit when running linters in fix mode
- Removing brakeman as it runs on all files and takes too long as a pre-commit step

Remove brakeman from pre-commit and fail on changed files

---

app/controllers/concerns/authentication_concern.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/views/users/errors/organisation_not_found.html.erb
lib/omni_auth_strategies_openid_connect_patch.rb
spec/features/user_cis2_authentication_with_empty_role_spec.rb
spec/features/user_cis2_authentication_with_wrong_organisation_spec.rb
spec/features/user_cis2_authentication_with_wrong_role_spec.rb
spec/features/user_cis2_authentication_with_wrong_workgroup_spec.rb
spec/support/cis2_auth_helper.rb

This allows us to return a more meaningful error when someone from an organisation that hasn't been setup in Mavis but that is otherwise setup correctly tries to login. This will be useful for pre-launch checks by orgs.
The organisation-not-found page has been updated to the following:
[MAV-364](https://nhsd-jira.digital.nhs.uk/browse/MAV-364)

Show a more meaningful error to users from organisations that aren't set up in Mavis

---

.github/workflows/test.yml

- Simply check if changes are confined within non-ruby/rails relevant directories
- Exit with 0 to have job succeed but skip following steps

Add step to check if rails tests are needed

---

app/jobs/send_vaccination_confirmations_job.rb

This change ensures that the CSV report’s RECORD_UPDATED_AT column reflects only genuine updates to a VaccinationRecord. Previously, automated updates when vaccination confirmation emails were sent to parents modified the updated_at timestamp and affected the report.

Exclude confirmation email updates from CSV report's RECORD_UPDATED_AT column

---

app/models/patient_import_row.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

During an import, if the existing patient's gender is `nil`, `not_known` or `not_specified`, and the incoming value is different, then Mavis will now automatically accept the new value without staging it and asking for a review.

Accumulate gender on import

---

terraform/app/rds.tf

This PR updates the DB to the latest available PostgreSQL version. The change will be applied during the maintenance window and involves a ~10min downtime.

Update PostgreSQL to 16.8

---

.github/workflows/test.yml

The test fails when the PR is from fork
- Handle all edge cases by simply running when the reference cannot be found

Patch PR-tests to work with forks

---

app/models/patient_import_row.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

During an import, if all the existing patient's address fields are `nil`, then Mavis will now automatically accept the full incoming address without staging it and asking for a review.

Accumulate address on import

---

app/lib/csv_parser.rb
lib/core_ext/string/normalise_whitespace.rb
spec/lib/core_ext/string_normalise_whitespace_spec.rb
spec/lib/csv_parser_spec.rb

During an import, all string fields now have their whitespace normalised before any other processing occurs. This includes the headers
[MAV-1080](https://nhsd-jira.digital.nhs.uk/browse/MAV-1080)

Normalise spaces during import

---

spec/lib/csv_parser_spec.rb

This adds a test to the `CSVParser` class to ensure that the input data is parsed in whatever encoding it is provided in and then converted to UTF-8 for manipulation and storage in the database.
Currently we're seeing an issue in production which will be fixed in 04ecafb8280bc4a406620a08a9f4df230ff3590d but hasn't been deployed yet. This adds a test to ensure that we don't introduced any regressions in future releases.

Add a test to ensure CSV files are converted to UTF-8

---

terraform/resources/github_actions_policy.json

The workflows need this permission to be able to deploy changes to the autoscaling rules.
Example failure without the permission: https://github.com/nhsuk/manage-vaccinations-in-schools/actions/runs/14773383019/job/41477398883

Add ecs:UpdateCluster permission

---

app/components/app_patient_session_search_result_card_component.rb
app/models/patient_session.rb
spec/features/doubles_vaccination_administered_spec.rb
spec/models/patient_session_spec.rb

Previously when vaccination a patient's next action status would show as "Report for [programme]". We don't currently have a mechanism for reporting and in the future it's likely to be automated anyway, so we can remove this and instead show nothing to make it clear that no action is required.

Remove "Report" action required

---

app/forms/vaccinate_form.rb
spec/features/e2e_journey_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/hpv_vaccination_pre_screening_spec.rb
spec/features/vaccination_todays_batch_spec.rb

The question is not required for clinical decisions. It’s a legacy question from when it was contraindicated to receive. There is no rationale to have it there.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-976)

Remove pregnancy pre-screening for HPV

---

app/views/draft_consents/confirm.html.erb
spec/features/self_consent_spec.rb

When submitting self-consent via Gillick assessment, we should be able to change the response method without the service displaying an error page.
At the moment, this takes the user back through the entire flow, but this is the case for all the other change links so I think that should be fixed in a further enhancement. Also, going back through the entire journey is currently the only way to change whether the parents should be notified or not so some design work is needed as well.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-966)

Avoid crash when editing response method

---

app/assets/stylesheets/_header.scss
app/assets/stylesheets/_overrides.scss

`nhsuk-frontend v9.4.x` changed the implementation of the header navigation to fix the behaviour around the overflow navigation menu, and using `padding` instead of `gap` to improve presentation on older devices. This conflicts with the specific changes we’ve made to the container width and current item indicator.
(`nhsuk-frontend v10.0.0` will change the header markup considerably, and provide a number of these features saving us from needing to implement them separately.)

Fix header navigation to be compatible with NHS.UK Frontend 9.4.x

---

app/models/patient_import_row.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

Automatically overwrites with the incoming address fields (`address_line_1`, `address_line_2`, `address_town`) under the following conditions:
- `address_postcode` matches the existing value
- any of the incoming `address_line_1`, `address_line_2` or `address_town` are populated

Automatically overwrite incoming address

---

app/models/draft_vaccination_record.rb
spec/models/draft_vaccination_record_spec.rb

This fixes a regression that was introduced in 2073e01c1d6db2277cf677c5d4f9d00262c34469 where the vaccine isn't being set on vaccination records when recorded in the service itself. I've fixed the regression and then introduced a test to ensure this doesn't break again in the future.

Ensure vaccine is set when saving a vaccination record

---

app/models/patient_import.rb
spec/models/cohort_import_spec.rb

This change auto-confirms a school move when processing a cohort or class upload for a patient with a nil organisation. The generated school move is immediately confirmed—replicating the behavior of importing a new patient—so the confirmed move isn’t returned for further processing by the user.

Improve workflow for adding back into cohort

---

app/components/app_child_summary_component.rb
app/components/app_parent_card_component.rb
app/components/app_parent_summary_component.rb
app/components/app_patient_card_component.rb
app/components/app_vaccination_record_summary_component.rb
app/controllers/parent_relationships_controller.rb
app/models/parent_relationship.rb
app/models/patient.rb
app/views/parent_relationships/destroy.html.erb
app/views/patients/edit.html.erb
config/locales/en.yml
config/routes.rb
spec/components/app_parent_summary_component_spec.rb
spec/features/manage_children_spec.rb
spec/features/parent_relationships_spec.rb

This adds a new page which allows the anyone to remove a parent relationship from a patient while retaining any consents submitted against this patient by the parent.
This is based on the latest designs in the prototype.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1088)

Add ability to remove parent relationships

---

app/helpers/vaccinations_helper.rb
app/models/programme.rb
app/views/draft_vaccination_records/delivery.html.erb
spec/features/hpv_vaccination_administered_spec.rb

This fixes a regression that was added in 2073e01c1d6db2277cf677c5d4f9d00262c34469 where the "Other" delivery site no longer works as it requires the vaccine to be present, but we don't have a vaccine at that point. Instead we can allow the user to select a delivery site across all the vaccines.
I suspect this will need to be revisited for Flu where we have nasal spray and injection vaccines and the vaccine that the nurse selects needs to match the approriate delivery site.

Ensure "Other" delivery site can be chosen

---

.github/workflows/test.yml

This cherry-picks a couple of PRs from the 2.2.1 branch which fixes a couple of issues with the job which checks whether to run the Rails tests, to ensure the Rails tests run.

Fix "Check if Rails tests need to run" job

---

hk.pkl

This makes a number of small changes to the linting configuration to fix a number of small issues related to switching to `hk`. See individual commits for more details.

Various linting improvements

---

app/assets/stylesheets/_header.scss

`nhsuk-frontend` v9.4 increased this space to 16px which, when accumulated across all navigation items, moves the last item beyond the container on desktop. We’ll override this value to 12px to resolve this issue in the short term.

Reduce spacing between header navigation items above tablet breakpoint

---

terraform/app/rds.tf

* Minor DB version upgrades happen automatically during the weekly DB maintenance window. On 5 May, a new minor version upgrade from 14.9 to 14.15 has become available and will be applied during the next maintenance window.
* On preview, this has already been done. It will happen without any downtime
* This PR only updates the terraform config to match the current DB state

Upgrade DB engine version to 14.15

---

.github/workflows/lint.yml
hk.pkl

- Without specifying the configuration file it does not apply correct fixes
- Pathing is relative to directory hk is running in, therefore with --recursive we must pass absolute paths

Fixing tf_lint stage of hk

---

.github/workflows/test.yml

- Therefore the rails tests were always executed
- This fixes the issue

Proper encapsulation was missing

---

app/forms/batch_form.rb
app/models/batch.rb
app/models/gillick_assessment.rb
app/models/pre_screening.rb
config/locales/en.yml
spec/forms/batch_form_spec.rb
spec/models/batch_spec.rb
spec/models/consent_spec.rb
spec/models/gillick_assessment_spec.rb
spec/models/pre_screening_spec.rb

This adds a number of length validations to fields where the user inputs a value directly. I looked over the models and found only a few places where we were missing appropriate length validation.
This will be followed up with a PR which adds similar validations to the import process, as currently we don't validate the length of any of the fields coming from an import.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-955)

Add missing length validations

---

spec/lib/reports/careplus_exporter_spec.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

This ensures that when using `include_examples`, any variables are placed within a context, ensuring that they don't leak outside the current context and cause other tests to fail/pass.
This is necessary because `include_examples` adds the examples directly in to the current context, whereas using `it_behaves_like` creates its own nested context first.
Best reviewed [ignoring white space changes](https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3517/files?diff=unified&w=1).

Refactor usage of `include_examples`

---

app/jobs/send_vaccination_confirmations_job.rb
config/cron_jobs.rb

This updates the schedule for the vaccination record confirmations to send them earlier in the day closer to when schools typically finish. This has been requested by one of our SAIS organisations.
The vaccination record confirmations will now be sent at 3pm.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1105)

Send vaccination record confirmations earlier

---

terraform/app/rds.tf

The backup window cannot overlap with the weekly DB maintenance window. This PR ensures that they don't overlap on any environment.

Set preferred DB backup window

---

app/controllers/sessions/triage_controller.rb
spec/features/triage_spec.rb

When viewing the "Triage" tab of a session, patients who don't need triage should not be shown in this list. This was always the intention behind the design and this commit fixes a bug which meant that it wasn't working as expected.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1141)

Ensure patients who don't need triage are hidden

---

app/models/patient/triage_status.rb
spec/features/triage_partially_vaccinated_spec.rb
spec/models/patient/triage_status_spec.rb

This fixes a bug where for a patient to be triaged based on their vaccination history, they should receive have received consent.
This is logic that we used to have (https://github.com/nhsuk/manage-vaccinations-in-schools/blob/a3c88d2900b11ae7aea67d6655046ef4a6d2233d/app/models/patient/triage_outcome.rb#L94) but was inadvertently removed in version 2.1.2 with the performance improvements that stored the patient statuses in the database.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1162)

Triage from vaccination history requires consent

---

app/helpers/phone_helper.rb
app/lib/govuk_notify_personalisation.rb
app/models/organisation.rb
app/models/team.rb
app/views/organisations/show.html.erb
app/views/parent_interface/consent_forms/cannot_consent_responsibility.html.erb
db/migrate/20250429081203_add_phone_instructions_to_organisations_and_teams.rb
db/schema.rb
spec/factories/organisations.rb
spec/factories/teams.rb
spec/fixtures/files/onboarding/valid.yaml
spec/helpers/phone_helper_spec.rb
spec/lib/govuk_notify_personalisation_spec.rb
spec/models/onboarding_spec.rb
spec/models/organisation_spec.rb
spec/models/team_spec.rb

Some organisations may need to provide additional guidance when sharing phone numbers (like menu options), and this change allows that information to be stored and consistently displayed throughout the application.
Added a phone_instructions string field to both organisation and team models, with corresponding database migrations. The instructions now appear in brackets next to phone numbers in all user-facing views and are included in the Notify personalisation for emails and text communications.
The onboarding process also supports importing these instructions.

Add phone instructions for organisations and teams

---

app/models/patient_import_row.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

If a patient has either `preferred_given_name` or `preferred_family_name` set to `nil` in Mavis, but a name (eg "Benny") is uploaded for a matching record (in either a class upload, or cohort upload), this is now automatically accepted, rather than prompting the user to review.
[MAV-1100](https://nhsd-jira.digital.nhs.uk/browse/MAV-1100)

Automatically accept preferred names

---

app/views/school_moves/index.html.erb

This tweak changes the width of the container for the introduction text on the School moves page. This means the text wraps more sensibly at smaller viewport sizes – and also removes the runt ‘it.’ at the end of the sentence on desktop.

Use reading width for school moves introduction

---

app/models/immunisation_import_row.rb
spec/models/immunisation_import_row_spec.rb

The batch name length limit in the model itself is 100, so we need to ensure that the batch length while importing matches this.

Set batch name length limit to 100 when importing

---

config/initializers/semantic_logger.rb

The time in the logs can be more precise than microseconds, i.e. more than 6 digits of precision, but this gets stringified into exponential/scientific notation and breaks Splunk. e.g. `1747143707.1161711` gets stringified as `1.7471437071161711e+9`.
Also, there are instances where messages can get logged during Rails boot, before `HostingEnvironment` can be auto-loaded.

Trim the timestamps being sent to Splunk

---

app/controllers/parent_interface/consent_forms/base_controller.rb
app/controllers/parent_interface/consent_forms_controller.rb
spec/features/parental_consent_closed_spec.rb

There is an edge case where parents giving consent would get an error page if they begin the consent journey before the deadline has passed, but only finish it after. Instead of getting the helpful "the deadline has passed, please contact the SAIS team", they got the generic 500 error page.
This fixes that and adds a test.
https://good-machine.sentry.io/issues/6428092252/
https://nhsd-jira.digital.nhs.uk/browse/MAV-1123

Deadline passed

---

app/models/draft_consent.rb
spec/features/self_consent_spec.rb

When changing the consent response from a child, currently this doesn't reset the "route" from self-consent, meaning that the consent continues to show as part of the self-consent journey even if the consent has been changed to be from a parent.

Allow changing consent response from child to parent

---

.github/workflows/build-and-push-image.yml
.github/workflows/deploy.yml

Otherwise we always build from using the workflow ref, but tag using the
deploy sha.

Use inputs.git-sha to checkout out code for build

---

app/controllers/cohorts_controller.rb
app/views/cohorts/index.html.erb
spec/features/cohorts_index_spec.rb

This is a follow-up to 2e58ba96bce4b071cc15e48155d2d1db569e469d.
The implementation was buggy and not guaranteed to be sorted in all cases. The spec was passing because the implementation worked for that particular scenario.
This commit makes the sorting explicit in the view and simplies the controller logic.

Bugfix: sort cohorts index in all cases

---

app/lib/govuk_notify_personalisation.rb
spec/lib/govuk_notify_personalisation_spec.rb

Updated team phone method to include instructions in brackets, as required due to Notify template limitations on using variables inside conditionals. The team_phone in Notify now will always have instructions (if present) next to the phone number.

Fix team phone formatting for Notify

---

app/components/app_programme_session_table_component.html.erb
app/controllers/sessions/invite_to_clinic_controller.rb
app/jobs/send_clinic_initial_invitations_job.rb
app/jobs/send_clinic_subsequent_invitations_job.rb
app/lib/govuk_notify_personalisation.rb
app/models/session.rb
app/views/sessions/invite_to_clinic/edit.html.erb
spec/lib/govuk_notify_personalisation_spec.rb

This fixes the session reminder email to ensure that if there's a session date today and one tomorrow, we show tomorrow's date in the email and not today's date.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-944)

Don't show today's date in session reminder

---

app/lib/reports/programme_vaccinations_exporter.rb
config/feature_flags.yml
spec/lib/reports/programme_vaccinations_exporter_spec.rb

This feature went live in 2.2.1 and therefore we can safely remove the feature flag and simplify the code.

Remove report_gillick_notify_parents feature flag

---

.github/workflows/data-replication-pipeline.yml
bin/docker-start
terraform/app/modules/ecs_service/autoscaling.tf
terraform/app/modules/ecs_service/main.tf
terraform/app/modules/ecs_service/variables.tf
terraform/data_replication/README.md
terraform/data_replication/ecs.tf
terraform/data_replication/env/production-backend.hcl
terraform/data_replication/env/production.tfvars
terraform/data_replication/env/qa-backend.hcl
terraform/data_replication/env/qa.tfvars
terraform/data_replication/env/sandbox-alpha-backend.hcl
terraform/data_replication/env/sandbox-alpha.tfvars
terraform/data_replication/env/sandbox-beta-backend.hcl
terraform/data_replication/env/sandbox-beta.tfvars
terraform/data_replication/env/test-backend.hcl
terraform/data_replication/env/test.tfvars
terraform/data_replication/env/training-backend.hcl
terraform/data_replication/env/training.tfvars
terraform/data_replication/iam.tf
terraform/data_replication/main.tf
terraform/data_replication/network.tf
terraform/data_replication/rds.tf
terraform/data_replication/variables.tf
terraform/resources/github_data_replication_actions_policy.json

- This produces a replicate DB with a single ECS task connected
- Useful for testing migrations/sql/etc on a production data without actually modifying the production system
- The replicate system is completely ignorant of source db/service
- The replicate DB will be spawned from a snapshot which is passed as a variable
- Some modification was done to the ecs module to ensure that task definitions are distinct

Create configuration for data replication

---

lib/core_ext/string/normalise_whitespace.rb
spec/lib/core_ext/string_normalise_whitespace_spec.rb
spec/lib/csv_parser_spec.rb

In rare scenarios it's possible to end up calling `normalise_whitespace` on a non-unicode string. In this case, we shouldn't be removing whitespace characters that are specific to unicode as a `Encoding::CompatibilityError` error ends up being raised.
This has only happened in practice once, and only in the test environment: https://good-machine.sentry.io/issues/6604598285/
In this case, a CSV file was uploaded where the encoding couldn't be detected, which lead to a unhandled exception being raised, rather than a validation error on the file.

Ensure non-unicode strings aren't normalised

---

app/controllers/programmes_controller.rb
spec/features/programmes_index_spec.rb

When looking at the table of programmes this ensures that the programmes are listed in an alphabetical order like other parts of the service.

Ensure programmes are shown in alphabetical order

---

.github/workflows/build-and-push-image.yml
.github/workflows/deploy.yml

Otherwise we always build from using the workflow ref, but tag using the deploy sha.
This is a version of https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3549 that we need as part of an emergency release. The original PR is already merged in for the next release.

 Use inputs.git-sha to checkout out code for build #3549 

---

app/components/app_activity_log_component.rb
app/lib/consent_grouper.rb
app/models/consent.rb
app/models/consent_form.rb
app/models/draft_consent.rb
db/migrate/20250515173205_add_submitted_at_to_consents.rb
db/schema.rb
spec/components/app_activity_log_component_spec.rb
spec/factories/consents.rb
spec/jobs/consent_form_matching_job_spec.rb
spec/models/consent_form_spec.rb
spec/models/consent_spec.rb
spec/models/draft_consent_spec.rb
spec/models/patient/consent_status_spec.rb

This changes how we determine the most recent consent response from the `created_at` to the `submitted_at`. In most cases these values will be the same, but it's possible for a consent to be matched with a patient manually which can occur some period of time after the consent was submitted.
In particular, it's possible to manually match multiple consents in a different order to when they were submitted, which can lead to bugs where the patient is given the wrong consent status.
This has been implemented by storing a `submitted_at` column on consent responses, which has been done to ensure we don't hit performance issues when filtering or ordering consents where we need to fetch the related consent form.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1196)

Generate consent status from submitted at time

---

app/models/patient.rb
spec/models/patient_spec.rb

When editing the NHS number of a patient we should normalise the whitespace on the NHS number to ensure that it's accepted and is valid. We do this already for spaces, but not for special unicode whitespace characters.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-504)

Normalise whitespace in NHS number

---

.github/workflows/data-replication-pipeline.yml
terraform/resources/github_data_replication_actions_policy.json

Ensures S3 buckets can be accessed by data replication pipeline. Changes to the workflow also ensures that approvers for production deployments know what resources will be deleted before approving.

Data replication pipeline and policy tweaks

---

terraform/app/env/preview.tfvars
terraform/app/env/production.tfvars
terraform/app/env/test.tfvars
terraform/app/env/training.tfvars

This change has passed performance testing on QA and Test environments. As the configuration already exists in production this change only enables the feature.

Enable autoscaling on all environments

---

terraform/scripts/check-for-running-deployments.sh

- Strange behaviour caused output to be None\nNone in some cases and simply None in others. Refactoring to not get null as query output fixes the issue

Fix check for running deployments script

---

lib/generate/consents.rb
lib/generate/vaccination_records.rb
spec/lib/generate/vaccination_records_spec.rb

Changes consents and vaccination records generators to use bulk inserts for faster processing.
Includes other optimisations such as only updating statuses for patients that have had a consent or a vaccination record generated.
An example, creating 3000 consents including consent forms.
```
[5] pry(main)> Benchmark.bm { it.report { Generate::Consents.call(organisation: org, programme: hpv, given: 1000, refused: 1000, given_needs_triage: 1000) } }
user     system      total        real
22.676558   8.623392  31.299950 ( 35.757822)
```

Bulk import consents in generator

---

app/controllers/draft_vaccination_records_controller.rb
app/forms/vaccinate_form.rb
app/models/concerns/has_dose_volume.rb
app/models/draft_vaccination_record.rb
app/models/immunisation_import_row.rb
app/models/vaccination_record.rb
db/migrate/20250522140257_add_full_dose_to_vaccination_records.rb
db/schema.rb
spec/factories/vaccination_records.rb
spec/models/draft_vaccination_record_spec.rb
spec/models/vaccination_record_spec.rb

This is a small refactor in preparation for Flu where we need to record half dose vs full dose vaccination records. This has no user facing changes, but it adds the new column to the data model so it can be released sooner.

Store dose sizes on vaccination records

---

app/components/app_import_errors_component.rb
app/views/parent_interface/consent_forms/edit/confirm_school.html.erb

`data-testid` is the default attribute that Playwright looks for, so by using this we avoid needing additional configuration in the testing repo.
Related to https://github.com/NHSDigital/manage-vaccinations-in-schools-testing/pull/242.

Rename `data-qa` to `data-testid`

---

app/views/vaccines/index.html.erb
tests/accessibility.spec.ts

At the moment all these buttons have the same accessible name ("Add a new batch") meaning when using an accessibility tool it can be hard to know which button to press. This also helps us in the automated tests which use the accessible name.

Add `aria-label` to new batch buttons

---

app/models/concerns/pending_changes_concern.rb
spec/models/concerns/pending_changes_concern_spec.rb
spec/models/patient_spec.rb

Since records using this mixin will be bulk imported later in the process, using `update!` would trigger an immediate database write, validation checks, and callbacks for each record, negatively impacting performance without providing any benefit.

Remove unnecessary update! call in PendingChangesConcern

---

.github/workflows/deploy-infrastructure.yml
terraform/scripts/update-github-actions-policy.sh
terraform/scripts/validate-github-actions-policy.sh

This change updates the IAM permissions used by the Github Actions role before every production deployment. 
This way, the source of truth for the IAM permissions is always the the file `terraform/resources/github_actions_policy.json`
The workflow will first check the file for differences to the currently deployed policy. If there is a mismatch, the workflow will wait for approval before updating the policy.
The workflow will proceed with the terraform plan/apply commands only if the policy has been updated successfully or if no differences have been detected. This reduces the risk of partial terraform deployments that fail due to missing permissions.

Policy version sync

---

app/controllers/api/locations_controller.rb
app/controllers/api/onboard_controller.rb
app/models/location.rb
app/models/onboarding.rb
config/routes.rb
docs/api.md
spec/models/location_spec.rb
spec/requests/api/locations_spec.rb
spec/requests/api/onboard_spec.rb

This adds two new API endpoints which for now will be only used by the functional tests:
- `GET /api/locations` - Fetch locations that the service knows about.
- `POST /api/onboard` - Onboard a new organisation.
The idea behind this is to allow the tests to set up a fresh organisation each time they are run (by fetching a number of schools using the `/api/locations` endpoint and then using `/api/onboard` to create the organisation). By using a fresh organisation each time we avoid issues where multiple parallel test runs conflict with each other.

Add basic API endpoints to be used in testing

---

.github/workflows/deploy-infrastructure.yml

* With this condition, `apply` runs whenever the `plan` job finished successfully, regardless of whether the `update-permissions` job was skipped or not.

Fix condition to run apply job

---

.github/workflows/data-replication-pipeline.yml
.github/workflows/deploy-application.yml
.github/workflows/deploy-backup-infrastructure.yml
.github/workflows/deploy-infrastructure.yml
.github/workflows/destroy-infrastructure.yml
.github/workflows/test.yml
.tool-versions
terraform/account/main.tf
terraform/app/main.tf
terraform/app/modules/dns/main.tf
terraform/app/modules/ecs_service/main.tf
terraform/app/modules/vpc_endpoint/main.tf
terraform/backup/destination-bootstrap/main.tf
terraform/backup/destination/main.tf
terraform/backup/source/main.tf
terraform/bootstrap/main.tf
terraform/data_replication/main.tf

* Version 1.11 supports write-only attributes which is needed for the DB migration resources

Update terraform version

---

app/controllers/api/base_controller.rb
app/controllers/api/locations_controller.rb
app/controllers/api/onboard_controller.rb
app/controllers/api/organisations_controller.rb
config/feature_flags.yml
config/routes.rb
docs/api.md
spec/controllers/api/organisations_controller_spec.rb
spec/requests/api/locations_spec.rb
spec/requests/api/onboard_spec.rb

This moves it to the new API that's mostly used for testing at the moment, under `DELETE /api/organisations/:ods_code`.
I've also put the API behind a feature flag ensuring that it's only enabled in environments where we want it enabled (specifically QA and possibly test). The routes for the API are already not set when in a production environment, but this allows us to turn off the API functionality in preview and training.

Move `/dev/reset/:ods_code` endpoint

---

app/controllers/api/locations_controller.rb
spec/requests/api/locations_spec.rb

When filtering locations by year groups, we want to only return locations that have all the year groups requested. The idea is that if the tests are going to be running for HPV and Doubles, we want to find schools that administeres years 8, 9, 10, and 11, not just a subset of those.

Query full subset of year groups

---

.github/CODEOWNERS
CODEOWNERS

This fixes the specified code owners team to use the correct one which contains the Mavis developers.

Fix code owners team

---

.github/workflows/data-replication-pipeline.yml
terraform/data_replication/network.tf
terraform/data_replication/variables.tf

* This PR adds the necessary infrastructure for outgoing connections from the data-replication service. Only requests to the NHS API IP address are routed through to the internet.

Enable PDS lookups from data-replication stack

---

app/components/app_consent_refused_table_component.html.erb
app/components/app_consent_refused_table_component.rb
app/models/concerns/gelatine_vaccines_concern.rb
app/models/consent_form.rb
app/models/programme.rb
app/views/parent_interface/consent_forms/edit/reason.html.erb
app/views/programmes/show.html.erb
spec/components/app_consent_refused_table_component_spec.rb
spec/models/consent_form_spec.rb
spec/models/programme_spec.rb
spec/models/vaccine_spec.rb

Only for the Flu programme should this reason for refusal show in the list of reasons for refusal, as this is not a valid reason for the other programmes.
I've implemented this by passing in whether to show this option when using the component. We could be more dynamic and the component to check each consent to see if any of the programmes' vaccines may contain gelatine, but the performance hit on that (when we may have hundreds of thousands of responses) seemed not worth it.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-562)

Hide "Contains gelatine" reason when not valid

---

app/lib/health_answers_deduplicator.rb
app/models/consent_form.rb
spec/features/parental_consent_change_answers_spec.rb
spec/features/parental_consent_flu_spec.rb
spec/lib/health_answers_deduplicator_spec.rb

This updates the deduplication logic introduced to support health answers across multiple vaccines to also support health answers with followup questions, which so far aren't in use but will be used for Flu.
I've introduced a new class `HealthAnswersDeduplicator` which handles this logic and then re-instated the tests we had for Flu which are currently to show that it's working as expected.
I think there are likely some scenarios where the deduplicator doesn't work correctly, most likely if there are questions with the same title but different followups, however we don't know of any where that is the case currently.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1176)

Deduplicate health answers with followups

---

app/components/app_search_component.rb
app/controllers/concerns/search_form_concern.rb
app/forms/search_form.rb
spec/features/filter_state_persistence_spec.rb
spec/forms/search_form_spec.rb

User feedback suggested that filters maintain state because they often filter patients, move away from the page, and then come back having to apply the same filters again.
This update will ensure each page with filters maintains its own unique state. This state can only be cleared with the "Clear filters" button on the form.
**Test Guidance:**
1. Visit the various pages with filters
2. Apply filters to each of those pages
3. Visit other pages and come back to the filtered page
4. The filters previously set should still be there even though there's no URL params
5. Click the "Clear filters" button to reset the filters (it should only apply to that particular page)

Persist filters, per user, per view, per browser session

---

app/controllers/parent_relationships_controller.rb
app/views/parent_relationships/edit.html.erb
config/locales/en.yml
spec/features/edit_parent_spec.rb

This amends the ability to edit parent contact details to also allow editing the communication preferences of the parent, which are captured as part of the consent form but weren't shown on this page.
[Jira issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-275)

Allow editing parent contact details

---

config/locales/en.yml

This adds missing validation error messages when editing parent relationships and not entering a value for the "Other" field. I've copied this content from the existing messaging we have in the consent journey for parents.
[Jira issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-275)

Add content for parent relationship type validation

---

.github/workflows/deploy-infrastructure.yml
terraform/scripts/validate-github-actions-policy.sh

- Ensure relevant jobs run in relevant environments afterwards
- Use result of job instead of custom outputs for clarity

Make github policy matching check fail on missmatch

---

.github/workflows/build-and-push-image.yml
.github/workflows/deploy-infrastructure.yml
.github/workflows/deploy.yml
config/initializers/version.rb
terraform/app/variables.tf

The previous implementation to display the Mavis version number in the footer of the app used the deploy git ref to create a file with the version number which was baked into the image. With the current deploy strategy, the image is only built during deploys to QA and test, before the version tag is even created. So the version number isn't displayed appropriately in production.
This change uses environment variables to set the version number instead. The MAVIS_APP_VERSION environment variable is now set during infrastructure deployment and passed to the ECS containers. For production deployments, the version format is validated to ensure it follows semantic versioning (v1.2.3 format).
This ensures the correct version number is displayed regardless of when the Docker image was built, as …

Fix version number display in production

---

bin/brakeman

This removes this flag by default when running Brakeman. With this flag, an Internet connection is required to run `bin/brakeman` which may not always be available, and we already have Dependabot available to upgrade Brakeman when a new version is available.

Remove `--ensure-latest` when running Brakeman

---

app/components/app_search_component.rb

The app button style was removed meaning these buttons were incorrectly getting the primary button style.

Use NHS secondary button style

---

app/models/draft_consent.rb
app/views/draft_consents/confirm.html.erb
app/views/draft_consents/parent_details.html.erb
spec/features/verbal_consent_change_answers_spec.rb

This fixes the change link for the parent when recording consent to the right place ensuring that the user isn't taken back to the beginning of the journey where they have start the process again.

Update change link for parents in consent journey

---

app/controllers/draft_vaccination_records_controller.rb
app/models/patient/triage_status.rb
app/models/vaccination_record.rb
spec/features/td_ipv_already_had_spec.rb
spec/models/patient/triage_status_spec.rb

If a patient has already been vaccinated, then they don't need another vaccination. This means that they don't need to be triaged.
Previously, Mavis would've requested triage for this patient. Now it won't.
[MAV-1089](https://nhsd-jira.digital.nhs.uk/browse/MAV-1089)

Stop requesting triage for already vaccinated patients

---

lib/tasks/schools.rake
spec/lib/tasks/schools_rake_spec.rb

Added a new rake task schools:roll_over that updates the location and school IDs for sessions, patients, and consent forms when rolling over a school to a new one, in the event the old one has been closed and reopened under a new name and URN for example. The task takes two arguments: old_urn and new_urn, which are the URNs of the old and new schools, respectively.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1229

Add rake task to transfer school data

---

app/components/app_vaccinate_form_component.html.erb
app/components/app_vaccinate_form_component.rb
app/components/app_vaccination_record_summary_component.rb
app/controllers/draft_vaccination_records_controller.rb
app/models/programme.rb
app/models/vaccine.rb
db/seeds.rb
spec/components/app_vaccinate_form_component_spec.rb
spec/factories/programmes.rb
spec/factories/vaccination_records.rb
spec/models/programme_spec.rb
spec/models/vaccine_spec.rb

This adds the minimum configuration to allow us to start testing the Flu programme. Specifically, it adds Flu to the list of programmes in the seeds and makes it possible to record a Flu vaccination even if this doesn't yet follow the designs.
This can be safely merged in as no organisations in production are set up with Flu yet.

Allow testing Flu programme

---

app/models/programme.rb
lib/tasks/vaccines.rake

This adds the health questions for the Flu vaccines matching the latest content in the prototype.
This can be safely merged in as no organisations in production are set up with Flu yet.

Add Flu vaccine health questions

---

app/policies/patient_policy.rb
spec/policies/patient_policy_spec.rb

When filtering on patients that an organisation is allowed to see, using a left outer join means that each patient will be returned for each school move, session or vaccination record they have. This means duplicate patients are shown in various parts of the UI.
Instead, we can use an `EXISTS` query, which is actually more performant as it can short-circuit the conditionals, and avoids duplicate patients being shown.

Ensure duplicate patients aren't shown

---

README.md
docs/rake-tasks.md

This is a **documentation-only** change.  
The given example invocation did not work - it was missing some new parameters added / updated in #2357:
*  A users name must now be split across two parameters, `:given_name` and `:family_name`
* `:organisation_ods_code` is required
* `:fallback_role` is optional, but not mentioned in the given command line example
Also added a note about escaping the brackets on Macs running `zsh`, linked it to the corresponding entry in the rake tasks documents, and added some information about the new `:fallback_role` parameter in that page too.

Correct & enhance the README entry on creating test users

---

app/components/app_vaccination_record_summary_component.rb
app/controllers/draft_vaccination_records_controller.rb
app/forms/vaccinate_form.rb
app/models/draft_vaccination_record.rb
app/models/vaccine.rb
app/views/draft_vaccination_records/confirm.html.erb
app/views/draft_vaccination_records/dose.html.erb
config/locales/en.yml
config/locales/helpers.en.yml
spec/models/draft_vaccination_record_spec.rb
spec/models/vaccine_spec.rb

When recording a vaccination, if using a nasal spray, we need to record whether the patient received a full dose or a half dose (meaning the spray was only in one nostril). This builds the step as per the latest designs in the prototype.
This can be safely merged in as no organisations in production are set up with Flu yet.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1233)

Add full dose or half dose step

---

app/models/draft_vaccination_record.rb
config/locales/en.yml
spec/models/draft_vaccination_record_spec.rb

It must be less than 1000 characters as that is what the model requires, and without this the user sees an error page when we try to save the model to the database.
[Sentry Issue](https://good-machine.sentry.io/issues/6334292237/)

Validate `DraftVaccinationRecord` `notes` length

---

app/controllers/draft_consents_controller.rb
app/models/consent.rb
app/models/draft_consent.rb
spec/features/verbal_consent_change_answers_spec.rb

When going through the consent journey, if we're changing the details of an existing parent, we should make sure that the parent relationship is also saved.
This follows on from https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3253 which mostly implemented this behaviour except for the parent relationships.
[Jira Issue - MAV-790](https://nhsd-jira.digital.nhs.uk/browse/MAV-790)

Save parent relationship when editing consent

---

app/lib/programme_grouper.rb
app/lib/unsupported_programme.rb
lib/tasks/vaccines.rake

This adds an exception to capture the case where an unsupported programme has been passed in to a method. This has no change on behaviour as we already raise exceptions, but rather than raising a `RuntimeError` we can raise a more specific class and handle the message generation in one place.

Add `UnsupportedProgramme` exception

---

app/helpers/consent_forms_helper.rb
app/models/consent.rb
app/models/consent_form.rb
app/models/health_answer.rb
spec/models/consent_form_spec.rb

When a parent fills out health questions, if they're answering the start of a set of follow up questions, their answer to that question should have no impact on whether the patient needs to be triaged or not.
Instead, only if any of the follow up health questions are responded to with yes should the patient be triaged.

Start of follow up questions shouldn't trigger triage

---

.gitignore
.tool-versions
hk.pkl
lib/tasks/vaccines.rake

This upgrades to the latest version of `hk` and ensures that we're not asking Prettier to lint files that it's not responsible for and cuts down the speed of the linter. I'm also hoping this will help towards the issue we've been seeing where it occasionally hits an error with an invalid JSON response.

Small improvements to `hk` configuration

---

db/migrate/20250605084740_add_response_to_consent_form_programmes.rb

We may need this when testing the original migration, so opening this to make it available if we need it.

Make `AddResponseToConsentFormProgrammes` reversible

---

app/models/session.rb
db/migrate/20250609112437_remove_unique_index_from_sessions.rb
db/schema.rb
spec/factories/sessions.rb
spec/models/session_spec.rb

As part of the upcoming flu vaccination feature, we need to support multiple sessions at the same location within the same academic year. This requires removing the unique composite index that previously enforced a one-to-one relationship between locations and sessions.
For query optimisation:
- Added a composite index on `[organisation_id, location_id]` which:
- Supports queries filtering by both columns together
- Supports queries filtering by `organisation_id` alone (leftmost prefix rule)
- Added a separate index on `location_id` for queries that filter by location alone (since `location_id` isn't the leftmost column in the composite index)
https://nhsd-jira.digital.nhs.uk/browse/MAV-1276

Remove unique index constraint from sessions

---

app/components/app_vaccinate_form_component.rb
app/models/patient/consent_status.rb
db/migrate/20250608172900_add_vaccine_methods_to_consent_statuses.rb
db/schema.rb
spec/components/app_vaccinate_form_component_spec.rb
spec/factories/consents.rb
spec/factories/patient_consent_statuses.rb
spec/models/patient/consent_status_spec.rb

This ensures than when recording a vaccination we set the default delivery method according to the consent that was given.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1232)

Vary vaccination flow depending on consented vaccination method

---

config/initializers/sentry.rb

We've reached our limit on spans so we should try to reduce the number of transactions going to Sentry while still being useful for debugging.

Reduce transactions going to Sentry

---

app/models/consolidated_health_answers.rb
spec/models/consolidated_health_answers_spec.rb

Some answers won't have a response, specifically if they are part of follow up questions which only require a response if the root of the follow up questions was responded to with "No".
[Sentry Issue](https://good-machine.sentry.io/issues/6686274636/)

Don't add answers without a response

---

app/models/class_import.rb
db/migrate/20250610154510_change_class_import_serialized_errors_to_jsonb.rb
db/schema.rb
spec/factories/class_imports.rb
spec/models/class_import_spec.rb

- All other columns are jsonb even columns of the same type of data
- This column was likely missed in previous migration or missconfiguraed

Migrate json columns to jsonb type

---

.github/workflows/data-replication-pipeline.yml
terraform/account/resources/iam_policy_DeployDataReplicationResources.json
terraform/account/resources/iam_policy_DeployMavisResources.json

* Now that the DB uses a custom KMS key, the role for deploying data replication resources needs access to this key.
* To keep the restrictions restrictive, any actions that would disable the key are still denied

Fix data replication deployment

---

app/components/app_programme_status_tags_component.rb
app/helpers/consents_helper.rb
config/locales/en.yml
spec/components/app_programme_status_tags_component_spec.rb

Updates the programme status tag component to display "Nasal spray (or injection)" when multiple delivery methods are associated with a programme (flu). This replaces the previous behaviour of showing only the first vaccine method, ensuring consistency with how delivery methods are communicated to users in the prototype.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1234

Show full vaccine method label when consent for multiple delivery methods exist

---

app/components/app_triage_form_component.rb
app/forms/triage_form.rb
config/locales/helpers.en.yml
spec/components/app_triage_form_component_spec.rb

The triage form now specifies which delivery method in every safe to vaccinate option, for programmes with multiple delivery methods. The hint is also more explicit on what method(s) the parent has consented to.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1285
https://nhsd-jira.digital.nhs.uk/browse/MAV-1398

Change triage options text

---

terraform/app/rds.tf

- Once a month is sufficient
- Alco change time to ensure it happens during low traffic hours
Ref: [MAV-1412](https://nhsd-jira.digital.nhs.uk/browse/MAV-1412)

Reduce frequency of secret rotation

---

spec/forms/triage_form_spec.rb

This validation was failing whenever the form was randomly initialized
with flu data (or anything that has multiple vaccination method) as in
those cases the status_and_vaccine_method could take on arbitrary values
depending on what methods were available. Instead, we now validate based
on :status_and_vaccine_method_options which should always contain 
exactly the right values.

Fix the :status_and_vaccine_method validation

---

app/controllers/patient_sessions/triages_controller.rb
spec/features/triage_delay_vaccination_spec.rb
spec/features/triage_spec.rb
spec/features/triage_then_parental_consent_refused_spec.rb

While we don’t currently have the ability to provide a triage outcome for multiple programmes at a time, we require users to create a triage outcome multiple times.
This becomes even trickier because currently we return the user to the session Triage list after a adding a triage outcome; they then need to find the patient again, and then click on the other programme tab and add their second triage outcome.
We can make this process a little easier by returning the user to the page they came from (i.e. the patient session page), instead of taking them to the session Triage list view.
[Jira Issue](https://nhsd-jira.digital.nhs.uk/browse/MAV-1129)

Redirect users back to the patient after triage

---

app/controllers/draft_consents_controller.rb
app/forms/triage_form.rb
app/models/draft_consent.rb
app/views/draft_consents/agree.html.erb
config/locales/en.yml
spec/features/verbal_consent_given_spec.rb
spec/forms/triage_form_spec.rb
spec/models/draft_consent_spec.rb
terraform/app/rds.tf

This enhancement updates the triage flow for Flu to reflect the consented vaccine method(s) provided by parents. It allows clinicians to select an appropriate method where multiple are consented, or restricts options when only one method is permitted.
| Non-flu programme | Flu programme |
|------------------|---------------------|
| <img width="665" alt="Screenshot 2025-06-25 at 09 43 24" src="https://github.com/user-attachments/assets/6245541e-a95d-4a5f-9941-1aa132630a43" /> | <img width="746" alt="Screenshot 2025-06-25 at 09 36 04" src="https://github.com/user-attachments/assets/dbc1c09a-9fd7-41c4-a47c-a395f89f53ae" /> | 
JIRA: [MAV-1267](https://nhsd-jira.digital.nhs.uk/browse/MAV-1267)

Update Flu triage flow to reflect consented vaccine methods

---

app/forms/triage_form.rb
spec/factories/consents.rb
spec/factories/patient_consent_statuses.rb
spec/factories/patient_sessions.rb
spec/factories/patients.rb
spec/features/triage_spec.rb
spec/forms/triage_form_spec.rb

* Ensure triage form records correct vaccine method, so if a patient is triaged as needing to receive nasal spray, that's what the recording flow asks for
* Extend the triage feature spec to cover injection-only and nasal-only consents
[JIRA ticket](https://nhsd-jira.digital.nhs.uk/browse/MAV-1421)

Ensure triage form records correct vaccine method

---

terraform/account/resources/iam_policy_DeployDataReplicationResources.json

* The `kms:CreateGrant` permission is needed and can not be denied. This has been applied already but not committed

Fix data replication policy

---

app/components/app_search_component.rb
app/controllers/concerns/search_form_concern.rb
app/controllers/sessions/record_controller.rb
app/forms/search_form.rb
app/models/patient/consent_status.rb
app/models/patient_session.rb
app/models/programme.rb
app/models/session.rb
app/views/sessions/record/show.html.erb
spec/forms/search_form_spec.rb
spec/models/programme_spec.rb
spec/models/session_spec.rb

This adds new filter options when viewing the "Record vaccinations" tab allowing users to filter on the consented or triaged vaccine methods for each patient.
[Jira Issue - MAV-1337](https://nhsd-jira.digital.nhs.uk/browse/MAV-1337)

Add ability to filter on vaccine method

---

app/components/app_consent_confirmation_component.rb
spec/components/app_consent_confirmation_component_spec.rb
spec/features/parental_consent_change_answers_spec.rb

The content needs to vary depending on whether the parents have consented to the Flu vaccine via nasal spray or via injection.
[Jira Issue - MAV-1339](https://nhsd-jira.digital.nhs.uk/browse/MAV-1339)

Update online consent confirmation page for Flu

---

app/components/app_search_component.rb
spec/features/filtering_by_programme_spec.rb

Previously, the programme filter checkboxes were displayed whenever any programmes existed in a session, even when there was only one programme. This created a confusing UX where users could see a filter option that wouldn't actually filter anything meaningful.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1452

Hide programme filter checkboxes when session has only one programme

---

app/components/app_consent_confirmation_component.rb
spec/components/app_consent_confirmation_component_spec.rb
spec/features/parental_consent_change_answers_spec.rb

Previosuly, the consent refused confirmation page refered to the flu injection specifically. This change removes confusion by referring to the general "flu vaccination".
https://nhsd-jira.digital.nhs.uk/browse/MAV-1456

Fix consent refused confirmation page for flu

---

app/models/patient.rb
spec/features/filtering_by_programme_spec.rb
spec/forms/search_form_spec.rb

The register and record-vaccinations tabs now show a “Year group” filter, intended to list only the pupils in the chosen year (e.g., Year 8). The filter appears but doesn’t work as intended as the full pupil list still displays.
The reason it wasn't working is that the original scope was overriding a previous scope `search_by_year_groups`. The new version considers the programme as it should but makes sure it returns patients who are eligible for that programme.
|------------------|---------------------|
| <img width="1135" alt="Screenshot 2025-07-02 at 16 36 37" src="https://github.com/user-attachments/assets/6aed26d7-80bd-4c0d-be97-a57f834ff210" /> | <img width="1116" alt="Screenshot 2025-07-02 at 16 37 14" src="https://github.com/user-attachments/assets/143bde97-def8- …

Fix: year group filters not filtering as expected

---

app/components/app_patient_vaccination_table_component.rb
app/lib/vaccinated_criteria.rb
app/models/vaccination_record.rb
spec/components/app_patient_vaccination_table_component_spec.rb

If displaying a table of vaccination records for Flu we should hide any that were performed in the previous academic year, as the Flu programme is administered yearly.
[Jira Issue - MAV-1359](https://nhsd-jira.digital.nhs.uk/browse/MAV-1359)

Hide previous years seasonal vaccinations

---

app/models/draft_vaccination_record.rb
spec/factories/patients.rb
spec/features/flu_vaccination_administered_spec.rb
spec/models/draft_vaccination_record_spec.rb

For flu vaccination recording, the delivery method (broadly nasal vs injection), the delivery site (part of the body) and the vaccine product need to be consistent.
If a vaccinator starts recording a nasal flu vaccination, changes prior to confirmation to an injection (or vice versa), they need to pick the vaccine product & batch again to avoid inconsistencies.
This PR makes this change, as well as adding feature spec coverage for flu vaccination administration.
JIRA: [MAV-1460](https://nhsd-jira.digital.nhs.uk/browse/MAV-1460), [MAV-1461](https://nhsd-jira.digital.nhs.uk/browse/MAV-1461)

Flu recording: reset batch if delivery method changes

---

app/components/app_vaccinate_form_component.html.erb
spec/features/community_clinic_vaccination_session_spec.rb
spec/features/doubles_vaccination_administered_spec.rb
spec/features/e2e_journey_spec.rb
spec/features/flu_vaccination_administered_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_delayed_spec.rb
spec/features/identity_check_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/pre_screening_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/features/vaccination_todays_batch_spec.rb

During the identity check pre-vaccination, the child is now selected by default, reducing the number of clicks most vaccination flows will have. This is because a vast majority of children will be able to  identify themselves.
Also adds feature tests for the identity check flow.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1349

Identity check default

---

Dockerfile
bin/internal_healthcheck
terraform/app/ecs.tf
terraform/app/loadbalancer.tf

- Try to initialize a new connection
- ActiveRecord persists connections after credential change
- New connections fails after credential change
- This means that while old connections exist we will identify that the
credentials have changed and trigger a redeployment of containers
- This avoids any disturbance to user traffic and avoids any `500`
error messages
- Additionally increase the frequency of ELB healthchecks to limit
impact to users in any potential future situations when a container
becomes unhealthy
[JIRA ticket](https://nhsd-jira.digital.nhs.uk/browse/MAV-1464)

Validate DB connection in internal healthcheck

---

terraform/account/main.tf
terraform/app/main.tf
terraform/app/modules/dms/main.tf
terraform/app/modules/dns/main.tf
terraform/app/modules/ecs_service/main.tf
terraform/app/modules/vpc_endpoint/main.tf
terraform/backup/destination-bootstrap/main.tf
terraform/backup/destination/main.tf
terraform/backup/source/main.tf
terraform/bootstrap/main.tf
terraform/modules/s3/main.tf

Version upgrade of the terraform provider.
Release notes of the breaking changes: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v6.0.0

Aws provider version upgrade

---

app/controllers/draft_vaccination_records_controller.rb
app/lib/enqueue_sync_vaccination_record_to_nhse.rb
app/models/immunisation_import.rb
config/feature_flags.yml
spec/features/flu_vaccination_administered_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/lib/enqueue_sync_vaccination_record_to_nhse_spec.rb
spec/models/immunisation_import_spec.rb

Vaccination records recorded in Mavis need to be sent to the NHSE via the Immunisations FHIR API. Providing it is an HPV or flu vaccination, and the outcome is administered. This includes vaccinations recorded in the UI and via the offline import functionality.
NB: This PR requires that the flu vaccination records get a dose number recorded. Currently that isn't the case, but the PR this one, #3882 is based on adds that change.
[MAV-1482](https://nhsd-jira.digital.nhs.uk/browse/MAV-1482)

Sync vaccination records to NHSE Immunisations FHIR API

---

app/lib/govuk_notify_personalisation.rb
app/models/concerns/has_side_effects.rb
app/models/concerns/has_vaccine_methods.rb
app/models/vaccine.rb
config/locales/en.yml
db/migrate/20250619125105_add_side_effects_to_vaccines.rb
db/schema.rb
lib/tasks/vaccines.rake
spec/factories/vaccines.rb
spec/lib/govuk_notify_personalisation_spec.rb
spec/models/vaccine_spec.rb

We need to add support for storing the side effects of each vaccine so these can be displayed dynamically in the emails for the session reminders and the vaccination confirmations. This allows them to be included in emails we send out to users, either before a session for all programmes, or after a session for a vaccination record.
The `vaccines:seed[...]` task needs to be run for HPV, MenACWY and Td/IPV. We don't run it for Flu yet.
Duplicate https://www.notifications.service.gov.uk/services/629645d8-feb9-4fc1-93f4-759c93ac0e21/templates/79e131b2-7816-46d0-9c74-ae14956dd77d and deploy a branch that uses new template, where new template has `((vaccine_side_effects))` instead of hard coded list.
[Jira Issue - MAV-1354](https://nhsd-jira.digital.nhs.uk/browse/MAV-1354)
[Jira Issue - …

Add side effects to vaccines

---

config/initializers/govuk_notify.rb

The new session reminder template accepts a `vaccine_side_effects` variable, allowing it to be customised for each programme. This change changes the template id to point to the new template.
https://www.notifications.service.gov.uk/services/629645d8-feb9-4fc1-93f4-759c93ac0e21/templates/8b8a9566-bb03-4b3c-8abc-5bd5a4b8797d
This needs to be merged in after https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3785
https://nhsd-jira.digital.nhs.uk/browse/MAV-1355

Change session reminder template to point to generic reminder

---

spec/forms/search_form_spec.rb

The test tries to create a vaccination record with a different programme to that currently being search across, however because the vaccination record factory picks programmes at random it's possible that sometimes the two programmes will match. There's a unique index on the type of programme meaning when two programmes of the same type are created we get a unique constraint failure.
Example failures:
- https://github.com/nhsuk/manage-vaccinations-in-schools/actions/runs/16131100054/job/45518594025?pr=3889
- https://github.com/nhsuk/manage-vaccinations-in-schools/actions/runs/16131000767/attempts/1?pr=3888
- https://github.com/nhsuk/manage-vaccinations-in-schools/actions/runs/16130163178/attempts/1?pr=3887

Fix flaky search form test

---

.github/workflows/data-replication-pipeline.yml
terraform/data_replication/rds.tf

This PR contains some improvements for the data replication workflow
* DB destruction and recreation is done in a single job, that shortens the workflow duration and requires just 1 approval
* The workflow stops if there was an error in the terraform plan job
* Added an option to deploy just a new web app, skipping the DB recreation altogether

Improve Data replication workflow

---

app/controllers/draft_vaccination_records_controller.rb
app/lib/enqueue_sync_vaccination_record_to_nhs.rb
app/models/immunisation_import.rb
config/feature_flags.yml
spec/features/flu_vaccination_administered_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/lib/enqueue_sync_vaccination_record_to_nhs_spec.rb
spec/models/immunisation_import_spec.rb

Vaccination records recorded in Mavis need to be sent to the NHSE via the Immunisations FHIR API. Providing it is an HPV or flu vaccination, and the outcome is administered. This includes vaccinations recorded in the UI and via the offline import functionality.
NB: This PR requires that the flu vaccination records get a dose number recorded. Currently that isn't the case, but the PR this one, https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3882 is based on adds that change.
[MAV-1482](https://nhsd-jira.digital.nhs.uk/browse/MAV-1482)

Send vaccination records to imms api

---

app/lib/govuk_notify_personalisation.rb
spec/lib/govuk_notify_personalisation_spec.rb

This adds two new personalisation variables that will be sent to GOV.UK Notify when sending an email or text message to allow for the templates to be customised according to the type of vaccine that will be given to the patient.
[Jira Issue - MAV-1355](https://nhsd-jira.digital.nhs.uk/browse/MAV-1355)

Add `vaccine_is_injection` and `vaccine_is_nasal`

---

app/lib/govuk_notify_personalisation.rb
spec/lib/govuk_notify_personalisation_spec.rb

This is a variable that will be passed to GOV.UK Notify and will be used to customise the content shown in a number of emails according to whether the session has lots of dates or not.
[Jira Issue - MAV-1277](https://nhsd-jira.digital.nhs.uk/browse/MAV-1277) &middot; [Jira Issue - MAV-1527](https://nhsd-jira.digital.nhs.uk/browse/MAV-1527)

Add `has_multiple_dates` personalisation variable

---

app/controllers/concerns/vaccination_mailer_concern.rb
config/initializers/govuk_notify.rb
spec/controllers/concerns/vaccination_mailer_concern_spec.rb
spec/features/doubles_vaccination_administered_spec.rb
spec/features/flu_vaccination_administered_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb

Now that the vaccine side effects are dynamic we can consolidate the text messages that are sent when a patient is administered as the only differences between them was the different side effects.
[Jira Issue - MAV-1529](https://nhsd-jira.digital.nhs.uk/browse/MAV-1529)

Consolidate vaccination administered texts

---

app/lib/govuk_notify_personalisation.rb
spec/lib/govuk_notify_personalisation_spec.rb

This is a variable that will be passed to GOV.UK Notify and will be used to customise the content shown in a number of emails according to whether or not the patient is able to self-consent via Gillick competence.
[Jira Issue - MAV-1277](https://nhsd-jira.digital.nhs.uk/browse/MAV-1277)

Add `can_self_consent` personalisation variable

---

app/lib/govuk_notify_personalisation.rb
spec/lib/govuk_notify_personalisation_spec.rb

As far as I can tell it's not being used in any of our templates so we can remove this variable.

Remove `programme_name` personalisation variable

---

app/controllers/api/organisations_controller.rb

Without this, the organisation can't be re-onboarded.

Clear generic clinic when reseting an org for dev

---

app/lib/govuk_notify_personalisation.rb
spec/lib/govuk_notify_personalisation_spec.rb

This adds a new personalisation variable which includes both the vaccination that was given plus the delivery method (if appropriate). This will only be shown for flu where there's a distinction between nasal spray and injection.
[Jira Issue - MAV-1529](https://nhsd-jira.digital.nhs.uk/browse/MAV-1529)

Add `vaccination_and_method` personalisation variable

---

app/lib/govuk_notify_personalisation.rb
spec/lib/govuk_notify_personalisation_spec.rb

This adds two new personalisation variables that will be passed to templates in GOV.UK Notify when sending emails and texts. These new variables will be used in the triage confirmation emails to display which vaccination method the child was triaged as appropriate for.
[Jira Issue - MAV-1525](https://nhsd-jira.digital.nhs.uk/browse/MAV-1525)

Add `vaccine` and `vaccine_and_method` personalisation

---

app/components/app_patient_session_record_component.rb
app/components/app_vaccinate_form_component.html.erb
app/components/app_vaccinate_form_component.rb
spec/components/app_vaccinate_form_component_spec.rb
spec/features/flu_vaccination_administered_spec.rb

The form is now makes explicit what vaccine method is being used in the case of flu vaccines. The title for the record section and the vaccination question include the method.
For non-flu programmes, the programme name is now specified in the record section title.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1414

Make flu vaccination form titles clearer

---

app/components/app_vaccinate_form_component.html.erb
config/locales/en.yml
spec/features/doubles_vaccination_administered_spec.rb
spec/features/e2e_journey_spec.rb
spec/features/flu_vaccination_administered_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_already_had_spec.rb
spec/features/hpv_vaccination_clinic_spec.rb
spec/features/identity_check_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/pre_screening_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/features/vaccination_todays_batch_spec.rb

With flu it is a possibility that the child is not old enough to identify themselves. In which case they would also not
be old enough to confirm the pre-screening questions themselves. In that case it makes more sense to direct
the questions to the nurse who can check/confirm with the child accordingly. 
https://nhsd-jira.digital.nhs.uk/browse/MAV-1494

Pre screening questions now directed to nurse

---

app/components/app_consent_confirmation_component.rb
app/components/app_patient_session_record_component.rb
app/components/app_patient_session_search_result_card_component.rb
app/components/app_patient_session_triage_component.html.erb
app/components/app_session_actions_component.rb
app/components/app_session_details_summary_component.rb
app/components/app_vaccinate_form_component.rb
app/controllers/draft_vaccination_records_controller.rb
app/models/immunisation_import_row.rb
app/models/programme.rb
app/views/draft_vaccination_records/batch.html.erb
app/views/draft_vaccination_records/date_and_time.html.erb
app/views/draft_vaccination_records/delivery.html.erb
app/views/draft_vaccination_records/location.html.erb
app/views/draft_vaccination_records/outcome.html.erb
app/views/parent_relationships/destroy.html.erb
lib/tasks/health_questions.rake
spec/features/flu_vaccination_administered_spec.rb
spec/models/programme_spec.rb

This adds a new method on the `Programme` model which can be used to get the name of the programme appropriate for rendering in the middle of a sentence. For most programmes this will be the same as their name, but for flu, when rendered in a sentence it should have a lowercase first letter.
By having this method we can also start to replace the hard-coded instances of `"flu"`.

Ensure flu is displayed lowercase in sentences

---

app/components/app_consent_confirmation_component.rb
app/components/app_patient_session_record_component.rb
app/components/app_vaccinate_form_component.rb
app/controllers/concerns/todays_batch_concern.rb
app/controllers/patient_sessions/vaccinations_controller.rb
app/controllers/sessions/record_controller.rb
app/controllers/vaccines_controller.rb
app/lib/govuk_notify_personalisation.rb
app/views/sessions/record/batch.html.erb
app/views/sessions/record/show.html.erb
app/views/vaccines/index.html.erb
app/views/vaccines/show.html.erb
config/locales/en.yml
config/routes.rb
spec/components/app_consent_confirmation_component_spec.rb
spec/features/parental_consent_change_answers_spec.rb
spec/features/todays_batch_spec.rb

This ensures that when administered vaccinations for a programme like flu where there are multiple vaccine methods (injection vs nasal), the default batch for the day is different for the two vaccine methods.
[Jira Issue - MAV-1431](https://nhsd-jira.digital.nhs.uk/browse/MAV-1431)

Allow default daily batch per vaccine method

---

app/lib/govuk_notify_personalisation.rb
spec/lib/govuk_notify_personalisation_spec.rb

This replaces the `can_self_consent` variable that was added in 37c4891e152b7f4e3423ba192bc342059393dbc2 as we can't use the variable as expected.
It was designed to be used with optional content, but the optional content in this case contains a link which is not supported in optional content. Instead we need to pass the entire block of content as a variable (`talk_to_your_child_message` added in this commit) and that handles the logic about whether to populate it or not.
[Jira Issue - MAV-1277](https://nhsd-jira.digital.nhs.uk/browse/MAV-1277)

Add `talk_to_your_child_message` personalisation

---

app/models/notify_log_entry.rb
config/initializers/govuk_notify.rb
spec/models/notify_log_entry_spec.rb

As we're removing or changing templates, we might have records of emails and texts that were sent using a template that we no longer used. In particular, to support the flu programme we've changed a large number of templates in the previous commits.
Without keeping a track of the previous templates, users will start seeing "Unknown Email" or "Unknown SMS" in the activity log.
I did think about updating the notify log entry model to track the template names rather than the IDs, however this is a simpler solution. Really we probably want to be storing the subject lines of the emails, and that would be a future enhancement, but since that will require further work in this area the simpler solution for now felt like the easier way to move forward.

Ensure we have names for unused Notify templates

---

app/controllers/sessions/record_controller.rb
app/models/patient.rb
app/models/patient_session.rb
spec/features/flu_vaccination_administered_spec.rb
spec/models/patient_session_spec.rb

When displaying a list of patients who need vaccinating when filtering on the vaccine method we should ensure that the vaccine method is appropriate for the vaccinations left to record. For example, if a patient has consent for flu and HPV, and they've been given the nasal spray vaccine for flu, if you now filter on "nasal spray" this patient should no longer appear in the list as for HPV they're only eligible for the injection.
[Jira Issue - MAV-1463](https://nhsd-jira.digital.nhs.uk/browse/MAV-1463)

Filter on patients with approriate vaccine method

---

app/controllers/draft_vaccination_records_controller.rb
app/controllers/patient_sessions/vaccinations_controller.rb
app/forms/vaccinate_form.rb
app/models/draft_vaccination_record.rb
app/models/vaccine.rb
spec/features/flu_vaccination_administered_spec.rb
spec/models/vaccine_spec.rb

When recording a vaccination the default should be full dose, and the nurse can change their answer to half dose if they need to. We shouldn't be asking this question by default.
In fact, this question was only being shown when today's batch had been selected due to the order of the questions, but now the behaviour is consistent regardless of whether a default batch has been selected or not.
[Jira Issue - MAV-1504](https://nhsd-jira.digital.nhs.uk/browse/MAV-1504)

Don't ask full or half dose question by default

---

app/models/session_notification.rb
config/initializers/govuk_notify.rb
spec/models/session_notification_spec.rb

CWPT (Coventry & Warwickshire Partnership NHS Trust) uses a unique clinic booking system (SwiftQueue) that requires specific instructions in their notifications. We discovered instances where non-CWPT organisations were inadvertently sending CWPT-specific clinic invitation emails and SMS. This occurred because the notification sending process lacked organisation-specific checks, resulting in parents receiving incorrect communications.
JIRA Ticket: [MAV-1024](https://nhsd-jira.digital.nhs.uk/browse/MAV-1024)
Create two versions of clinic invitation and reminder templates:
  1. The existing CWPT-specific templates on Gov UK Notify gets mapped to new keys postfixed with `_ryg` where RYG is    the `ods_code` for the organisation
  3. New generic templates for all other organisations will use …

Implement separate email templates for CWPT and other organisations

---

app/components/app_vaccinate_form_component.html.erb
app/components/app_vaccinate_form_component.rb
app/controllers/patient_sessions/vaccinations_controller.rb
app/forms/vaccinate_form.rb
app/models/draft_vaccination_record.rb
app/models/patient.rb
app/models/vaccine.rb
config/locales/en.yml
spec/features/flu_vaccination_administered_spec.rb
spec/features/triage_delay_vaccination_spec.rb
spec/forms/vaccinate_form_spec.rb

This adds the ability for nurses to record an injection for a patient if they've got consent for both the nasal spray and the injection. See individual commits for more details.
[Jira Issue - MAV-1338](https://nhsd-jira.digital.nhs.uk/browse/MAV-1338)

Allow recording injection for nasal patients

---

app/components/app_consent_card_component.rb
app/components/app_consent_summary_component.rb
app/helpers/consents_helper.rb
app/views/patient_sessions/consents/show.html.erb
spec/components/app_consent_card_component_spec.rb
spec/components/app_consent_summary_component_spec.rb
spec/features/self_consent_spec.rb
spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
spec/features/verbal_consent_given_spec.rb
spec/features/verbal_consent_refused_personal_choice_spec.rb
spec/features/verbal_consent_refused_spec.rb

When displaying a consent either on the patient session page or when viewing a consent directly, we should show if the parent also consented to any alternative vaccine methods. This is only relevant for the flu programme where you can consent to both the nasal spray and the injection.
To support this I've also updated the summary list showing the consent response to match the latest designs in the prototype.
[Jira Issue - MAV-1473](https://nhsd-jira.digital.nhs.uk/browse/MAV-1473)

Show secondary consent vaccine methods

---

config/initializers/govuk_notify.rb

This updates the session reminder text template which now shows an appropriate message according to whether the vaccine is nasal or injection.
[Jira Issue - MAV-1564](https://nhsd-jira.digital.nhs.uk/browse/MAV-1564)

Update session reminder text template

---

app/models/consent_form.rb
lib/tasks/vaccines.rake
spec/features/parental_consent_change_answers_spec.rb
spec/features/parental_consent_flu_spec.rb

When submitting consent this updates the injection alternative question to appear before the health questions, allowing for the questions to be customised according to the vaccine method.
[Jira Issue - MAV-1565](https://nhsd-jira.digital.nhs.uk/browse/MAV-1565)

Reorder injection alternative question

---

app/components/app_activity_log_component.rb
app/components/app_patient_search_result_card_component.rb
app/components/app_patient_session_search_result_card_component.rb
app/components/app_patient_session_triage_component.html.erb
app/components/app_patient_session_triage_component.rb
app/components/app_triage_form_component.html.erb
app/components/app_triage_table_component.rb
app/forms/triage_form.rb
app/helpers/triages_helper.rb
config/locales/en.yml
config/locales/status.en.yml
spec/components/app_activity_log_component_spec.rb
spec/features/triage_spec.rb
spec/features/verbal_consent_given_spec.rb

Make vaccine method explicit in relation to triage for the flu programme and other minor visual changes to the triage form
- Display vaccine method in status tags on session >triage pages, patient session pages and programme>children page
- Add an "or" divider between yes and no options on the triage form (applies to all programmes)
- Add hints to flu triage form to indicate the vaccine method the nurse has triaged safe for
- Add the vaccine method to the "safe to vaccinate" triage entry in the activity log for all flu triages
https://nhsd-jira.digital.nhs.uk/browse/MAV-1413
https://nhsd-jira.digital.nhs.uk/browse/MAV-1500

Triage for flu: UI changes

---

app/components/app_programme_status_tags_component.rb
config/locales/en.yml
spec/components/app_programme_status_tags_component_spec.rb

This label should no longer be shown as we now have a separate row shown whether the parents also consented to the injection.
[Jira Issue - MAV-1565](https://nhsd-jira.digital.nhs.uk/browse/MAV-1565)

Don't show "Nasal spray (or injection)"

---

terraform/data_replication/main.tf

The data replication module still required terraform major version 5 which made it incompatible with the other modules that require version 6.2

Align terraform versions

---

app/components/app_patient_vaccination_table_component.html.erb
app/components/app_programme_navigation_component.rb
app/components/app_programme_stats_component.html.erb
app/components/app_vaccination_record_table_component.html.erb
app/controllers/draft_vaccination_records_controller.rb
app/controllers/programmes/base_controller.rb
app/controllers/programmes/cohorts_controller.rb
app/controllers/programmes/overview_controller.rb
app/controllers/programmes/patients_controller.rb
app/controllers/programmes/reports_controller.rb
app/controllers/programmes/sessions_controller.rb
app/controllers/programmes/vaccinations_controller.rb
app/controllers/programmes_controller.rb
app/controllers/sessions/register_controller.rb
app/controllers/vaccination_records_controller.rb
app/controllers/vaccination_reports_controller.rb
app/views/programmes/cohorts/index.html.erb
app/views/programmes/cohorts/show.html.erb
app/views/programmes/index.html.erb
app/views/programmes/overview/show.html.erb
app/views/programmes/patients/index.html.erb
app/views/programmes/sessions/index.html.erb
app/views/programmes/show.html.erb
app/views/programmes/vaccinations/index.html.erb
app/views/vaccination_records/destroy.html.erb
app/views/vaccination_records/show.html.erb
app/views/vaccination_reports/dates.html.erb
config/locales/en.yml
config/routes.rb
spec/features/download_vaccination_reports_spec.rb

This refactors the various controllers responsible for rendering the various parts of the programmes pages to split up the single `ProgrammesController` in to separate controllers response for each time ([similar to what we did for patient sessions](https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3658)).
This should hopefully make it easier to understand what these controllers are for and how they relate to the other controllers. At the moment they're all in the root module which can make it difficult to see that they're actually all part of the patient sessions section of the service.

Refactor programme controllers

---

app/controllers/draft_vaccination_records_controller.rb
app/models/vaccination_record.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/models/concerns/vaccination_record_sync_to_nhs_immunisations_api_concern_spec.rb
spec/models/vaccination_record_spec.rb

This fixes the issue of updating a vaccination after the duplicate is merged, and replaces the manual sync that was added to the draft vaccinations controller to trigger when a vaccination is edited.
[MAV-1553](https://nhsd-jira.digital.nhs.uk/browse/MAV-1553)

Add after_save hook to sync vaccination

---

.github/workflows/lint.yml

This reverts commit ed98acd9a9c78ab9a8c99044efe90b5c6b8098bf.
The issue with downloading the latest version of mise seems to have been fixed.

Revert "Pin mise version"

---

app/lib/academic_year.rb
config/settings.yml
spec/lib/academic_year_spec.rb
terraform/app/variables.tf

This adds support for adding academic years to the service before their official start date through the introduce of a preparation period.
For now this has no impact on the service, but in the future this will change which programme years are displayed on the programmes page and which year groups patients are assigned to when importing records.
We're not quite ready yet to enable this in production on the 1st August, so once this variable is live we will edit the setting in production to ensure it's closer to the 1st September.
[Jira Issue - MAV-1505](https://nhsd-jira.digital.nhs.uk/browse/MAV-1505)

Academic year preparation start date

---

app/components/app_register_status_tag_component.rb
config/locales/status.en.yml

Changing the registration attending status colour to aqua-green means that nurses can more easily see if a child is ready to vaccinate as all the status colours align: consent outcome, (triage outcome), (registration outcome) and soon (PSD outcome). Nurses often like to think that “green means good to go”.

Use aqua-green for registration attending status colour

---

app/components/app_patient_session_consent_component.html.erb
app/components/app_patient_session_consent_component.rb
spec/components/app_patient_session_consent_component_spec.rb

This ensures that the button is hidden if no consent response is needed for this patient to prevent nurses from accidentally recording a consent response when not needed.
Specifically this prevents a scenario that was found to be possible in testing, but wouldn't occur in reality where a patient already had consent from a parent and then the nurse could request consent from another parent which changed the status from consent given to consent conflicting.
[Jira Issue - MAV-1591](https://nhsd-jira.digital.nhs.uk/browse/MAV-1591)

Hide "Get a new consent response" button

---

app/lib/mavis_cli/clinics/add_to_organisation.rb
app/lib/mavis_cli/clinics/create.rb
app/lib/mavis_cli/schools/add_programme_year_group.rb
app/lib/mavis_cli/schools/add_to_organisation.rb
app/lib/mavis_cli/schools/remove_programme_year_group.rb

A number of new CLI commands have been added recently, but I forgot to add `MavisCLI.load_rails` meaning when run in a deployment environment they don't have access to any of the models or other classes autoloaded by Rails.

Ensure `MavisCLI.load_rails` is called

---

Gemfile.lock

Reverts nhsuk/manage-vaccinations-in-schools#4023
This was accidentally merged in to `main` when it should have instead been merged in to `next`.

Revert "Bump the bundler group across 1 directory with 2 updates"

---

app/models/vaccination_report.rb
spec/models/vaccination_report_spec.rb

The general mappings for flu have been added so it is safe to enable the S1 file format for the flu programme.

Enable SystmOne file format for flu

---

app/models/immunisation_import_row.rb
spec/features/hpv_vaccination_offline_spec.rb

When recording offline, if a user is editing an existing record from the spreadsheet, we should ensure that all changes to that record are staged and highlighted to the user. This is to prevent the confusing scenario where some of the changes are staged and some others are accepted automatically.
[Jira Issue - MAV-1597](https://nhsd-jira.digital.nhs.uk/browse/MAV-1597)

Ensure all changes are staged when recording offline

---

app/lib/academic_year.rb
spec/lib/academic_year_spec.rb

This changes the order of academic years when displayed in a number of places to ensure that the most recent years are shown first.

Order academic years most recent first

---

app/models/concerns/vaccination_record_sync_to_nhs_immunisations_api_concern.rb
config/feature_flags.yml
spec/features/delete_vaccination_record_spec.rb
spec/features/edit_vaccination_record_spec.rb
spec/features/flu_vaccination_administered_spec.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/manage_children_spec.rb
spec/features/menacwy_vaccination_administered_spec.rb
spec/features/td_ipv_vaccination_administered_spec.rb
spec/lib/patient_merger_spec.rb
spec/models/concerns/vaccination_record_sync_to_nhs_immunisations_api_concern_spec.rb
spec/models/immunisation_import_spec.rb

This name better describes what the flag is used for.
Once deployed we'll have to update the feature flag in `qa` manually.

Rename feature flag used to enqueue for imms api

---

app/lib/fhir_mapper/programme.rb
app/lib/fhir_mapper/vaccination_record.rb
app/lib/fhir_mapper/vaccine.rb
app/lib/reports/programme_vaccinations_exporter.rb
app/models/programme.rb
app/models/vaccination_record.rb
app/models/vaccine.rb
spec/lib/fhir_mapper/programme_spec.rb
spec/lib/fhir_mapper/vaccine_spec.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb
spec/models/vaccine_spec.rb

Following on from #4047 this adds the procedure codes for the flu vaccines. These codes are different depending on the method of the vaccine and the dose sequence so we need to consider both of those when returning the code.
[Jira Issue - MAV-1112](https://nhsd-jira.digital.nhs.uk/browse/MAV-1112)

Add flu procedure codes

---

app/lib/academic_year.rb
spec/lib/academic_year_spec.rb

This represents either the current academic year, or if during the preparation for the next academic year, the next academic year.
Pending was chosen as the word to use to try and explain how it's neither the `next` or the `current` academic year, and can be either at different times in the year.
Although this is not used yet, most of the changes related to rollover rely on this value so it would be good to get this change merged in to base off.

Add `AcademicYear#pending`

---

lib/tasks/create_default_programme_year_groups.rake

We need to run this task after deploying 2.11 to production and it looks like a refactor since the task was initially created and run in the test environment has broken it. This fixes the Rake task to run correctly.
This task doesn't have any tests as it's a one off task that will be run after a deploy and then deleted, it's been run in test and QA successfully.

Fix `create_default_programme_year_groups` task

---

app/models/programme.rb
spec/models/programme_spec.rb

Some patients will receive a second flu dose and therefore we need to increase the maximum dose sequence for the programme to allow that.
[Jira Issue - MAV-1666](https://nhsd-jira.digital.nhs.uk/browse/MAV-1666)

Increase flu maximum dose sequence

---

app/forms/vaccinate_form.rb
spec/features/flu_vaccination_administered_spec.rb

If a delivery site is selected, but the vaccine method means that there's only one possible delivery site, we can ignore the provided value.
This fixes a bug where if the user were to select injection and then select a delivery site, but then go back and select nasal spray, the delivery site for injection would still come through and it would be invalid for nasal spray.
[Jira Issue - MAV-1656](https://nhsd-jira.digital.nhs.uk/browse/MAV-1656)

Ignore delivery site if there's only one

---

app/lib/generic_clinic_factory.rb
spec/factories/locations.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/manage_clinic_sessions_spec.rb
spec/features/parental_consent_clinic_spec.rb

In the prototype it's written as a singular, "Community clinic". Because of how the sessions are created, this won't affect any existing ones in production but it will for the next academic year.

Rename "Community clinics"

---

app/components/app_patient_session_record_component.rb
app/components/app_session_actions_component.rb
app/controllers/sessions/record_controller.rb
app/models/session.rb
app/views/patient_sessions/_header.html.erb
app/views/sessions/_header.html.erb
db/migrate/20250717093714_add_requires_registration_field_to_sessions.rb
db/schema.rb
spec/components/app_patient_session_record_component_spec.rb
spec/components/app_session_actions_component_spec.rb
spec/factories/sessions.rb
spec/features/hpv_vaccination_administered_spec.rb
spec/features/manage_attendance_spec.rb
spec/models/session_spec.rb

This PR introduces a new boolean column `requires_registration` to the `Session` model, allowing us to control whether registration is required for a specific session. When registration is not required, the "Register" tab will be hidden, but users can still access all patients under the "Record vaccinations" tab.
JIRA: [MAV-1292](https://nhsd-jira.digital.nhs.uk/browse/MAV-1292)

Allow sessions to not have registration

---

app/views/draft_class_imports/session.html.erb

Adds formatted address as a hint under school names on the class list import page, to help differentiate schools with identical names. This aims to prevent misselection, especially with increased number of schools on mavis for the flu programme.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1131

Add address to school options in select dropdown

---

app/models/draft_vaccination_record.rb
config/locales/en.yml
spec/features/edit_vaccination_record_spec.rb
spec/models/draft_vaccination_record_spec.rb

This change adds a validation that the vaccination event administration date falls within the same academic year as the session it is attached to. This validation prevents editing vaccination records to be outside the given academic year.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1567

Prevent changing the vaccination record administration date to a different academic year

---

app/lib/reports/systm_one_exporter.rb
spec/lib/reports/systm_one_exporter_spec.rb

SystmOne templates do not have a dedicated field for storing the administering professional information, so LPT and HCT have been using the notes field to capture this information. 
https://nhsd-jira.digital.nhs.uk/browse/MAV-1082

Add administering professional info to SystmOne export

---

app/models/concerns/pending_changes_concern.rb
spec/models/class_import_row_spec.rb
spec/models/class_import_spec.rb
spec/models/cohort_import_row_spec.rb
spec/models/cohort_import_spec.rb
spec/models/immunisation_import_row_spec.rb

Names which only differ by capitalisation (eg "SMITH" vs "Smith") currently require a manual review. This has caused many (100s) manual reviews per import for C&W. This is made even more confusing by the fact that Mavis capitalises all surnames in the front end, so the "change" looked identical to the users.
This should probably be automated, accepting the incoming capitalisation.
[MAV-1084](https://nhsd-jira.digital.nhs.uk/browse/MAV-1084)

Accept import capitalisation differences during import

---

app/controllers/programmes/cohorts_controller.rb
app/models/organisation.rb
app/models/programme.rb
app/views/programmes/cohorts/show.html.erb
spec/features/cohorts_index_spec.rb

When viewing the cohorts of a programme, sometimes patients can appear multiple times, if they appear in multiple sessions. These pages are shortly going to be redesigned to link to the children page with filters which doesn't have this problem, but until then this fixes the immediate issue.

Ensure duplicate patients aren't shown on cohort pages

---

app/components/app_patient_search_form_component.rb
app/components/app_patient_session_search_result_card_component.rb
app/components/app_session_actions_component.rb
app/components/app_session_details_summary_component.rb
app/controllers/concerns/patient_search_form_concern.rb
app/controllers/sessions/register_controller.rb

This simplifies the query parameters for the patient search form to avoid the `patient_search_form` prefix appearing for every parameter. This is something Rails does by default and is useful for POST requests, but with a GET request it can result in particularly long URLs which can be difficult to work with. For example, what we have currently:
```
/patients?patient_search_form[q]=Thomas
```
Will be replaced with:
```
/patients?q=Thomas
```
One of the reasons to make this change is that I was concerned about reaching the length limit of URLs, particularly on pages with lots of filters.
Initially I wanted to implement this change by setting the `scope` parameter to `form_with` to `nil`, however this results in it defaulting to the `param_key` of the model. I tried a version where the …

Simplify search form query parameters

---

terraform/app/network.tf

Adding the default security group to the terraform configuration will replace the existing default security group. This way, the ingress and egress of the existing one gets removed
Jira-Issue: MAV-1577

Remove ingress and egress for default security group

---

terraform/account/main.tf

With this lifecycle policy, images will be stored only for three months in ECR before they get deleted
Jira-Issue: MAV-1582

Set ECR lifecycle policy

---

terraform/app/loadbalancer.tf

Drop invalid HTTP headers already at the load balancer instead of forwarding them to the application
Jira-Issue: MAV-1580

Drop invalid HTTP headers

---

Dockerfile
terraform/app/modules/ecs_service/main.tf

Making the ECS container filesystem readonly prevents unlimited write access in case a running container gets compromised.
Specific write-access is allowed to certain directories that are added as volumes in the Dockerfile. In addition to the rails directories, the SSM systems manager that gives CLI access on running containers also needs write access to certain directories

Readonly container filesystem

---

app/components/app_child_summary_component.rb
app/components/app_patient_search_result_card_component.rb
app/components/app_patient_session_search_result_card_component.rb
app/helpers/patients_helper.rb
app/models/note.rb
app/models/patient.rb
app/views/imports/show.html.erb
app/views/patient_sessions/_header.html.erb
spec/helpers/cohorts_helper_spec.rb
spec/helpers/patients_helper_spec.rb

When displaying the year group of a patient the academic year should be displayed if it is different to the current academic year. This only affects when viewing a patient in the context of a session where there is an associated academic year.

Show academic year next to year group 

---

app/lib/academic_year.rb
config/settings.yml
spec/lib/academic_year_spec.rb
terraform/app/env/production.tfvars
terraform/app/env/qa.tfvars
terraform/app/env/test.tfvars
terraform/app/variables.tf

When calculating the current academic year, this adds a setting and an environment variable that can be used to customise today's date. This is useful for testing.
[Jira Issue - MAV-1563](https://nhsd-jira.digital.nhs.uk/browse/MAV-1563)

Add ability to override today's date 

---

spec/lib/academic_year_spec.rb
terraform/app/variables.tf

Initially I set this to `null`, but this causes an error when running Terraform. Instead we can default this to an empty string, and the code will only try to parse the value if it's not blank.
Failed run: https://github.com/nhsuk/manage-vaccinations-in-schools/actions/runs/16564031087/job/46841865740
```
│ Error: Invalid combination of arguments
│ 
│   with aws_ssm_parameter.environment_config["MAVIS__ACADEMIC_YEAR_TODAY_OVERRIDE"],
│   on ssm_parameters.tf line 1, in resource "aws_ssm_parameter" "environment_config":
│    1: resource "aws_ssm_parameter" "environment_config" {
│ 
│ "value_wo": one of `insecure_value,value,value_wo` must be specified
╵
╷
│ Error: Invalid combination of arguments
│ 
│   with aws_ssm_parameter.environment_config["MAVIS__ACADEMIC_YEAR_TODAY_OVERRIDE"],
│ …
```

Set `academic_year_today_override` to an empty string

---

app/lib/academic_year.rb
spec/lib/academic_year_spec.rb
terraform/app/variables.tf

It turns out a blank string is not a valid parameter store value, so we need to set it to a specific value which is understood to mean unset.
We can't remove this variable while it's unused because we need to be able to change it dynamically, and therefore it needs to exist.
Follows on from #4088 
```
│ Error: creating SSM Parameter (/qa/env/MAVIS__ACADEMIC_YEAR_TODAY_OVERRIDE): operation error SSM: PutParameter, https response error StatusCode: 400, RequestID: c71334cc-0527-4396-9083-457b61c60c83, api error ValidationException: 1 validation error detected: Value at 'value' failed to satisfy constraint: Member must have length greater than or equal to 1
```

Set `academic_year_today_override` to `nil`

---

app/models/patient.rb
app/models/school_move.rb
spec/controllers/api/organisations_controller_spec.rb
spec/features/import_child_records_spec.rb
spec/models/cohort_import_spec.rb
spec/models/school_move_spec.rb

In fe664a976ea1383d0be6d0cf712ac7b7a0a4340d the unscheduled session factory was changed to create multiple sessions per programme group. This means that the same school location might have multiple sessions per academic year and organisation.
To support this we need to ensure that when moving patients between schools, the patients are added to any school sessions at the school, and not just the first one (which is what happens currently).
[Jira Issue - MAV-1293](https://nhsd-jira.digital.nhs.uk/browse/MAV-1293)

Add patients to multiple school sessions

---

app/components/app_programme_stats_component.rb
app/controllers/programmes/overview_controller.rb
app/controllers/programmes/patients_controller.rb
app/forms/patient_search_form.rb
app/models/note.rb
app/models/patient.rb
app/models/patient_session.rb
app/models/session.rb
app/views/programmes/index.html.erb
lib/generate/triages.rb
lib/generate/vaccination_records.rb
spec/controllers/api/organisations_controller_spec.rb
spec/features/import_child_records_spec.rb
spec/forms/patient_search_form_spec.rb
spec/models/cohort_import_spec.rb
spec/models/patient_session_spec.rb
spec/models/patient_spec.rb

This makes a number of improvements to the `in_programmes` scopes on the `Patient` and `PatientSession` models:
- The `PatientSession` scope no longer needs an academic year. This is because the academic year can come from the associated session. This prevents the scope being used for a different academic year to the session which could cause unusual bugs.
- The logic of the `PatientSession` scope has been fixed to ensure that patients who are eligible for a programme based on their year group, but not eligible in a particular session (perhaps because the year groups aren't administered at the location), don't appear in the query. This fixes the possibility of a patient appearing incorrectly if they go to a school, but aren't eligible for any of the programmes administered at the school. …

Clarify `in_programmes` scope on patients and patient sessions

---

.github/workflows/data-replication-pipeline.yml
terraform/data_replication/outputs.tf

The ECS service ignored task definition changes and must be explicitly redeployed to run with the updated task definition. 
This wasn't an issue earlier when the old infrastructure was recreated from scratch during every deployment
Also, fix an issue regarding fetching the db_secret_arn. It must always be fetched, regardless of whether the DB got redeployed or not

Fix data replication workflow

---

app/views/sessions/record/batch.html.erb

It used to have `.downcase` as part of the text in the UI:

Fix the text in the "Select a default batch" header

---

config/locales/en.yml
spec/features/verbal_consent_given_spec.rb

This fixes the confirmation labels shown as part of the verbal consent journey to match the designs in the prototype. Specifically the `DraftConsent` model was missing locale strings for the `response` attribute.
[Jira Issue - MAV-1693](https://nhsd-jira.digital.nhs.uk/browse/MAV-1693)

Fix content of verbal consent labels

---

app/lib/mavis_cli/organisations/create_sessions.rb

Move academic year default from argument definition to call method to ensure Rails is loaded before accessing AcademicYear model

Remove academic year default assignment in CreateSession CLI command

---

app/components/app_hosting_environment_component.rb
app/controllers/application_controller.rb
app/lib/hosting_environment.rb
app/views/layouts/application.html.erb
spec/lib/hosting_environment_spec.rb

If I’ve got this right, this means that we can correctly set a `theme-color` of NHS brand blue (`#005eb8`) on the production environment, otherwise the `theme-color` will share that of the banner at the top of the page.

Add `theme-color` meta tag, adapt based on hosting environment

---

app/views/vaccines/index.html.erb

Currently long batch names cause the table to look weird. This was not really an issue as we do not have batch names over length 6 on prod. Regardless, a ticket was opened and so here is a fix.
Using this class, batch names are now allowed to wrap inside of the name, allowing the table with to remain limited.
See also https://github.com/nhsuk/manage-vaccinations-in-schools/pull/3652, which is this same PR but from before I had access to the repo.
[Jira Issue - MAV-1240](https://nhsd-jira.digital.nhs.uk/browse/MAV-1240)

Fix long batch name

---

config/locales/devise.en.yml

Mainly because the capitalisation and full stop in ‘Invalid Email or password.’ has been making my eyes twitch. Also replaces ‘sign in’ with ‘log in’ to be consistent with the wording we use throughout the service.
Very much 💅🤏

Update Devise localisation strings

---

app/helpers/locations_helper.rb
app/views/draft_class_imports/session.html.erb
app/views/parent_interface/consent_forms/edit/school.html.erb

When schools have the same name, the autocomplete controller only finds the first match with the name and renders all other options with the same name as a duplicate of the first. This means the user will not be able to see or select the other options. Making the option names uniqe (e.g. by adding the URN) ensures all the options render and can be selected. We only add the URN for SAIS view and postcode for parent view when schools have the same name, not for all schools.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1131

Add URN/postcode to school options drop down

---

app/models/session.rb

This is not being used anywhere and in fact should have been removed in 44027aaa7a81efed1a513ba1aa9e69ceda2cfae4 so this can be safely removed.

Remove `Session#today` scope

---

app/models/immunisation_import_row.rb
spec/models/immunisation_import_row_spec.rb

This ensures that the validation check on the clinic name is not case sensitive when importing vaccination records for community clinics.
This replaces #3664 as that was raised from a fork.
[Jira Issue - MAV-691](https://nhsd-jira.digital.nhs.uk/browse/MAV-691)

Remove case sensitivity in validation check of clinic name

---

app/controllers/programmes_controller.rb
app/models/programme.rb
app/views/programmes/index.html.erb
spec/lib/fhir_mapper/vaccination_record_spec.rb

When viewing the list of programmes this removes the column displaying the vaccines administered in the programme to match the latest designs in the prototype.

Remove "Vaccines administered" column

---

app/models/consent.rb
app/models/draft_consent.rb
app/views/draft_consents/reason.html.erb
spec/features/verbal_consent_given_spec.rb
spec/features/verbal_consent_refused_spec.rb

When a nurse records a consent response, if the parent is refusing a flu vaccine, one of the options needs to be because it contains gelatine.
This option already appears on the parent journey.
[Jira Issue - MAV-1696](https://nhsd-jira.digital.nhs.uk/browse/MAV-1696)

Ensure gelatine is a refusal option

---

app/controllers/sessions/invite_to_clinic_controller.rb
app/forms/patient_search_form.rb
app/models/class_import.rb
app/models/consent_form.rb
app/models/onboarding.rb
app/models/organisation.rb
app/models/patient.rb
app/models/patient_import_row.rb
app/models/patient_session.rb
app/models/school_move.rb
app/models/session.rb
db/seeds.rb
lib/core_ext/integer/year_group.rb
lib/tasks/performance.rake
spec/factories/patients.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/manage_clinic_sessions_spec.rb
spec/features/manage_school_sessions_spec.rb
spec/features/programme_cohorts_spec.rb
spec/lib/reports/offline_session_exporter_spec.rb
spec/models/class_import_spec.rb
spec/models/cohort_import_spec.rb
spec/models/school_move_spec.rb
spec/models/vaccination_record_spec.rb

When importing patient records this ensures that the year group is determined using the pending academic year. This means that during the preparation period for the upcoming academic year, patients can be imported using the year group they will be rather than their current year group.
In making this change I've been able to make the `academic_year` argument on the `to_year_group` and `to_birth_academic_year` methods a required argument, ensuring we're more deliberate about which academic year we're using.

Import patients in to pending year group

---

app/views/draft_class_imports/location.html.erb

For consistency reasons, it was decided that displaying the URN for all school options (for class import flow) in the dropdown is better, rather than just for schools with the same name.
This also enables users to search by URN.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1131

Display URN for all school options

---

app/forms/patient_search_form.rb
app/models/patient_session.rb
app/views/programmes/index.html.erb
spec/features/import_child_records_spec.rb
spec/models/patient_session_spec.rb
spec/models/patient_spec.rb

This fixes a bug where patients would appear in the wrong programmes for their year groups. The reason this was happening is because the resulting SQL query generated was incorrect:
- `PatientSession#appear_in_programmes` scope joined on the patients.
- `Patient#appear_in_programmes` scope used the scope on `PatientSession` but it also did a `where("patient_id = patients.id")`.
- Due to these to facts, in the resulting SQL, the `patient_id` was referring to `patient_sessions.id` and so was `patients.id` (due to the join), meaning it would also be `true`.
Therefore, this scope would only work if there was only 1 patient. If not, any patient sessions for any other patients would be caught in the `EXISTS`.
To fix this I've taken the joins out of the `appear_in_programmes` scope and it's …

Fix issue with incorrect patients appearing in programmes

---

app/components/app_session_card_component.rb
spec/components/app_session_card_component_spec.rb

When displaying a session card, the dates should be shown on one line to match the designs in the prototype. Specifically, this means that if there are no dates some static content is shown, and otherwise the first and last date is shown with a hyphen between them.

Improve rendering of session dates

---

app/forms/session_search_form.rb
app/models/location.rb
app/models/session.rb
spec/models/session_spec.rb

This improves the ordering of sessions on the new sessions page. Specifically, when you search for a location by name this ensures that the results are ordered by the closest match, and if not searching by name then the sessions are ordered by date with the next closest sessions appearing at the top of the results.
[Jira Issue - MAV-1703](https://nhsd-jira.digital.nhs.uk/browse/MAV-1703)

Improve session ordering

---

app/controllers/programmes/base_controller.rb
app/controllers/programmes/patients_controller.rb
spec/features/import_child_records_spec.rb

In aebbe50364e78c826b410f4fb7f521d4853ff1b8 we attempted to fix the issue of duplicate patients being shown by using a `distinct` on the scope. This works, but it causes issues if we want to start ordering or grouping the patients.
Specifically, when using `DISTINCT` or `DISTINCT ON`, anything in the `ORDER BY` needs to be included, and this makes it tricky to use as you need to know before applying the ordering, what columns to select.
Instead, we can use a subquery to achieve the same result while avoiding the issues around using `DISTINCT`.
This also fixes a bug where you can't search for children on the programmes view.
[Sentry Issue](https://good-machine.sentry.io/issues/6782169105/)

Refactor how distinct patients are determined

---

app/controllers/draft_class_imports_controller.rb
app/views/class_imports/new.html.erb
spec/features/import_class_lists_spec.rb

This ensures that when displaying the class import for a school, we only include year groups where programmes are administered at the school. Specifically, this ensures that users won't see year groups that are taught at the school, but not administered by any programmes.

Restrict which year groups are shown 

---

app/controllers/parent_interface/consent_forms/base_controller.rb

At the moment we decide whether to show the navigation bar based on whether the user is signed in or not. Normally, when a parent fills in the consent journey they're not signed in so they won't see the navigation bar. However, if a nurse clicks on the link to view the parent consent journey then the navigation bar is shown and it currently doesn't render correctly as it has some missing CSS.

Hide navigation bar in parent consent journey

---

app/models/immunisation_import_row.rb
spec/features/hpv_vaccination_offline_spec.rb

This updates the immunisation import process to ensure that when importing details for a vaccination record that already exists, we use the `patient_id` as the value rather than the `patient` object. This ensures that the resulting pending changes can be saved successfully as it contains a single value rather than a hash of the patient.
Although we anticipate this structure will change soon with the PDS improvements, we saw an unhandled error occur in the test environment so this puts in a fix for the issue.
[Sentry Issue](https://good-machine.sentry.io/issues/6784604544/)

Use `patient_id` when staging vaccination record changes

---

app/components/app_count_component.rb
app/components/app_header_navigation_item_component.rb
app/components/app_imports_navigation_component.rb
app/helpers/imports_helper.rb
app/policies/vaccination_record_policy.rb
app/views/layouts/_header.html.erb
spec/features/import_child_records_spec.rb
spec/features/import_child_records_with_duplicates_spec.rb
spec/features/import_vaccination_records_with_duplicates_spec.rb
spec/features/manage_children_spec.rb

This updates the "Import" header item to show the count of the number of import issues rather than the count of the number of imports. This was actually supposed to be the case originally but it was built incorrectly.
I've implemented this by using a helper method since we need this number to be accessible in both the import issues navigation item and the global header item. A helper means it's available to every page.
It's a little awkward to test the helper on its own as it relies on the use of `policy_scope`, so instead test coverage is provided by the feature tests.
[Jira Issue - MAV-1695](https://nhsd-jira.digital.nhs.uk/browse/MAV-1695)

Show import issues count on header item

---

app/lib/nhs/immunisations_api.rb

This logic was checking `is_recorded` inside a block where `is_recorded` is already `true`, and therefore it was unnecessary to make those checks. Instead this can be simplified while ensuring the same result is given before and after.

Simplify logic for next immunisations API action

---

app/jobs/patients_refused_consent_already_vaccinated_job.rb
app/models/vaccination_record.rb
config/cron_jobs.rb
spec/jobs/patients_refused_consent_already_vaccinated_job_spec.rb
spec/models/vaccination_record_spec.rb

If the parents responded to consent during an academic year and indicated that the patient was already vaccinated, provided that the academic year has come to an end, we should be recording these as vaccination records to ensure that the patient doesn't get asked for consent again next year.
To implement this I've created a job which only runs during the preparation period before an academic year starts.
[Jira Issue - MAV-1517](https://nhsd-jira.digital.nhs.uk/browse/MAV-1517)

Record already had vaccinations from consent response

---

app/lib/mavis_cli/clinics/add_to_team.rb
app/lib/mavis_cli/schools/add_to_team.rb
app/lib/mavis_cli/teams/add_programme.rb
app/models/immunisation_import_row.rb
docs/disaster-recovery.md
docs/ops-tasks.md
docs/rake-tasks.md
lib/tasks/onboard.rake
lib/tasks/subteams.rake
lib/tasks/teams.rake
spec/lib/reports/school_moves_exporter_spec.rb
spec/models/location_spec.rb

This fixes a number of typos where the phrase "an team" is used. This happened when team was renamed from organisation.

Fix "an team" typos

---

app/components/app_vaccination_record_summary_component.rb

Before, the Imms API sync status was visible in production, which was confusing for users. Now it won't show until the feature flag is enabled.
[MAV-1709](https://nhsd-jira.digital.nhs.uk/browse/MAV-1709)

Put imms API sync status behind feature flag

---

app/components/app_programme_session_table_component.rb
app/components/app_session_actions_component.rb
app/components/app_session_details_summary_component.rb
spec/components/app_programme_session_table_component_spec.rb
spec/components/app_session_actions_component_spec.rb
spec/components/app_session_details_summary_component_spec.rb

This follows on from 830467ea55b97b411669e25c5fb760b0494b21bf and applies the same filtering in a number of other places which were missed in the original commit.
Without this filtering we can end up with percentages higher than 100% which is incorrect.
[Jira Issue - MAV-1520](https://nhsd-jira.digital.nhs.uk/browse/MAV-1520)

Continue to fix session cohort stats

---

app/components/app_activity_log_component.rb
spec/components/app_activity_log_component_spec.rb

This achieves two things. First, the academic year rollover date should not be hard-coded so we get rid of that, second  it means that this now works with the date override which can be performed on AcademicYear.

fix: use AcademicYear.current rather than Date.current

---

terraform/app/env/qa.tfvars

Reverts nhsuk/manage-vaccinations-in-schools#4127
We can enable the regression tests in QA after https://nhsd-jira.digital.nhs.uk/browse/MAV-1700 is built.

Revert "Delay preparation period in QA"

---

lib/tasks/archive_moved_out_of_cohort_patients.rake

These have now been renamed to `Team` and so we need to do the same in this temporary Rake task.

Fix incorrect reference to organisations

---

app/views/patients/show.html.erb

This was accidentally rebased incorrectly and the tags ended up the wrong way around in the ERB leading to the patient page looking incorrect.
This wasn't spotted by any tests because the content was here, just visually it looked all wrong.

Fix patient show page layout

---

app/models/patient_import_row.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

This ensures that when a patient has a date of death, they are not added to any upcoming sessions.
[Jira Issue - MAV-1228](https://nhsd-jira.digital.nhs.uk/browse/MAV-1228)

Don't add deceased patients to sessions

---

app/components/app_consent_summary_component.rb
app/views/draft_consents/confirm.html.erb
spec/components/app_consent_summary_component_spec.rb
spec/features/self_consent_spec.rb
spec/features/verbal_consent_given_spec.rb
spec/features/verbal_consent_refused_personal_choice_spec.rb

If a child self-consents, we ask them if they would like their parents to receive confirmation of their vaccination. Until 4f87a86ece6fdc0155abb482ca49fbb6e7547232 we weren't able to show this as it wasn't being stored in the database, but we can now show this information to the users when they view a consent response.
[Jira Issue - MAV-1708](https://nhsd-jira.digital.nhs.uk/browse/MAV-1708)

Show `notify_parents_on_vaccination` on confirmation

---

app/controllers/patients/archive_controller.rb
app/forms/patient_search_form.rb
app/views/patients/_header.html.erb
app/views/patients/log.html.erb
app/views/patients/show.html.erb
spec/features/archive_children_spec.rb
spec/forms/patient_search_form_spec.rb

This fixes a couple of design issues that were missed in #4120. See individual commits for more details.
[Jira Issue - MAV-1506](https://nhsd-jira.digital.nhs.uk/browse/MAV-1506)

Small changes to archive design

---

app/jobs/sync_vaccination_record_to_nhs_job.rb
app/lib/nhs/immunisations_api.rb

Adds log messages when we make a request to the immunisations API, and also adds job and transaction identifiers to the logs and Sentry payloads.
Jira-Issue: MAV-1719

Log requests to immunisations API

---

app/lib/patient_merger.rb
spec/lib/patient_merger_spec.rb

When merging two patients we need to make sure that any discarded vaccination records are also merged correctly, without this the user sees an unhandled error.
[Jira Issue - MAV-1718](https://nhsd-jira.digital.nhs.uk/browse/MAV-1718)

Handle discarded vaccination records on merge

---

app/models/patient.rb
spec/models/patient_spec.rb

In https://github.com/nhsuk/manage-vaccinations-in-schools/pull/4175 we made it so that the year group is hidden for some patients. This was supposed to apply for the pending academic year, not the current one. The idea is that during the preparation period, you would be looking at patients who are due to age out at the start of next academic year, and for those patients the year group is hidden.
[Jira Issue - MAV-1512](https://nhsd-jira.digital.nhs.uk/browse/MAV-1512)

Show year group according to pending academic year

---

app/models/patient_import.rb
app/models/patient_import_row.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

When an archived patient is re-imported, we should unarchive them. This was added in to the school moves in
b35cc281ea7e813f5525ee4d52f1a17049fab6ba however, we didn't handle the case where a school move wouldn't be created.
If a patient is archived, and they're being re-imported exactly as they were (same school, etc) we don't create a school move. This results in them not being unarchived.
Instead, we can ensure that a school move is created if the patient is already archived.
I haven't written a feature test for this scenario as it's being covered by the regression tests.
[Jira Issue - MAV-1506](https://nhsd-jira.digital.nhs.uk/browse/MAV-1506)

Ensure patients are unarchived

---

app/lib/nhs/immunisations_api.rb
app/models/patient.rb
spec/features/patient_invalidation_spec.rb
spec/lib/nhs/immunisations_api_spec.rb
spec/models/patient_spec.rb
spec/support/pds_helper.rb

This will prevent the vaccination records from being sent in the first place, and also trigger a sync whenever `Patient.validated_at` is edited
[MAV-1720](https://nhsd-jira.digital.nhs.uk/browse/MAV-1720)

Prevent invalidated patients' records from being sent to the Imms API

---

lib/generate/cohort_imports.rb
spec/lib/generate/cohort_imports_spec.rb

PR #4095 made a change to the `Generate::CohortImports` class, but it was merged in without rebasing, and therefore I wasn't aware that the change broke some tests that were subsequently added.

Fix tests following independent merges

---

app/components/app_activity_log_component.rb
spec/components/app_activity_log_component_spec.rb

This implements [MAV-1711](https://nhsd-jira.digital.nhs.uk/browse/MAV-1711) and follows up on [PR-4053]( https://github.com/nhsuk/manage-vaccinations-in-schools/pull/4053)

Show expired flu consents in activity log

---

app/controllers/patients_controller.rb
app/controllers/sessions/invite_to_clinic_controller.rb
app/jobs/enqueue_clinic_session_invitations_job.rb
app/jobs/send_clinic_initial_invitations_job.rb
app/jobs/send_clinic_subsequent_invitations_job.rb
app/lib/clinic_patient_sessions_factory.rb
app/lib/location_sessions_factory.rb
app/models/consent_form.rb
app/models/patient.rb
app/models/school_move.rb
app/models/team.rb
app/views/patients/show.html.erb
config/routes.rb
spec/controllers/api/testing/teams_controller_spec.rb
spec/features/access_log_spec.rb
spec/features/archive_children_spec.rb
spec/features/delete_vaccination_record_spec.rb
spec/features/edit_parent_spec.rb
spec/features/edit_vaccination_record_spec.rb
spec/features/manage_children_spec.rb
spec/features/manage_school_sessions_spec.rb
spec/features/parent_relationships_spec.rb
spec/features/parental_consent_manual_matching_spec.rb
spec/jobs/enqueue_clinic_session_invitations_job_spec.rb
spec/jobs/send_clinic_initial_invitations_job_spec.rb
spec/lib/location_sessions_factory_spec.rb
spec/models/cohort_import_spec.rb
spec/models/school_move_spec.rb

This updates the logic around school moves to not add patients in to the community clinic if they're assigned to a school. This is to reduce the number of patients who will exist in the community clinic session, to make it more useable, especially when it comes to flu where the total number of patients is high.
At the same time a button has been added that allows patients to be added individually to community clinics.
[Jira Issue - MAV-278](https://nhsd-jira.digital.nhs.uk/browse/MAV-278)
[Jira Issue - MAV-1430](https://nhsd-jira.digital.nhs.uk/browse/MAV-1430)

Don't add school patients to community clinic

---

app/policies/session_attendance_policy.rb
spec/policies/session_attendance_policy_spec.rb

This ensures that when a patient is previously vaccinated for one of the programmes, they will at least have the buttons visible to record attendance in the current session.
[Jira Issue - MAV-1746](https://nhsd-jira.digital.nhs.uk/browse/MAV-1746)

Ensure register attendance buttons show correctly

---

app/components/app_patient_summary_component.rb
app/components/app_session_actions_component.rb
app/components/app_session_needs_review_warning_component.rb
app/views/sessions/consent/show.html.erb
app/views/sessions/patients/show.html.erb
app/views/sessions/record/show.html.erb
app/views/sessions/register/show.html.erb
app/views/sessions/triage/show.html.erb
config/locales/en.yml
spec/components/app_patient_summary_component_spec.rb
spec/components/app_session_actions_component_spec.rb
spec/components/app_session_needs_review_warning_component_spec.rb
spec/features/filter_state_persistence_spec.rb

This is [MAV-1604](https://nhsd-jira.digital.nhs.uk/browse/MAV-1604). This warning is desired now as without NHS numbers, we cannot use the imms api to automatically check that the child has not already been vaccinated. The PR also resolves [MAV-1748](https://nhsd-jira.digital.nhs.uk/browse/MAV-1748) by updating the session overview page to be like in the prototype.

Show notice in session if any patients are missing NHS number

---

terraform/app/env/qa.tfvars

This reverts commit 38008089df0951a3ddfb7331e1210a66fb70891e.
We've finished testing QA with the preparation period off so we can re-enable it now.

Revert "Turn off preparation period in QA"

---

terraform/app/env/production.tfvars

We'd like the preparation period to be enabled on the 18th August as it's now ready for teams to use in production.
[Jira Issue - MAV-1725](https://nhsd-jira.digital.nhs.uk/browse/MAV-1725)

Enable preparation period from 18th August

---

app/policies/patient_policy.rb
app/policies/vaccination_record_policy.rb
spec/policies/patient_policy_spec.rb
spec/policies/vaccination_record_policy_spec.rb

At the moment if a patient is vaccinated by one team, and there's another team in the same organisation, they will be shown the patient because it's vaccination record has the same ODS code.
Instead, for a non-historical vaccination, we shouldn't be looking at the ODS code, instead we should be looking at the team that's attached to the session.
[Jira Issue - MAV-1280](https://nhsd-jira.digital.nhs.uk/browse/MAV-1280)

Hide patients vaccinated by the same organisation but different team

---

app/jobs/patients_aged_out_of_school_job.rb
spec/jobs/patients_aged_out_of_school_job_spec.rb

This fixes a bug where patients who have aged out of their school aren't added to the community clinic when the nightly job runs, meaning they're left in a state where they exist but don't belong to any sessions, resulting in the patient being in a strange state.

Ensure aged out patients are added to community clinic

---

app/forms/session_search_form.rb
spec/features/td_ipv_already_had_spec.rb
spec/features/triage_delay_vaccination_spec.rb
spec/forms/session_search_form_spec.rb

When viewing the sessions during the preparation period, we should default to the upcoming sessions rather than the current ones.

Default session form academic year to pending

---

app/models/concerns/request_session_persistable.rb
spec/models/concerns/request_session_persistable_spec.rb

This ensures that when creating an instance of a `RequestSessionPersistable` model, if there are unknown keys in the session data these get ignored rather than the current behaviour where an exception is raised.
This allows us to migrate attributes in these models without needing users to sign out and clear their browser session data, instead any old values will simply be ignored.

Handle unknown session keys

---

app/controllers/concerns/authentication_concern.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/forms/select_team_form.rb
app/models/cis2_info.rb
app/views/users/errors/workgroup_not_found.html.erb
spec/factories/users.rb
spec/features/user_cis2_authentication_from_redirect_spec.rb
spec/features/user_cis2_authentication_from_start_page_spec.rb
spec/features/user_cis2_authentication_with_empty_role_spec.rb
spec/features/user_cis2_authentication_with_wrong_organisation_spec.rb
spec/features/user_cis2_authentication_with_wrong_role_spec.rb
spec/features/user_cis2_authentication_with_wrong_workgroup_spec.rb
spec/support/cis2_auth_helper.rb

This allows users to sign in to any team that's part of an organisation, even if they're not part of the workgroup for that team.
This is necessary to allow release 2.17 to be deployed even if the SAIS teams haven't yet updated their CIS2 workgroups. This change will need to be reverted in 2.18.

Allow signing in without a team workgroup

---

app/lib/mavis_cli/gias/download.rb

Without this the script seems to fail with a forbidden HTTP status code.
```
/usr/local/bundle/ruby/3.4.0/gems/mechanize-2.14.0/lib/mechanize/http/agent.rb:340:in 'Mechanize::HTTP::Agent#fetch': 403 => Net::HTTPForbidden for https://get-information-schools.service.gov.uk/Downloads -- unhandled response (Mechanize::ResponseCodeError)
```

Spoof user agent when downloading GIAS data

---

app/helpers/consents_helper.rb
app/helpers/triages_helper.rb

In terms of the vaccination journey, green is reserved the final programme outcome, with all other intermediate success states using aqua-green.
Because there is no `aqua-green` tag colour in GOV.UK Frontend but there is in NHS.UK frontend, we can’t use the `colour` param on `govuk_tag` and instead have to supply the (correct) colour as an explicit class.

Ensure triage and consent tags use the correct status colour

---

Dockerfile

This is needed to support the GIAS download command which gets the latest school data from GIAS so it can be imported.

Allow writing to db/data

---

app/lib/team_migration/base.rb

This moves the log line that is displayed when adding additional flu year groups to a school to make it clear when this is happening. Currently the log entry prints always, whereas it should only print it when it happens.

Move logging line in to correct place

---

app/models/concerns/csv_importable.rb
spec/features/import_child_pds_lookup_extravaganza_spec.rb

This is being triggered for immunisations imports as well as patient imports. We also want to disable this for the next release so that we can say with 100% certainty the new code paths won't be triggered.

Disable PDS update during import completely

---

app/lib/reports/systm_one_exporter.rb
spec/factories/vaccination_records.rb
spec/lib/reports/systm_one_exporter_spec.rb

In the SystmOne exporter. This situation can occur if a vaccination is recorded in the community clinic, where the `location` will be `nil`, and the `location_name` will be set instead.
This change was made in aae7b838a035e4d7124b95c80702f29a1a1fd1f9, previously vaccination records in the generic clinic would have a location of the generic clinic, but we want to move to a world where the location is the specific community clinic where the record took place.
This error was spotted by the regression tests and fixes this Sentry error: https://good-machine.sentry.io/issues/6818602795/

Handle `nil` vaccination record location

---

app/models/class_imports_patient.rb
app/models/cohort_imports_patient.rb
app/models/session.rb
db/migrate/20250820145646_add_delegation_to_sessions.rb
db/schema.rb
spec/factories/patient_changesets.rb
spec/factories/sessions.rb
spec/models/session_spec.rb

As part of the delegation work, sessions will need a boolean field to determine if the session is using the PSD protocol or national protocol. PSD or Patient Specific Direction is the protocol that allows healthcare workers to administer nasal vaccines without having the necessary qualifications as a nurse.
Setting the default value to false until the full delegation feature is ready to go live.

Add delegation columns to sessions

---

app/controllers/concerns/authentication_concern.rb
app/models/cis2_info.rb
app/models/user.rb
app/policies/gillick_assessment_policy.rb
app/policies/triage_policy.rb
app/policies/vaccination_record_policy.rb
spec/models/user_spec.rb

Renaming this method because it makes it clearer that nurses prescribe PSDs for vaccines (nasal only atm) or can supply injection vaccines to healthcare workers using a PGD (Patient Group Direction).

Rename CIS2Info#can_prescribe_pgd? to can_supply_using_pgd?

---

spec/factories/organisations.rb
spec/factories/teams.rb

This refactors the team and organisation test factory to share the same ODS code sequence generator, ensuring that they can never generate the same ODS code, leading to test failures due to unique constraints on the `ods_code` column.
Specifically, this fixes the flaky tests in `programme_vaccinations_exporter_spec.rb` where they will fail occasionally due to an ODS code already existing when the organisation is created.

Use global ODS code sequence in tests

---

app/controllers/api/reporting/base_controller.rb
app/controllers/api/reporting/one_time_tokens_controller.rb
app/controllers/api/reporting/totals_controller.rb
app/controllers/concerns/authentication_concern.rb
app/controllers/users/teams_controller.rb
config/feature_flags.yml
config/routes.rb
config/settings.yml
config/settings/test.yml
spec/controllers/api/reporting/one_time_tokens_controller_spec.rb
spec/controllers/api/reporting/totals_controller_spec.rb

These controllers are disabled by default, through the `:reporting_api` feature flag.
As an extra safeguard against accidental enablement, for now they are also only routable on non-production environments, regardless of the feature flag settings.
**Do Not Merge Yet** - as this adds API endpoints, we need this to be tested and allocated to a release before merging.
Jira-Issue: MAV-1784

Add /api/reporting controllers, config and tests

---

app/assets/stylesheets/components/_summary-list.scss
app/helpers/parents_helper.rb
app/views/consent_forms/search.html.erb

When matching consent responses, it would be useful to see the submitted parent email, as a way to double check it is not a spoof parent, by comparing to details stored on patient in Mavis.
This allows us to send consent warning emails to non-matching parents, only where the consent form has _not_ been manually matched to the child. See [MAV-1717](https://nhsd-jira.digital.nhs.uk/browse/MAV-1717).
https://nhsd-jira.digital.nhs.uk/browse/MAV-1782

Add parent details to consent summary

---

app/jobs/commit_patient_changesets_job.rb
app/jobs/patient_nhs_number_lookup_job.rb
app/jobs/process_patient_changesets_job.rb
app/models/class_import.rb
app/models/class_imports_patient.rb
app/models/cohort_import.rb
app/models/cohort_imports_patient.rb
app/models/patient.rb
app/models/patient_changeset.rb
app/models/pds/patient.rb
app/models/pds_search_result.rb
db/migrate/20250815205653_create_pds_search_results.rb
db/schema.rb
spec/factories/patient_changesets.rb
spec/features/import_child_pds_lookup_extravaganza_spec.rb
spec/features/import_child_records_preparation_spec.rb
spec/features/import_child_records_spec.rb
spec/features/import_child_records_with_duplicates_spec.rb
spec/features/import_child_records_with_twins_spec.rb
spec/features/import_class_lists_move_spec.rb
spec/features/import_class_lists_spec.rb
spec/features/import_class_lists_with_duplicates_spec.rb
spec/jobs/patient_nhs_number_lookup_job_spec.rb
spec/jobs/process_patient_changesets_job_spec.rb
spec/models/patient_changeset_spec.rb
spec/support/pds_helper.rb

This implements the "cascading" search in MAV-1415. In the event an NHS number isn't found
through our default search, we try different PDS search options and return any unique NHS number we find.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1415

Multiple PDS searches during import

---

app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/sessions_controller.rb
app/models/user.rb
config/initializers/inflections.rb
db/migrate/20250822094829_add_show_in_suppliers_to_users.rb
db/schema.rb
spec/factories/users.rb
spec/features/user_cis2_authentication_from_redirect_spec.rb
spec/features/user_cis2_authentication_spec.rb
spec/features/user_cis2_authentication_with_wrong_organisation_spec.rb
spec/models/patient_changeset_spec.rb
spec/models/user_spec.rb

This adds a new column to the users table which we can use to track which users should appear in the list of suppliers that healthcare assistances can choose from when they administer a nasal flu vaccine.
This is effectively the same as whether or not the user is a nurse, but I've decided to not name this column `is_nurse` for two reasons:
- To avoid confusing with the `nurse` `fallback_role` which is only used in non-CIS2 environments.
- To allow for flexibility in the future in case a new role type is added that can also supply a PGD vaccine to healthcare assistants.
Our users log in using CIS2, and it's only at the point of logging in do we know what permissions a user has, so at that point we will update the this value for them. For non-CIS2 environments, we could in theory rely on …

Track which users should be shown in list of suppliers

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_vaccine-method.scss
app/components/app_patient_session_record_component.rb
app/components/app_patient_session_search_result_card_component.rb

Bringing this back to life now that v3.1 has gone live.
Nurses and Healthcare Assistants (HCAs) found that the "donuts and diamonds" significantly helped them understand what vaccination method (e.g., nasal or injection) was needed for a particular child.
The icon will show up on the "Vaccination method" row and also on the record vaccination page.
[Jira Issue - MAV-1794](https://nhsd-jira.digital.nhs.uk/browse/MAV-1794)
| nasal - donut | injection - diamond |
|------------------|---------------------------|
| <img width="765" height="289" alt="Screenshot 2025-08-18 at 15 12 55" src="https://github.com/user-attachments/assets/37a3f34e-595e-45c7-b693-e26fee108d6c" />  | <img width="747" height="290" alt="Screenshot 2025-08-18 at 15 21 15" …

Add new vaccine icons

---

app/jobs/process_patient_changesets_job.rb
app/models/pds_search_result.rb
spec/jobs/process_patient_changesets_job_spec.rb

Wildcard searches like "Al*" are ineffective, so skip directly to the next search step when given/family names are 3 characters or less.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1415

Skip wildcard searches for names ≤ 3 characters

---

spec/features/parental_consent_school_session_completed_spec.rb
spec/features/triage_then_parental_consent_refused_spec.rb
spec/jobs/send_clinic_subsequent_invitations_job_spec.rb

These tests are currently failing as they all schedule sessions for a week in to the future which falls on the next academic year resulting in a validation failure on the academic year of the session.

Fix tests that fail during preparation period

---

app/jobs/process_patient_changesets_job.rb

This ensures that we handle failures more gracefully, was missing from the error handling added previously.
Here is what the search history looks like now when it encounters an error:
```ruby
[{"step" => "no_fuzzy_with_history", "result" => "no_matches", "nhs_number" => nil},
{"step" => "no_fuzzy_with_wildcard_postcode", "result" => "no_matches", "nhs_number" => nil},
{"step" => "no_fuzzy_with_wildcard_given_name", "result" => "no_matches", "nhs_number" => nil},
{"step" => "no_fuzzy_with_wildcard_family_name", "result" => "no_matches", "nhs_number" => nil},
{"step" => "fuzzy_without_history", "result" => "no_matches", "nhs_number" => nil},
{"step" => "fuzzy_with_history", "result" => "error", "nhs_number" => nil}]],
```
Jira-Issue: …

Finish processing patient changeset on error

---

app/jobs/process_patient_changesets_job.rb
app/models/pds_search_result.rb
spec/features/import_child_pds_lookup_extravaganza_spec.rb
spec/jobs/process_patient_changesets_job_spec.rb

All fuzzy searches always include searching of history (see [the PDS FHIR API documentation](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir#get-/Patient)).
This removes the `fuzzy_without_history` step, merging it in with `fuzzy_with_history`. Has been tested locally, here are what the search results look like when a patient isn't found in PDS:
```ruby
[{"step" => "no_fuzzy_with_history", "result" => "no_matches", "nhs_number" => nil},
{"step" => "no_fuzzy_with_wildcard_postcode", "result" => "no_matches", "nhs_number" => nil},
{"step" => "no_fuzzy_with_wildcard_given_name", "result" => "no_matches", "nhs_number" => nil},
{"step" => "no_fuzzy_with_wildcard_family_name", "result" => "no_matches", "nhs_number" => nil},
{"step" => "fuzzy", "result" => …
```

Remove redundant PDS fuzzy search with history

---

app/jobs/commit_patient_changesets_job.rb
app/models/patient_import.rb

Parents could appear multiple times in memory during import, causing `parents.any?(&:changed?)` to incorrectly return true even when no data had actually changed. This was due to duplicate Parent instances with the same ID being included in the batch.
Ensure we call `.uniq` on parents and relationships before checking for changes to avoid false positives.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1825

Deduplicate parents and relationships before incrementing import counts

---

app/lib/patient_merger.rb
spec/factories/pds_search_results.rb
spec/lib/patient_merger_spec.rb

Without this, if a user tries to merge a patient that has a PDS search result then they will see an error screen saying something went wrong.
[Sentry Issue](https://good-machine.sentry.io/issues/6819259117/)

Ensure patients with PDS search results can be merged

---

app/lib/mavis_cli/vaccination_records/sync.rb
spec/features/cli_vaccination_records_sync_spec.rb

This change adds a check at the beginning of the vaccination records sync command to verify that the `immunisations_fhir_api_integration` feature flag is enabled before initiating the sync operation.
Previously, the command claimed that the sync was successful, even though nothing had happened.

Check flipper before running CLI imms API sync command

---

app/models/programme.rb
app/models/session.rb
db/seeds.rb
spec/models/programme_spec.rb
spec/models/session_spec.rb
spec/support/cis2_auth_helper.rb

This extracts a number of commits related to delegation from #4393 so they can be used in a number of different delegation PRs. This should have no user-facing changes to the service.

Add foundational delegation methods

---

app/lib/apostrophe_normaliser.rb
app/models/patient_import_row.rb
spec/fixtures/cohort_import/invalid_fields.csv
spec/models/cohort_import_row_spec.rb
spec/models/cohort_import_spec.rb

PDS restricts the allowable characters in a patient's name to be alphanumeric, including letters used in European alphabets, and the extra characters '-', '.' and "'". Especially now that we perform PDS updates as a part of the import process, we need to ensure that we follow these same guidelines that PDS uses.
This change adds another validation to the import to ensure we only accept the valid characters PDS accepts. The error message, when triggered, looks like:
It also adds automatic conversion of "fancy quotes" into "plain quotes" as accepted by PDS. Again, see ticket for more details.
See comments on the Jira ticket for more details.
Jira-Issue: MAV-1807

Validate child names on import

---

app/lib/status_updater.rb
app/models/patient_session/registration_status.rb
app/models/session_attendance.rb
spec/models/patient_session/registration_status_spec.rb

This fixes an issue where the `session_attendance` association on the `PatientSession::RegistrationStatus` ends up being attached to the wrong record when pre-loaded. As far as I can tell this appears to be a bug in Rails as I can't see anything wrong with the approach, but the test I've written reproduces the problem. When using `eager_load` the correct association is found, but when using `preload` the criteria for the session attendance to be today's atendance seems to be lost. Having investigated the queries a little, it seems to be due to the fact that the association is through `patient_session`.
The impact of this issue means that if a patient has multiple session attendance records (i.e. they have attended or not attended multiple session dates), then sometimes the status won't …

Fix `session_attendance` association

---

app/controllers/concerns/authentication_concern.rb
app/models/cis2_info.rb
app/models/user.rb
spec/factories/users.rb
spec/models/user_spec.rb

This adds a method to `User` and `CIS2Info` which can be used to determine with a particular user has permission to prescribe a vaccination using either a PSD or the national protocol.
[Jira Issue - MAV-1400](https://nhsd-jira.digital.nhs.uk/browse/MAV-1400)

Add `is_prescriber?`

---

app/models/immunisation_import_row.rb
app/models/vaccination_record.rb
spec/models/vaccination_record_spec.rb

This allows historic records, and records received from the API to leave `protocol = nil`.
Also set imported records' protocol to `nil`.

Make `VaccinationRecord.protocol` optional from imports and API

---

app/components/app_triage_form_component.html.erb
app/components/app_triage_form_component.rb
app/controllers/patient_sessions/triages_controller.rb
app/forms/triage_form.rb
app/models/patient.rb
app/models/patient_session.rb
app/models/patient_specific_direction.rb
app/policies/patient_specific_direction_policy.rb
app/views/patient_sessions/_header.html.erb
config/locales/en.yml
db/migrate/20250827091512_remove_full_dose_from_patient_specific_directions.rb
db/schema.rb
spec/factories/patient_specific_directions.rb
spec/features/triage_spec.rb
spec/forms/triage_form_spec.rb
spec/models/patient_specific_direction_spec.rb
spec/policies/patient_specific_direction_policy_spec.rb

Implements the ability for prescribers (e.g. qualified nurses) to add Patient Specific Directions (PSDs) during the triage process when a child is marked as safe to vaccinate with nasal spray. This feature supports delegation workflows where Healthcare Assistants (HCAs) can administer vaccinations under PSD authority.
[Jira Ticket - MAV-1362](https://nhsd-jira.digital.nhs.uk/browse/MAV-1362)
- Added conditional PSD option when selecting "safe to vaccinate with nasal spray" in triage page
- Only appears when:
- Delegation feature flag is enabled
- User has permission to create PSDs
- PSD functionality is enabled for the session
- Vaccination method is nasal spray
- "PSD added" tag appears on patient page if they have a PSD record
| Choosing to add PSD | Patient page after PSD added | …

Prescribers can create PSD instructions during triage

---

app/jobs/commit_patient_changesets_job.rb
app/jobs/process_patient_changesets_job.rb
spec/jobs/process_patient_changesets_job_spec.rb
spec/models/pds_search_result_spec.rb

Ensures search timestamps are preserved during the import process, rather than defaulting to current time in the final commit job.

Persist `created_at` on PDS search results

---

app/jobs/commit_patient_changesets_job.rb
spec/features/import_child_pds_lookup_extravaganza_spec.rb
spec/fixtures/cohort_import/pds_extravaganza.csv

Ensure patients with blank NHS numbers are also deduplicated by applying `.uniq!` to the patients array. Previously, multiple duplicate patient records without NHS numbers could slip through, leading to conflict errors on import.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1862

deduplicate patients without NHS numbers

---

app/components/app_patient_session_search_result_card_component.rb
spec/components/app_patient_session_search_result_card_component_spec.rb

Fixes issue where donut/diamond icons were incorrectly displayed on consent and triage screens when they should only appear on registration and record vaccination lists.
[Jira Issue - MAV-1849](https://nhsd-jira.digital.nhs.uk/browse/MAV-1849)

Vaccine method icon incorrectly shown on consent and triage screens

---

.github/workflows/data-replication-pipeline.yml
terraform/account/deployment_permissions.tf
terraform/account/resources/iam_policy_DatabaseSnapshotPolicy.json

This adds an option to the data replication workflow to take a new DB snapshot as a base for the data replication environment
Jira-Issue: MAV-1864

On-demand DB snapshot for data replication environment

---

config/initializers/sentry.rb
terraform/app/variables.tf

These environments are used for testing and can often be broken, and by sending errors to Sentry it makes Sentry harder to use for production as it includes lots of noise to filter through.

Disable Sentry in sandbox environments

---

app/controllers/class_imports_controller.rb
app/controllers/cohort_imports_controller.rb
app/controllers/immunisation_imports_controller.rb
app/jobs/process_patient_changesets_job.rb
app/models/concerns/csv_importable.rb
spec/features/e2e_journey_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/import_child_pds_lookup_extravaganza_spec.rb
spec/features/import_child_records_preparation_spec.rb
spec/features/import_child_records_spec.rb
spec/features/import_child_records_with_duplicates_spec.rb
spec/features/import_child_records_with_twins_spec.rb
spec/features/import_class_lists_move_spec.rb
spec/features/import_class_lists_spec.rb
spec/features/import_class_lists_with_duplicates_spec.rb
spec/features/import_vaccination_records_spec.rb
spec/features/import_vaccination_records_with_duplicates_spec.rb
spec/features/triage_partially_vaccinated_spec.rb
spec/jobs/process_patient_changesets_job_spec.rb

With the new background process where PDS checks are performed, we're seeing a problem where if any of the PDS checks fail due to a 429 error, the users see an unexpected error page because we catch the error expecting Sidekiq to re-process it. However, if the user uploads a file that is smaller than 15 rows we currently process it synchronously meaning we can't take advantage of the retry behaviour in the job.
Rather than trying to make the synchronous process work well with retries, it seems simpler to make all imports run in the background, especially since in practice the vast majority of files are larger than 15 rows.

Always run imports in the background

---

app/controllers/draft_vaccination_records_controller.rb
app/controllers/patient_sessions/programmes_controller.rb
app/helpers/address_helper.rb
app/models/draft_vaccination_record.rb
app/views/draft_vaccination_records/location.html.erb
spec/helpers/address_helper_spec.rb

This ensures that when we're recording a vaccination from a community clinic session, we link the location of the community clinic or school using the `location_id` foreign key rather than storing the name of the location in `location_name`. This enables us to have more structured data, including access to various other bits of information on the location.
We still need the `location_name` column to handle importing unknown locations.
[Jira Issue - MAV-550](https://nhsd-jira.digital.nhs.uk/browse/MAV-550)

Set `location_id` on vaccination records in clinic

---

app/components/app_patient_session_record_component.rb
app/components/app_vaccinate_form_component.rb
app/controllers/api/testing/teams_controller.rb
app/controllers/patient_sessions/base_controller.rb
app/controllers/patient_sessions/session_attendances_controller.rb
app/controllers/patient_sessions/vaccinations_controller.rb
app/forms/vaccinate_form.rb
app/lib/patient_merger.rb
app/models/patient.rb
app/models/patient_session.rb
app/models/pre_screening.rb
app/models/session.rb
app/models/session_date.rb
db/migrate/20250821124416_remove_patient_session_from_pre_screenings.rb
db/schema.rb
spec/components/app_activity_log_component_spec.rb
spec/components/app_vaccinate_form_component_spec.rb
spec/controllers/api/testing/teams_controller_spec.rb
spec/factories/pre_screenings.rb
spec/lib/patient_merger_spec.rb
spec/models/pre_screening_spec.rb
spec/models/session_date_spec.rb

This replaces the foreign key association between pre-screenings and patient sessions to instead link directly to the patient and the session (via the date). This is needed as we eventually want to replace the PatientSession model and to do that we need to make sure all foreign keys to it have been replaced.
The functionality should be the same before and after, actually slightly improved as pre-screening is only supposed to exist on the day it happened, so now we link directly to the session date rather than the overall session.
[Jira Issue - MAV-1819](https://nhsd-jira.digital.nhs.uk/browse/MAV-1819)

Replace pre-screening patient session foreign key

---

terraform/monitoring/aws/variables.tf

This PR grants editor access to grafana to the DataReplication SSO group. This is helpful for investigating any potential production issues

Grafana access for DataReplication SSO group

---

app/views/sessions/manage_consent_reminders/show.html.erb
db/seeds.rb
spec/components/app_patient_session_table_component_spec.rb
spec/features/cli_gias_check_import_spec.rb
spec/features/cli_stats_organisations_spec.rb
spec/features/hpv_vaccination_offline_spec.rb
spec/forms/triage_form_spec.rb
spec/lib/reports/careplus_exporter_spec.rb
spec/lib/reports/systm_one_exporter_spec.rb
spec/lib/stats/consents_by_school_spec.rb
spec/lib/status_generator/consent_spec.rb
spec/lib/status_generator/registration_spec.rb
spec/lib/vaccination_notification_criteria_spec.rb
spec/models/draft_vaccination_record_spec.rb
spec/models/immunisation_import_row_spec.rb
spec/models/immunisation_import_spec.rb
spec/models/patient/consent_status_spec.rb
spec/models/patient_session/registration_status_spec.rb
spec/models/pre_screening_spec.rb
spec/models/session_date_spec.rb
spec/policies/session_attendance_policy_spec.rb

This updates a number of tests that are now failing due to the current date being outside the preparation period. Where possible I've tried to avoid freezing time, but in most cases it's necessary to make sure we're always testing inside or outside a preparation period.

Fix tests outside of preparation period

---

db/seeds.rb

This ensures that when creating a session in the seeds, the date fits within the range of suitable dates for the current academic year. This fixes running the tests on the first and last day of the preparation period.
This was missed from #4453.

Ensure seeds don't create session dates outside range

---

app/assets/javascripts/application.js
app/views/layouts/application.html.erb

This is some magic Stimulus surely handled, but in [a post-stimulus world](https://github.com/nhsuk/manage-vaccinations-in-schools/pull/4450) we need to do this ourselves. Phun!

Ensure components are initiated when a page uses Turbo

---

app/lib/reports/systm_one_exporter.rb
spec/lib/reports/systm_one_exporter_spec.rb

When exporting a SystmOne report, if the vaccination record was performed and supplied by two different people (in the case of delegation) then we need to include this information in the report.
[Jira Issue - MAV-1605](https://nhsd-jira.digital.nhs.uk/browse/MAV-1605)

Add prescriber to SystmOne export

---

app/forms/vaccinate_form.rb
app/models/draft_vaccination_record.rb
app/models/session.rb
app/models/vaccination_record.rb
config/locales/en.yml
spec/features/flu_vaccination_hca_national_protocol_spec.rb
spec/models/session_spec.rb

This adds support for healthcase assistants to administer the injected flu vaccine under the national protocol, requiring the session to have the national protocol enabled and for the HCA to specify which nurse supplied to them the vaccine.

Allow HCAs to administer injected flu

---

app/controllers/api/reporting/one_time_tokens_controller.rb
app/controllers/concerns/reporting_api/token_authentication_concern.rb
app/models/reporting_api/one_time_token.rb
spec/controllers/api/reporting/one_time_tokens_controller_spec.rb
spec/controllers/api/reporting/totals_controller_spec.rb
spec/controllers/concerns/reporting_api/token_authentication_concern_spec.rb
spec/models/reporting_api/one_time_token_spec.rb

An 'under the hood' PR which does two things:
1. Moves the JWT-generation methods out of the OneTimeTokens controller, and into the OneTimeToken model.
This is tidier, and also enables a one-liner in the console which is useful when developing locally:
```
> jwt = ReportingAPI::OneTimeToken.find_or_generate_for!(user: User.first, cis2_info: {...}).to_jwt
```
2. Adds a `JWT_SIGNING_ALGORITHM` constant to define the `HS512` algorithm in one place, rather than hard-coding it everywhere

Refactor JWT-generation methods out of ReportingAPI controller and into the model

---

app/components/app_patient_session_triage_component.html.erb
spec/features/triage_spec.rb

If the user is logged in as a role who cannot triage, this updates the content to make it clear that a nurse needs to triage the patient and this is not something the current user can do.

Update content shown in triage section

---

app/models/vaccination_record.rb
db/migrate/20250903153120_make_vaccination_record_patient_id_not_null.rb
db/schema.rb
spec/factories/vaccination_records.rb
spec/models/vaccination_record_spec.rb

Vaccination records will always be associated with a patient so we can make this column not nullable. This is likely a historical oversight, we didn't have `optional: true` specified on the `belongs_to`.

Ensure `patient_id` is not null

---

spec/factories/patients.rb
spec/features/flu_vaccination_hca_national_protocol_spec.rb
spec/features/flu_vaccination_hca_pgd_supply_spec.rb

This test verifies the existing behavior where Healthcare Assistants (HCAs) cannot see patients in the record vaccination tab when:
- National protocol is turned off
- Patients triaged for injection (consented for nasal, with injection as a second option)
This behavior is working as intended - HCAs can only record vaccinations under specific protocols, so hiding patients they cannot treat prevents confusion and maintains proper clinical governance.

Verify that HCA's can't see triaged injected patients when national protocol is off

---

app/views/vaccines/index.html.erb

This fixes a potential issue trying to navigate a double-nested array by using `dig` instead.
[Sentry Issue](https://good-machine.sentry.io/issues/6855749667/)

Use dig for safe nested array navigation

---

app/components/app_activity_log_component.rb
app/views/patient_sessions/_header.html.erb
spec/features/flu_vaccination_hca_psd_spec.rb

On this page we're not in the context of a specific programme so the tag always shows as "PSD not added", instead the users can see the entries in the activity log.
[Jira Issue - MAV-1912](https://nhsd-jira.digital.nhs.uk/browse/MAV-1912)

Hide PSD tags on session activity page

---

app/lib/reports/offline_session_exporter.rb
spec/factories/patient_specific_directions.rb
spec/lib/reports/offline_session_exporter_spec.rb

This ensures that when including in the offline spreadsheet whether or not a patient has a PSD, we ignore any that have been invalidated.
[Jira Issue - MAV-1914](https://nhsd-jira.digital.nhs.uk/browse/MAV-1914)

Ensure invalidated PSDs aren't in offline export

---

app/controllers/api/reporting/one_time_tokens_controller.rb
app/controllers/users/logout_controller.rb
app/views/logout/show.html.erb
config/routes.rb
spec/controllers/api/reporting/one_time_tokens_controller_spec.rb

This will be used to populate the header on the reporting side.
It also adds a `GET /logout` page. This will not be linked to from Mavis, but from the Reporting app, which can't `POST /logout` as it can't generate CSRF tokens.

Return user nav info in reporting token

---

app/jobs/concerns/notify_throttling_concern.rb
app/jobs/email_delivery_job.rb
app/jobs/notify_delivery_job.rb
app/jobs/sms_delivery_job.rb
app/jobs/status_updater_job.rb
config/initializers/sentry.rb
config/initializers/sidekiq.rb
config/settings.yml
config/sidekiq.yml
spec/jobs/email_delivery_job_spec.rb
spec/jobs/sms_delivery_job_spec.rb

This updates the jobs which send emails and text messages to use Sidekiq as part of our general move towards using Sidekiq instead of Good Job. This allows us to get automatic job failure retries and also allows us to enable rate limiting to match GOV.UK Notify's rate limit.

Use Sidekiq for comms and add rate limits

---

config/settings.yml

We're seeing in QA that even if we throttle emails and texts by 3000 requests per minute, we still experience the occasional errors related to rate limiting. Although the jobs now retry so this isn't an operational issue, we want to reduce throttling on our side to avoid this issue.

Reduce GOV.UK Notify rate limit

---

app/controllers/sessions/manage_consent_reminders_controller.rb
app/views/sessions/manage_consent_reminders/show.html.erb
config/locales/en.yml

This slightly changes the logic related to when the button is shown to ensure that it's not shown when the consent is not open. The logic was already close to this, but it would show on the last session day when consent is already closed.
[Jira Issue - MAV-1894](https://nhsd-jira.digital.nhs.uk/browse/MAV-1894)

Hide button to send reminders if not open 

---

app/lib/patient_merger.rb
spec/lib/patient_merger_spec.rb

This fixes an issue where patients with notes cannot be merged as the foreign key constraint prevents the patient from being deleted.
[Sentry Issue](https://good-machine.sentry.io/issues/6859186837/)

Ensure patients with notes can be merged

---

app/components/app_activity_log_component.rb
app/components/app_programme_status_tags_component.rb
app/controllers/sessions/consent_controller.rb
app/forms/patient_search_form.rb
app/models/session.rb
config/locales/status.en.yml
spec/components/app_patient_session_search_result_card_component_spec.rb
spec/components/app_programme_status_tags_component_spec.rb
spec/forms/patient_search_form_spec.rb
spec/models/session_spec.rb

This updates the consent status as shown in the "Consent" tab, so that when consent has been given for the flu programme, it is shown with the chosen vaccine method as a single status rather than currently where the vaccine method is shown in text next to the status. This matches the latest designs in the prototype.
[Jira Issue - MAV-1847](https://nhsd-jira.digital.nhs.uk/browse/MAV-1847)

Combine consent given status and vaccine method

---

app/policies/vaccination_record_policy.rb

- This is guaranteed by forcing a JOIN instead of an IN clause on an indexed column
- In testing this reduces execution time from ca 60s to 1s
JIRA: [MAV-1927](https://nhsd-jira.digital.nhs.uk/browse/MAV-1927)

Improve performance of lookup by ensuring patient results have hash

---

app/jobs/process_patient_changesets_job.rb
spec/features/import_child_pds_lookup_extravaganza_spec.rb
spec/jobs/process_patient_changesets_job_spec.rb
spec/support/pds_helper.rb

Previously, `nhs_number` within `patient_changeset.search_results` was accessed using symbol keys (e.g., `sr[:nhs_number]`). However, when `search_results` (stored in a `jsonb` column) are deserialized from the database, they become standard Ruby hash objects with string keys, causing symbol access to fail.
Updated the `unique_nhs_numbers` method to use string keys (`sr["nhs_number"]`) for accessing the NHS number.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1887

Ensure reliable NHS number retrieval from search results

---

app/jobs/process_patient_changesets_job.rb
spec/factories/patient_changesets.rb
spec/features/import_child_pds_lookup_extravaganza_spec.rb
spec/jobs/process_patient_changesets_job_spec.rb

We have seen at least two cases where fuzzy matching in PDS returned a patient that was obviously wrong (first name and last name swapped around and spellings completely different, and postcode different). We think it is safest to remove the last search step (fuzzy step) from the cascading search. The updated flow is below.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1886

Remove fuzzy-search from cascading PDS search algorithm

---

app/components/app_imports_table_component.html.erb
app/views/imports/show.html.erb
spec/components/app_imports_table_component_spec.rb

Displays the CSV file name on the import summary screens.
https://nhsd-jira.digital.nhs.uk/browse/MAV-1827

Show uploaded file name on import screens

---

app/components/app_programme_tags_component.rb
spec/components/app_programme_tags_component_spec.rb

This ensures that when displaying a list of programme tags they are always ordered alphabetically, even if they're not ordered in that way when they're passed in.
Generally we order the results of programmes when querying from the database, but there seems to be an issue in QA currently where preloading the programmes means they are not always ordered. This change guarantees that users will see the programmes in the correct order.

Ensure programme tags are ordered

---

app/lib/reports/systm_one_exporter.rb
spec/lib/reports/systm_one_exporter_spec.rb

This adds the SystmOne codes for flu to ensure that the exporter includes the right values for the SAIS teams to import.
[Jira Issue - MAV-1678](https://nhsd-jira.digital.nhs.uk/browse/MAV-1678)

Add SystmOne codes for flu

---

app/components/app_patient_session_record_component.rb
spec/factories/sessions.rb
spec/features/manage_attendance_spec.rb

If viewing a patient in a session that has no date today, and has registration disabled, the users will see an error when trying to view the patient.
This happens because we try to render the vaccinate form, which fails when there isn't a session date today.
[Sentry Issue](https://good-machine.sentry.io/issues/6864512518/)

Fix viewing patient when there's no date today

---

app/views/sessions/patient_specific_directions/show.html.erb
spec/features/flu_vaccination_hca_psd_spec.rb

Use `pluralize` helper to correctly display "There is 1 child" instead of "There are 1 children" when only one child is eligible for PSD creation.

Fix grammar in PSD eligibility message for singular case

---

app/lib/reports/systm_one_exporter.rb
spec/lib/reports/systm_one_exporter_spec.rb

In 1a2f96876702a4da675b5045ff2fd4904bc1ba34 I added the SystmOne codes for flu under the assumption that the dose sequence would be `nil`, but actually the dose sequence will instead be `1`. This fixes an issue where the codes weren't coming through correctly.
[Jira Issue - MAV-1678](https://nhsd-jira.digital.nhs.uk/browse/MAV-1678)

Make flu SystmOne codes based on dose sequence

---

app/controllers/api/testing/teams_controller.rb

Under-the-hood change which only affects testing. 
Deletes PatientSession and SessionAttendance entries for patients and ArchiveReason entries for teams when the delete endpoint is called, which seems to prevent most errors that could appear when deleting teams.

Prevent delete endpoint from failing to delete teams

---

app/components/app_vaccinate_form_component.rb
spec/features/flu_vaccination_hca_national_protocol_spec.rb
spec/features/flu_vaccination_hca_pgd_supply_spec.rb

If a PSD exists on a patient from when the session had PSD enabled, and then PSD is subsequently disabled, HCAs are unable to record vaccinations for these patients. This is because the service thinks we're using the PSD to record the vaccination and doesn't display the field asking the HCA to specify who supplied the vaccine. Instead, even if the patient has a PSD, when PSD is disabled on the session, the HCA will not be using the PSD protocol, they will be using PGD with supply.

Fix HCAs unable to record vaccination if PSD exists

---

config/sidekiq.yml

This is preventing the service from deploying successfully. Once we've got Sidekiq configured locally, this should be easier to spot before merging in.

Fix syntax error in Sidekiq configuration

---

app/lib/patient_merger.rb
spec/lib/patient_merger_spec.rb

This fixes an issue where patients with session attendances cannot be merged together due to the foreign key constraint on the session attendance failing when the old patient is destroyed.
[Sentry Issue](https://good-machine.sentry.io/issues/6859186837/)

Fix merging patients with session attendances

---

db/migrate/20250822153747_remove_patient_session_from_patient_registration_statuses.rb

This optimises the code we use in this migration to ensure it runs much quicker, by executing a single query. This is to avoid a situation where the migration takes too long to run in production and causes issues with the deployment.
This migration has already run in QA and test, but I've tested locally and this change does the same thing. I will test this in data replication before deploying.

Optimise migration that replaces `patient_session_id`

---

app/jobs/commit_patient_changesets_job.rb
config/sidekiq.yml

This sets the right queue for the `CommitPatientChangesetsJob` which should be the `imports` queue as it's higher priority than other queues.
I've also added `default` to the Sidekiq configuration for the `TrimActiveRecordSessionsJob` job.

Ensure `CommitPatientChangesetsJob` runs in `imports` queue

---

app/components/app_vaccination_record_summary_component.rb
spec/components/app_vaccination_record_summary_component_spec.rb

The sync jobs won't run if `imms_api_integration` is disabled, so it feels ambiguous to show it.
[MAV-1968](https://nhsd-jira.digital.nhs.uk/browse/MAV-1968)

Check all the relevant feature flags when displaying in the UI

---

.tool-versions
Procfile
Procfile.dev
README.md

This makes it possible to run Sidekiq locally by adding Redis/Valkey as a dependency and adding the `sidekiq` process to the `Procfile`.

Run sidekiq locally

---

app/jobs/sync_vaccination_record_to_nhs_job.rb
spec/models/immunisation_import_spec.rb

This fixes the queue name as currently it refers to a queue that doesn't exist and isn't processed by Sidekiq.

Fix queue for `SyncVaccinationRecordToNHSJob`

---

app/jobs/search_vaccination_records_in_nhs_job.rb
spec/jobs/search_vaccination_records_in_nhs_job_spec.rb

Previously the patients' vaccination status wasn't changing after a search to the API. Now they should be.
[MAV-1780](https://nhsd-jira.digital.nhs.uk/browse/MAV-1780)

Call `StatusUpdater` after Imms API search

---

app/components/app_vaccinations_summary_table_component.html.erb
app/components/app_vaccinations_summary_table_component.rb
app/controllers/sessions/record_controller.rb
spec/components/app_vaccinations_summary_table_component_spec.rb
spec/features/tallying_spec.rb

This ensures that when the summary table is shown, any discontinued vaccines are not shown, unless vaccinations are recorded against them in the session in which case they will show in the table.
I've also refactored the `AppVaccinationsSummaryTableComponent` to simplify the code.
[Jira Issue - MAV-1991](https://nhsd-jira.digital.nhs.uk/browse/MAV-1991)

Hide discontinued vaccines from summary table

---

spec/features/import_child_pds_lookup_extravaganza_spec.rb
spec/features/import_child_records_spec.rb
spec/support/imports_helper.rb

This fixes the test by using `travel 1.minute` to ensure that we're always clicking on the most recent import (currently the test creates two imports at the same time which results in them having the same link text).

Fix flaky PDS import test

---

app/views/errors/internal_server_error.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unprocessable_entity.html.erb
app/views/parent_interface/consent_forms/deadline_passed.html.erb

This simplifies some code related to generating links to emails, instead of using `link_to` and linking to `mailto:` href, we can instead use the `mail_to` helper.

Use `mail_to` helper

---

app/controllers/api/testing/teams_controller.rb

This makes a small change to the endpoint to delete teams using the testing API to ensure any notify log entries attached to the team's consent forms get deleted.

Ensure `NotifyLogEntry` is deleted in testing

---

lib/tasks/data_migrations.rake

This fixes an issue where some vaccination records are currently invalid as they have both a `location_id` and a `location_name`.
[Jira Issue - MAV-2016](https://nhsd-jira.digital.nhs.uk/browse/MAV-2016)

Add `data_migrations:fix_vaccination_records_location`

---

terraform/app/ecs.tf
terraform/app/valkey.tf

- Prevent frequently querying database for infrequently changing results

Introduce a rails cache for web server

---

app/controllers/sessions_controller.rb
app/models/patient.rb
app/models/patient_location.rb

This should have an improvement on performance, avoiding the need to compare the entire result set. Due to the size of the set, it's unlikely to be able to use a hash and instead performs a sequential scan.
[Jira Issue - MAV-2004](https://nhsd-jira.digital.nhs.uk/browse/MAV-2004)

Use `EXISTS` instead of `IN`

---

app/controllers/consent_forms_controller.rb
app/controllers/imports/issues_controller.rb
app/forms/import_duplicate_form.rb
app/forms/school_move_form.rb
spec/features/import_child_records_with_duplicates_spec.rb
spec/features/parental_consent_clinic_spec.rb
spec/features/parental_consent_manual_matching_spec.rb

This fixes a number of places where the cache for the counts in the header weren't being invalidated meaning they would end up with the incorrect value.
[Jira Issue - MAV-2004](https://nhsd-jira.digital.nhs.uk/browse/MAV-2004)

Ensure cache invalidation happens

---

spec/policies/school_move_policy_spec.rb

The factory no longer exists but these variables weren't being referenced anywhere in the test so it wasn't failing. I've fixed the test and updated the reference to the right factory.

Fix reference to patient session factory

---

spec/features/manage_school_sessions_spec.rb

This improves test coverage for the invite to clinic feature by ensuring we can handle adding patients to clinic that are already in the clinic, and also covering the scenario where a patient exists in the clinic already and have received an invitation.
This covers a bug that currently exists in production: https://good-machine.sentry.io/issues/6885411856/

Import test coverage for invite to clinic

---

app/jobs/commit_patient_changesets_job.rb
spec/features/import_child_pds_lookup_extravaganza_spec.rb
spec/fixtures/cohort_import/pds_extravaganza.csv

Previously, match_existing only handled deduplication against parents already persisted in the database. This meant that when the same parent appeared multiple times in a single import file, duplicate parent records could still be created. We now deduplicate parents within the import batch itself by email to ensure only one parent record is created per unique email.
JIRA: [MAV-1915](https://nhsd-jira.digital.nhs.uk/browse/MAV-1915)

Deduplicate parents with same email in same file

---

.github/workflows/data-replication-pipeline.yml
.github/workflows/deploy-application.yml
.github/workflows/deploy-backup-infrastructure.yml
.github/workflows/deploy-infrastructure.yml
.github/workflows/deploy-monitoring.yml
.github/workflows/destroy-infrastructure.yml
.github/workflows/test.yml
.tool-versions
terraform/account/main.tf
terraform/app/main.tf
terraform/app/modules/dms/main.tf
terraform/app/modules/dns/main.tf
terraform/app/modules/ecs_service/main.tf
terraform/app/modules/vpc_endpoint/main.tf
terraform/backup/destination-bootstrap/main.tf
terraform/backup/destination/main.tf
terraform/backup/source/main.tf
terraform/bootstrap/main.tf
terraform/data_replication/main.tf
terraform/modules/s3/main.tf
terraform/monitoring/aws/main.tf
terraform/monitoring/grafana/main.tf

This ensures that we're staying up to date with the latest version of Terraform and potentially fixes an issue we've been seeing with the AWS provider.

Upgrade to latest Terraform

---

app/models/session_notification.rb
spec/models/session_notification_spec.rb

This fixes an issue where patients who are invited to a clinic, and are vaccinated for some of the programmes but not all of them, were receiving an email/text for all the programmes they're eligible for rather than just the programmes they are eligible for and need a vaccination for.
[Jira Issue - MAV-1994](https://nhsd-jira.digital.nhs.uk/browse/MAV-1994)

Ensure already vaccinated patients don't receive clinic invitations

---

app/lib/nhs/immunisations_api.rb
spec/lib/nhs/immunisations_api_spec.rb

This prevents the `RECORD_UPDATED_AT` column in the vaccination report download from being updated, ensuring only genuine user edits to the record are reflected in the report.
Fixes [MAV-1988](https://nhsd-jira.digital.nhs.uk/browse/MAV-1988).

Prevent Imms API syncs from changing vaccs record `updated_at` field

---

app/jobs/enqueue_vaccinations_search_in_nhs_job.rb
config/sidekiq.yml
spec/jobs/enqueue_vaccinations_search_in_nhs_job_spec.rb

This PR:
* reverts #4630 
* fixes a bug in #4612 which prevented `EnqueueVaccinationsSearchInNHSJob` from running at the right time

Ensure flu search is done before consents go out

---

app/jobs/enqueue_vaccinations_search_in_nhs_job.rb
spec/jobs/enqueue_vaccinations_search_in_nhs_job_spec.rb

`Session`s whose `location`s are `generic_clinic`s use `send_invitations_at` instead of `send_consent_requests_at`. Both need notifications to be sent, so must be extracted separately in the DB query.
[MAV-1723](https://nhsd-jira.digital.nhs.uk/browse/MAV-1723)

Fix session selection logic

---

app/controllers/api/testing/teams_controller.rb
app/models/class_imports_parent.rb
app/models/class_imports_parent_relationship.rb
app/models/class_imports_patient.rb
app/models/cohort_imports_parent.rb
app/models/cohort_imports_parent_relationship.rb
app/models/cohort_imports_patient.rb
app/models/consent_form_programme.rb
db/migrate/20250918075325_add_foreign_key_cascade_to_join_tables.rb
db/schema.rb
spec/factories/consent_form_programmes.rb

This improves the performance of the endpoint we can use to reset a team while running performance or regression tests by using `delete_all` instead of `destroy_all` and avoiding the need to run Rails callbacks. To support this I've added `ON DELETE CASCADE` to the foreign keys of the join tables.

Improve performance of team reset endpoint

---

app/forms/session_programmes_form.rb
app/lib/mavis_cli/schools/move_patients.rb
spec/features/cli_schools_move_patients_spec.rb
spec/forms/session_programmes_form_spec.rb

This fixes two scenarios where `LocationProgrammeYearGroups` are being created automatically meaning patients can't be seen in sessions.
- This ensures that when moving patients between locations, the `LocationProgrammeYearGroups` are moved as well otherwise the session won't have any patients in it.
- When adding a programme to a session we need to ensure that `LocationProgrammeYearGroups` are added to the location to ensure that any patients eligible for the new programme are shown.
[Jira Issue - MAV-1986](https://nhsd-jira.digital.nhs.uk/browse/MAV-1986)
[Jira Issue - MAV-2030](https://nhsd-jira.digital.nhs.uk/browse/MAV-2030)

Ensure `LocationProgrammeYearGroups` are created

---

app/controllers/api/testing/teams_controller.rb

This endpoint is only used for testing and having it operate in a transaction makes it less useful for testing. It means that if we get a timeout, the whole action has failed, whereas the testers would prefer to be able to simply run it again to delete everything that was left behind. It should also improve performance and remove the chance of deadlocks.

Don't delete teams in a transaction

---

app/lib/patient_merger.rb
spec/lib/patient_merger_spec.rb

This fixes a potential issue with the patient merger where it will try to create multiple school moves for the same patient which is no longer valid as of be2609ad7fd94e8ce037acfd890b5d0ec56406c0.

Ensure duplicate school moves don't exist

---

app/forms/import_duplicate_form.rb
app/lib/reports/offline_session_exporter.rb
app/models/concerns/pending_changes_concern.rb
app/models/immunisation_import_row.rb
app/views/imports/issues/show.html.erb
spec/features/hpv_vaccination_offline_spec.rb
spec/features/vaccination_offline_spec.rb
spec/forms/import_duplicate_form_spec.rb
spec/models/immunisation_import_row_spec.rb

Vaccination records which are received from the Imms API are considered
immutable in Mavis, because we are not the vaccination record's primary
source. As such, users should not be allowed to edit the records by any
means, including an offline spreadsheet upload.
We (Thomas, Mike, Alistair) considered exposing this as a validation
error on the import, but that approach was discarded. This is because we
would have needed to duplicate a lot of the import logic to decide
whether it was appropriate to throw a validation error. This led to
circular dependencies in the validation logic.
Instead this approach was taken, where an adjusted import issue page is
shown, forcing the user to discard the incoming changes.
Off the back of this change, another issue needed to be resolved;
unedited …

Disallow offline spreadsheets from editing records received from the Imms API

---

app/models/cohort_import_row.rb
spec/models/cohort_import_row_spec.rb

This ensures that when importing a cohort, you can only provide school URNs for schools managed by the team, avoiding the possibility of editing the cohort of a different team.
[Jira Ticket - MAV-503](https://nhsd-jira.digital.nhs.uk/browse/MAV-503)

Limit cohort imports by team's schools

---

app/models/patient_import_row.rb
spec/models/class_import_row_spec.rb
spec/models/cohort_import_row_spec.rb

Anyone born before 2000 is clearly not going to be in secondary education anymore.
This isn't a perfect cut-off point but it's low enough that it will never be a problem for anyone who still is going to school, but it will prevent uploads of children born in the wrong century, which we sometimes see when the CHILD_YEAR_GROUP parameter is set while the date of birth for example does not have a century set. (e.g. 01/01/0015 may show as 01/01/15 in excel)
This is [MAV-1833](https://nhsd-jira.digital.nhs.uk/browse/MAV-1833)

Check birth century

---

app/components/app_parent_summary_component.rb
app/jobs/sms_delivery_job.rb
app/models/notify_log_entry.rb
spec/jobs/sms_delivery_job_spec.rb

This ensures that we handle the `InvalidPhoneError: Not a UK mobile number` error from GOV.UK Notify by recording the response as a permanent failure (which is accurate since retrying is not going to succeed). This also means the job finishes and doesn't get put back on the retry queue, and also allows the nurses to see useful feedback.
[Sentry Issue](https://good-machine.sentry.io/issues/6235087330/)

Handle invalid phone errors from GOV.UK Notify

---

app/controllers/api/reporting/base_controller.rb
app/controllers/sessions/record_controller.rb
app/controllers/sessions_controller.rb
config/initializers/pagy.rb
spec/features/manage_children_spec.rb

This configures Pagy to ensure that if a user tries to access a page that doesn't exist, rather than seeing an error page (and an unhandled exception going to Sentry), the user is shown the last possible page.
To support this I've also reconfigured how we include the Pagy extras to make it globally configured across the codebase. This is because the Pagy behaviour was dependent on which files had been executed and which `pagy/extra` files had been required, meaning the tests were flaky depending on the order.

Gracefully handle page overflow errors

---

app/models/patient.rb
spec/models/patient_spec.rb

This ensures that we handle the situation where an archive reason needs to be created because we get a notification from PDS that the patient is deceased, but the patient record already has an archive reason.
[Sentry Issue](https://good-machine.sentry.io/issues/6885440241/)

Ensure deceased archive reason is created

---

app/lib/reports/export_formatters.rb
spec/lib/reports/programme_vaccinations_exporter_spec.rb

This moves the date to the start of the consent string,
allowing it to be sorted alphabetically.
Also, the newest consents must be shown first.
It now reads:
[MAV-2025](https://nhsd-jira.digital.nhs.uk/browse/MAV-2025)

Allow users to sort offline sheet by consent time

---

terraform/account/main.tf

This policy will restrict 
* Shell access to the ECS tasks
* Modifying the policies attached to the role
There is a bit of a circular dependency here, the role to which this policy will be attached doesn't exist yet and will be created in the aws-prod-sso-config repo.
However, for this role to be created, a policy already needs to exist. So we have to update the policy in a subsequent PR once the role exists
Jira-Issue: MAV-1973
- Apply account stack

Add IAM policy to deny PII access

---

app/components/app_import_errors_component.rb

Replace custom card markup in AppImportErrorsComponent with AppCardComponent for consistency. The main heading is now styled via the card heading slot with `colour: "red"`, so only the title text is highlighted while the card itself is white.
JIRA- [MAV-2092](https://nhsd-jira.digital.nhs.uk/browse/MAV-2092)
- ...
- ...

Render import errors inside AppCardComponent

---

app/controllers/sessions/record_controller.rb
spec/features/flu_vaccination_hca_psd_spec.rb

This fixes a bug where patients don't appear to show in the "Record vaccinations" tab if they've got a PSD and only PSDs are enabled for the session (i.e. national protocol is switched off).
The bug was happening because we were not handling the situation where only PSD is enabled for the session, in that case the scope was being reduce to find no patients.
[Jira Issue - MAV-2065](https://nhsd-jira.digital.nhs.uk/browse/MAV-2065)
- ...

Ensure patients are visible when PSDs only are enabled

---

app/models/concerns/pending_changes_concern.rb
spec/models/concerns/pending_changes_concern_spec.rb

Add whitespace normalisation when creating pending changes
[MAV-2063](https://nhsd-jira.digital.nhs.uk/browse/MAV-2063)

Fix pending changes whitespace normalisation

---

app/controllers/api/testing/teams_controller.rb

Under-the-hood change which only affects testing.
The endpoint is failing to delete teams as it currently tries to delete consent forms before deleting the notify log entries, resulting in an error.

Update team endpoint to delete notify log entries before deleting consent forms

---

app/models/cis2_info.rb
app/models/user.rb
app/policies/notices_policy.rb
app/policies/vaccination_record_policy.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/support/cis2_auth_helper.rb

This updates how a user is allowed to perform certain superuser tasks by checking their activity codes rather than the `mavissuperusers` workgroup. This is being done to allow for a more granular permissions system where different users have permission to perform different tasks.
[Jira Issue - MAV-1681](https://nhsd-jira.digital.nhs.uk/browse/MAV-1681)

Make superuser permissions based on activities

---

app/controllers/parent_interface/consent_forms/base_controller.rb
app/models/consent_form.rb
spec/features/parental_consent_school_session_completed_spec.rb
spec/models/consent_form_spec.rb

When filling in a consent form and recording that the child goes to a different school to the one we thought, this ensures that the consent form doesn't show the "deadline passed" end state if the new school session is unscheduled. This situation could occur if the new school doesn't have dates yet, but will do in the future, meaning that submitting consent at this point is worth doing.
This partially reverts 63b0d9329aef8db8746201a27494703ab458ec65 which introduce this regression in this specific scenario.

Allow submitting consent for an unscheduled session

---

app/controllers/draft_consents_controller.rb
app/models/draft_consent.rb
spec/features/e2e_journey_spec.rb
spec/features/self_consent_spec.rb
spec/features/verbal_consent_change_answers_spec.rb
spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
spec/features/verbal_consent_given_spec.rb
spec/features/verbal_consent_given_triage_psd_spec.rb
spec/features/verbal_consent_given_when_previously_refused_spec.rb

This allows nurses to skip the triage step when recording verbal consent if the answers to the health questions indicates that triage is not required. After this change, the triage requirements are the same for both verbal consent and online parental consent.
[Jira Issue - MAV-2109](https://nhsd-jira.digital.nhs.uk/browse/MAV-2109)

Skip triage after verbal consent if not required

---

app/assets/stylesheets/vendor/nhsuk-frontend/overrides/_index.scss
app/components/app_import_pds_unmatched_summary_component.rb
app/views/imports/show.html.erb
db/seeds.rb
spec/components/app_import_pds_unmatched_summary_component_spec.rb

When an import fails due to a low PDS match rate, we should render the unmatched records in row number order to allow the user in easily identifying and editing the original file.
The summary component should also be sticky to handle large numbers of records.
JIRA: [MAV-2126](https://nhsd-jira.digital.nhs.uk/browse/MAV-2126)
- ...
- ...

Fix low pds match rate rendering

---

spec/lib/status_generator/vaccination_spec.rb

This test comes off the back of discussions relating to the new design for the session overview page, specifically the programme status tallies.
The test confirms that if we get conflicting consent records, the consent status generator will return `could_not_vaccinate`.

Add test to verify the consent status for conflicting consents

---

app/helpers/application_helper.rb

Without this we get errors when retrieving the manifest behind basic auth.
Jira-Issue: [MAV-1975](https://nhsd-jira.digital.nhs.uk/browse/MAV-1975)

Add crossorigin auth for manifest in non-prod

---

app/components/app_timeline_component.rb
app/components/app_timeline_filter_component.html.erb
app/components/app_timeline_filter_component.rb
app/controllers/inspect/timeline/patients_controller.rb
app/views/inspect/timeline/patients/show.html.erb
config/routes.rb
lib/timeline_records.rb
spec/features/timeline_records_spec.rb
spec/lib/timeline_records_spec.rb

An endpoint which serves a UI used to view events related to a patient record.
This is a tool designed for use by the Ops Support people, to visualise the patient data without having to use the console.
The information that can be displayed for each 'event' is as follows: https://github.com/nhsuk/manage-vaccinations-in-schools/blob/730766c641fd414b9b1b721f684214adaa37b6b3/lib/timeline_records.rb#L21-L77
And the following audited changes are allowed: https://github.com/nhsuk/manage-vaccinations-in-schools/blob/730766c641fd414b9b1b721f684214adaa37b6b3/lib/timeline_records.rb#L89-L133
These details include PII, but there is a `show_pii` flag that can be turned off in the controller to remove any identifiable information from the above lists

TimelineRecords UI

---

app/controllers/draft_sessions_controller.rb
spec/features/manage_school_sessions_spec.rb

This fixes an issue when trying to save session dates where one of the dates cannot be modified due to patients have already been seen at that date.
[Jira Issue - MAV-516](https://nhsd-jira.digital.nhs.uk/browse/MAV-516)
[Sentry Issue](https://good-machine.sentry.io/issues/6925585376/)

Fix issue saving session dates

---

app/models/concerns/delegatable.rb
app/models/draft_session.rb
app/models/session.rb

This adds a concern which can be shared by both the `DraftSession` and `Session` models to avoid needing to determine whether a draft session supports delegation through the underlying session.

Add `Delegatable` concern

---

terraform/app/env/preview.tfvars
terraform/app/env/production.tfvars
terraform/app/env/training.tfvars

This change is a follow-up to #4781. It is needed because a deployment happened for the 5.0.0 release, which switched the active target groups again.

Active Load balancer target groups

---

app/controllers/concerns/vaccination_mailer_concern.rb
app/lib/already_had_notification_sender.rb
app/lib/govuk_notify_personalisation.rb
app/lib/notification_parent_selector.rb
spec/lib/already_had_notification_sender_spec.rb
spec/lib/govuk_notify_personalisation_spec.rb
spec/lib/notification_parent_selector_spec.rb

This fixes a bug for templates which don't need to reference a session.
[MAV-2204](https://nhsd-jira.digital.nhs.uk/browse/MAV-2204)

Allow `GovukNotifyPersonalisation` to handle `session = nil`
